AXO X1: drv/spi/adxl37x.h File Reference
adxl37x.h File Reference
Header file of Adxl37x class.
Detailed Description
Header file of Adxl37x class.
Project
AXO Track Firmware 2023
Copyright
(c) 2023 AXO Track GmbH, Berlin. All rights reserved.
Author
AXO Track GmbH, Berlin (Germany)
Detailed Description
ADXL372 is connected to nRF9160 via SPI bus. Acceleration data will be received from driver via FIFO. If data is written from driver into FIFO callback function fifo_handler will be triggered by FIFO full interrupt. The fifo_handler retrieve the data from FIFO and inform own task via message. Data then will be send to eAdxlStore task for further processing. Adxl37x class uses functions provided by the ADXL372 driver, located at zephyr/driver/sensor/adxl372. These functions are included in this file by extern declaration.
Note
To use these functions from the driver, the driver implementation has to be patched. The function are mentioned only for internal use in the driver and are defined as static. For use in Adxl37x class static declaration has to be removed or commented out in patch.
Remarks
This source code is confidential and proprietary information of AXO Track GmbH, Berlin. You may not disclose, copy, or distribute this source code or any part thereof without the explicit permission of AXO Track GmbH, Berlin.
Definition in file adxl37x.h.
Data Structures
struct adxl37x_sensor_value
struct adxl372_xyz_accel_data
Structure containing the x, y, and z values of the acceleration data.
struct adxl372_status
Structure containing status information and number of FIFO entries.
class Adxl37x
Adxl37x acceleration sensor class derived from task base class.
Macros
#define ADXL372_Z_DATA_H 0x0Cu /* Z-axis acceleration data [11:4] */
#define ADXL372_Z_DATA_L 0x0Du /* Z-axis acceleration data [3:0] */
#define ADXL372_POWER_CTL 0x3Fu /* Power control */
#define ADXL372_SELF_TEST 0x40u /* Self Test */
#define ADXL372_RESET 0x41u /* Reset */
#define ADXL372_RESET_CODE 0x52u /* Writing code 0x52 resets the device */
#define ADXL372_POWER_CTL_LPF_DIS_MODE(x) (((x) & 0x1) << 3)
#define ADXL372_POWER_CTL_MODE(x) (((x) & 0x3) << 0)
Enumerations
enum adxl372_op_mode { ADXL372_STANDBY , ADXL372_WAKE_UP , ADXL372_INSTANT_ON , ADXL372_FULL_BW_MEASUREMENT }
enum adxl372_fifo_mode { ADXL372_FIFO_BYPASSED , ADXL372_FIFO_STREAMED , ADXL372_FIFO_TRIGGERED , ADXL372_FIFO_OLD_SAVED }
enum adxl372_fifo_format {
ADXL372_XYZ_FIFO , ADXL372_X_FIFO , ADXL372_Y_FIFO , ADXL372_XY_FIFO ,
ADXL372_Z_FIFO , ADXL372_XZ_FIFO , ADXL372_YZ_FIFO , ADXL372_XYZ_PEAK_FIFO
}
Functions
int adxl372_get_fifo_xyz_data (const struct device *dev, struct adxl372_xyz_accel_data *samples, uint16_t *cnt)
int adxl372_set_op_mode (const struct device *dev, enum adxl372_op_mode op_mode)
int adxl372_configure_fifo (const struct device *dev, enum adxl372_fifo_mode mode, enum adxl372_fifo_format format, uint16_t fifo_samples)
int adxl372_set_ext_sync (const struct device *dev, int state)
int adxl372_get_status (const struct device *dev, uint8_t *status1, uint8_t *status2, uint16_t *fifo_entries)
bool getSelftestSuccess (void)
Macro Definition Documentation
ADXL372_Z_DATA_H
#define ADXL372_Z_DATA_H 0x0Cu /* Z-axis acceleration data [11:4] */
Definition at line 80 of file adxl37x.h.
ADXL372_Z_DATA_L
#define ADXL372_Z_DATA_L 0x0Du /* Z-axis acceleration data [3:0] */
Definition at line 81 of file adxl37x.h.
ADXL372_POWER_CTL
#define ADXL372_POWER_CTL 0x3Fu /* Power control */
Definition at line 82 of file adxl37x.h.
ADXL372_SELF_TEST
#define ADXL372_SELF_TEST 0x40u /* Self Test */
Definition at line 83 of file adxl37x.h.
ADXL372_RESET
#define ADXL372_RESET 0x41u /* Reset */
Definition at line 84 of file adxl37x.h.
ADXL372_RESET_CODE
#define ADXL372_RESET_CODE 0x52u /* Writing code 0x52 resets the device */
Definition at line 87 of file adxl37x.h.
ADXL372_POWER_CTL_LPF_DIS_MODE
#define ADXL372_POWER_CTL_LPF_DIS_MODE (x) (((x) & 0x1) << 3)
Definition at line 88 of file adxl37x.h.
ADXL372_POWER_CTL_MODE
#define ADXL372_POWER_CTL_MODE (x) (((x) & 0x3) << 0)
Definition at line 89 of file adxl37x.h.
Enumeration Type Documentation
adxl372_op_mode
enum adxl372_op_mode
Operation mode definition, copy of from driver located at zephyr/driver/sensor/adxl372/adxl372.h
Enumerator
ADXL372_STANDBY
ADXL372_WAKE_UP
ADXL372_INSTANT_ON
ADXL372_FULL_BW_MEASUREMENT
Definition at line 95 of file adxl37x.h.
adxl372_fifo_mode
enum adxl372_fifo_mode
FIFO mode definition, copy of from driver located at zephyr/driver/sensor/adxl372/adxl372.h
Enumerator
ADXL372_FIFO_BYPASSED
ADXL372_FIFO_STREAMED
ADXL372_FIFO_TRIGGERED
ADXL372_FIFO_OLD_SAVED
Definition at line 114 of file adxl37x.h.
adxl372_fifo_format
enum adxl372_fifo_format
FIFO format definition, copy of from driver located at zephyr/driver/sensor/adxl372/adxl372.h
Enumerator
ADXL372_XYZ_FIFO
ADXL372_X_FIFO
ADXL372_Y_FIFO
ADXL372_XY_FIFO
ADXL372_Z_FIFO
ADXL372_XZ_FIFO
ADXL372_YZ_FIFO
ADXL372_XYZ_PEAK_FIFO
Definition at line 123 of file adxl37x.h.
Function Documentation
adxl372_get_fifo_xyz_data()
int adxl372_get_fifo_xyz_data (const struct device * dev, struct adxl372_xyz_accel_data * samples, uint16_t * cnt)
Extern declaration of function adxl372_get_fifo_xyz_data, implemented by driver located at zephyr/driver/sensor/adxl372/adxl372.c
Referenced by Adxl37x::fifo_handler().
adxl372_set_op_mode()
int adxl372_set_op_mode (const struct device * dev, enum adxl372_op_mode op_mode)
Extern declaration of function adxl372_set_op_mode, implemented by driver located at zephyr/driver/sensor/adxl372/adxl372.c
Referenced by Adxl37x::setOpMode().
adxl372_configure_fifo()
int adxl372_configure_fifo (const struct device * dev, enum adxl372_fifo_mode mode, enum adxl372_fifo_format format, uint16_t fifo_samples)
Extern declaration of function adxl372_configure_fifo, implemented by driver located at zephyr/driver/sensor/adxl372/adxl372.c
Referenced by Adxl37x::setFifoBypass(), and Adxl37x::setFifoOn().
adxl372_set_ext_sync()
int adxl372_set_ext_sync (const struct device * dev, int state)
Extern declaration of function adxl372_set_ext_sync, implemented by driver located at zephyr/driver/sensor/adxl372/adxl372.c
Referenced by Adxl37x::setExtSync().
adxl372_get_status()
int adxl372_get_status (const struct device * dev, uint8_t * status1, uint8_t * status2, uint16_t * fifo_entries)
Extern declaration of function adxl372_get_status, implemented by driver located at zephyr/driver/sensor/adxl372/adxl372.c
getSelftestSuccess()
bool getSelftestSuccess (void)
Referenced by Adxl37x::getHwStatus().
#include <date_time.h>
#include <zephyr/drivers/sensor.h>
#include <zephyr/kernel.h>
#include <zephyr/drivers/clock_control.h>
#include <zephyr/drivers/clock_control/nrf_clock_control.h>
#include "rtos/task.h"
#include "data/hw_metrics.h"