AXO X1: certmgr Class Reference
certmgr Class Reference
Certification management class implemented according to C++ singleton design pattern.
#include <certmgr.h>
Detailed Description
Certification management class implemented according to C++ singleton design pattern.
Detailed Description
Certification manager class is the central module for the broker switching feature. It provides methods to store received device keys abnd certificates in the file system and into the modem, methods to read and write the broker configuration file and getter function to retrieve current and desired broker. Furthermore it provides a metod to check if all precondition for the broker switching are full filled.
Definition at line 80 of file certmgr.h.
Public Member Functions
~certmgr ()
void init ()
int WriteJoviaRootCert2Modem ()
int WriteThingsboardRootCert2Modem ()
int WriteDeviceCert2Modem ()
int WriteDeviceKey2Modem ()
bool CheckCertExistInModem (enum modem_key_mgmt_cred_type credType)
bool CompareRootCertInModem (const char *pCert, size_t len)
enBroker GetConfiguredBrokerInModem ()
stBrokerCfg readBrokerCfg ()
void writeBrokerCfg (enBroker current, enBroker desired)
enBroker getCurrentBroker ()
enBroker getDesiredBroker ()
void writeDeviceCert (enBroker broker, const char *pCert)
void appendDeviceCert (enBroker broker, const char *pCert)
void appendDeviceKey (enBroker broker, const char *pCert)
void readDeviceCertAndKey (enBroker broker)
std::string parseCert (char *pJsonBuf, char *cmd)
void storeJoviaCert1 (char *pBuf)
void storeJoviaCert2 (char *pBuf)
void storeJoviaKey (char *pBuf)
void storeThingsboardCert1 (char *pBuf)
void storeThingsboardCert2 (char *pBuf)
void storeThingsboardKey (char *pBuf)
bool AllPrecondFullFilled ()
void GetFsStat ()
void EraseFs ()
void ListFs ()
bool BrokerSwitchRequested ()
void ClearBrokerSwitchRequested ()
void printCert (char *pCert)
Static Public Member Functions
static certmgr * inst ()
static int shell_switch2jovia (const struct shell *shell, size_t argc, char **argv)
Private Member Functions
certmgr ()
Private Attributes
char certBuf [2048]
Buffer for the device certificates.
char keyBuf [512]
Buffer for the device key.
struct cJSON * root_obj
The JSON root object.
struct cJSON * child
A JSON child object.
stBrokerCfg brokerCfg
The current broker configuration.
bool bBrokerSwitchRequested
Constructor & Destructor Documentation
~certmgr()
~certmgr ()
certmgr()
certmgr () private
Member Function Documentation
inst()
static certmgr* inst () static
Referenced by MqttConnector::connect(), main(), and MqttConnector::task().
init()
void init ()
Referenced by main().
WriteJoviaRootCert2Modem()
int WriteJoviaRootCert2Modem ()
WriteThingsboardRootCert2Modem()
int WriteThingsboardRootCert2Modem ()
WriteDeviceCert2Modem()
int WriteDeviceCert2Modem ()
WriteDeviceKey2Modem()
int WriteDeviceKey2Modem ()
CheckCertExistInModem()
bool CheckCertExistInModem (enum modem_key_mgmt_cred_type credType)
CompareRootCertInModem()
bool CompareRootCertInModem (const char * pCert, size_t len)
GetConfiguredBrokerInModem()
enBroker GetConfiguredBrokerInModem ()
readBrokerCfg()
stBrokerCfg readBrokerCfg ()
writeBrokerCfg()
void writeBrokerCfg (enBroker current, enBroker desired)
Referenced by MqttConnector::connect().
getCurrentBroker()
enBroker getCurrentBroker ()
Referenced by MqttConnector::connect().
getDesiredBroker()
enBroker getDesiredBroker ()
writeDeviceCert()
void writeDeviceCert (enBroker broker, const char * pCert)
appendDeviceCert()
void appendDeviceCert (enBroker broker, const char * pCert)
appendDeviceKey()
void appendDeviceKey (enBroker broker, const char * pCert)
readDeviceCertAndKey()
void readDeviceCertAndKey (enBroker broker)
parseCert()
std::string parseCert (char * pJsonBuf, char * cmd)
storeJoviaCert1()
void storeJoviaCert1 (char * pBuf)
storeJoviaCert2()
void storeJoviaCert2 (char * pBuf)
storeJoviaKey()
void storeJoviaKey (char * pBuf)
storeThingsboardCert1()
void storeThingsboardCert1 (char * pBuf)
storeThingsboardCert2()
void storeThingsboardCert2 (char * pBuf)
storeThingsboardKey()
void storeThingsboardKey (char * pBuf)
AllPrecondFullFilled()
bool AllPrecondFullFilled ()
GetFsStat()
void GetFsStat ()
EraseFs()
void EraseFs ()
ListFs()
void ListFs ()
BrokerSwitchRequested()
bool BrokerSwitchRequested ()
ClearBrokerSwitchRequested()
void ClearBrokerSwitchRequested ()
Referenced by MqttConnector::task().
printCert()
void printCert (char * pCert)
shell_switch2jovia()
static int shell_switch2jovia (const struct shell * shell, size_t argc, char ** argv) static
Field Documentation
certBuf
char certBuf[2048] private
Buffer for the device certificates.
Definition at line 133 of file certmgr.h.
keyBuf
char keyBuf[512] private
Buffer for the device key.
Definition at line 134 of file certmgr.h.
root_obj
struct cJSON* root_obj private
The JSON root object.
Definition at line 136 of file certmgr.h.
child
struct cJSON* child private
A JSON child object.
Definition at line 137 of file certmgr.h.
brokerCfg
stBrokerCfg brokerCfg private
The current broker configuration.
Definition at line 139 of file certmgr.h.
bBrokerSwitchRequested
bool bBrokerSwitchRequested private
Definition at line 141 of file certmgr.h.
The documentation for this class was generated from the following file:
util/certmgr.h