AXO X1: MeasurementBuilder Class Reference
MeasurementBuilder Class Reference
Measurement builder helper class.
#include <measurement.h>
Detailed Description
Measurement builder helper class.
Detailed Description
The measurement builder helper class provides methods to create the measurement JSON string, which will be send via LTE with topic /device/DEVICE_ID/measurement/update to the MQTT broker.
Definition at line 46 of file measurement.h.
Public Member Functions
MeasurementBuilder (bool have_http_connector=true)
Metric builder constructor.
~MeasurementBuilder ()
Measurement builder destructor.
void addTemperature (PoolElem *pElem)
void add (PoolElem *pElem)
Add function to append prepared measurement data to the measurement JSON string.
void addRmsData (PoolElem *pElem)
Add function to append RMS data to measurement JSON string and store hit counter.
void addDispStatistics (PoolElem *pElem)
Add function to store displacement statistic values in member string variables.
void addMaxXYZ (PoolElem *pElem)
Add function to store x, y and z maximum values in member string variables.
void finalize (void)
Function to finalize the measurement JSON string.
void reset ()
Function clear all private string variables related to metrics JSON string.
bool isComplete (bool disp_mode_off, double rmsZThres)
isComplete function to check if the measurement JSON string is completely filled
void print (void)
Function to print the measurement JSON string.
const std::string & getPayload (void)
Getter function to retrieve the measurement JSON string.
const std::string & getTimestamp (void)
Getter function to retrieve the timestamp of measurement JSON string.
Private Member Functions
MeasurementBuilder (const MeasurementBuilder &)=delete
MeasurementBuilder & operator= (const MeasurementBuilder &)=delete
void SetFloatStrings (std::string &s1, std::string &s2, std::string &s3, double val1, double val2, double val3)
Helper function to convert three double values to strings.
Private Attributes
std::string payload
the measurement JSON string
std::string timestamp
the timestamp in JSON string
std::string sDispMin
Minimum displacement value, to be send to backend with RMS data.
std::string sDispMax
Maximum displacement value, to be send to backend with RMS data.
std::string sDispP2P
Peak To Peak displacement value, to be send to backend with RMS data.
std::string sMaxX
Maximum x value, to be send to backend with RMS data.
std::string sMaxY
Maximum y value, to be send to backend with RMS data.
std::string sMaxZ
Maximum z value, to be send to backend with RMS data.
double max_rms_z
Maximun RMS value in z-direction of one train passing.
std::vector< int16_t > med_hit_cnt
Vector to store medium hit counter.
std::vector< int16_t > crit_hit_cnt
Vector to store critical hit counter.
bool have_http_connector
Constructor & Destructor Documentation
MeasurementBuilder() [1/2]
MeasurementBuilder (bool have_http_connector = true) explicit
Metric builder constructor.
Parameters
have_http_connector Flag indicationg if HTTP Connector is used (X1 devices) or not (MINI devices)
The constructor reseves memory for 20 hit counter values in the vector variables med_hit_cnt and crit_hit_cnt. Finally the member fuction rset is called to clear the vectors med_hit_cnt and crit_hit_cnt and initialize variable payload (the measurement JSON string).
Definition at line 80 of file measurement.cpp.
References crit_hit_cnt, have_http_connector, med_hit_cnt, and reset().
~MeasurementBuilder()
~MeasurementBuilder ()
Measurement builder destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 98 of file measurement.cpp.
MeasurementBuilder() [2/2]
MeasurementBuilder (const MeasurementBuilder &) private delete
Member Function Documentation
addTemperature()
void addTemperature (PoolElem * pElem)
add()
void add (PoolElem * pElem)
Add function to append prepared measurement data to the measurement JSON string.
Parameters
pElem Pointer to the received message (pool element)
According to the message type of the message one of the specific add functions of the class will be called.
Definition at line 305 of file measurement.cpp.
References addDispStatistics(), addMaxXYZ(), addRmsData(), eAdxl37xRmsData, eDispStatistics, eMaxXYZ, and PoolElem::mtype.
Referenced by DataManager::task().
addRmsData()
void addRmsData (PoolElem * pElem)
Add function to append RMS data to measurement JSON string and store hit counter.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure adxl_rms_data and stored in private member variable adxl_rms_data. The function calculate the highest RMS value of the complete measurement and store it in member variable max_rms_z. The hit counter for medium and critical hits will be appended to the vectors med_hit_cnt and crit_hit_cnt and the x, y and z RMS values will be appended to the measurement JSON string variable payload. In case it is the first measurement data the message header will be written in front of the first RMS entries.
Definition at line 177 of file measurement.cpp.
References crit_hit_cnt, adxl_rms_data::critical_hits, eTimestamp, PoolElem::getBuffer(), have_http_connector, max_rms_z, med_hit_cnt, adxl_rms_data::medium_hits, Mbox::sendMsg(), timestamp, adxl_rms_data::ts, adxl_rms_data::x, adxl_rms_data::y, and adxl_rms_data::z.
Referenced by add().
addDispStatistics()
void addDispStatistics (PoolElem * pElem)
Add function to store displacement statistic values in member string variables.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure stDispStatistics and stored in private member variable p. The variables in structure p will be converted to the member string variables sDispMin, sDispMax and sDispP2P by calling function SetFloatStrings.
Definition at line 260 of file measurement.cpp.
References PoolElem::getBuffer(), _stDispStatistics::max, _stDispStatistics::min, _stDispStatistics::p2p, sDispMax, sDispMin, sDispP2P, and SetFloatStrings().
Referenced by add().
addMaxXYZ()
void addMaxXYZ (PoolElem * pElem)
Add function to store x, y and z maximum values in member string variables.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure Adxl_xyz_max_data and stored in private member variable p. The variables in structure p will be converted to the member string variables sMaxX, sMaxY and sMaxZ by calling function SetFloatStrings.
Definition at line 283 of file measurement.cpp.
References PoolElem::getBuffer(), SetFloatStrings(), sMaxX, sMaxY, sMaxZ, Adxl_xyz_max_data::x, Adxl_xyz_max_data::y, and Adxl_xyz_max_data::z.
Referenced by add().
finalize()
void finalize (void)
Function to finalize the measurement JSON string.
The function append the medium hit counter in vector med_hit_cnt to private string variable payload, which represets the measurement JSON string. Afterwards it append the critical hit counter in vector crit_hit_cnt to private string variable payload, before appending the x, y and z maximum values and the displacement minimum, maximum and peak to peak statistic values to string variable payload. The metrics JSON string will be terminated with closing square and curly bracket. Finally member function print will be called to output the measurement JSON string with debug log level INFO.
Definition at line 341 of file measurement.cpp.
References crit_hit_cnt, med_hit_cnt, print(), sDispMax, sDispMin, sDispP2P, sMaxX, sMaxY, and sMaxZ.
Referenced by DataManager::task().
reset()
void reset ()
Function clear all private string variables related to metrics JSON string.
The function initialize member variable max_rms_z with 0, clear the vectors med_hit_cnt and crit_hit_cnt for medium and critical hit counter. Variable payload will be reinitializes with opening curly bracket and entry time_interval with fixed value of 1000 ms (1 sec) and variable timestamp will be initialized with an empty string. By call of function SetFloatStrings the variables sDispMin, sDispMax, sDispP2P and sMaxX, sMaxY, sMaxZ will be initialized with constant value VAL_NOT_INITIALIZED_FLOAT in string representation.
Definition at line 422 of file measurement.cpp.
References crit_hit_cnt, max_rms_z, med_hit_cnt, sDispMax, sDispMin, sDispP2P, SetFloatStrings(), sMaxX, sMaxY, sMaxZ, timestamp, and VAL_NOT_INITIALIZED_FLOAT.
Referenced by MeasurementBuilder(), and DataManager::task().
isComplete()
bool isComplete (bool disp_mode_off, double rmsZThres)
isComplete function to check if the measurement JSON string is completely filled
Parameters
disp_mode_off Flag indication if displacement calculation is disabled
rmsZThres Activation threshold for displacement calculation and raw / displacement data transmission
Returns
returns true if measurement JSON string is complete, false otherwise
The function checks if displacement calculation is disabled, flag disp_mode_off is true or maximum RMS z value is lower or equal to RMS z threshold. In this case it checks if the size of measurement JSON string is greater than 30 bytes. If size is greater it is ensured, that at least one measurement entry is present and the function returns true indicating, that JSON string is completely filled. If displacement calculation is enabled the function compairs the content of the string sDispP2P with the string sVal, which contains the value of the VAL_NOT_INITIALIZED_FLOAT constant. If the strings are equal, the displacement calculation is still ongoing and the function returns false. If the strings are not equal, the displacement values are still calculated and stored in measurement JSON string and the function returns true indicating, that JSON string is completely filled.
Definition at line 127 of file measurement.cpp.
References max_rms_z, sDispP2P, and VAL_NOT_INITIALIZED_FLOAT.
Referenced by DataManager::task().
print()
void print (void)
Function to print the measurement JSON string.
The function print the measurement JSON string with debug log level INFO.
Definition at line 405 of file measurement.cpp.
Referenced by finalize().
getPayload()
const std::string & getPayload (void)
Getter function to retrieve the measurement JSON string.
Returns
Returns the private string variable payload
The function returns the private string variable payload, which represents the measurement JSON string.
Definition at line 381 of file measurement.cpp.
References payload.
Referenced by DataManager::publishMeasurements().
getTimestamp()
const std::string & getTimestamp (void)
Getter function to retrieve the timestamp of measurement JSON string.
Returns
Returns the private string variable timestamp
The function returns the private string variable timestamp, which represents the time of sending measurement JSON string. This timestamp will be inserted by HTTP connector class in raw and displacement data header.
Definition at line 395 of file measurement.cpp.
References timestamp.
operator=()
MeasurementBuilder& operator= (const MeasurementBuilder &) private delete
SetFloatStrings()
void SetFloatStrings (std::string & s1, std::string & s2, std::string & s3, double val1, double val2, double val3) private
Helper function to convert three double values to strings.
Parameters
s1 Reference to first string variable
s2 Reference to second string variable
s3 Reference to third string variable
val1 First double value
val2 Second double value
val3 Third double value
The three double values will be converted to char string by calling function snprintf and the char strings will be assiged to the std strings s1, s2 and s3.
Definition at line 235 of file measurement.cpp.
Referenced by addDispStatistics(), addMaxXYZ(), and reset().
Field Documentation
payload
std::string payload private
the measurement JSON string
Definition at line 71 of file measurement.h.
Referenced by getPayload().
timestamp
std::string timestamp private
the timestamp in JSON string
Definition at line 72 of file measurement.h.
Referenced by addRmsData(), getTimestamp(), and reset().
sDispMin
std::string sDispMin private
Minimum displacement value, to be send to backend with RMS data.
Definition at line 75 of file measurement.h.
Referenced by addDispStatistics(), finalize(), and reset().
sDispMax
std::string sDispMax private
Maximum displacement value, to be send to backend with RMS data.
Definition at line 77 of file measurement.h.
Referenced by addDispStatistics(), finalize(), and reset().
sDispP2P
std::string sDispP2P private
Peak To Peak displacement value, to be send to backend with RMS data.
Definition at line 79 of file measurement.h.
Referenced by addDispStatistics(), finalize(), isComplete(), and reset().
sMaxX
std::string sMaxX private
Maximum x value, to be send to backend with RMS data.
Definition at line 81 of file measurement.h.
Referenced by addMaxXYZ(), finalize(), and reset().
sMaxY
std::string sMaxY private
Maximum y value, to be send to backend with RMS data.
Definition at line 83 of file measurement.h.
Referenced by addMaxXYZ(), finalize(), and reset().
sMaxZ
std::string sMaxZ private
Maximum z value, to be send to backend with RMS data.
Definition at line 85 of file measurement.h.
Referenced by addMaxXYZ(), finalize(), and reset().
max_rms_z
double max_rms_z private
Maximun RMS value in z-direction of one train passing.
Definition at line 87 of file measurement.h.
Referenced by addRmsData(), isComplete(), and reset().
med_hit_cnt
std::vector<int16_t> med_hit_cnt private
Vector to store medium hit counter.
Definition at line 91 of file measurement.h.
Referenced by addRmsData(), finalize(), MeasurementBuilder(), and reset().
crit_hit_cnt
std::vector<int16_t> crit_hit_cnt private
Vector to store critical hit counter.
flag, indicating that http_connector class is present in device SW
Definition at line 93 of file measurement.h.
Referenced by addRmsData(), finalize(), MeasurementBuilder(), and reset().
have_http_connector
bool have_http_connector private
Definition at line 95 of file measurement.h.
Referenced by addRmsData(), and MeasurementBuilder().
The documentation for this class was generated from the following files:
data/measurement.h
data/measurement.cpp