AXO X1: DispTask Class Reference
DispTask Class Reference
Disp class derived from task base class.
#include <disptask.h>
Detailed Description
Disp class derived from task base class.
The displacement task class implements the calulation of the displacement values based on the recorded acceleration data in z-direction. The calculation will be performed in the following steps:
Zero phase highpass filtering
Integration of filtered values to calculate velocity
Integration of velocity to calculate displacement
Removing linear trend from calculated displacement values (detrending) Zero phase highpass filtering:
Zero phase highpass filtering is implemented according to matlab / python filtfilt function. The filter coefficients were taken over from python (see function butter_highpass in file disp_scipy.py in AXOTrack repository).
Integration of filtered values to calculate velocity:
Calculation according to python disp_scipy.py
Integration of velocity to calculate displacement:
Calculation according to python disp_scipy.py
Removing linear trend:
Calculation according to python function signal.detrend().
Definition at line 100 of file disptask.h.
Public Member Functions
DispTask (const char *name="??", bool have_http_connector=true)
Displacement task constructor.
virtual ~DispTask ()
Displacement task destructor.
virtual void task (void)
DispTask task function.
virtual void configure ()
DispTask virtual task configure function.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static int filt_dump (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'f'.
static int itegrate_detrend (const struct shell *shell, size_t argc, char **argv)
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the HW metrics task.
bool bIdle
Flag indicating if calculation is in progress or not.
Private Member Functions
void HandleCalcDisplacementReq (PoolElem *pElem)
Function handle incoming request to calculate displacement values.
void HandleDispFirstEntries (PoolElem *pElem)
Function handle incoming raw data message for left initial condition calculation.
void HandleDispLastEntries (PoolElem *pElem)
Function handle incoming raw data message for right initial condition calculation.
void HandleRawDataStatus (PoolElem *pElem)
Function handle incoming raw data status indication message.
void HandleRawData (PoolElem *pElem)
Function handle incoming raw data message for forward filtering the received data.
void InitBwFiltering ()
Function to initialize the backward filtering.
void HandleFwFiltData (PoolElem *pElem)
Function handle incoming message with forward filtered data and realize the backward filtering.
void InitDispCalc ()
Function to initialize the displacement calculation.
void HandleBwFiltData (PoolElem *pElem)
Function handle incoming message with backward filtered data and realize the displacement calculation (before detrending)
void InitDetrend ()
Function to initialize the detrend calculation.
void HandleSResultData (PoolElem *pElem)
Function handle incoming message with S values (displacement values before detrending)
void reqRawData ()
Function to request raw data from AdxlStore task.
void reqFwFiltData ()
Function to request forward filtered data from AdxlStore task.
void reqBwFiltData ()
Function to request backward filtered data from AdxlStore task.
void reqSResultData ()
Function to request intermediate S result (displacement data before detrending) data from AdxlStore task.
void reqFiltResultWrite (vectord F, enum msgType mType)
Function to request writing of filtered result values into FRAM.
void reqSResultWrite (vectord S)
Function to request writing of S result values into FRAM (displacement data before detrending)
void reqDResultWrite (vectord D)
Function to request writing of D result values into FRAM (displacement data after detrending, final result)
void sendDispStatistics ()
Function to request intermediate S result (displacement data before detrending) data from AdxlStore task.
void calcDisplacement (vectord in, vectord &Vout, vectord &Sout)
Function to calculate displacement before detrending.
void detrendCalcSums (int idx, double inVal, stDetrendVar &v)
Function to calculate intermediate sums for detrending.
void detrendCalcSlopeIntercept (int numValues, stDetrendVar &v)
Function to calculate slope and intercept for detrending.
void detrendRemoveTrend (uint32_t idx, double inp, double &out, stDetrendVar v)
Detrend function to remove a linear trend from a calculated displacement data point
Private Attributes
int nfilt
filter order
int nfact
length of filter edge transients
uint32_t totalNumEntries
Total number of raw data entries.
uint32_t startReadPos
The starting raw data read position.
uint32_t rcvdEntries
Number of received raw data entries.
uint32_t requestedEntries
Number of requested raw data entries.
uint32_t startWritePos
The starting raw data read position.
uint32_t sentEntries
Number of received raw data entries.
uint32_t requestedWrEntries
uint32_t detrendIdx
vectord leftpad
filtering (calculation of initial conditions based on Matlab)
vectord rightpad
filtering (calculation of initial conditions based on Matlab)
vectord leftpadFilt
Forward filtered left initial conditions.
vectord rightpadFilt
Forward filtered right initial conditions.
vectord leftpadFiltFilt
Forward and backward filtered left initial conditions.
vectord rightpadFiltFilt
Forward and backward filtered right initial conditions.
stDetrendVar detrendVars
Structure to store intermediate results for detrend calculation.
uint32_t dVIdx
Current data point index.
double V_last
double S_last
Previous displacement value S(n-1), before detrending.
double IN_last
bool have_http_connector
flag deciding if data are sent to http connector
double dispMin
Minimum displacement value, to be send to backend with RMS data.
double dispMax
Maximum displacement value, to be send to backend with RMS data.
double dispP2P
Peak To Peak displacement value, to be send to backend with RMS data.
double b1
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
DispTask()
DispTask (const char * name = "??", bool have_http_connector = true) explicit
Displacement task constructor.
Parameters
name The name of the class
have_http_connector Flag indicationg if HTTP Connector is used (X1 devices) or not (MINI devices)
The constructor initialize variable bIdle and filter coefficents vectors. Filter coefficents are taken over from python implementation in AXOTrack repository. It allocate and register the tasks mailbox and initialize the zero phase highpass filter with call of function filtfilt_init provided by class CFilter.
Definition at line 61 of file disptask.cpp.
References bIdle, Mbox::eDispTask, CFilter::filtfilt_init(), have_http_connector, CFilter::inst(), pInMbox, and Mbox::registerMbox().
~DispTask()
~DispTask () virtual
Displacement task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 86 of file disptask.cpp.
Member Function Documentation
task()
void task (void) virtual
DispTask task function.
The function directly enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eCalcDisplacementReq: Member function HandleCalcDisplacementReq will be called with message pointer pElem as parameter.
eRawDataStatus: Member function HandleRawDataStatus will be called with message pointer pElem as parameter.
eDispFirstEntries: Member function HandleDispFirstEntries will be called with message pointer pElem as parameter.
eDispLastEntries: Member function HandleDispLastEntries will be called with message pointer pElem as parameter.
eRawData: Member function HandleRawData will be called with message pointer pElem as parameter.
eStoredFwFiltVals: Member function InitBwFiltering will be called.
eFwFiltData: Member function HandleFwFiltData will be called with message pointer pElem as parameter.
eStoredBwFiltVals: Member function InitDispCalc will be called.
eBwFiltData: Member function HandleBwFiltData will be called with message pointer pElem as parameter.
eStoredSResultVals: Member function InitDetrend will be called.
eSResultData: Member function HandleSResultData will be called with message pointer pElem as parameter.
eStoredDResultVals: Flag bIdle will be set to true, to indicate that displacement calculation has been finished and message eSendDispDataReq will be send to HTTP Connector to start transmission of displacement data to HTTP server.
Implements Task.
Definition at line 1107 of file disptask.cpp.
References bIdle, eBwFiltData, eCalcDisplacementReq, eDispFirstEntries, eDispLastEntries, eFwFiltData, eRawData, eRawDataStatus, eSendDispDataReq, eSResultData, eStoredBwFiltVals, eStoredDResultVals, eStoredFwFiltVals, eStoredSResultVals, PoolElem::free(), HandleBwFiltData(), HandleCalcDisplacementReq(), HandleDispFirstEntries(), HandleDispLastEntries(), HandleFwFiltData(), HandleRawData(), HandleRawDataStatus(), HandleSResultData(), have_http_connector, InitBwFiltering(), InitDetrend(), InitDispCalc(), PoolElem::mtype, Task::myName, pInMbox, Mbox::read(), Mbox::sendMsg(), and UNIT_TEST_STOP_LOOP.
configure()
void configure () virtual
DispTask virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to datalog by call of the function getCfgDisplacement provided by the Config class and set the beautification factor b1 according to the configuration values.
Reimplemented from Task.
Definition at line 97 of file disptask.cpp.
References _stCfgDisplacement::b1, b1, Config::getCfgDisplacement(), and Config::inst().
Referenced by main().
filt_dump()
int filt_dump (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'f'.
The function send a message of type eCalcDisplacementReq to its own (DispTask) mailbox.
Note
For testing only: trigger to start displacement calculation via shell command.
Definition at line 1202 of file disptask.cpp.
References eCalcDisplacementReq, and Mbox::sendMsg().
itegrate_detrend()
static int itegrate_detrend (const struct shell * shell, size_t argc, char ** argv) static
HandleCalcDisplacementReq()
void HandleCalcDisplacementReq (PoolElem * pElem) private
Function handle incoming request to calculate displacement values.
Parameters
pElem The incoming message with the request
The function set flag bIdle to false, indicating that displacement calculation is ongoing and send message eRawDataStatus to ADXL store task to retrieve number of raw data entries among other informations.
Definition at line 177 of file disptask.cpp.
References bIdle, eRawDataStatus, and Mbox::sendMsg().
Referenced by task().
HandleDispFirstEntries()
void HandleDispFirstEntries (PoolElem * pElem) private
Function handle incoming raw data message for left initial condition calculation.
Parameters
pElem The incoming message with the indication
The function extracts a structure of type adxl372_xyz_accel_data from the message payload and initialize a vector Z of type double with length nfact + 2 and the initial values 0. Than the function enters a loop and convert the received z raw values to double and copy them to the vector Z. With call of function prepare_leftpad provided by class CFilter the left initial conditions will be calculated and stored in vector leftpad. By calling function fwfilter_init the forward filtering will be prepaired and with call of function filterFirstIter also provided by class CFilter the first filter iteration will be initiated with the values in vector leftpad. Afterwards a structure of type AdxlRawDataProgress will be filled with start read position, the number of currently received entries, which in this case is totalNumEntries - (nfact + 1) to get the last recorded samples. Additionally the number of requested entries will be assigned, which is nfact + 1. Finally a message of type eDispLastEntries is send to ADXL store task to retrieve the last raw data values, which than will be used to calculate right initial conditions.
Definition at line 254 of file disptask.cpp.
References Adxl37x::convert(), eDispLastEntries, CFilter::filterFirstIter(), CFilter::fwfilter_init(), PoolElem::getBuffer(), CFilter::inst(), leftpad, leftpadFilt, nfact, CFilter::prepare_leftpad(), AdxlRawDataProgress::rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), AdxlRawDataProgress::startRd, totalNumEntries, and adxl372_xyz_accel_data::z.
Referenced by task().
HandleDispLastEntries()
void HandleDispLastEntries (PoolElem * pElem) private
Function handle incoming raw data message for right initial condition calculation.
Parameters
pElem The incoming message with the indication
The function extracts a structure of type adxl372_xyz_accel_data from the message payload and initialize a vector Z of type double with length nfact + 1 and the initial values 0. Than the function enters a loop and convert the received z raw values to double and copy them to the vector Z. With call of function prepare_rightpad provided by class CFilter the right initial conditions will be calculated and stored in vector rightpad. Afterwards the first raw data entries will be requested by call of function reqRawData and finally the member variable sentEntries will be initialized with 0.
Definition at line 446 of file disptask.cpp.
References Adxl37x::convert(), PoolElem::getBuffer(), CFilter::inst(), nfact, CFilter::prepare_rightpad(), reqRawData(), rightpad, sentEntries, and adxl372_xyz_accel_data::z.
Referenced by task().
HandleRawDataStatus()
void HandleRawDataStatus (PoolElem * pElem) private
Function handle incoming raw data status indication message.
Parameters
pElem The incoming message with the indication
The function extracts a structure of type AdxlRawDataStatus from the message payload and assign start read position and number of samples within structure to the member variables startReadPos and totalNumEntries. Member variable rcvdEntries will be initialized with 0. Please note, that start read position allways points to the beginning of the complete data area, not to the current read position. In case number of samples is greater than zero, the function retrieves the filter order and the length of edge transients, provided by class CFilter and assign it to the member variables nfact and nfilt. Afterward a structure of type AdxlRawDataProgress will be filled with start read position, the number of currently received entries, which in this case is 0 and with the number of requested entries, which is nfact + 2. A message of type eDispFirstEntries is than send to ADXL store task to retrieve the first raw data values, which than will be used to calculate left initial conditions. If number of samples is not greater than 0, the flag bIdle is set to true and the function returns.
Definition at line 204 of file disptask.cpp.
References bIdle, eDispFirstEntries, AdxlRawDataStatus::entries, PoolElem::getBuffer(), CFilter::getNfact(), CFilter::getNfilt(), CFilter::inst(), nfact, nfilt, AdxlRawDataProgress::rcvdEntries, rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), AdxlRawDataStatus::startRd, AdxlRawDataProgress::startRd, startReadPos, and totalNumEntries.
Referenced by task().
HandleRawData()
void HandleRawData (PoolElem * pElem) private
Function handle incoming raw data message for forward filtering the received data.
Parameters
pElem The incoming message with the raw data
The function increases received entries in member variable rcvdEntries by the number of previously requested enttries and extracts a structure of type adxl372_xyz_accel_data from the message payload and initialize a vector Z of type double with a length of requestedEntries the initial values 0. Than the function enters a loop and convert the received z raw values to double and copy them to the vector Z. With call of function filterNthIter provided by class CFilter the raw data will be
forward filtered and the result will be stored stored in vector filterOutput. By call of member function reqFiltResultWrite the storage of the filtered data in FRAM will be initiated. Afterwards the function checks, if number of received entries is equal to the total number of entries and in this case function filterLastIter will be called with the initial conditions in vector rightpad, the result will be stored in vector rightpadFilt.
Otherwise new raw data will be requested from ADXL store by call of member function reqRawData.
Definition at line 665 of file disptask.cpp.
References Adxl37x::convert(), eStoreFwFiltResult, CFilter::filterLastIter(), CFilter::filterNthIter(), PoolElem::getBuffer(), CFilter::inst(), rcvdEntries, reqFiltResultWrite(), reqRawData(), requestedEntries, rightpad, rightpadFilt, totalNumEntries, and adxl372_xyz_accel_data::z.
Referenced by task().
InitBwFiltering()
void InitBwFiltering () private
Function to initialize the backward filtering.
The function deletes the first nfilt values from vectror rightpadFilt, reverse the vectors leftpadFilt and rightpadFilt by call of function reverse and call the functions bwfilter_init and filterFirstIter, provided by class CFilter with input vector rightpadFilt. The result of the backward filtering will be stored in vector rightpadFiltFilt. Afterward the member variables rcvdEntries and startReadPos will be initialized with 0 before calling member function reqFwFiltData to request the first forward filtered data stored in FRAM. Finally the number of still sent entries in member variable sentEntries will be set to 0.
Definition at line 718 of file disptask.cpp.
References CFilter::bwfilter_init(), CFilter::filterFirstIter(), CFilter::inst(), leftpadFilt, nfilt, rcvdEntries, reqFwFiltData(), rightpadFilt, rightpadFiltFilt, sentEntries, and startReadPos.
Referenced by task().
HandleFwFiltData()
void HandleFwFiltData (PoolElem * pElem) private
Function handle incoming message with forward filtered data and realize the backward filtering.
Parameters
pElem The incoming message with the raw data
The function increases received entries in member variable rcvdEntries by the number of previously requested enttries and extracts the forward filtered data from the message payload and initialize a vector FwFilt of type double with a length of requestedEntries the initial values 0. Than the function enters a loop and copy the received forward filtered values from message payload into the vector FwFilt. With call of function filterNthIter provided by class CFilter the forward filtered data will be backward filtered and the result will be stored in vector filterOutput. By call of member function reqFiltResultWrite the storage of the filtered data in FRAM will be initiated. Afterwards the function checks, if number of received entries is equal to the total number of entries and in this case function filterLastIter will be called with the forward filtered initial conditions in vector leftpadFilt, the result will be stored in vector leftpadFiltFilt. Otherwise new forward filtered data will be requested from ADXL store by call of member function reqFwFiltData.
Definition at line 760 of file disptask.cpp.
References eStoreBwFiltResult, CFilter::filterLastIter(), CFilter::filterNthIter(), PoolElem::getBuffer(), CFilter::inst(), leftpadFilt, leftpadFiltFilt, rcvdEntries, reqFiltResultWrite(), reqFwFiltData(), requestedEntries, and totalNumEntries.
Referenced by task().
InitDispCalc()
void InitDispCalc () private
Function to initialize the displacement calculation.
The function initialize the sum variables in structure detrendVars with 0, afterwards the member variables rcvdEntries, startReadPos and startWritePos will be initialized with 0 before calling member function reqBwFiltData to request the first backward filtered data stored in FRAM. and set number of still sent entries in member variable sentEntries to 0. Finally current data point index is set to 1, previous velocity value V_last, previous displacement value S_last and previous input value IN_last will initialized with 0.
Definition at line 809 of file disptask.cpp.
References detrendVars, dVIdx, IN_last, rcvdEntries, reqBwFiltData(), S_last, sentEntries, startReadPos, startWritePos, _stDetrendVar::sumX, _stDetrendVar::sumX2, _stDetrendVar::sumXY, _stDetrendVar::sumY, and V_last.
Referenced by task().
HandleBwFiltData()
void HandleBwFiltData (PoolElem * pElem) private
Function handle incoming message with backward filtered data and realize the displacement calculation (before detrending)
Parameters
pElem The incoming message with the raw data
The function increases received entries in member variable rcvdEntries by the number of previously requested enttries, extracts the backward filtered data from the message payload and initialize the vector FwFilt of type double with a length of requestedEntries the initial values 0. Furthermore two output vectors VOutput and SOutput for the velocity and the displacement values before detrending will be also initialized with a length of requestedEntries and initial values 0. Than the function enters a loop and copy the received backward filtered values from message payload into the vector BwFilt. With call of member function calcDisplacement velocity and displacement will be calculated and stored in the vectors VOutput and SOutput. By call of member function reqSResultWrite the storage of the calculated displacement (S) values in FRAM will be initiated. Afterwards the function checks, if number of received entries is unequal to the total number of entries and in this case new backward filtered data will be requested from ADXL store by call of member function reqBwFiltData.
Definition at line 911 of file disptask.cpp.
References calcDisplacement(), PoolElem::getBuffer(), rcvdEntries, reqBwFiltData(), reqSResultWrite(), requestedEntries, and totalNumEntries.
Referenced by task().
InitDetrend()
void InitDetrend () private
Function to initialize the detrend calculation.
The function initialize the index detrendIdx in with 0 and calculate slope and intercept value by calling member function detrendCalcSlopeIntercept. Afterwards the member variables rcvdEntries, startReadPos and startWritePos will be initialized with 0 before calling member function reqSResultData to request the first S values (displacement values before detrending) stored in FRAM. Finally the number of still sent entries in member variable sentEntries to 0.
Definition at line 962 of file disptask.cpp.
References detrendCalcSlopeIntercept(), detrendIdx, detrendVars, dispMax, dispMin, dispP2P, NUM_FILT_REMOVE, rcvdEntries, reqSResultData(), sentEntries, startReadPos, startWritePos, and totalNumEntries.
Referenced by task().
HandleSResultData()
void HandleSResultData (PoolElem * pElem) private
Function handle incoming message with S values (displacement values before detrending)
Parameters
pElem The incoming message with the raw data
The function increases received entries in member variable rcvdEntries by the number of previously requested enttries, extracts the displacement data from the message payload and initialize the vector SResult of type double with a length of requestedEntries the initial values 0. Furthermore output vector DOutput for the the displacement values after detrending will be also initialized with a length of requestedEntries and initial values 0. Than the function enters a loop and copy the received S values from message payload into the vector SResult. By checking the current detrend index the output values in range [0, NUM_FILT_REMOVE] and [totalNumEntries - NUM_FILT_REMOVE - 1, totalNumEntries -1] will be set to 0. Outside of these ranges the output values will be calculated by call of function detrendRemoveTrend, which removes the linear trend from the input data. At the end of the loop
detrendIdx will be incremented by 1.
By call of member function reqDResultWrite the storage of the calculated displacement (D) values in FRAM will be initiated. Afterwards the function checks, if number of received entries is unequal to the total number of entries and in this case new S result data will be requested from ADXL store by call of member function reqSResultData.
Definition at line 1005 of file disptask.cpp.
References b1, detrendIdx, detrendRemoveTrend(), detrendVars, dispMax, dispMin, dispP2P, PoolElem::getBuffer(), NUM_FILT_REMOVE, rcvdEntries, reqDResultWrite(), reqSResultData(), requestedEntries, sendDispStatistics(), and totalNumEntries.
Referenced by task().
reqRawData()
void reqRawData () private
Function to request raw data from AdxlStore task.
By calling function sendMsg provided by Mbox class the method request raw data from AdxlStore task with message type eRawData. In the payload of the message a structure of type struct AdxlRawDataProgress will be copied by function sendMsg. The structure contains the read position of the first raw data entry, the number of currently received raw data entries and the number of currently requested raw data entries.
Definition at line 295 of file disptask.cpp.
References eRawData, MAX_NUM_REQ_ENTRIES, AdxlRawDataProgress::rcvdEntries, rcvdEntries, AdxlRawDataProgress::requestedEntries, requestedEntries, Mbox::sendMsg(), AdxlRawDataProgress::startRd, startReadPos, and totalNumEntries.
Referenced by HandleDispLastEntries(), and HandleRawData().
reqFwFiltData()
void reqFwFiltData () private
Function to request forward filtered data from AdxlStore task.
By calling function sendMsg provided by Mbox class the method request forward filtered data from AdxlStore task with message type eFwFiltData. In the payload of the message a structure of type struct AdxlRawDataProgress will be copied by function sendMsg. The structure contains the read position of the first forward filtered data entry, the number of currently received forward filtered data entries and the number of currently requested forward filtered data entries.
Definition at line 325 of file disptask.cpp.
References eFwFiltData, MAX_NUM_REQ_ENTRIES, AdxlRawDataProgress::rcvdEntries, rcvdEntries, AdxlRawDataProgress::requestedEntries, requestedEntries, Mbox::sendMsg(), AdxlRawDataProgress::startRd, startReadPos, and totalNumEntries.
Referenced by HandleFwFiltData(), and InitBwFiltering().
reqBwFiltData()
void reqBwFiltData () private
Function to request backward filtered data from AdxlStore task.
By calling function sendMsg provided by Mbox class the method request backward filtered data from AdxlStore task with message type eBwFiltData. In the payload of the message a structure of type struct AdxlRawDataProgress will be copied by function sendMsg. The structure contains the read position of the first backward filtered data entry, the number of currently received backward filtered data entries and the number of currently requested backward filtered data entries.
Definition at line 355 of file disptask.cpp.
References eBwFiltData, MAX_NUM_REQ_ENTRIES, AdxlRawDataProgress::rcvdEntries, rcvdEntries, AdxlRawDataProgress::requestedEntries, requestedEntries, Mbox::sendMsg(), AdxlRawDataProgress::startRd, startReadPos, and totalNumEntries.
Referenced by HandleBwFiltData(), and InitDispCalc().
reqSResultData()
void reqSResultData () private
Function to request intermediate S result (displacement data before detrending) data from AdxlStore task.
By calling function sendMsg provided by Mbox class the method request S result data from AdxlStore task with message type eSResultData. In the payload of the message a structure of type struct AdxlRawDataProgress will be copied by function sendMsg. The structure contains the read position of the first S result data entry, the number of currently received S result data entries and the number of currently requested S result data entries.
Definition at line 386 of file disptask.cpp.
References eSResultData, MAX_NUM_REQ_ENTRIES, AdxlRawDataProgress::rcvdEntries, rcvdEntries, AdxlRawDataProgress::requestedEntries, requestedEntries, Mbox::sendMsg(), AdxlRawDataProgress::startRd, startReadPos, and totalNumEntries.
Referenced by HandleSResultData(), and InitDetrend().
reqFiltResultWrite()
void reqFiltResultWrite (vectord F, enum msgType mType) private
Function to request writing of filtered result values into FRAM.
Parameters
F Vector of type double with the filtered result values
mType The message type to be send to ADXL store task
The function initialize the remaining entries to write in variable remainingWrEntries and set variable requestedWrEntries to the maximum number of requested entries MAX_NUM_REQ_ENTRIES. In case remainingWrEntries are less than MAX_NUM_REQ_ENTRIES variable requestedWrEntries will be set to remainingWrEntries. Afterwards start write address will be assigned in structure progress of type AdxlFilterDataProgress in dependency of for- or backward filter results indicated by parameter mType. Start write address will be than readjusted. Please note, that the result vector will be stored in reverse order to be in correct direction for the next calculation step (for backward filtering or correct order after backward filtering). Structure progress will be filled with number of still sent entries and number of requested write entries. Afterwards the values in vector S will be stored in a temporary array in reverse order and copied in structure progress. By calling function sendMsg provided by class Mbox a message of type mType will be send to ADXL store task with structure progress in the payload. Finally member variable sentEntries will be increased by requestedWrEntries.
Definition at line 487 of file disptask.cpp.
References BW_D_START_ADDR, AdxlFilterDataProgress::data, eStoreBwFiltResult, eStoreFwFiltResult, FW_S_START_ADDR, MAX_NUM_REQ_ENTRIES, nfilt, AdxlFilterDataProgress::requestedEntries, requestedWrEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, sentEntries, AdxlFilterDataProgress::startWr, and totalNumEntries.
Referenced by HandleFwFiltData(), and HandleRawData().
reqSResultWrite()
void reqSResultWrite (vectord S) private
Function to request writing of S result values into FRAM (displacement data before detrending)
Parameters
S Vector of type double with the S result values
The function initialize the remaining entries to write in variable remainingWrEntries and set variable requestedWrEntries to the maximum number of requested entries MAX_NUM_REQ_ENTRIES. In case remainingWrEntries are less than MAX_NUM_REQ_ENTRIES variable requestedWrEntries will be set to remainingWrEntries. Afterwards start write address will be assigned in structure progress of type AdxlFilterDataProgress with FW_S_START_ADDR plus number of still sent entries multiplied by sizeof data type double. Structure progress will be filled with number of still sent entries and
number of requested write entries. Afterwards the values in vector S will be stored in a temporary array and copied in structure progress. By calling function sendMsg provided by class Mbox a message of type eStoreSResult will be send to ADXL store task with structure progress in the payload. Finally the member variables sentEntries and startWritePos will be increased by requestedWrEntries.
Definition at line 556 of file disptask.cpp.
References AdxlFilterDataProgress::data, eStoreSResult, FW_S_START_ADDR, MAX_NUM_REQ_ENTRIES, AdxlFilterDataProgress::requestedEntries, requestedWrEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, sentEntries, AdxlFilterDataProgress::startWr, startWritePos, and totalNumEntries.
Referenced by HandleBwFiltData().
reqDResultWrite()
void reqDResultWrite (vectord D) private
Function to request writing of D result values into FRAM (displacement data after detrending, final result)
Parameters
D Vector of type double with the D result values
The function initialize the remaining entries to write in variable remainingWrEntries and set variable requestedWrEntries to the maximum number of requested entries MAX_NUM_REQ_ENTRIES. In case remainingWrEntries are less than MAX_NUM_REQ_ENTRIES variable requestedWrEntries will be set to remainingWrEntries. Afterwards start write address will be assigned in structure progress of type AdxlFilterDataProgress with BW_D_START_ADDR plus number of still sent entries multiplied by sizeof data type double. Structure progress will be filled with number of still sent entries and
number of requested write entries. Afterwards the values in vector D will be stored in a temporary array and copied in structure progress. By calling function sendMsg provided by class Mbox a message of type eStoreDResult will be send to ADXL store task with structure progress in the payload. Finally the member variables sentEntries and startWritePos will be increased by requestedWrEntries.
Definition at line 610 of file disptask.cpp.
References BW_D_START_ADDR, AdxlFilterDataProgress::data, eStoreDResult, MAX_NUM_REQ_ENTRIES, AdxlFilterDataProgress::requestedEntries, requestedWrEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, sentEntries, AdxlFilterDataProgress::startWr, startWritePos, and totalNumEntries.
Referenced by HandleSResultData().
sendDispStatistics()
void sendDispStatistics () private
Function to request intermediate S result (displacement data before detrending) data from AdxlStore task.
By calling function sendMsg provided by Mbox class the method request S result data from AdxlStore task with message type eSResultData. In the payload of the message a structure of type struct AdxlRawDataProgress will be copied by function sendMsg. The structure contains the read position of the first S result data entry, the number of currently received S result data entries and the number of currently requested S result data entries.
Definition at line 417 of file disptask.cpp.
References dispMax, dispMin, dispP2P, eDispStatistics, _stDispStatistics::max, _stDispStatistics::min, _stDispStatistics::p2p, and Mbox::sendMsg().
Referenced by HandleSResultData().
calcDisplacement()
void calcDisplacement (vectord in, vectord & Vout, vectord & Sout) private
Function to calculate displacement before detrending.
Parameters
in Incoming vector of type double with for- and backward filtered values
Vout Output vector with the integrated velocity values
Sout Output vector with the integrated displacement values before detrending
The function initialize the current data index idx with difference of received entries minus requested entries. To avoid the influence of transient response of the filtering the first and last NUM_FILT_REMOVE entries will be deleted by setting them to 0. By checking the current data index the output values in range [0, NUM_FILT_REMOVE] and [totalNumEntries - NUM_FILT_REMOVE - 1, totalNumEntries -1] will be set to 0. Outside of these ranges the output values of the velocity Vout will be calculated by integration of the filtered input values and the displacement values before detrending Sout will be calculated by integration of the velocity.
Definition at line 848 of file disptask.cpp.
References DELTA_T, detrendCalcSums(), detrendVars, dVIdx, IN_last, NUM_FILT_REMOVE, rcvdEntries, requestedEntries, S_last, totalNumEntries, and V_last.
Referenced by HandleBwFiltData().
detrendCalcSums()
void detrendCalcSums (int idx, double inVal, stDetrendVar & v) private
Function to calculate intermediate sums for detrending.
Parameters
idx The current index of the data point
inVal The current data point
v Structure of type stDetrendVar with the intermediate calculated sums
This function is called whenever new S data (displacement data before detrending) has been calculated. For every data point the sums in structure v will updated.
Definition at line 121 of file disptask.cpp.
References _stDetrendVar::sumX, _stDetrendVar::sumX2, _stDetrendVar::sumXY, and _stDetrendVar::sumY.
Referenced by calcDisplacement().
detrendCalcSlopeIntercept()
void detrendCalcSlopeIntercept (int numValues, stDetrendVar & v) private
Function to calculate slope and intercept for detrending.
Parameters
numValues The total number of data points
v Structure of type stDetrendVar with the intermediate results
This function calculate slope and intercept for detrending and store the calculated values in structure v.
Definition at line 138 of file disptask.cpp.
References _stDetrendVar::intercept, _stDetrendVar::slope, _stDetrendVar::sumX, _stDetrendVar::sumX2, _stDetrendVar::sumXY, and _stDetrendVar::sumY.
Referenced by InitDetrend().
detrendRemoveTrend()
void detrendRemoveTrend (uint32_t idx, double inp, double & out, stDetrendVar v) private
Detrend function to remove a linear trend from a calculated displacement data point
Parameters
idx The current index of the data point
inp The current data point
out The detrended data point
v Structure of type stDetrendVar with the intermediate results
This function calculate detrended value for one data point at index idx.
Definition at line 162 of file disptask.cpp.
References _stDetrendVar::intercept, and _stDetrendVar::slope.
Referenced by HandleSResultData().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the HW metrics task.
Definition at line 108 of file disptask.h.
Referenced by DispTask(), and task().
bIdle
bool bIdle
Flag indicating if calculation is in progress or not.
Definition at line 109 of file disptask.h.
Referenced by DispTask(), HandleCalcDisplacementReq(), HandleRawDataStatus(), and task().
nfilt
int nfilt private
filter order
Definition at line 115 of file disptask.h.
Referenced by HandleRawDataStatus(), InitBwFiltering(), and reqFiltResultWrite().
nfact
int nfact private
length of filter edge transients
Definition at line 116 of file disptask.h.
Referenced by HandleDispFirstEntries(), HandleDispLastEntries(), and HandleRawDataStatus().
totalNumEntries
uint32_t totalNumEntries private
Total number of raw data entries.
Definition at line 117 of file disptask.h.
Referenced by calcDisplacement(), HandleBwFiltData(), HandleDispFirstEntries(), HandleFwFiltData(), HandleRawData(), HandleRawDataStatus(), HandleSResultData(), InitDetrend(), reqBwFiltData(), reqDResultWrite(), reqFiltResultWrite(), reqFwFiltData(), reqRawData(), reqSResultData(), and reqSResultWrite().
startReadPos
uint32_t startReadPos private
The starting raw data read position.
Definition at line 118 of file disptask.h.
Referenced by HandleRawDataStatus(), InitBwFiltering(), InitDetrend(), InitDispCalc(), reqBwFiltData(), reqFwFiltData(), reqRawData(), and reqSResultData().
rcvdEntries
uint32_t rcvdEntries private
Number of received raw data entries.
Definition at line 119 of file disptask.h.
Referenced by calcDisplacement(), HandleBwFiltData(), HandleFwFiltData(), HandleRawData(), HandleRawDataStatus(), HandleSResultData(), InitBwFiltering(), InitDetrend(), InitDispCalc(), reqBwFiltData(), reqFwFiltData(), reqRawData(), and reqSResultData().
requestedEntries
uint32_t requestedEntries private
Number of requested raw data entries.
Definition at line 120 of file disptask.h.
Referenced by calcDisplacement(), HandleBwFiltData(), HandleFwFiltData(), HandleRawData(), HandleSResultData(), reqBwFiltData(), reqFwFiltData(), reqRawData(), and reqSResultData().
startWritePos
uint32_t startWritePos private
The starting raw data read position.
Definition at line 122 of file disptask.h.
Referenced by InitDetrend(), InitDispCalc(), reqDResultWrite(), and reqSResultWrite().
sentEntries
uint32_t sentEntries private
Number of received raw data entries.
Definition at line 123 of file disptask.h.
Referenced by HandleDispLastEntries(), InitBwFiltering(), InitDetrend(), InitDispCalc(), reqDResultWrite(), reqFiltResultWrite(), and reqSResultWrite().
requestedWrEntries
uint32_t requestedWrEntries private
Number of requested raw data entries
Definition at line 124 of file disptask.h.
Referenced by reqDResultWrite(), reqFiltResultWrite(), and reqSResultWrite().
detrendIdx
uint32_t detrendIdx private
Current index to calculate intermediate sum values for detrend calculation
Definition at line 127 of file disptask.h.
Referenced by HandleSResultData(), and InitDetrend().
leftpad
vectord leftpad private
filtering (calculation of initial conditions based on Matlab)
Vector of type double to store the initial conditions for forward
Definition at line 131 of file disptask.h.
Referenced by HandleDispFirstEntries().
rightpad
vectord rightpad private
filtering (calculation of initial conditions based on Matlab)
Vector of type double to store the initial conditions for backward
Definition at line 134 of file disptask.h.
Referenced by HandleDispLastEntries(), and HandleRawData().
leftpadFilt
vectord leftpadFilt private
Forward filtered left initial conditions.
Definition at line 136 of file disptask.h.
Referenced by HandleDispFirstEntries(), HandleFwFiltData(), and InitBwFiltering().
rightpadFilt
vectord rightpadFilt private
Forward filtered right initial conditions.
Definition at line 138 of file disptask.h.
Referenced by HandleRawData(), and InitBwFiltering().
leftpadFiltFilt
vectord leftpadFiltFilt private
Forward and backward filtered left initial conditions.
Definition at line 140 of file disptask.h.
Referenced by HandleFwFiltData().
rightpadFiltFilt
vectord rightpadFiltFilt private
Forward and backward filtered right initial conditions.
Definition at line 142 of file disptask.h.
Referenced by InitBwFiltering().
detrendVars
stDetrendVar detrendVars private
Structure to store intermediate results for detrend calculation.
Definition at line 145 of file disptask.h.
Referenced by calcDisplacement(), HandleSResultData(), InitDetrend(), and InitDispCalc().
dVIdx
uint32_t dVIdx private
Current data point index.
Definition at line 146 of file disptask.h.
Referenced by calcDisplacement(), and InitDispCalc().
V_last
double V_last private
Previous velocity value V(n-1)
Definition at line 147 of file disptask.h.
Referenced by calcDisplacement(), and InitDispCalc().
S_last
double S_last private
Previous displacement value S(n-1), before detrending.
Definition at line 149 of file disptask.h.
Referenced by calcDisplacement(), and InitDispCalc().
IN_last
double IN_last private
Previous input (backward filtered) value in(n-1) for velocity calulation
Definition at line 152 of file disptask.h.
Referenced by calcDisplacement(), and InitDispCalc().
have_http_connector
bool have_http_connector private
flag deciding if data are sent to http connector
Definition at line 155 of file disptask.h.
Referenced by DispTask(), and task().
dispMin
double dispMin private
Minimum displacement value, to be send to backend with RMS data.
Definition at line 158 of file disptask.h.
Referenced by HandleSResultData(), InitDetrend(), and sendDispStatistics().
dispMax
double dispMax private
Maximum displacement value, to be send to backend with RMS data.
Definition at line 160 of file disptask.h.
Referenced by HandleSResultData(), InitDetrend(), and sendDispStatistics().
dispP2P
double dispP2P private
Peak To Peak displacement value, to be send to backend with RMS data.
Definition at line 162 of file disptask.h.
Referenced by HandleSResultData(), InitDetrend(), and sendDispStatistics().
b1
double b1 private
Beautification factor b1, multiplication factor for displacement Minimum and Maximum values
Definition at line 166 of file disptask.h.
Referenced by configure(), and HandleSResultData().
The documentation for this class was generated from the following files:
disp/disptask.h
disp/disptask.cpp