AXO X1: FwUpd Class Reference
FwUpd Class Reference
Firmware update task class derived from task base class.
#include <update.h>
Detailed Description
Firmware update task class derived from task base class.
Detailed Description
The firmware update task implements the interface to the FOTA download library. It starts the download process and receives the FOTA download event. It provides a callback function to receive and process the FOTA events, a function to start the download process and functions to call on download success and download failure. Furthermore two setter functions to set the name of the host, which is the server to download from and name of the binary file to be downloaded.
Receive
FOTA download events via callback function
Firmware update control task
Transmit
Firmware update control task
Definition at line 70 of file update.h.
Public Types
enum { max_filename_size = 80 }
enum { max_hostname_size = 80 }
Public Member Functions
FwUpd (const char *name="??")
Firmware update task constructor.
virtual ~FwUpd ()
Firmware update control task destructor.
virtual void task (void)
Firmware update task function.
void setUrl (const char *url)
void setHostname (std::string name)
Setter function to set the hostname.
void setFilename (std::string name)
Setter function to set the filename.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void fota_dl_handler (const struct fota_download_evt *evt)
Callback function to receive the FOTA download events.
static void download_failed (int error_code=3)
Send OTA Failure event message to firmware update control task.
static void download_success (void)
Send OTA Success event message to firmware update control task.
static void download_start (void)
Function to start the OTA download process.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the firmware update task.
uint8_t sha1_expected [41]
int32_t size_expected
Expected file size from fw_info.
Static Public Attributes
static char filename [max_filename_size]
static char hostname [max_hostname_size]
Private Member Functions
FwUpd ()=delete
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
max_filename_size
Definition at line 89 of file update.h.
anonymous enum
anonymous enum
Enumerator
max_hostname_size
Definition at line 94 of file update.h.
Constructor & Destructor Documentation
FwUpd() [1/2]
FwUpd (const char * name = "??") explicit
Firmware update task constructor.
Parameters
name The name of the class
The constructor allocates and register the mailbox of the task.
Definition at line 55 of file update.cpp.
References Mbox::eFwUpd, pInMbox, and Mbox::registerMbox().
~FwUpd()
~FwUpd () virtual
Firmware update control task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 67 of file update.cpp.
FwUpd() [2/2]
FwUpd () private delete
Member Function Documentation
task()
void task (void) virtual
Firmware update task function.
Initially the task function calls function boot_write_img_confirmed provided by the MCUboot API. This marks the currently running image as confirmed, which will install it permanently, preventing MCUboot from reverting it for an older image at the next reset.
Afterwards the function fota_download_init, provided by the FOTA download library of the nRF Connect SDK, will be called to initialize the firmware over-the-air download library.
The function than enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eFwInfo: The function allocates an object of type FwInfo and call its method parse to parse the JSON string and to extract the download parameters. To check the validity of the parameters method validate will be called. It extracts the size of the firmware binary and the sha1 checksum and write to download library with call of function fota_download_set_expected provided by the FOTA download library ofthe nRF Connect SDK. With a call of method splitUrl of the FwInfo instance the received URL will be split into host (the http server to download from) and filename (File to request in download) and both will be stored in the member variables hostname and filename by calling the appropriate setter functions. Finally the download will be started by calling the member function download_start.
eFwDownload: Download will be retried because of a previous failure by calling the member function download_start.
Implements Task.
Definition at line 233 of file update.cpp.
References download_start(), eFwDownload, eFwInfo, fota_dl_handler(), PoolElem::free(), FwInfo::getFileName(), FwInfo::getFileSize(), FwInfo::getHost(), FwInfo::getProto(), FwInfo::getSha1(), PoolElem::mtype, Task::myName, FwInfo::parse(), pInMbox, Mbox::read(), setFilename(), setHostname(), sha1_expected, size_expected, FwInfo::splitUrl(), UNIT_TEST_STOP_LOOP, and FwInfo::validate().
fota_dl_handler()
void fota_dl_handler (const struct fota_download_evt * evt) static
Callback function to receive the FOTA download events.
Parameters
evt Pointer to the event of type struct fota_download_evt
The function checks the event ID. In case the event ID is FOTA_DOWNLOAD_EVT_ERROR or FOTA_DOWNLOAD_EVT_CANCELLED member function download_failed will be called with an appropriate error code. In case the event ID is FOTA_DOWNLOAD_EVT_FINISHED member function download_success will be called. On unexpected event IDs a debug message at error level will be printed.
Definition at line 105 of file update.cpp.
References download_failed(), and download_success().
Referenced by task().
download_failed()
void download_failed (int error_code = 3) static
Send OTA Failure event message to firmware update control task.
The function defines the JSON string with the OTA Failure event, request a message from message pool, set message type to eFwDlFailed, set eFwUpd as sender, copy the JSON string in the message payload, retrieve a pointer to the mailbox of the firmware update control task and send message to firmware update control task's mailbox.
Definition at line 159 of file update.cpp.
References eFwDlFailed, and Mbox::sendMsg().
Referenced by download_start(), and fota_dl_handler().
download_success()
void download_success (void) static
Send OTA Success event message to firmware update control task.
The function defines the JSON string with the OTA Success event, request a message from message pool, set message type to eFwDlSuccess, set eFwUpd as sender, copy the JSON string in the message payload, retrieve a pointer to the mailbox of the firmware update control task and send message to firmware update control task's mailbox.
Definition at line 184 of file update.cpp.
References eFwDlSuccess, and Mbox::sendMsg().
Referenced by fota_dl_handler().
download_start()
void download_start (void) static
Function to start the OTA download process.
The function start the OTA download process by calling function fota_download_start provided by the FOTA download library of the nRF Connect SDK. Function fota_download_start start downloading the given file from the given host. When the download is complete, the secondary slot of MCUboot is tagged as having valid firmware inside it. The completion is reported through an event (see fota_dl_handler). In case of an error, indicated by a return value unequal to 0, the member function download_failed will be called.
Definition at line 140 of file update.cpp.
References download_failed(), filename, hostname, and SEC_TAG.
Referenced by task().
setUrl()
void setUrl (const char * url)
setHostname()
void setHostname (std::string name)
Setter function to set the hostname.
Parameters
name The name of the host of type C++ string
The Function copy parameter name in c string member variable hostname.
Definition at line 76 of file update.cpp.
References hostname.
Referenced by task().
setFilename()
void setFilename (std::string name)
Setter function to set the filename.
Parameters
name The name of the file of type C++ string
The Function copy parameter name in c string member variable filename.
Definition at line 88 of file update.cpp.
References filename.
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the firmware update task.
Definition at line 76 of file update.h.
Referenced by FwUpd(), and task().
filename
char filename static
File to request in download, e.g. "/stg/app_update.bin"
Definition at line 92 of file update.h.
Referenced by download_start(), and setFilename().
hostname
char hostname static
http server to download from, e.g. "myserver.amazonaws.com"
Definition at line 97 of file update.h.
Referenced by download_start(), and setHostname().
sha1_expected
uint8_t sha1_expected[41]
Expected checksum from fw_info
Todo:
no magic numbers
Definition at line 100 of file update.h.
Referenced by task().
size_expected
int32_t size_expected
Expected file size from fw_info.
Definition at line 102 of file update.h.
Referenced by task().
The documentation for this class was generated from the following files:
update/update.h
update/update.cpp