AXO X1: LteMonitor Class Reference
LteMonitor Class Reference
LTE monitor class derived from task base class.
#include <lte_monitor.h>
Detailed Description
LTE monitor class derived from task base class.
Detailed Description
Todo:
RMS task receives the acceleration raw data from ADXL data store task, calculate RMS and with the help of class HitDetector hit values. RMS, medium and critical hit values will be send to RMS store task together with a timestamp. The class provides an idle detection timer, and for medium and critical hit detection an instance of class HitDetector. It provides the function update_rms to calculate RMS and hit values and to send them to the RMS store task.
Receive
Timer interrupt callback
RMS task (self)
ADXL data store task
Transmit
RMS store task
RMS task (self, transmission in timer callback)
Definition at line 118 of file lte_monitor.h.
Public Types
enum { IMEI_LEN = 15 }
enum { IMSI_LEN = 15 }
Public Member Functions
LteMonitor (const char *name="??")
LTE monitor task constructor.
LteMonitor ()=delete
virtual ~LteMonitor ()
LTE monitor task destructor.
void task (void) override
MQTT connector task function.
void timer1_expired ()
Timer expired function for the IMSI / IMEI read timer.
void reportIMEI (Mbox::MboxId toWhom=Mbox::eDataManager)
Send IMEI to the receiver mailbox.
void reportIMSI (Mbox::MboxId toWhom=Mbox::eDataManager)
Send IMSI to the receiver mailbox.
void reportBattVoltage (Mbox::MboxId toWhom=Mbox::eDataManager)
Send modem battery voltage to the receiver mailbox.
void reportTemperature (Mbox::MboxId toWhom=Mbox::eDataManager)
Send modem temperature to the receiver mailbox.
void reportLinkQuality (Mbox::MboxId toWhom=Mbox::eDataManager)
Send link quality value to the receiver mailbox.
void reportFwVersion (Mbox::MboxId toWhom=Mbox::eDataManager)
Send firmware version of the modem software to the receiver mailbox.
void reportPsmAct (Mbox::MboxId toWhom=Mbox::eDataManager)
Send TAU period and active time to the receiver mailbox.
void psm_read (void)
Function to retrieve power saving mode informations of the modem.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the IMSI / IMEI read timer.
static void resume_all_notifications ()
Function to resume the AT monitor for all notifications.
static void at_notif_handler (const char *notif)
Handler callback function to receive all notifications.
static void register_link_quality_notifications ()
Function to subscribe to signal quality notifications.
static void resume_link_quality_notifications ()
Function to resume the AT monitor for link quality notifications.
static void at_ecsq_handler (const char *notif)
Handler callback function to receive link quality notifications.
static void register_network_notifications ()
Function to set network registration status.
static void resume_network_notifications ()
Function to resume the AT monitor for network notifications.
static void at_cereg_handler (const char *notif)
Handler callback function to receive network notifications.
static const char * cereg_str_get (enum cereg_status status)
Function to get network notification status as string.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the LTE monitor task.
Timer * myTimer
Static Public Attributes
static struct at_monitor_entry catch_all
The AT monitor to catch all notifications.
static struct at_monitor_entry link_quality
The AT monitor to receive the link quality.
static struct at_monitor_entry network
The AT monitor to catch network notifications.
Private Member Functions
int getBattVoltage ()
Function to retrieve the battery voltage of the modem.
int getTemperature ()
Function to retrieve the temperature of the modem.
const char * getFwVersion ()
Function to retrieve the firmware version of the modem software.
int getIMEI ()
Function to retrieve the IMEI.
int getIMSI ()
Function to retrieve the IMSI.
Private Attributes
int32_t battVoltage
The LTE modem battery voltage in [mV].
int8_t linkQuality
The LTE modem link quality in [dBm].
int32_t temperature
The LTE modem temperature in [°C].
int32_t psm_enabled
psm_timer psm_act
TAU period and active time granted by operator [sec].
char request_periodic_tau [8]
char request_active_time [8]
Requested active timer value.
char imei [IMEI_LEN+1]
The IMEI string.
char imsi [IMSI_LEN+1]
The IMSI string.
char fw_version [MODEM_INFO_FWVER_SIZE]
The firmware version string.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IMEI_LEN
Definition at line 120 of file lte_monitor.h.
anonymous enum
anonymous enum
Enumerator
IMSI_LEN
Definition at line 121 of file lte_monitor.h.
Constructor & Destructor Documentation
LteMonitor() [1/2]
LteMonitor (const char * name = "??") explicit
LTE monitor task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocates and initialize the one shot IMSI and IMEI read timer with duration of 5 ms.
Definition at line 88 of file lte_monitor.cpp.
References Mbox::eLteMonitor, myTimer, pInMbox, Mbox::registerMbox(), and timer_cb().
LteMonitor() [2/2]
LteMonitor () delete
~LteMonitor()
~LteMonitor () virtual
LTE monitor task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 105 of file lte_monitor.cpp.
Member Function Documentation
task()
void task (void) override virtual
MQTT connector task function.
Initially the function initialize the modem information library by calling function modem_info_init provided by the modem information library. The one shot IMSI / IMEI read timer will be started and firmware version will be retrieved by call of function getFwVersion provided from version module.
Afterwards the function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On timer expiry the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static. Afterwards the function read and print out IMSI and IMEI by calling the member functions getIMSI and getIMEI. Afterwards
eLteLinkQuality: On receiving the link quality from AT handler callback function at_ecsq_handler, the link quality value will be extracted from message payload and stored in private member variable linkQuality.
eLteReport: On receiving LTE report request from data manger task, LTE modem specific data will be read by calling the functions psm_read, getIMSI, getBattVoltage and getTemperature. These informations will be reported to data manger task by call of the functions reportLinkQuality, reportIMSI, reportPsmAct, reportBattVoltage and reportTemperature.
Note
that the sequence of the reports matters, since the receiver deduces "metrics complete" when modem voltage and temperature are received
Implements Task.
Definition at line 137 of file lte_monitor.cpp.
References Mbox::eHttpConnector, eLteLinkQuality, eLteReport, eTimerExpired, PoolElem::free(), PoolElem::from, getBattVoltage(), getFwVersion(), getIMEI(), getIMSI(), getTemperature(), linkQuality, PoolElem::mtype, Task::myName, myTimer, PoolElem::p2, pInMbox, psm_read(), Mbox::read(), reportBattVoltage(), reportIMEI(), reportIMSI(), reportLinkQuality(), reportPsmAct(), reportTemperature(), Timer::start(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the IMSI / IMEI read timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call MQTT connector timer expired function timer1_expired.
Definition at line 57 of file lte_monitor.cpp.
References timer1_expired().
Referenced by LteMonitor().
timer1_expired()
void timer1_expired ()
Timer expired function for the IMSI / IMEI read timer.
The function initializes the static pool element e1 with message type eTimerExpired, set LTE connector as sender and put message into own (LTE monitor's) mailbox.
Definition at line 72 of file lte_monitor.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
reportIMEI()
void reportIMEI (Mbox::MboxId toWhom = Mbox::eDataManager)
Send IMEI to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteIMEI with attached IMEI to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 640 of file lte_monitor.cpp.
References eLteIMEI, imei, and Mbox::sendMsg().
Referenced by task().
reportIMSI()
void reportIMSI (Mbox::MboxId toWhom = Mbox::eDataManager)
Send IMSI to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteIMSI with attached IMSI to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 684 of file lte_monitor.cpp.
References eLteIMSI, imsi, and Mbox::sendMsg().
Referenced by task().
reportBattVoltage()
void reportBattVoltage (Mbox::MboxId toWhom = Mbox::eDataManager)
Send modem battery voltage to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteBattVoltage with attached battery voltage to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 496 of file lte_monitor.cpp.
References battVoltage, eLteBattVoltage, and Mbox::sendMsg().
Referenced by task().
reportTemperature()
void reportTemperature (Mbox::MboxId toWhom = Mbox::eDataManager)
Send modem temperature to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteTemperature with attached temperature to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 532 of file lte_monitor.cpp.
References eLteTemperature, Mbox::sendMsg(), and temperature.
Referenced by task().
reportLinkQuality()
void reportLinkQuality (Mbox::MboxId toWhom = Mbox::eDataManager)
Send link quality value to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteLinkQuality with attached link quality to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 580 of file lte_monitor.cpp.
References eLteLinkQuality, linkQuality, and Mbox::sendMsg().
Referenced by task().
reportFwVersion()
void reportFwVersion (Mbox::MboxId toWhom = Mbox::eDataManager)
Send firmware version of the modem software to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteFwVersion with attached firmware version to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 565 of file lte_monitor.cpp.
References eLteFwVersion, fw_version, and Mbox::sendMsg().
reportPsmAct()
void reportPsmAct (Mbox::MboxId toWhom = Mbox::eDataManager)
Send TAU period and active time to the receiver mailbox.
Parameters
toWhom ID of the receiver mailbox, where to send the message, default is ID eDataManager
The function send a message of type eLteIMEI with attached TAU period and active time in structure psm_act to mailbox toWhom by calling function sendMsg provided by Mbox class.
Definition at line 596 of file lte_monitor.cpp.
References eLtePsmAct, psm_act, and Mbox::sendMsg().
Referenced by task().
resume_all_notifications()
void resume_all_notifications () static
Function to resume the AT monitor for all notifications.
By call of function at_monitor_resume, provided by the AT monitor library this method resumes the AT monitor for all notifications.
Note
This function is unused and will never called
Definition at line 227 of file lte_monitor.cpp.
References catch_all.
at_notif_handler()
void at_notif_handler (const char * notif) static
Handler callback function to receive all notifications.
Parameters
notif Pointer to the notification string
The function only prints a debug message al information level.
Note
This function is unused and will never called
Definition at line 240 of file lte_monitor.cpp.
Referenced by __attribute__().
register_link_quality_notifications()
void register_link_quality_notifications () static
Function to subscribe to signal quality notifications.
By call of function nrf_modem_at_printf, provided by the modem library of nrfxlib this method send the AT command CESQ with parameter 1 to the modem to enable link quality notifications, which will be received by the link quality AT monitor handler callback function at_ecsq_handler. See Command Reference Guide, page 19f for details.
Definition at line 269 of file lte_monitor.cpp.
Referenced by main().
resume_link_quality_notifications()
void resume_link_quality_notifications () static
Function to resume the AT monitor for link quality notifications.
By call of function at_monitor_resume, provided by the AT monitor library this method resumes the AT monitor for link quality notifications.
Definition at line 310 of file lte_monitor.cpp.
References link_quality.
Referenced by main().
at_ecsq_handler()
void at_ecsq_handler (const char * notif) static
Handler callback function to receive link quality notifications.
Parameters
notif Pointer to the notification string
The function transforms the notification into an integer dBm value. If the dBm value is invalid the function returns immediately, otherwise the function send a message of type eLteLinkQualitywith attached link quality dBm to its own (LTE monitor's) mailbox by calling function sendMsg provided by Mbox class.
Definition at line 287 of file lte_monitor.cpp.
References eLteLinkQuality, and Mbox::sendMsg().
register_network_notifications()
void register_network_notifications () static
Function to set network registration status.
By call of function nrf_modem_at_printf, provided by the modem library of nrfxlib this method send the AT command +CEREG with parameter 1 to the modem to enable unsolicited status result codes, which will be received by the network AT monitor handler callback function at_cereg_handler. See Command Reference Guide, page 97f for details.
Definition at line 326 of file lte_monitor.cpp.
Referenced by main().
resume_network_notifications()
void resume_network_notifications () static
Function to resume the AT monitor for network notifications.
By call of function at_monitor_resume, provided by the AT monitor library this method resumes the AT monitor for network notifications.
Definition at line 353 of file lte_monitor.cpp.
References network.
Referenced by main().
at_cereg_handler()
void at_cereg_handler (const char * notif) static
Handler callback function to receive network notifications.
Parameters
notif Pointer to the notification string
The function transforms the notification into an integer status value and cast it to enumeration type enum cereg_status to pass it into function cereg_str_get to get the status in string format.
Definition at line 400 of file lte_monitor.cpp.
References cereg_str_get().
cereg_str_get()
const char * cereg_str_get (enum cereg_status status) static
Function to get network notification status as string.
Parameters
status Status of enumeration type enum cereg_status
Returns
Returns the network notification status as string
The function returns a string for the network notification status according to input parameter status of enumeration type enum cereg_status.
Definition at line 368 of file lte_monitor.cpp.
References DENIED, EMERGENCY, HOME, NO_NETWORK, ROAMING, SEARCHING, UICC_FAILURE, and UNKNOWN.
Referenced by at_cereg_handler(), and LteConnector::lte_event_handler().
psm_read()
void psm_read (void)
Function to retrieve power saving mode informations of the modem.
The method send the AT command "Power saving mode setting" +CPSMS to the modem and read the formatted response into the arguments psm_enabled, request_periodic_tau and request_active_time by calling function nrf_modem_at_scanf provided by the modem library of nrfxlib provided by Nordic semiconductor. In case of an error the method returns immediately. See Command Reference Guide, page 88ff for details. Afterwards function lte_lc_psm_get is called for getting the current PSM (Power Saving Mode) configurations for periodic TAU (Tracking Area Update) and active time, both in units of seconds. In case of an error the method returns immediately.
Definition at line 427 of file lte_monitor.cpp.
References psm_timer::active_time, psm_act, psm_enabled, request_active_time, request_periodic_tau, and psm_timer::tau.
Referenced by task().
getBattVoltage()
int getBattVoltage () private
Function to retrieve the battery voltage of the modem.
Returns
The battery voltage in mV
The method retrieves the battery voltage of the modem by calling function modem_info_get_batt_voltage provided by the modem information library of the nRF Connect SDK and store it in member variable battVoltage.
Definition at line 475 of file lte_monitor.cpp.
References battVoltage.
Referenced by task().
getTemperature()
int getTemperature () private
Function to retrieve the temperature of the modem.
Returns
The temperature value in °C
The method retrieves the temperature of the modem by calling function modem_info_get_temperature provided by the modem information library of the nRF Connect SDK and store it in member variable temperature.
Definition at line 511 of file lte_monitor.cpp.
References temperature.
Referenced by task().
getFwVersion()
const char * getFwVersion () private
Function to retrieve the firmware version of the modem software.
Returns
Ponter to the firmware version of the modem software
The method retrieves the firmware version of the modem software by calling function modem_info_get_fw_version provided by the modem information library of the nRF Connect SDK and store it in member variable fw_version.
Definition at line 547 of file lte_monitor.cpp.
References fw_version.
Referenced by task().
getIMEI()
int getIMEI () private
Function to retrieve the IMEI.
Returns
0 on success, error code otherwise
The method retrieves the IMEI by calling function modem_info_string_get provided by the modem information library of the nRF Connect SDK. In case of an error the function returns error code -EIO, otherwise the received IMEI will be stored in member variable imei and function returns 0.
Definition at line 612 of file lte_monitor.cpp.
References imei, and IMEI_LEN.
Referenced by task().
getIMSI()
int getIMSI () private
Function to retrieve the IMSI.
Returns
0 on success, error code otherwise
The method retrieves the IMSI by calling function modem_info_string_get provided by the modem information library of the nRF Connect SDK. In case of an error the function returns error code -EIO, otherwise the received IMSI will be stored in member variable imsi and function returns 0.
Definition at line 656 of file lte_monitor.cpp.
References imsi, and IMSI_LEN.
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the LTE monitor task.
Definition at line 139 of file lte_monitor.h.
Referenced by LteMonitor(), task(), and timer1_expired().
myTimer
Timer* myTimer
One shot timer provides delay for IMSI and IMEI reading + printing
Definition at line 140 of file lte_monitor.h.
Referenced by LteMonitor(), and task().
catch_all
struct at_monitor_entry catch_all static
The AT monitor to catch all notifications.
Definition at line 155 of file lte_monitor.h.
Referenced by resume_all_notifications().
link_quality
struct at_monitor_entry link_quality static
The AT monitor to receive the link quality.
Definition at line 155 of file lte_monitor.h.
Referenced by resume_link_quality_notifications().
network
struct at_monitor_entry network static
The AT monitor to catch network notifications.
Definition at line 155 of file lte_monitor.h.
Referenced by resume_network_notifications().
battVoltage
int32_t battVoltage private
The LTE modem battery voltage in [mV].
Definition at line 170 of file lte_monitor.h.
Referenced by getBattVoltage(), and reportBattVoltage().
linkQuality
int8_t linkQuality private
The LTE modem link quality in [dBm].
Definition at line 171 of file lte_monitor.h.
Referenced by reportLinkQuality(), and task().
temperature
int32_t temperature private
The LTE modem temperature in [°C].
Definition at line 172 of file lte_monitor.h.
Referenced by getTemperature(), and reportTemperature().
psm_enabled
int32_t psm_enabled private
Flag indicating if power saving mode is enabled or not
Definition at line 173 of file lte_monitor.h.
Referenced by psm_read().
psm_act
psm_timer psm_act private
TAU period and active time granted by operator [sec].
Definition at line 176 of file lte_monitor.h.
Referenced by psm_read(), and reportPsmAct().
request_periodic_tau
char request_periodic_tau[8] private
Requested periodic TAU timer value (Tracking Area Update)
Definition at line 177 of file lte_monitor.h.
Referenced by psm_read().
request_active_time
char request_active_time[8] private
Requested active timer value.
Definition at line 179 of file lte_monitor.h.
Referenced by psm_read().
imei
char imei[IMEI_LEN+1] private
The IMEI string.
Definition at line 180 of file lte_monitor.h.
Referenced by getIMEI(), and reportIMEI().
imsi
char imsi[IMSI_LEN+1] private
The IMSI string.
Definition at line 181 of file lte_monitor.h.
Referenced by getIMSI(), and reportIMSI().
fw_version
char fw_version[MODEM_INFO_FWVER_SIZE] private
The firmware version string.
Definition at line 182 of file lte_monitor.h.
Referenced by getFwVersion(), and reportFwVersion().
The documentation for this class was generated from the following files:
modem/lte_monitor.h
modem/lte_monitor.cpp