AXO X1: MsgPool Class Reference
MsgPool Class Reference
RTOS wrapper for message pool support implemented according to C++ singleton design pattern.
#include <mpool.h>
Detailed Description
RTOS wrapper for message pool support implemented according to C++ singleton design pattern.
Detailed Description
The MsgPool class implements a C++ wrapper for message pool support using the kernel memory slab API provided by the Zephyr operating system. See details in Zephyr Memory Slab documentation or in API documentation. The MsgPool class provides methods to allocate messages from the pool and to release (free) them back into the pool. Furthermore it provides a method to count the number of objects in the queue and to print statistics.
Definition at line 56 of file mpool.h.
Public Member Functions
~MsgPool ()
MsgPool class destructor.
PoolElem * getNewElem (int minSize)
Function to allocate a message of type PoolElem from message pool.
PoolElem * getNewElem ()
Getter function to allocate a message of type PoolElem from message pool.
void freeElem (PoolElem *elem)
Function to free (release) a message of type PoolElem to the message pool.
uint16_t size ()
Getter function to retrieve the total number of messages in the pool.
uint16_t used ()
Getter function to retrieve the number of used messages of the pool.
uint16_t maxused ()
Getter function to retrieve the maximum number of used messages of the pool.
uint16_t available ()
Getter function to retrieve the number of available messages of the pool.
uint16_t bufpool_size (uint16_t size)
Getter function to retrieve the total number of buffer memory in one of the buffer pools.
uint16_t bufpool_used (uint16_t size)
Getter function to retrieve the number of used buffer memory in one of the buffer pools.
uint16_t bufpool_maxused (uint16_t size)
Getter function to retrieve the maximum number of used buffer memory in one of the buffer pools.
uint16_t bufpool_available (uint16_t size)
Getter function to retrieve the number of available buffer memory in one of the buffer pools.
Static Public Member Functions
static void stats ()
MsgPool status function.
static MsgPool * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Data Fields
Mutex lock
Mutex to avoid concurrent access.
Private Member Functions
MsgPool ()
MsgPool class constructor.
Static Private Attributes
static const uint8_t max_elements
Number of preallocated message (PoolElem) objects.
static MemoryPool< PoolElem, max_elements > elemPool
static const uint8_t max_buf32
Number of preallocated buffers of fixed size 32.
static MemoryPool< uint8_t[32], max_buf32 > buf32Pool
static const uint8_t max_buf128
Number of preallocated buffers of fixed size 128.
static MemoryPool< uint8_t[128], max_buf128 > buf128Pool
static const uint8_t max_buf256
Number of preallocated buffers of fixed size 256.
static MemoryPool< uint8_t[256], max_buf256 > buf256Pool
static const uint8_t max_buf512
Number of preallocated buffers of fixed size 512.
static MemoryPool< uint8_t[512], max_buf512 > buf512Pool
static const uint8_t max_buf1024
Number of preallocated buffers of fixed size 1024.
static MemoryPool< uint8_t[1024], max_buf1024 > buf1024Pool
Constructor & Destructor Documentation
~MsgPool()
~MsgPool ()
MsgPool class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 48 of file mpool.cpp.
MsgPool()
MsgPool () private
MsgPool class constructor.
The constructor simply triggers a debug message on info debug level.
Definition at line 39 of file mpool.cpp.
Member Function Documentation
getNewElem() [1/2]
PoolElem * getNewElem (int minSize)
Function to allocate a message of type PoolElem from message pool.
Parameters
minSize The minimal size of the message buffer
Returns
A pointer to the allocated message of type PoolElem
The function lock mutex lock to avoid concurrent access and allocate a message by calling function alloc of the message pool elemPool of class MemoryPool. According to the minimal size of the message buffer minSize the buffer will be allocated from one of the fixed sized buffer pools and the member variables buf and bufLen of the PoolElem class are set accordingly. Finally the member variables of the PoolElem class are assigned. Variable dataLen to 0, variable pool with this pointer of MsgPool instance and variable inPool to false before the pointer to the message of type PoolElem will be returned.
Definition at line 78 of file mpool.cpp.
References MemoryPool< T, num_blocks >::alloc(), PoolElem::buf, buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, PoolElem::bufLen, PoolElem::dataLen, elemPool, PoolElem::inPool, lock, PoolElem::maxAlloc, and PoolElem::pool.
Referenced by LteConnector::notify(), ADConverter::notifyListener(), and Mbox::sendMsg().
getNewElem() [2/2]
PoolElem * getNewElem ()
Getter function to allocate a message of type PoolElem from message pool.
Returns
A pointer to the allocated message of type PoolElem
The function allocate a message by calling member function getNewElem with paramter minSize = 0 and return the pointer to the allocated message.
Definition at line 59 of file mpool.cpp.
freeElem()
void freeElem (PoolElem * elem)
Function to free (release) a message of type PoolElem to the message pool.
Parameters
elem Pointer to the allocated message of type PoolElem
The function lock mutex lock to avoid concurrent access. According to the size of the buffer the message buffer will be released to the fixed size buffer it belongs to by calling the fixed size pools free method. Afterwards the message will be released by cvalling the message pool method free and variable inPool will be set to true.
Definition at line 137 of file mpool.cpp.
References PoolElem::buf, buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, PoolElem::bufLen, elemPool, MemoryPool< T, num_blocks >::free(), PoolElem::inPool, and lock.
Referenced by PoolElem::free().
stats()
void stats () static
MsgPool status function.
This function print out statistics of the all allocated memory pools.
Definition at line 181 of file mpool.cpp.
References buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, elemPool, and MemoryPool< T, num_blocks >::stats().
inst()
MsgPool * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 199 of file mpool.cpp.
Referenced by LteConnector::notify(), ADConverter::notifyListener(), and Mbox::sendMsg().
size()
uint16_t size ()
Getter function to retrieve the total number of messages in the pool.
Returns
Total number of messages in the pool
The function returns the total number of messages in the pool
Definition at line 212 of file mpool.cpp.
References max_elements.
Referenced by bufpool_available(), bufpool_maxused(), bufpool_size(), and bufpool_used().
used()
uint16_t used ()
Getter function to retrieve the number of used messages of the pool.
Returns
The number of used messages of the pool
The function returns the number of used messages of the pool
Definition at line 223 of file mpool.cpp.
References elemPool, and MemoryPool< T, num_blocks >::used().
Referenced by bufpool_used().
maxused()
uint16_t maxused ()
Getter function to retrieve the maximum number of used messages of the pool.
Returns
The number of maximal used messages of the pool
The function returns the number of maximal used messages of the pool
Definition at line 235 of file mpool.cpp.
References elemPool, and MemoryPool< T, num_blocks >::maxused().
Referenced by bufpool_maxused().
available()
uint16_t available ()
Getter function to retrieve the number of available messages of the pool.
Returns
The number of available messages of the pool
The function returns the number of available messages of the pool
Definition at line 247 of file mpool.cpp.
References elemPool, MemoryPool< T, num_blocks >::size(), and MemoryPool< T, num_blocks >::used().
Referenced by bufpool_available().
bufpool_size()
uint16_t bufpool_size (uint16_t size)
Getter function to retrieve the total number of buffer memory in one of the buffer pools.
Parameters
size Size of the buffer
Returns
Total number of buffers in one of the buffer pools
The function returns the total number of buffers in one of the buffer pools
Definition at line 261 of file mpool.cpp.
References buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, MemoryPool< T, num_blocks >::size(), and size().
bufpool_used()
uint16_t bufpool_used (uint16_t size)
Getter function to retrieve the number of used buffer memory in one of the buffer pools.
Parameters
size Size of the buffer
Returns
Number of used buffers in one of the buffer pools
The function returns the number of used buffers in one of the buffer pools
Definition at line 288 of file mpool.cpp.
References buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, size(), MemoryPool< T, num_blocks >::used(), and used().
bufpool_maxused()
uint16_t bufpool_maxused (uint16_t size)
Getter function to retrieve the maximum number of used buffer memory in one of the buffer pools.
Parameters
size Size of the buffer
Returns
Number of maximal used buffers in one of the buffer pools
The function returns the maximalnumber of used buffers in one of the buffer pools
Definition at line 316 of file mpool.cpp.
References buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, MemoryPool< T, num_blocks >::maxused(), maxused(), and size().
bufpool_available()
uint16_t bufpool_available (uint16_t size)
Getter function to retrieve the number of available buffer memory in one of the buffer pools.
Parameters
size Size of the buffer
Returns
Number of available buffers in one of the buffer pools
The function returns the number of available buffers in one of the buffer pools
Definition at line 344 of file mpool.cpp.
References MemoryPool< T, num_blocks >::available(), available(), buf1024Pool, buf128Pool, buf256Pool, buf32Pool, buf512Pool, and size().
Field Documentation
lock
Mutex lock
Mutex to avoid concurrent access.
Definition at line 66 of file mpool.h.
Referenced by freeElem(), and getNewElem().
max_elements
const uint8_t max_elements static private
Initial value:
=
        16
Number of preallocated message (PoolElem) objects.
Definition at line 83 of file mpool.h.
Referenced by size().
elemPool
MemoryPool< PoolElem, MsgPool::max_elements > elemPool static private
Statically allocated memory pool for messages of type PoolElem
Definition at line 86 of file mpool.h.
Referenced by available(), freeElem(), getNewElem(), maxused(), stats(), and used().
max_buf32
const uint8_t max_buf32 static private
Initial value:
=
        8
Number of preallocated buffers of fixed size 32.
Definition at line 89 of file mpool.h.
buf32Pool
MemoryPool< uint8_t[32], MsgPool::max_buf32 > buf32Pool static private
Statically allocated memory pool for 32 byte fixed size buffer
Definition at line 92 of file mpool.h.
Referenced by bufpool_available(), bufpool_maxused(), bufpool_size(), bufpool_used(), freeElem(), getNewElem(), and stats().
max_buf128
const uint8_t max_buf128 static private
Initial value:
=
        4
Number of preallocated buffers of fixed size 128.
Definition at line 95 of file mpool.h.
buf128Pool
MemoryPool< uint8_t[128], MsgPool::max_buf128 > buf128Pool static private
Statically allocated memory pool for 128 byte fixed size buffer
Definition at line 98 of file mpool.h.
Referenced by bufpool_available(), bufpool_maxused(), bufpool_size(), bufpool_used(), freeElem(), getNewElem(), and stats().
max_buf256
const uint8_t max_buf256 static private
Initial value:
=
        4
Number of preallocated buffers of fixed size 256.
Definition at line 101 of file mpool.h.
buf256Pool
MemoryPool< uint8_t[256], MsgPool::max_buf256 > buf256Pool static private
Statically allocated memory pool for 256 byte fixed size buffer
Definition at line 104 of file mpool.h.
Referenced by bufpool_available(), bufpool_maxused(), bufpool_size(), bufpool_used(), freeElem(), getNewElem(), and stats().
max_buf512
const uint8_t max_buf512 static private
Initial value:
=
        2
Number of preallocated buffers of fixed size 512.
Definition at line 107 of file mpool.h.
buf512Pool
MemoryPool< uint8_t[512], MsgPool::max_buf512 > buf512Pool static private
Statically allocated memory pool for 512 byte fixed size buffer
Definition at line 110 of file mpool.h.
Referenced by bufpool_available(), bufpool_maxused(), bufpool_size(), bufpool_used(), freeElem(), getNewElem(), and stats().
max_buf1024
const uint8_t max_buf1024 static private
Initial value:
=
        4
Number of preallocated buffers of fixed size 1024.
Definition at line 113 of file mpool.h.
buf1024Pool
MemoryPool< uint8_t[1024], MsgPool::max_buf1024 > buf1024Pool static private
Statically allocated memory pool for 1024 byte fixed size buffer
Definition at line 116 of file mpool.h.
Referenced by bufpool_available(), bufpool_maxused(), bufpool_size(), bufpool_used(), freeElem(), getNewElem(), and stats().
The documentation for this class was generated from the following files:
rtos/mpool.h
rtos/mpool.cpp