AXO X1: FlashFS Class Reference
FlashFS Class Reference
Represents the FlashFS file system for embedded systems with limited resources.
#include <flashfs.h>
Detailed Description
Represents the FlashFS file system for embedded systems with limited resources.
Name: class FlashFS Purpose:
      The FlashFS class provides an interface to interact with the
FlashFS file system on embedded devices. It abstracts file system operations, such as mounting, unmounting, file and directory operations, error handling, and efficient utilization of flash memory. This class structure is adapted so, a Developers can use this class to manage files and directories in the FlashFS file system without dealing with low-level details of c functions.
Definition at line 50 of file flashfs.h.
Public Member Functions
FlashFS (const char *name="??", struct fs_mount_t *mp=nullptr)
Public constructor for the FlashFS class, enforcing the singleton pattern.
FlashFS ()=delete
Deleted default constructor for the FlashFS class.
virtual ~FlashFS ()
Destructor for the FlashFS class.
int mount (struct fs_mount_t *mp)
int unmount ()
int remove (const char *path)
int rename (const char *path, const char *newpath)
int mkdir (const char *path, mode_t mode=0)
int stat (const char *path, struct fs_dirent *st)
int statvfs (const char *path, struct fs_statvfs *buf)
fs_file_t * file_open (const char *path, int flags)
int file_close (fs_file_t *file)
ssize_t file_read (fs_file_t *file, void *buffer, size_t size)
ssize_t file_write (fs_file_t *file, const void *buffer, size_t size)
int file_sync (fs_file_t *file)
off_t file_seek (fs_file_t *file, off_t offset, int whence)
off_t file_tell (fs_file_t *file)
off_t file_size (fs_file_t *file)
int file_truncate (fs_file_t *file, off_t length)
bool file_exists (const char *path)
fs_dir_t * dir_open (const char *path)
int dir_close (fs_dir_t *dir)
ssize_t dir_read (fs_dir_t *dir, struct fs_dirent *ent)
void dir_seek (fs_dir_t *dir, off_t offset)
off_t dir_tell (fs_dir_t *dir)
int dir_rewind (fs_dir_t *dir)
int dir_list (const char *path)
int file_tree (const char *path)
unsigned char * GetFsStat (const char *path)
void CheckAvailableSpace ()
Static Public Member Functions
static FlashFS & inst ()
The inst function to retrieve the exclusiv only instance of the class.
static int lfs_toerror (int err)
static int erase (struct fs_mount_t *mp)
Erase function for file system. This function erases the file system on the specified mount point.
static void eraseFs ()
static int format (struct fs_mount_t *mp)
Format function for file system. This function formats the file system on the specified mount point.
static int shell_file_tree (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'ls'.
static int shell_fs_stat (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'fs'.
static int clear_fs (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'del'.
Private Attributes
lfs_t * lfs
Pointer to the LittleFS context (LittleFS instance)
struct fs_mount_t * mp
struct lfs_config * config
Constructor & Destructor Documentation
FlashFS() [1/2]
FlashFS (const char * name = "??", struct fs_mount_t * mp = nullptr) explicit
Public constructor for the FlashFS class, enforcing the singleton pattern.
This constructor creates a new FlashFS instance or retrieves an existing one if it already exists, following the singleton pattern. It allows providing a name for the FlashFS instance and an optional mount point.
Parameters
name A unique name identifier for the FlashFS instance (default is "??").
mp A pointer to a file system mount structure (default is nullptr).
Definition at line 94 of file flashfs.cpp.
References mount(), and mp.
FlashFS() [2/2]
FlashFS () delete
Deleted default constructor for the FlashFS class.
The default constructor is deleted to prevent accidental instantiation of FlashFS without proper parameters, as the class enforces the singleton pattern.
~FlashFS()
~FlashFS () virtual
Destructor for the FlashFS class.
The destructor cleans up resources associated with the FlashFS instance, ensuring proper cleanup and deallocation when the instance is no longer needed.
Definition at line 116 of file flashfs.cpp.
References unmount().
Member Function Documentation
inst()
FlashFS & inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 110 of file flashfs.cpp.
Referenced by BoostConverter::BoostConverter(), BootCnt::BootCnt(), CheckAvailableSpace(), clear_fs(), Config::deleteConfigFile(), KeyGen::deleteKeyFiles(), MetricsBuilder::finalize(), GetFsStat(), KeyGen::getPrivateKey(), KeyGen::getPublicKey(), MqttConnector::HandleFsErase(), MqttConnector::HandleFsStatus(), KeyGen::init(), Config::loadFromFile(), main(), Config::saveToFile(), KeyGen::setKeyTransfered(), shell_file_tree(), shell_fs_stat(), and BoostConverter::task().
lfs_toerror()
int lfs_toerror (int err) static
Converts FlashFS error codes to standard POSIX error codes.
Parameters
err The FlashFS error code to convert.
Returns
Returns the corresponding POSIX error code.
Definition at line 45 of file flashfs.cpp.
Referenced by dir_close(), and file_size().
erase()
int erase (struct fs_mount_t * mp) static
Erase function for file system. This function erases the file system on the specified mount point.
Parameters
mp Pointer to the file system mount structure.
Returns
0 on success, or an error code on failure.
Definition at line 118 of file flashfs.cpp.
References mp.
Referenced by eraseFs().
eraseFs()
void eraseFs () static
Definition at line 144 of file flashfs.cpp.
References erase().
Referenced by clear_fs(), and MqttConnector::HandleFsErase().
format()
int format (struct fs_mount_t * mp) static
Format function for file system. This function formats the file system on the specified mount point.
Parameters
mp Pointer to the file system mount structure.
Returns
0 on success, or an error code on failure.
Definition at line 191 of file flashfs.cpp.
References mp.
mount()
int mount (struct fs_mount_t * mp)
Mounts the file system using the provided mount configuration.
Parameters
mp A pointer to the mount configuration structure.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 153 of file flashfs.cpp.
References config, lfs, and mp.
Referenced by FlashFS().
unmount()
int unmount ()
Unmounts the currently mounted file system.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 179 of file flashfs.cpp.
References config, lfs, and mp.
Referenced by clear_fs(), MqttConnector::HandleFsErase(), and ~FlashFS().
remove()
int remove (const char * path)
Removes a file from the FlashFS file system.
Parameters
path The path of the file to be removed.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 243 of file flashfs.cpp.
Referenced by Config::deleteConfigFile(), KeyGen::deleteKeyFiles(), Config::saveToFile(), and BoostConverter::task().
rename()
int rename (const char * path, const char * newpath)
Renames a file in the FlashFS file system.
Parameters
path The path of the file to be renamed.
newpath The desired new name for the file.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 250 of file flashfs.cpp.
mkdir()
int mkdir (const char * path, mode_t mode = 0)
Creates a new directory in the file system.
Parameters
path The path of the directory to be created.
mode The permissions of the newly created directory (optional, defaults to 0).
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 257 of file flashfs.cpp.
stat()
int stat (const char * path, struct fs_dirent * st)
Gets file or directory information from the file system.
Parameters
path The path of the file or directory to retrieve information for.
st A pointer to the fs_dirent structure to store the information.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 264 of file flashfs.cpp.
statvfs()
int statvfs (const char * path, struct fs_statvfs * buf)
Gets file system statistics for the specified path.
Parameters
path The path of the file or directory to retrieve file system statistics for.
buf A pointer to the fs_statvfs structure to store the statistics.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 276 of file flashfs.cpp.
References mp.
Referenced by CheckAvailableSpace(), GetFsStat(), and shell_fs_stat().
file_open()
fs_file_t * file_open (const char * path, int flags)
Opens a file in the file system.
Parameters
path The path of the file to be opened.
flags The flags specifying the file open mode.
Returns
Returns a pointer to the opened file, or NULL on failure.
Definition at line 306 of file flashfs.cpp.
Referenced by BootCnt::BootCnt(), KeyGen::getPrivateKey(), KeyGen::getPublicKey(), KeyGen::init(), Config::loadFromFile(), Config::saveToFile(), KeyGen::setKeyTransfered(), and BoostConverter::task().
file_close()
int file_close (fs_file_t * file)
Closes a file in the file system.
Parameters
file A pointer to the fs_file_t structure representing the file to be closed.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 322 of file flashfs.cpp.
Referenced by BootCnt::BootCnt(), KeyGen::getPrivateKey(), KeyGen::getPublicKey(), KeyGen::init(), Config::loadFromFile(), Config::saveToFile(), KeyGen::setKeyTransfered(), and BoostConverter::task().
file_read()
ssize_t file_read (fs_file_t * file, void * buffer, size_t size)
Reads data from a file in the file system.
Parameters
file A pointer to the fs_file_t structure representing the file to read from.
buffer A pointer to the buffer where the read data will be stored.
size The number of bytes to read from the file.
Returns
Returns the number of bytes read on success, or a negative error code on failure.
Definition at line 330 of file flashfs.cpp.
Referenced by BootCnt::BootCnt(), KeyGen::getPrivateKey(), KeyGen::getPublicKey(), and Config::loadFromFile().
file_write()
ssize_t file_write (fs_file_t * file, const void * buffer, size_t size)
Writes data to a file in the file system.
Parameters
file A pointer to the fs_file_t structure representing the file to write to.
buffer A pointer to the data buffer containing the data to be written.
size The number of bytes to write to the file.
Returns
Returns the number of bytes written on success, or a negative error code on failure.
Definition at line 338 of file flashfs.cpp.
Referenced by BootCnt::BootCnt(), KeyGen::init(), Config::loadFromFile(), Config::saveToFile(), KeyGen::setKeyTransfered(), and BoostConverter::task().
file_sync()
int file_sync (fs_file_t * file)
Synchronizes the file data to the storage device.
Parameters
file A pointer to the fs_file_t structure representing the file to sync.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 345 of file flashfs.cpp.
Referenced by BootCnt::BootCnt(), Config::loadFromFile(), Config::saveToFile(), and BoostConverter::task().
file_seek()
off_t file_seek (fs_file_t * file, off_t offset, int whence)
Seeks to a specified position in a file.
Parameters
file A pointer to the fs_file_t structure representing the file to seek within.
offset The offset to move the file pointer.
whence The reference position for the offset (SEEK_SET, SEEK_CUR, or SEEK_END).
Returns
Returns the new file pointer position on success, or -1 on failure.
Definition at line 352 of file flashfs.cpp.
Referenced by BootCnt::BootCnt(), Config::loadFromFile(), Config::saveToFile(), and BoostConverter::task().
file_tell()
off_t file_tell (fs_file_t * file)
Retrieves the current file pointer position in a file.
Parameters
file A pointer to the fs_file_t structure representing the file.
Returns
Returns the current file pointer position on success, or -1 on failure.
Definition at line 359 of file flashfs.cpp.
file_size()
off_t file_size (fs_file_t * file)
Retrieves the size of a file in bytes.
Parameters
file A pointer to the fs_file_t structure representing the file.
Returns
Returns the size of the file on success, or -1 on failure.
Definition at line 366 of file flashfs.cpp.
References lfs, and lfs_toerror().
file_truncate()
int file_truncate (fs_file_t * file, off_t length)
Truncates a file to a specified length.
Parameters
file A pointer to the fs_file_t structure representing the file to truncate.
length The new length of the file after truncation.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 378 of file flashfs.cpp.
file_exists()
bool file_exists (const char * path)
Checks if a file exists in the file system.
Parameters
path The path of the file to check.
Returns
Returns true if the file exists, false otherwise.
Definition at line 385 of file flashfs.cpp.
dir_open()
fs_dir_t * dir_open (const char * path)
Function Related to Directories Opens a directory in the file system.
Parameters
path The path of the directory to be opened.
Returns
Returns a pointer to the fs_dir_t structure representing the opened directory, or NULL on failure.
Definition at line 400 of file flashfs.cpp.
dir_close()
int dir_close (fs_dir_t * dir)
Closes a directory.
Parameters
dir A pointer to the fs_dir_t structure representing the directory to be closed.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 416 of file flashfs.cpp.
References lfs_toerror().
dir_read()
ssize_t dir_read (fs_dir_t * dir, struct fs_dirent * ent)
Reads the next entry from a directory.
Parameters
dir A pointer to the fs_dir_t structure representing the directory to read from.
ent A pointer to the fs_dirent structure to store the directory entry information.
Returns
Returns the number of bytes read on success, 0 if the end of the directory is reached, or a negative error code on failure.
Definition at line 424 of file flashfs.cpp.
dir_seek()
void dir_seek (fs_dir_t * dir, off_t offset)
Sets the directory stream position.
Parameters
dir A pointer to the fs_dir_t structure representing the directory.
offset The new position within the directory stream.
Definition at line 431 of file flashfs.cpp.
References lfs.
dir_tell()
off_t dir_tell (fs_dir_t * dir)
Retrieves the current directory stream position.
Parameters
dir A pointer to the fs_dir_t structure representing the directory.
Returns
Returns the current position within the directory stream on success, or -1 on failure.
Definition at line 438 of file flashfs.cpp.
References lfs.
dir_rewind()
int dir_rewind (fs_dir_t * dir)
Resets the directory stream position to the beginning.
Parameters
dir A pointer to the fs_dir_t structure representing the directory.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 446 of file flashfs.cpp.
References lfs.
dir_list()
int dir_list (const char * path)
Lists the contents of a directory.
Parameters
path The path of the directory to list.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 454 of file flashfs.cpp.
file_tree()
int file_tree (const char * path)
Lists the contents of a directory and all subdirectories.
Parameters
path The path of the directory to list.
Returns
Returns 0 on success, or a negative error code on failure.
Definition at line 489 of file flashfs.cpp.
Referenced by GetFsStat(), and shell_file_tree().
GetFsStat()
unsigned char * GetFsStat (const char * path)
Gets file system statistics and file tree for the specified path.
Parameters
path The path of the file or directory to retrieve file system statistics for.
Returns
A pointer to a static char array which stores the statistics and file informations (name and size in bytes) in JSON format.
Definition at line 544 of file flashfs.cpp.
References file_tree(), inst(), and statvfs().
CheckAvailableSpace()
void CheckAvailableSpace ()
Function to retrieve the available space in blocks. The available space will be printed out with debug message
Definition at line 532 of file flashfs.cpp.
References inst(), and statvfs().
Referenced by main().
shell_file_tree()
int shell_file_tree (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'ls'.
The function print out the complete content of the file system by callling member function file_tree with root directory as input folder.
Definition at line 609 of file flashfs.cpp.
References file_tree(), and inst().
shell_fs_stat()
int shell_fs_stat (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'fs'.
The function retrieve the status of the file system by calling member function statvfs and print status information via debug output at warning level.
Definition at line 625 of file flashfs.cpp.
References inst(), and statvfs().
clear_fs()
int clear_fs (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'del'.
The function clear the file system by calling the member functions unmount and eraseFs. Finally the function performs a reset with the call of function performSwReset provided by class ResetCtrl.
Definition at line 645 of file flashfs.cpp.
References eraseFs(), inst(), ResetCtrl::performSwReset(), and unmount().
Field Documentation
lfs
lfs_t* lfs private
Pointer to the LittleFS context (LittleFS instance)
Definition at line 375 of file flashfs.h.
Referenced by dir_rewind(), dir_seek(), dir_tell(), file_size(), mount(), and unmount().
mp
struct fs_mount_t* mp private
Structure to hold the mount configuration for FlashFS This structure is used to configure and mount the FlashFS file system.
Definition at line 379 of file flashfs.h.
Referenced by erase(), FlashFS(), format(), mount(), statvfs(), and unmount().
config
struct lfs_config* config private
Pointer to the FlashFS configuration structure This structure holds various configuration settings for LittleFS.
Definition at line 383 of file flashfs.h.
Referenced by mount(), and unmount().
The documentation for this class was generated from the following files:
fs/flashfs.h
fs/flashfs.cpp