AXO X1: MQueue Class Reference
MQueue Class Reference
#include <mqueue.h>
Detailed Description
Definition at line 52 of file mqueue.h.
Public Member Functions
MQueue ()
MQueue class constructor.
int32_t put (T *data)
MQueue put function.
T * get ()
MQueue get function.
uint32_t count ()
MQueue count function.
uint32_t avail ()
MQueue available function.
uint32_t size ()
MQueue size function.
uint32_t msg_size ()
MQueue message size function.
void stats (void)
MQueue status function.
Private Member Functions
char __aligned (4) my_msgq_buffer[sizeof(T) *num_slots]
Reserved memory to store the objects.
Private Attributes
struct k_msgq my_msgq
Message queue administration structure.
Constructor & Destructor Documentation
MQueue()
MQueue () inline
MQueue class constructor.
The constructor initializes the message queue by calling RTOS function k_msgq_init. This function initializes the message queue object, prior to its first use. It returns the message queue administration structure my_msgq.
Definition at line 62 of file mqueue.h.
References my_msgq.
Member Function Documentation
put()
int32_t put (T * data) inline
MQueue put function.
Returns
0 Message sent.
ENOMSG Returned without waiting or queue purged.
EAGAIN Waiting period timed out.
Parameters
data Pointer to message object. Type needs to be concretized by calling task
This function sends a message to message queue by calling function k_msgq_put provided by the operating system. Sending means putting the message object at the end position of the queue (FIFO).
Definition at line 84 of file mqueue.h.
References my_msgq.
Referenced by Mbox::write().
get()
T* get () inline
MQueue get function.
Returns
data Pointer to message object. Type needs to be concretized by calling task
This function receives a message from the message queue by calling function k_msgq_get provided by the operating system. Receiving means getting the message object from the start position of the queue (FIFO).
Definition at line 107 of file mqueue.h.
References my_msgq.
Referenced by Mbox::read().
count()
uint32_t count () inline
MQueue count function.
Returns
Number of used objects in the queue
This function returns the number of used objects the message queue by calling function k_msgq_num_used_get provided by the operating system.
Definition at line 124 of file mqueue.h.
References my_msgq.
Referenced by Mbox::count().
avail()
uint32_t avail () inline
MQueue available function.
Returns
Number of available objects in the queue
This function returns the number of available objects the message queue by calling function k_msgq_num_free_get provided by the operating system.
Definition at line 135 of file mqueue.h.
References my_msgq.
size()
uint32_t size () inline
MQueue size function.
Returns
Total number of objects in the queue
This function returns the total number of objects of the message queue.
Definition at line 144 of file mqueue.h.
References my_msgq.
msg_size()
uint32_t msg_size () inline
MQueue message size function.
Returns
Size of the objects of the queue
This function returns the size of objects of the message queue.
Definition at line 153 of file mqueue.h.
References my_msgq.
stats()
void stats (void) inline
MQueue status function.
This function print out statistics about the message queue.
Definition at line 160 of file mqueue.h.
Referenced by Mbox::stats().
__aligned()
char __aligned (4) private
Reserved memory to store the objects.
Field Documentation
my_msgq
struct k_msgq my_msgq private
Message queue administration structure.
Definition at line 160 of file mqueue.h.
Referenced by avail(), count(), get(), MQueue(), msg_size(), put(), and size().
The documentation for this class was generated from the following file:
rtos/mqueue.h