AXO X1: HttpConnector Class Reference
HttpConnector Class Reference
HTTP connector class derived from task base class.
#include <http_connector.h>
Detailed Description
HTTP connector class derived from task base class.
Detailed Description
HTTP connector task handle the HTTPS connection to send raw data to the remote JOVIA webserver. It uses the BSD socket API provided by Zephyr OS.
See details of BSD socket API The HttpConnector class provides functions to request connection, to send raw data via HTTP POST and to receive the server responses. It provides suppport of Transport layer security (TLS) and furthermore provides functions to request and receive the raw data from ADXL Store task, to request the status of the ADXL Store data and to inform ADXL task about running or stopped raw data transmission. Message Interaction:
Receive
Timer interrupt callback
MQTT connector task (self)
LTE connector task
LTE monitor task
ADXL store task
Transmit
ADXL store task
ADXL task
HTTP connector task (self, callback function for shell command 'z')
Definition at line 111 of file http_connector.h.
Public Member Functions
HttpConnector (const char *name="??")
HttpConnector task constructor.
HttpConnector ()=delete
virtual ~HttpConnector ()
HttpConnector task destructor.
virtual void configure ()
HttpConnector virtual task configure function.
void task (void)
HTTP connector task function.
void delayTimer_expired ()
Timer expired function for the HTTP connector delay timer.
void oneDayTimer_expired ()
Timer expired function for the one day timer.
void http_connect ()
Function to create a socket stream and send a HTTP connect request.
void http_disconnect ()
Function to send a disconnect request.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static void delayTimer_cb (k_timer *timer)
Timer callback function for the HTTP connector delay timer.
static void oneDayTimer_cb (k_timer *timer)
Timer callback function for the one day timer.
static int HttpRawDataSend (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'z'.
static int HttpDispDataSend (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'zd'.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the HTTP connector.
Timer * delayTimer
Raw data transfer delay timer.
Timer * oneDayTimer
One day timer.
Private Member Functions
int blocking_connect (int fd, struct sockaddr *local_addr, socklen_t len)
HttpConnector connect function.
int blocking_send (int fd, uint8_t *buf, uint32_t size, uint32_t flags)
HttpConnector send function.
int blocking_recv (int fd, uint8_t *buf, uint32_t size, uint32_t flags)
HttpConnector receive function.
int tls_setup (int sock)
Function to setup TLS peer verification.
void BuildDataHeader (eDataType dataType)
Function to create the raw data header.
void SendHttpPostHeader (eDataType dataType)
Function to send HTTP POST header to the host.
void SendSingleDataFrame (uint8_t *data, uint32_t datalen)
Function to send a single data frame to the host.
void SendSignatureFrame (std::string &signature, uint8_t signatureLen)
Function to send a single data frame to the host.
void reqData (msgType msgDataType)
Function to request raw data from AdxlStore task.
bool HandleRcvdData (PoolElem *pElem, uint16_t dataSize)
Function to handle received data from AdxlStore task.
void StartHttpRawDataTransmission ()
Function to initiate the raw data transmission to the host.
void reqRawDataStatus ()
Function to request the raw data status from AdxlStore task.
void reqRawData ()
Function to request raw data from AdxlStore task.
void HandleRcvdRawData (PoolElem *pElem)
Function to handle received raw data from AdxlStore task.
void HandleRawDataStatus (PoolElem *pElem)
Function to handle received raw data status from AdxlStore task.
void HandleAdxlIdleInd (PoolElem *pElem)
Function to handle idle indication from AdxlStore task.
void StartHttpDispDataTransmission ()
Function to initiate the displacement data transmission to the host.
void reqDispData ()
Function to request displacement data from AdxlStore task.
void HandleRcvdDispData (PoolElem *pElem)
Function to handle received displacement data from AdxlStore task.
Private Attributes
bool http_connected
Flag indicating that connection to HTTP server is established.
bool lte_connected
Flag indicating that connection to LTE modem is established.
bool bDispModeOff
bool bRawTransferEnabled
Flag indicating that raw data transmission is enabled or not.
bool bDispTransferEnabled
Flag indicating that displacement data transmission is enabled or not.
int client_fd
Socket file descriptor.
uint8_t responsebuf [1024]
Buffer to receive responses from webserver.
uint8_t sendbuf [1025]
Buffer to collect the data to be send to webserver.
double zMaxRms
maximum RMS value in z direction per train
double rms_z_Thres
RMS z Threshold.
uint32_t startReadPos
The starting raw data read position.
uint32_t totalNumEntries
Total number of raw data entries.
uint32_t rcvdEntries
Number of received raw data entries.
uint32_t requestedEntries
Number of requested raw data entries.
uint16_t dailyRawSendCnt
Flag indicating that number of raw data sendings has been exceeded.
bool bDailyRawSendCntExceeded
uint16_t maxRawPerDay
Maximum raw data sendings per day from config.
std::string rawDataHeader
The data header to be send to webserver.
std::string imei
std::string timestamp
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
HttpConnector() [1/2]
HttpConnector (const char * name = "??") explicit
HttpConnector task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocates and initialize the non cyclic timer with duration of 5 ms and the one day timer with duration and period on one day in seconds. Furthermore the member variables lte_connected, http_connected and bRawTransferEnabled will be initialized with false and member variables dailyRawSendCnt and zMaxRms with 0. Finally the one day timer will be started by callin function start provided by Timer class.
Definition at line 72 of file http_connector.cpp.
References bDailyRawSendCntExceeded, bRawTransferEnabled, dailyRawSendCnt, delayTimer, delayTimer_cb(), Mbox::eHttpConnector, http_connected, lte_connected, ONE_DAY_IN_SEC, oneDayTimer, oneDayTimer_cb(), pInMbox, Mbox::registerMbox(), Timer::start(), and zMaxRms.
HttpConnector() [2/2]
HttpConnector () delete
~HttpConnector()
~HttpConnector () virtual
HttpConnector task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 95 of file http_connector.cpp.
Member Function Documentation
configure()
void configure () virtual
HttpConnector virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to datalog by call of the function getCfgDatalog provided by the Config class and set the flags bDispModeOff, bRawTransferEnabled and bDispTransferEnabled according to the configuration values. Furthermore the activation threshold for raw / displacement data transmission and the displacement calculation is stored in private variable rms_z_Thres and the number of maximum raw data transfers per day in private member variable maxRawPerDay. Finally the private ECDSA key will be retrieved by calling function getPrivateKey provided by class KeyGen. In case the key is valid and do not contains the string "-----INVALID KEY-----" it will be stored in class ECDSASigner by call of setter function setPrivateKey.
Reimplemented from Task.
Definition at line 115 of file http_connector.cpp.
References bDispModeOff, bDispTransferEnabled, bRawTransferEnabled, _stCfgDatalog::dispmodeoff, _stCfgDatalog::disptransferon, Config::getCfgDatalog(), KeyGen::getPrivateKey(), Config::inst(), ECDSASigner::inst(), KeyGen::inst(), _stCfgDatalog::max_raw_per_day, maxRawPerDay, _stCfgDatalog::rawtransferon, _stCfgDatalog::rms_thres, rms_z_Thres, and ECDSASigner::setPrivateKey().
Referenced by main().
task()
void task (void) virtual
HTTP connector task function.
The function directly enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On delay timer expiry the ADXL store idle status will be checked again by sending message of type eAdxlIdleReq to AdxlStore task by call of function sendMsg provided by Mbox class. Afterwards the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static.
eOneDayTimerExpired: The counter for raw data sendings per day dailyRawSendCnt will be reset to 0 and the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static.
eLteSleepEnter: Will be ignored, only debug message at info level will be printed.
eLteSleepExit: Will be ignored, only debug message at info level will be printed.
eLteConnected: If LTE is not connected, the flag lte_connected will be set to true. Furthermore Adxl37x task will be requested to enable measurement by call of function sendMsg with message type eAdxlResumeMeas.
eLteDisconnected: The flag lte_connected will be set to false and the member function http_disconnect will be called.
eLteIMEI: The IMEI will be extracted from message payload and stored in member variable imei.
eTimestamp: Timestamp will be extracted from message payload and stored in member variable timestamp
eRawDataStatus: Member function HandleRawDataStatus will be called with message pointer pElem as parameter.
eRawData: Member function HandleRcvdRawData will be called with message pointer pElem as parameter.
eAdxlIdleReq: The received message of type eAdxlIdleReq will be forwarded to AdxlStore task by calling function send provided by Mbox class. Afterwards the pointer pElem will be set to 0, to prevent releasing the message. Releasing the message to the pool is task of the AdxlStore task.
eAdxl37xRmsData: Structure Adxl_xyz_max_data will be extracted from message payload and the maximum value in Z direction will be calculated and stored in variable zMaxRms. Finally the received message will be forwarded to data manager task and the pointer pElem will be set to 0, to prevent releasing the message.
eAdxl37xIdle: Member variable zMaxRms is set to 0.
eAdxlIdleInd: Member function HandleAdxlIdleInd will be called with message pointer pElem as parameter.
eHttpRawDataSend: If LTE is connected and raw data tranfer is enabled, provided by the dynamic configuration the raw data transmission will be started by call of member function StartHttpRawDataTransmission, otherwise a debug message at error level will be printed.
eSendDispDataReq: If LTE is connected and raw data tranfer is enabled, provided by the dynamic configuration the displacement data transmission will be started by call of member function StartHttpDispDataTransmission, otherwise a debug message at error level will be printed and Adxl37x task will be requested to enable measurement by call of function sendMsg with message type eAdxlResumeMeas.
eDispData: Handle the received displacement data (calculate SHA1 hash, send data to remote server, request next data) by calling member function HandleRcvdDispData.
Implements Task.
Definition at line 982 of file http_connector.cpp.
References bDailyRawSendCntExceeded, bDispTransferEnabled, bRawTransferEnabled, dailyRawSendCnt, eAdxl37xIdle, eAdxl37xRmsData, eAdxlIdleInd, eAdxlIdleReq, eAdxlResumeMeas, Mbox::eAdxlStore, Mbox::eDataManager, eDispData, eHttpRawDataSend, eLteConnected, eLteDisconnected, eLteIMEI, eLteSleepEnter, eLteSleepExit, eOneDayTimerExpired, eRawData, eRawDataStatus, eSendDispDataReq, eTimerExpired, eTimestamp, PoolElem::free(), PoolElem::getBuffer(), HandleAdxlIdleInd(), HandleRawDataStatus(), HandleRcvdDispData(), HandleRcvdRawData(), http_disconnect(), imei, lte_connected, PoolElem::mtype, Task::myName, pInMbox, Mbox::read(), Mbox::send(), Mbox::sendMsg(), StartHttpDispDataTransmission(), StartHttpRawDataTransmission(), timestamp, UNIT_TEST_STOP_LOOP, adxl_rms_data::z, and zMaxRms.
delayTimer_cb()
void delayTimer_cb (k_timer * timer) static
Timer callback function for the HTTP connector delay timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call HTTP connector timer expired function delayTimer_expired.
Definition at line 865 of file http_connector.cpp.
References delayTimer_expired().
Referenced by HttpConnector().
delayTimer_expired()
void delayTimer_expired ()
Timer expired function for the HTTP connector delay timer.
The function initializes the static pool element e1 with message type eTimerExpired, set HTTP connector as sender and put message into own (HTTP connector's) mailbox.
Definition at line 880 of file http_connector.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by delayTimer_cb().
oneDayTimer_cb()
void oneDayTimer_cb (k_timer * timer) static
Timer callback function for the one day timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call HTTP connector timer expired function oneDayTimer_expired.
Definition at line 897 of file http_connector.cpp.
References oneDayTimer_expired().
Referenced by HttpConnector().
oneDayTimer_expired()
void oneDayTimer_expired ()
Timer expired function for the one day timer.
The function initializes the static pool element e2 with message type eOneDayTimerExpired, set HTTP connector as sender and put message into own (HTTP connector's) mailbox.
Definition at line 912 of file http_connector.cpp.
References eOneDayTimerExpired, pInMbox, and Mbox::write().
Referenced by oneDayTimer_cb().
http_connect()
void http_connect ()
Function to create a socket stream and send a HTTP connect request.
The function call the getaddrinfo function provided by Zephyr BSD socket API, which itself is a POSIX wrapper for zsock_getaddrinfo (see details) to retrieve a set of socket addresses and associated information to be used to create a socket. The socket will be created by call of the function socket provided by Zephyr BSD socket API, which itself is a POSIX wrapper for zsock_socket (see details). The returned file descriptor client_fd is then used to setup Transport Layer Security (TLS) if requested protocol is of type IPPROTO_TLS_1_2. Finally member function blocking_connect is called to connect the device to the HTTP host. On success the flag http_connected will be set to true, otherwise function http_connect close the socket and returns immediately.
Definition at line 309 of file http_connector.cpp.
References blocking_connect(), client_fd, http_connected, HTTP_HOST, HTTP_PORT, and tls_setup().
Referenced by StartHttpDispDataTransmission(), and StartHttpRawDataTransmission().
http_disconnect()
void http_disconnect ()
Function to send a disconnect request.
For future use, prints only a debug message at info level.
Definition at line 852 of file http_connector.cpp.
Referenced by task().
HttpRawDataSend()
int HttpRawDataSend (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'z'.
The function send a message with message type eAdxlIdleReq, with sender ID eHttpConnector and receiver ID eHttpConnector by calling the method sendMsg provided by the Mbox class.
Note
For testing only: trigger raw data send via shell command
Definition at line 1127 of file http_connector.cpp.
References eAdxlIdleReq, and Mbox::sendMsg().
HttpDispDataSend()
int HttpDispDataSend (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'zd'.
The function send a message with message type eSendDispDataReq, with sender ID eHttpConnector and receiver ID eHttpConnector by calling the method sendMsg provided by the Mbox class.
Note
For testing only: trigger displacement data send via shell command
Definition at line 1145 of file http_connector.cpp.
References eSendDispDataReq, and Mbox::sendMsg().
blocking_connect()
int blocking_connect (int fd, struct sockaddr * local_addr, socklen_t len) private
HttpConnector connect function.
Parameters
fd Specifies the file descriptor associated with the socket.
local_addr Pointer to a sockaddr structure containing the peer address.
len The length of the sockaddr structure
Returns
On success return 0, otherwise -1 and errno set to indicate the error.
The function call the connect function provided by Zephyr BSD socket API, which itself is a POSIX wrapper for zsock_connect (see details). It is called in a loop which ends if function connect returns 0 indicating no error or if error number is EAGAIN (11, see details). Finally function return 0 on success or -1 in case of an error.
Definition at line 158 of file http_connector.cpp.
References UNIT_TEST_STOP_LOOP.
Referenced by http_connect().
blocking_send()
int blocking_send (int fd, uint8_t * buf, uint32_t size, uint32_t flags) private
HttpConnector send function.
Parameters
fd Specifies the file descriptor associated with the socket.
buf Pointer to the buffer containing the message to send
size The length of the message in bytes
flags The send flags
Returns
On success return the number of bytes sent, otherwise -1 and errno set to indicate the error.
The function call the send function provided by Zephyr BSD socket API, which itself is a POSIX wrapper for zsock_send (see details). It is called in a loop which ends if function connect returns 0 indicating no error or if error number is EAGAIN (11, see details). Finally function return number of bytes sent on success or -1 in case of an error.
Definition at line 188 of file http_connector.cpp.
References UNIT_TEST_STOP_LOOP.
Referenced by SendHttpPostHeader(), SendSignatureFrame(), and SendSingleDataFrame().
blocking_recv()
int blocking_recv (int fd, uint8_t * buf, uint32_t size, uint32_t flags) private
HttpConnector receive function.
Parameters
fd Specifies the file descriptor associated with the socket.
buf Pointer to the buffer containing the message to send
size The length of the message in bytes
flags The send flags
Returns
On success return the number of bytes sent, otherwise -1 and errno set to indicate the error.
The function call the recv function provided by Zephyr BSD socket API, which itself is a POSIX wrapper for zsock_recv (see details). It is called in a loop which ends if function connect returns 0 indicating no error, if error number is EAGAIN (11, see details) or if number of bytes received is more then 300 byte. Finally function return number of bytes sent on success or -1 in case of an error.
Definition at line 218 of file http_connector.cpp.
References UNIT_TEST_STOP_LOOP.
Referenced by HandleRcvdData().
tls_setup()
int tls_setup (int sock) private
Function to setup TLS peer verification.
Parameters
sock Specifies the file descriptor associated with the socket.
Returns
On success return 0, otherwise -1 and errno set to indicate the error.
The function call the setsockopt function provided by Zephyr BSD socket API, which itself is a POSIX wrapper for zsock_setsockopt (see details). It is called first to setup the peer verification with option TLS_PEER_VERIFY and is called second to setup the TLS security tag with option TLS_SEC_TAG_LIST. Third call is to setup the TLS hostname with option TLS_HOSTNAME, If one of the calls fail the function returns immediatly with the error code returned by setsockopt. If all calls were successful function returns 0.
Definition at line 250 of file http_connector.cpp.
References HTTP_HOST, and TLS_SEC_TAG.
Referenced by http_connect().
BuildDataHeader()
void BuildDataHeader (eDataType dataType) private
Function to create the raw data header.
The function build the raw data header. To get the same timestamp in RMS message, raw data message and displacement message, the timestamp is send from data manager task to HTTP connector task. This timestamp will than copied in all three messages. RMS message will be send to MQTT broker from data manager task. The header contains the following information:
IMEI: IMEI-OF-DEVICE
Timestamp: TIMESTAMP
no_of_samples: NUM-SAMPLES
Type: Raw or Displacement
Definition at line 400 of file http_connector.cpp.
References eDATA_TYPE_DISP, eDATA_TYPE_RAW, imei, rawDataHeader, timestamp, and totalNumEntries.
Referenced by HandleRawDataStatus(), and StartHttpDispDataTransmission().
SendHttpPostHeader()
void SendHttpPostHeader (eDataType dataType) private
Function to send HTTP POST header to the host.
The function copies the header information into the send buffer and enters a loop. In the loop member function blocking_send is called until all data in send buffer has been transmitted. The header contains the following information:
POST / HTTP/1.1(CR)(LF)
Host: HOSTNAME+HOSTPATH(CR)(LF)
Content-Length: PAYLOAD-LEN(CR)(LF)" \n Content-Type: application/octet-stream(CR)(LF)"
(CR)(LF) Where PAYLOAD-LEN is the length of the data header + length of data bytes + length of SHA1 hash (20 bytes)
Definition at line 363 of file http_connector.cpp.
References blocking_send(), client_fd, eDATA_TYPE_DISP, eDATA_TYPE_RAW, HTTP_HOST, HTTP_PATH, MAX_SIGNATURE_LEN, RAW_DATA_POST_REQ, rawDataHeader, sendbuf, and totalNumEntries.
Referenced by HandleRawDataStatus(), and StartHttpDispDataTransmission().
SendSingleDataFrame()
void SendSingleDataFrame (uint8_t * data, uint32_t datalen) private
Function to send a single data frame to the host.
Parameters
data The data to be send
datalen The length of the data in bytes
The function copies the data into the send buffer and enters a loop. In the loop member function blocking_send is called until all data in send buffer has been transmitted.
Definition at line 434 of file http_connector.cpp.
References blocking_send(), client_fd, and sendbuf.
Referenced by HandleRawDataStatus(), HandleRcvdData(), and StartHttpDispDataTransmission().
SendSignatureFrame()
void SendSignatureFrame (std::string & signature, uint8_t signatureLen) private
Function to send a single data frame to the host.
Parameters
signature The signature to be send
signatureLen The length of the signature in bytes
The function initializes the send buffer with zeros, copies the length of the signature into the first byte and the data of the signature string into the send buffer and enters a loop. In the loop member function blocking_send is called until all data in send buffer has been transmitted.
Definition at line 459 of file http_connector.cpp.
References blocking_send(), client_fd, MAX_SIGNATURE_LEN, and sendbuf.
Referenced by HandleRcvdData().
reqData()
void reqData (msgType msgDataType) private
Function to request raw data from AdxlStore task.
Parameters
msgDataType The message type specifying the type of data
By calling function sendMsg provided by Mbox class the method request data from AdxlStore task with message type of parateter msgDataType. In the payload of the message a structure of type struct AdxlRawDataProgress will be copied by function sendMsg. The structure contains the read position of the first raw data entry, the number of currently received raw data entries and the number of now requested raw data entries.
Definition at line 569 of file http_connector.cpp.
References MAX_NUM_REQ_ENTRIES, AdxlRawDataProgress::rcvdEntries, rcvdEntries, AdxlRawDataProgress::requestedEntries, requestedEntries, Mbox::sendMsg(), AdxlRawDataProgress::startRd, startReadPos, and totalNumEntries.
Referenced by reqDispData(), and reqRawData().
HandleRcvdData()
bool HandleRcvdData (PoolElem * pElem, uint16_t dataSize) private
Function to handle received data from AdxlStore task.
Parameters
pElem Pointer to the received message
Returns
Returns boolean variable bLastFrame, indicating last frame has been send or not
The boolean variable bLastFrame will be initialized with false and the number of still received raw data entries in member variable rcvdEntries will be increased by the number of requested raw data entries. If the total number of entries in adxlStore instance is greater than 0, the SHA1 checksum will be updated with the received raw data by calling function update provided by class Hash, than the received raw data will be send to host in a data frame by calling member function SendSingleDataFrame with the raw data in the message payload and the size of the payload calculated by number of requested entries multiplied with number of bytes of a single raw data entry.
If all raw data has been sent, when number of received entries is equal to total number of entries the SHA256 hash checksum will be finalized by calling function finalize provided by class Hash and the signature of the hash checksum will be calculated by call of function signHash provided by class ECDSASigner. The signature will then be send to remote host by calling member function SendSignatureFrame. With call of function blocking_recv the response from remote server will be received, the socket will be closed by calling function close provided by Zephyr BSD socket API and boolean variable bLastFrame will be set to true. Finally bLastFrame will be returned.
Definition at line 641 of file http_connector.cpp.
References blocking_recv(), client_fd, Hash::finalize(), PoolElem::getBuffer(), ECDSASigner::inst(), Hash::inst(), Hash::print(), ECDSASigner::printSignature(), rcvdEntries, requestedEntries, responsebuf, SendSignatureFrame(), SendSingleDataFrame(), ECDSASigner::signHash(), totalNumEntries, and Hash::update().
Referenced by HandleRcvdDispData(), and HandleRcvdRawData().
StartHttpRawDataTransmission()
void StartHttpRawDataTransmission () private
Function to initiate the raw data transmission to the host.
By calling function sendMsg provided by Mbox class the method inform Adxl37x task about the start of raw data transmission before connecting device with host by call of member function http_connect. On success the flag http_connected is true and the method request the raw data status from AdxlStore task by the call of member function reqRawDataStatus. On failure Adxl37x task will be informed about the end of raw data transmission by call of function sendMsg with message type eRawDataTransferComplete and Adxl37x task will be requested to enable measurement by call of function sendMsg with message type eAdxlResumeMeas.
Definition at line 491 of file http_connector.cpp.
References eAdxlResumeMeas, eRawDataTransferActive, eRawDataTransferComplete, http_connect(), http_connected, reqRawDataStatus(), and Mbox::sendMsg().
Referenced by task().
reqRawDataStatus()
void reqRawDataStatus () private
Function to request the raw data status from AdxlStore task.
By calling function sendMsg provided by Mbox class the method request the raw data status from AdxlStore task with message type eRawDataStatus.
Definition at line 551 of file http_connector.cpp.
References eRawDataStatus, and Mbox::sendMsg().
Referenced by StartHttpRawDataTransmission().
reqRawData()
void reqRawData () private
Function to request raw data from AdxlStore task.
By calling private member function reqData the function request raw data from AdxlStore task.
Definition at line 597 of file http_connector.cpp.
References eRawData, and reqData().
Referenced by HandleRawDataStatus(), and HandleRcvdRawData().
HandleRcvdRawData()
void HandleRcvdRawData (PoolElem * pElem) private
Function to handle received raw data from AdxlStore task.
Parameters
pElem Pointer to the received message
By calling private member function HandleRcvdData the received data from AdxlStore task will be handled by updating signature nad sending data frames to remote HTTP server. If the last frame has been sended, indicated by flag bLastFram, the Adxl37x task will be informed about the end of raw data transmission by call of function sendMsg with message type eRawDataTransferComplete. Afterwards the function checks if displacement calculation is not disabled and in this case it send the message eCalcDisplacementReq to the disp task by calling function sendMsg to request the start of displacement calculation.
If not all raw data has been sent, the next raw data will be requested by calling function reqRawData.
Definition at line 695 of file http_connector.cpp.
References bDispModeOff, eAdxlResumeMeas, eCalcDisplacementReq, eRawDataTransferComplete, HandleRcvdData(), reqRawData(), and Mbox::sendMsg().
Referenced by task().
HandleRawDataStatus()
void HandleRawDataStatus (PoolElem * pElem) private
Function to handle received raw data status from AdxlStore task.
Parameters
pElem Pointer to the received message
A structure of type struct AdxlRawDataStatus will be extracted from message payload and the member varaibles startReadPos, totalNumEntries and rcvdEntries will be initialized with the received information respectively 0. Afterwards it starts the SHA1 checksum calculation with call of
function init provided by class Hash, before requesting the raw data from AdxlStore task by the call of member function reqRawData. It build the data header by call of member function BuildDataHeader and send HTTP POST header and data header to the remote host with call of the member functions SendHttpPostHeader and SendSingleDataFrame.
Definition at line 760 of file http_connector.cpp.
References BuildDataHeader(), eDATA_TYPE_RAW, AdxlRawDataStatus::entries, PoolElem::getBuffer(), Hash::init(), Hash::inst(), rawDataHeader, rcvdEntries, reqRawData(), SendHttpPostHeader(), SendSingleDataFrame(), AdxlRawDataStatus::startRd, startReadPos, totalNumEntries, and Hash::update().
Referenced by task().
HandleAdxlIdleInd()
void HandleAdxlIdleInd (PoolElem * pElem) private
Function to handle idle indication from AdxlStore task.
Parameters
pElem Pointer to the received message
The method checks, if raw data transmission is enabled by configuration and in this case it extract the idle flag from message and start a delay timer if idle flag is false indicating that raw data recording is still in progress. Otherwise it checks if current maximum RMS z value is greater than RMS z threshold and maximum number of raw data sendings per day is not exceeded. Iin this case it starts the raw data transmission by sending message of type eHttpRawDataSend to own (HttpConnector's) mailbox by call of function sendMsg, provided by the Mbox class, otherwise it send message eAdxlResumeMeas to eAdxl37x Task to resume the measurement. If raw data transmission is not enabled, the function checks if displacement calculation is enabled and if current maximum RMS z value is greater than RMS z threshold. In this case it send the message eCalcDisplacementReq to the disp task by calling function sendMsg to request the start of displacement calculation, otherwise it send message eAdxlResumeMeas to eAdxl37x Task to resume the measurement.
Definition at line 797 of file http_connector.cpp.
References bDailyRawSendCntExceeded, bDispModeOff, bRawTransferEnabled, dailyRawSendCnt, delayTimer, eAdxlResumeMeas, eCalcDisplacementReq, eHttpRawDataSend, maxRawPerDay, PoolElem::p1, rms_z_Thres, Mbox::sendMsg(), Timer::start(), and zMaxRms.
Referenced by task().
StartHttpDispDataTransmission()
void StartHttpDispDataTransmission () private
Function to initiate the displacement data transmission to the host.
By calling function sendMsg provided by Mbox class the method inform Adxl37x task about the start of displacement data transmission before connecting device with host by call of member function http_connect. On success the flag http_connected is true and the method initialize read start position with the FRAM address BW_D_START_ADDR and the variable rcvdEntries with 0. Afterwards it starts the SHA1 checksum calculation with call of
function init provided by class Hash, before requesting the displacement data from AdxlStore task by the call of member function reqDispData. It build the data header by call of member function BuildDataHeader and send HTTP POST header and data header to the remote host with call of the member functions SendHttpPostHeader and SendSingleDataFrame. On failure Adxl37x task will be informed about the end of raw data transmission by call of function sendMsg with message type eDispDataTransferComplete.
Definition at line 523 of file http_connector.cpp.
References BuildDataHeader(), BW_D_START_ADDR, eDATA_TYPE_DISP, eDispDataTransferActive, eDispDataTransferComplete, http_connect(), http_connected, Hash::init(), Hash::inst(), rawDataHeader, rcvdEntries, reqDispData(), SendHttpPostHeader(), Mbox::sendMsg(), SendSingleDataFrame(), startReadPos, totalNumEntries, and Hash::update().
Referenced by task().
reqDispData()
void reqDispData () private
Function to request displacement data from AdxlStore task.
By calling private member function reqData the function request raw data from AdxlStore task.
Definition at line 608 of file http_connector.cpp.
References eDispData, and reqData().
Referenced by HandleRcvdDispData(), and StartHttpDispDataTransmission().
HandleRcvdDispData()
void HandleRcvdDispData (PoolElem * pElem) private
Function to handle received displacement data from AdxlStore task.
Parameters
pElem Pointer to the received message
By calling private member function HandleRcvdData the received data from AdxlStore task will be handled by updating signature nad sending data frames to remote HTTP server. If the last frame has been sended, indicated by flag bLastFram, Adxl37x task will be informed about the end of displacement data transmission by call of function sendMsg with message type eDispDataTransferComplete and Adxl37x task will be requested to enable measurement by call of function sendMsg with message type eAdxlResumeMeas.
If not all displacement data has been sent, the next displacement data will be requested by calling function reqDispData.
Definition at line 732 of file http_connector.cpp.
References eAdxlResumeMeas, eDispDataTransferComplete, HandleRcvdData(), reqDispData(), and Mbox::sendMsg().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the HTTP connector.
Definition at line 121 of file http_connector.h.
Referenced by delayTimer_expired(), HttpConnector(), main(), oneDayTimer_expired(), and task().
delayTimer
Timer* delayTimer
Raw data transfer delay timer.
Definition at line 122 of file http_connector.h.
Referenced by HandleAdxlIdleInd(), and HttpConnector().
oneDayTimer
Timer* oneDayTimer
One day timer.
Definition at line 123 of file http_connector.h.
Referenced by HttpConnector().
http_connected
bool http_connected private
Flag indicating that connection to HTTP server is established.
Definition at line 139 of file http_connector.h.
Referenced by http_connect(), HttpConnector(), StartHttpDispDataTransmission(), and StartHttpRawDataTransmission().
lte_connected
bool lte_connected private
Flag indicating that connection to LTE modem is established.
Definition at line 141 of file http_connector.h.
Referenced by HttpConnector(), and task().
bDispModeOff
bool bDispModeOff private
Flag indicating if displacement data calculation is disabled (15 sec FRAM space) or enabled (5 sec FRAM space)
Definition at line 144 of file http_connector.h.
Referenced by configure(), HandleAdxlIdleInd(), and HandleRcvdRawData().
bRawTransferEnabled
bool bRawTransferEnabled private
Flag indicating that raw data transmission is enabled or not.
Definition at line 146 of file http_connector.h.
Referenced by configure(), HandleAdxlIdleInd(), HttpConnector(), and task().
bDispTransferEnabled
bool bDispTransferEnabled private
Flag indicating that displacement data transmission is enabled or not.
Definition at line 148 of file http_connector.h.
Referenced by configure(), and task().
client_fd
int client_fd private
Socket file descriptor.
Definition at line 150 of file http_connector.h.
Referenced by HandleRcvdData(), http_connect(), SendHttpPostHeader(), SendSignatureFrame(), and SendSingleDataFrame().
responsebuf
uint8_t responsebuf[1024] private
Buffer to receive responses from webserver.
Definition at line 153 of file http_connector.h.
Referenced by HandleRcvdData().
sendbuf
uint8_t sendbuf[1025] private
Buffer to collect the data to be send to webserver.
Definition at line 155 of file http_connector.h.
Referenced by SendHttpPostHeader(), SendSignatureFrame(), and SendSingleDataFrame().
zMaxRms
double zMaxRms private
maximum RMS value in z direction per train
Definition at line 156 of file http_connector.h.
Referenced by HandleAdxlIdleInd(), HttpConnector(), and task().
rms_z_Thres
double rms_z_Thres private
RMS z Threshold.
Definition at line 157 of file http_connector.h.
Referenced by configure(), and HandleAdxlIdleInd().
startReadPos
uint32_t startReadPos private
The starting raw data read position.
Definition at line 158 of file http_connector.h.
Referenced by HandleRawDataStatus(), reqData(), and StartHttpDispDataTransmission().
totalNumEntries
uint32_t totalNumEntries private
Total number of raw data entries.
Definition at line 159 of file http_connector.h.
Referenced by BuildDataHeader(), HandleRawDataStatus(), HandleRcvdData(), reqData(), SendHttpPostHeader(), and StartHttpDispDataTransmission().
rcvdEntries
uint32_t rcvdEntries private
Number of received raw data entries.
Definition at line 160 of file http_connector.h.
Referenced by HandleRawDataStatus(), HandleRcvdData(), reqData(), and StartHttpDispDataTransmission().
requestedEntries
uint32_t requestedEntries private
Number of requested raw data entries.
Definition at line 161 of file http_connector.h.
Referenced by HandleRcvdData(), and reqData().
dailyRawSendCnt
uint16_t dailyRawSendCnt private
Flag indicating that number of raw data sendings has been exceeded.
Raw data send counter per day
Definition at line 162 of file http_connector.h.
Referenced by HandleAdxlIdleInd(), HttpConnector(), and task().
bDailyRawSendCntExceeded
bool bDailyRawSendCntExceeded private
Definition at line 164 of file http_connector.h.
Referenced by HandleAdxlIdleInd(), HttpConnector(), and task().
maxRawPerDay
uint16_t maxRawPerDay private
Maximum raw data sendings per day from config.
Definition at line 165 of file http_connector.h.
Referenced by configure(), and HandleAdxlIdleInd().
rawDataHeader
std::string rawDataHeader private
The data header to be send to webserver.
Definition at line 166 of file http_connector.h.
Referenced by BuildDataHeader(), HandleRawDataStatus(), SendHttpPostHeader(), and StartHttpDispDataTransmission().
imei
std::string imei private
The IMEI as part of the data header
Definition at line 167 of file http_connector.h.
Referenced by BuildDataHeader(), and task().
timestamp
std::string timestamp private
The timestamp as part of the data header. NOTE This timestamp is equal in RMS measurement, raw and displacement messages.
Definition at line 170 of file http_connector.h.
Referenced by BuildDataHeader(), and task().
The documentation for this class was generated from the following files:
net/http_connector.h
net/http_connector.cpp