AXO X1: spimram Class Reference
spimram Class Reference
SPI MRAM class implemented according to C++ singleton design pattern.
#include <mram.h>
Detailed Description
SPI MRAM class implemented according to C++ singleton design pattern.
Detailed Description
The SPI MRAM class handle the storage of the acceleration raw data in MRAM. It provides methods to initialize and erase MRAM, to read and write the data, to push MRAM into power saving mode or release from it, to dump the data and to read and ship the devcie ID.
Todo:
May we need to implement also a selftest function if provided from maufacturer!! Furthermore it provides a private method to test the integrity of the FRAM at startup of the system.
Definition at line 53 of file mram.h.
Public Member Functions
~spimram ()
SPI MRAM class destructor.
uint8_t * getDeviceId ()
Function to retrieve MRAM device ID.
int getStatusRegVal ()
Function to retrieve MRAM status register content.
int getConfig1RegVal ()
Function to retrieve MRAM configuration register 1 content.
void erase ()
Function to erase the content of the MRAM.
void erase (void *from, size_t len)
Function to erase content of the MRAM.
void dump (uint32_t from, size_t len)
Function to print the content of the MRAM in a terminal.
int writeBytes (uint32_t addr, uint8_t *data, size_t num_bytes)
Function to write multiple bytes into MRAM.
int readBytes (uint32_t addr, uint8_t *data, size_t num_bytes)
Function to read multiple bytes from MRAM.
int sleep ()
Function to enter deep power down mode of MRAM.
int wakeup ()
Function to leave deep power down mode of MRAM.
void setPowerOnDelay (uint32_t usec)
Setter function to set the power on delay.
void init ()
The initialization function of the SPI MRAM class.
int power_on ()
Function to switch on MRAM.
int power_off ()
Function to switch off MRAM.
Static Public Member Functions
static spimram * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
spimram (uint32_t delay_usec=2500)
SPI MRAM class constructor.
int send_command (const struct device *spi, struct spi_config *spi_cfg, uint8_t cmd)
Function to send a command to MRAM.
int mram_access (const struct device *spi, struct spi_config *spi_cfg, uint8_t cmd, uint32_t addr, uint8_t *data, size_t len, bool is_write)
Function to access MRAM for reading and writing.
int read_device_id (const struct device *spi, struct spi_config *spi_cfg, uint8_t *id_buf, size_t len)
Function to read the device ID from MRAM.
int read_bytes (const struct device *spi, struct spi_config *spi_cfg, uint32_t addr, uint8_t *data, size_t len)
Function to read multiple bytes to MRAM.
int write_bytes (const struct device *spi, struct spi_config *spi_cfg, uint32_t addr, const uint8_t *data, size_t len)
Function to write multiple bytes to MRAM.
int write_status_reg (const struct device *spi, struct spi_config *spi_cfg, const uint8_t *data)
Function to write MRAM status register.
int write_config1_reg (const struct device *spi, struct spi_config *spi_cfg, const uint8_t *data)
Function to write MRAM configuration register 1.
int enter_deep_power_down (const struct device *spi, struct spi_config *spi_cfg)
Function to enter deep power down mode of MRAM.
int exit_deep_power_down (const struct device *spi, struct spi_config *spi_cfg)
Function to exit deep power down mode of MRAM.
int read_status_reg (const struct device *spi, struct spi_config *spi_cfg, uint8_t *id_buf, size_t len)
Function to read MRAM status register.
int read_config1_reg (const struct device *spi, struct spi_config *spi_cfg, uint8_t *id_buf, size_t len)
Function to read MRAM configuration register 1.
Private Attributes
const struct gpio_dt_spec power_gpio
Devicetree setup for the MRAM power enable pin.
uint32_t power_delay_usec
Power on delay.
uint8_t id [4]
The device ID.
uint8_t status_reg
uint8_t config1_reg
const struct device * spi_dev
SPI controller device.
struct spi_config * spi_cfg
SPI controller configuration.
Static Private Attributes
static constexpr uint8_t CMD_WRSR = 0x01
Command to write the status register.
static constexpr uint8_t CMD_WRTE = 0x02
Command to write a memory array.
static constexpr uint8_t CMD_READ = 0x03
Command to read memory area.
static constexpr uint8_t CMD_RDSR = 0x05
Command to read the status register.
static constexpr uint8_t CMD_WREN = 0x06
Write enable command.
static constexpr uint8_t CMD_RDC1 = 0x35
Command to read configuration register 1.
static constexpr uint8_t CMD_RDAR = 0x65
Command to read any register, address based.
static constexpr uint8_t CMD_WRAR = 0x71
Command to write any register, address based.
static constexpr uint8_t CMD_RDID = 0x9F
Command to read the device ID.
static constexpr uint8_t CMD_DPD_ENTER = 0xB9
Command to enter deep power down mode.
static constexpr uint8_t CMD_DPD_EXIT = 0xAB
Command to exit deep power down mode.
Constructor & Destructor Documentation
~spimram()
~spimram ()
SPI MRAM class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 72 of file mram.cpp.
spimram()
spimram (uint32_t delay_usec = 2500) explicit private
SPI MRAM class constructor.
The constructor is declared as private according to singleton pattern. It is called in the static inst function to create the exclusiv only instance of the class. It initializes the power delay and configures the power gpio for MRAM activity.
Definition at line 55 of file mram.cpp.
References power_gpio.
Member Function Documentation
inst()
spimram * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 40 of file mram.cpp.
getDeviceId()
uint8_t * getDeviceId ()
Function to retrieve MRAM device ID.
Returns
returns return pointer to the device ID, NULL otherwise
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns error code NULL, otherwise it read the device ID by call of member function read_device_id and switch off MRAM power supply by calling member function power_off. In case of an error function returns with error code NULL, otherwise the read device ID in member variable id will be returned.
Definition at line 572 of file mram.cpp.
References id, power_off(), power_on(), read_device_id(), spi_cfg, and spi_dev.
Referenced by init().
getStatusRegVal()
int getStatusRegVal ()
Function to retrieve MRAM status register content.
Returns
returns return 0 on success, otherwise error code -1
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns with error code -1, otherwise it read the status register by call of member function read_status_reg and switch off MRAM power supply by calling member function power_off. In case of an error function returns with error code -1, otherwise the read content of the status register in member variable status_reg will be returned.
Definition at line 601 of file mram.cpp.
References power_off(), power_on(), read_status_reg(), spi_cfg, spi_dev, and status_reg.
Referenced by init().
getConfig1RegVal()
int getConfig1RegVal ()
Function to retrieve MRAM configuration register 1 content.
Returns
returns return 0 on success, otherwise error code -1
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns with error code -1, otherwise it read the configuration register 1 by call of member function read_config1_reg and switch off MRAM power supply by calling member function power_off. In case of an error function returns with error code -1, otherwise the read content of the configuration register 1 in member variable config1_reg will be returned.
Definition at line 631 of file mram.cpp.
References config1_reg, power_off(), power_on(), read_config1_reg(), spi_cfg, and spi_dev.
Referenced by init().
erase() [1/2]
void erase ()
Function to erase the content of the MRAM.
Function initialize an array of size 256 Byte with 0xFF and write this array in a loop into MRAM by calling member function writeBytes until the complete memory has been written. In case of an error the loop will be interrupted and the function returns.
Definition at line 656 of file mram.cpp.
References writeBytes().
erase() [2/2]
void erase (void * from, size_t len)
Function to erase content of the MRAM.
Parameters
from Start address for erase operation
len Number of bytesd to be erased
Function initialize an array of size 256 Byte with 0xFF and write this array in a loop into MRAM by calling member function writeBytes until the complete memory from address from up to address from + len has been written. In case of an error the loop will be interrupted and the function returns.
Definition at line 684 of file mram.cpp.
References writeBytes().
dump()
void dump (uint32_t from, size_t len)
Function to print the content of the MRAM in a terminal.
Parameters
from Start point of data to be printed
len Length (number of bytes) of data to be printed
Function read blockwise bytes in a loop from start point until end point (from + len) by calling function readBytes. In case of an error the loop will be terminated, otherwise the read data will be printed out by call of macro LOG_HEXDUMP_INF.
Definition at line 715 of file mram.cpp.
References readBytes().
writeBytes()
int writeBytes (uint32_t addr, uint8_t * data, size_t num_bytes)
Function to write multiple bytes into MRAM.
Parameters
addr Startaddress for writing the data in MRAM
data Pointer to array with the data to be written
num_bytes Number of bytes to be written
Returns
returns return value of method write_bytes (0 no error, otherwise error code)
Function writes num_bytes from array data into MRAM starting at address addr by calling private method write_bytes.
Definition at line 747 of file mram.cpp.
References spi_cfg, spi_dev, and write_bytes().
Referenced by erase().
readBytes()
int readBytes (uint32_t addr, uint8_t * data, size_t num_bytes)
Function to read multiple bytes from MRAM.
Parameters
addr Startaddress for reading the data from MRAM
data Pointer to array for the data to be read
num_bytes Number of bytes to be read
Returns
returns return value of method read_bytes (0 no error, otherwise error code)
Function read num_bytes into array data from MRAM starting at address addr by calling private method read_bytes.
Definition at line 764 of file mram.cpp.
References read_bytes(), spi_cfg, and spi_dev.
Referenced by dump().
sleep()
int sleep ()
Function to enter deep power down mode of MRAM.
Returns
returns return value of method enter_deep_power_down (0 no error, otherwise error code)
Function
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns with error code , otherwise it enters deep power down mode by calling private method dpd_enter and switch off MRAM power supply by calling member function power_off. The function returns the return value of method enter_deep_power_down (0 no error, otherwise error code)
Definition at line 783 of file mram.cpp.
References enter_deep_power_down(), power_off(), power_on(), spi_cfg, and spi_dev.
wakeup()
int wakeup ()
Function to leave deep power down mode of MRAM.
Returns
returns return value of method exit_deep_power_down (0 no error, otherwise error code)
Function
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns with error code , otherwise it enters deep power down mode by calling private method dpd_enter and switch off MRAM power supply by calling member function power_off. The function returns the return value of method exit_deep_power_down (0 no error, otherwise error code)
Definition at line 808 of file mram.cpp.
References exit_deep_power_down(), power_off(), power_on(), spi_cfg, and spi_dev.
Referenced by init().
setPowerOnDelay()
void setPowerOnDelay (uint32_t usec)
Setter function to set the power on delay.
The function assign the parameter usec to the private member variable power_delay_usec.
Definition at line 80 of file mram.cpp.
References power_delay_usec.
init()
void init ()
The initialization function of the SPI MRAM class.
The function initialize the value for status register with 0x40 (Serial Number Write protected) and for the configuration register 1 with 0x01 (Unlock TB and BP[2:0], Write Protection for Augmented Area Data) and the private member variables spi_dev (SPI controller device) and spi_cfg (SPI controller configuration) by calling the functions getController and getConfig of the spibus instance spibus::inst(). Afterwards if wake up the MRAM by calling member function wakeup, read device id, status register and configuration register 1 by vall of the member functions getDeviceId, getStatusRegVal and getConfig1RegVal. If status register has not value 0x40, configuration register 1 and status register will be read by calling the member functions write_config1_reg and write_status_reg and status register will be read again by call of function getStatusRegVal. Finally device ID and content of status register will be checked. If davice ID is not 0xD9010501 or status register has not value 0x40, an exception will be raised with call of macro __ASSERT_NO_MSG.
Definition at line 504 of file mram.cpp.
References config1_reg, spibus::getConfig(), getConfig1RegVal(), spibus::getController(), getDeviceId(), getStatusRegVal(), spibus::init(), spibus::inst(), spi_cfg, spi_dev, status_reg, wakeup(), write_config1_reg(), and write_status_reg().
power_on()
int power_on ()
Function to switch on MRAM.
Returns
returns 0 on success, error code otherwise
The method calls function gpio_pin_set_dt provided by zephyr GPIO library to initialize private member variable power_gpio of type struct gpio_dt_spec. In case function returns an error the method returns the error code immediately, otherwise method performs a delay to prevent abnormal read/write operations(see MRAM data sheet, page 9) and returns 0.
Definition at line 97 of file mram.cpp.
References power_delay_usec, and power_gpio.
Referenced by getConfig1RegVal(), getDeviceId(), getStatusRegVal(), sleep(), wakeup(), write_config1_reg(), and write_status_reg().
power_off()
int power_off ()
Function to switch off MRAM.
Returns
returns 0 on success, error code otherwise
The method calls function gpio_pin_set_dt provided by zephyr GPIO library to initialize private member variable power_gpio of type struct gpio_dt_spec. In case function returns an error the method returns the error code immediately, otherwise it returns 0.
Definition at line 119 of file mram.cpp.
References power_gpio.
Referenced by getConfig1RegVal(), getDeviceId(), getStatusRegVal(), sleep(), wakeup(), write_config1_reg(), and write_status_reg().
send_command()
int send_command (const struct device * spi, struct spi_config * spi_cfg, uint8_t cmd) private
Function to send a command to MRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
cmd the command to be send
Returns
returns The return code of function spi_write (0 no error, otherwise error code)
Function initializes transmit buffer with the OP code command cmd and call function spi_write. Finally the return value of spi_write will be returned to the calling function.
Definition at line 287 of file mram.cpp.
References spi_cfg.
Referenced by enter_deep_power_down(), exit_deep_power_down(), write_bytes(), write_config1_reg(), and write_status_reg().
mram_access()
int mram_access (const struct device * spi, struct spi_config * spi_cfg, uint8_t cmd, uint32_t addr, uint8_t * data, size_t len, bool is_write) private
Function to access MRAM for reading and writing.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
cmd OP code command
addr Startaddress for reading or writing the data from / in FRAM
data Pointer to array for the data to be read or to be written
len Number of bytes to be read or to be written
is_write Flag to specify read / write direction
Returns
returns return value of method spi_transceive in case of reading or of method spi_write in case of writing (0 no error, otherwise error code)
Function initializes transmit buffer and set the OP code command cmd and start address in array access. In case of reading the receive buffer is initialized and read the data by calling function spi_transceive. In case of writing the data will be written by calling function spi_write. Finally the return value of function spi_transceive or spi_write will be returned to calling function. See MRAM data sheet, page 12ff.
Definition at line 318 of file mram.cpp.
References spi_cfg.
Referenced by read_bytes(), write_bytes(), write_config1_reg(), and write_status_reg().
read_device_id()
int read_device_id (const struct device * spi, struct spi_config * spi_cfg, uint8_t * id_buf, size_t len) private
Function to read the device ID from MRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
id_buf unused
Todo:
remove
Parameters
len unused
Todo:
remove
Returns
returns return value of method spi_transceive (0 no error, otherwise error code)
Function initializes transmit and receive buffer, set the read Device ID OP code command CMD_RDID and read the device ID by calling function spi_transceive. See MRAM data sheet, page 12ff for OP code commands and page 22 for device ID.
Definition at line 359 of file mram.cpp.
References CMD_RDID, id, and spi_cfg.
Referenced by getDeviceId().
read_bytes()
int read_bytes (const struct device * spi, struct spi_config * spi_cfg, uint32_t addr, uint8_t * data, size_t len) private
Function to read multiple bytes to MRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
addr Startaddress for reading the data from MRAM
data Pointer to array for the data to be read
len Number of bytes to be read
Returns
returns return 0 on success, otherwise error code
Function read the data calling function mram_access with OP code command CMD_READ. In case of an error function returns error code, otherwise returns 0 for success indication. See MB85RS4MTY data sheet, page 12ff.
Definition at line 146 of file mram.cpp.
References CMD_READ, mram_access(), and spi_cfg.
Referenced by readBytes().
write_bytes()
int write_bytes (const struct device * spi, struct spi_config * spi_cfg, uint32_t addr, const uint8_t * data, size_t len) private
Function to write multiple bytes to MRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
addr Startaddress for writing the data in MRAM
data Pointer to array for the data to be written
len Number of bytes to be written
Returns
returns return 0 on success, otherwise error code
Function enable writing by calling function send_command with OP code command CMD_WREN. In case of an error function returns immediately with error code, otherwise the data will be written by calling function mram_access with OP code command CMD_WRTE. In case of an error function returns error code, otherwise returns 0 for indication success. See MRAM data sheet, page 12ff.
Definition at line 179 of file mram.cpp.
References CMD_WREN, CMD_WRTE, mram_access(), send_command(), and spi_cfg.
Referenced by writeBytes().
write_status_reg()
int write_status_reg (const struct device * spi, struct spi_config * spi_cfg, const uint8_t * data) private
Function to write MRAM status register.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
data Pointer to data array to be written
Returns
returns return 0 on success, otherwise error code
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns with error code, otherwise it enable writing by calling function send_command with OP code command CMD_WREN. In case of an error function returns immediately with error code, otherwise the status register will be written by calling function mram_access with OP code command CMD_WRAR. In case of an error function returns error code, otherwise returns 0 for indication success. See MRAM data sheet, page 12ff.
Definition at line 216 of file mram.cpp.
References CMD_WRAR, CMD_WREN, mram_access(), power_off(), power_on(), send_command(), and spi_cfg.
Referenced by init().
write_config1_reg()
int write_config1_reg (const struct device * spi, struct spi_config * spi_cfg, const uint8_t * data) private
Function to write MRAM configuration register 1.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
data Pointer to data array to be written
Returns
returns return 0 on success, otherwise error code
Function switch on MRAM power supply by calling member function power_on. In case of an error function returns with error code, otherwise it enable writing by calling function send_command with OP code command CMD_WREN. In case of an error function returns immediately with error code, otherwise the configuration register 1 will be written by calling function mram_access with OP code command CMD_WRAR. In case of an error function returns error code, otherwise returns 0 for indication success. See MRAM data sheet, page 12ff.
Definition at line 253 of file mram.cpp.
References CMD_WRAR, CMD_WREN, mram_access(), power_off(), power_on(), send_command(), and spi_cfg.
Referenced by init().
enter_deep_power_down()
int enter_deep_power_down (const struct device * spi, struct spi_config * spi_cfg) private
Function to enter deep power down mode of MRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
Returns
returns return code of function send_command
The function send the command CMD_DPD_ENTER to enter deep power down mode to MRAM by calling member function send_command.
Definition at line 458 of file mram.cpp.
References CMD_DPD_ENTER, send_command(), and spi_cfg.
Referenced by sleep().
exit_deep_power_down()
int exit_deep_power_down (const struct device * spi, struct spi_config * spi_cfg) private
Function to exit deep power down mode of MRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
Returns
returns return code of function send_command
The function send the command CMD_DPD_EXIT to exit deep power down mode to MRAM by calling member function send_command.
Definition at line 477 of file mram.cpp.
References CMD_DPD_EXIT, send_command(), and spi_cfg.
Referenced by wakeup().
read_status_reg()
int read_status_reg (const struct device * spi, struct spi_config * spi_cfg, uint8_t * id_buf, size_t len) private
Function to read MRAM status register.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
id_buf UNUSED
Todo:
remove
Parameters
len UNUSED
Todo:
remove
Returns
returns return 0 on success, otherwise error code
Function initializes transmit and receive buffer, set the read read status register ID OP code command CMD_RDSR and read the status register by calling function spi_transceive. See MRAM data sheet, page 12ff for OP code commands and page 15 for status register.
Definition at line 393 of file mram.cpp.
References CMD_RDSR, spi_cfg, and status_reg.
Referenced by getStatusRegVal().
read_config1_reg()
int read_config1_reg (const struct device * spi, struct spi_config * spi_cfg, uint8_t * id_buf, size_t len) private
Function to read MRAM configuration register 1.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
id_buf UNUSED
Todo:
remove
Parameters
len UNUSED
Todo:
remove
Returns
returns return 0 on success, otherwise error code
Function initializes transmit and receive buffer, set the read read configuration register 1 ID OP code command CMD_RDC1 and read the configuration register 1 by calling function spi_transceive. See MRAM data sheet, page 12ff for OP code commands and page 17 for configuration register 1.
Definition at line 428 of file mram.cpp.
References CMD_RDC1, config1_reg, and spi_cfg.
Referenced by getConfig1RegVal().
Field Documentation
power_gpio
const struct gpio_dt_spec power_gpio private
Initial value:
= {
        .port = DEVICE_DT_GET(DT_NODELABEL(gpio0)),
        .pin = 13,
        .dt_flags = GPIO_ACTIVE_HIGH,
    }
Devicetree setup for the MRAM power enable pin.
Definition at line 97 of file mram.h.
Referenced by power_off(), power_on(), and spimram().
power_delay_usec
uint32_t power_delay_usec private
Power on delay.
Definition at line 107 of file mram.h.
Referenced by power_on(), and setPowerOnDelay().
CMD_WRSR
constexpr uint8_t CMD_WRSR = 0x01 static constexpr private
Command to write the status register.
Definition at line 110 of file mram.h.
CMD_WRTE
constexpr uint8_t CMD_WRTE = 0x02 static constexpr private
Command to write a memory array.
Definition at line 112 of file mram.h.
Referenced by write_bytes().
CMD_READ
constexpr uint8_t CMD_READ = 0x03 static constexpr private
Command to read memory area.
Definition at line 114 of file mram.h.
Referenced by read_bytes().
CMD_RDSR
constexpr uint8_t CMD_RDSR = 0x05 static constexpr private
Command to read the status register.
Definition at line 116 of file mram.h.
Referenced by read_status_reg().
CMD_WREN
constexpr uint8_t CMD_WREN = 0x06 static constexpr private
Write enable command.
Definition at line 118 of file mram.h.
Referenced by write_bytes(), write_config1_reg(), and write_status_reg().
CMD_RDC1
constexpr uint8_t CMD_RDC1 = 0x35 static constexpr private
Command to read configuration register 1.
Definition at line 120 of file mram.h.
Referenced by read_config1_reg().
CMD_RDAR
constexpr uint8_t CMD_RDAR = 0x65 static constexpr private
Command to read any register, address based.
Definition at line 122 of file mram.h.
CMD_WRAR
constexpr uint8_t CMD_WRAR = 0x71 static constexpr private
Command to write any register, address based.
Definition at line 124 of file mram.h.
Referenced by write_config1_reg(), and write_status_reg().
CMD_RDID
constexpr uint8_t CMD_RDID = 0x9F static constexpr private
Command to read the device ID.
Definition at line 126 of file mram.h.
Referenced by read_device_id().
CMD_DPD_ENTER
constexpr uint8_t CMD_DPD_ENTER = 0xB9 static constexpr private
Command to enter deep power down mode.
Definition at line 128 of file mram.h.
Referenced by enter_deep_power_down().
CMD_DPD_EXIT
constexpr uint8_t CMD_DPD_EXIT = 0xAB static constexpr private
Command to exit deep power down mode.
Definition at line 130 of file mram.h.
Referenced by exit_deep_power_down().
id
uint8_t id[4] private
The device ID.
Definition at line 133 of file mram.h.
Referenced by getDeviceId(), and read_device_id().
status_reg
uint8_t status_reg private
Variable to hold the content of the status register Bit 7: WPEN, R/W, HW Based Protect Bit, 1:P. Enabled, 0:P. Disabled
Bit 6: SNPEN, R/W, SerialNr Protect Bit, 1:Wr protected, 0;Writable
Bit 5: TB, R/W, Top/Bottom Memory Array Protect Selection, 1: Bottom P. Enabled, 0: Top P. Enabled
Bit 4: BP[2], R/W, Block Protection Bit 2
Bit 3: BP[1], R/W, Block Protection Bit 1
Bit 2: BP[0], R/W, Block Protection Bit 0
Bit 1: WREN, R, Write Protection Enable, 1:Disabled, 0:Enabled
Bit 0: RSVD, R, Reserved for future use
Definition at line 145 of file mram.h.
Referenced by getStatusRegVal(), init(), and read_status_reg().
config1_reg
uint8_t config1_reg private
Variable to hold the content of the configuration register 1 Bit 7: RSVD, R/W, Reserved for future use
Bit 6: RSVD, R/W, Reserved for future use
Bit 5: RSVD, R/W, Reserved for future use
Bit 4: RSVD, R/W, Reserved for future use
Bit 3: RSVD, R/W, Reserved for future use
Bit 2: MAPLK, R/W, Status Register TB, BP[2:0] Protect, 1: Lock TB and BP[2:0], 0: Unlock TB and BP[2:0]
Bit 1: RSVD, R/W, Reserved for future use
Bit 0: ASPLK, R/W, Augmented 256-Byte Area Data Protection, 1: Write Protection for Augmented Area Data regardless of ASP[7:0], 0: Write Protection for Augmented Area Data depending on ASP[7:0]
Definition at line 159 of file mram.h.
Referenced by getConfig1RegVal(), init(), and read_config1_reg().
spi_dev
const struct device* spi_dev private
SPI controller device.
Definition at line 161 of file mram.h.
Referenced by getConfig1RegVal(), getDeviceId(), getStatusRegVal(), init(), readBytes(), sleep(), wakeup(), and writeBytes().
spi_cfg
struct spi_config* spi_cfg private
SPI controller configuration.
Definition at line 162 of file mram.h.
Referenced by enter_deep_power_down(), exit_deep_power_down(), getConfig1RegVal(), getDeviceId(), getStatusRegVal(), init(), mram_access(), read_bytes(), read_config1_reg(), read_device_id(), read_status_reg(), readBytes(), send_command(), sleep(), wakeup(), write_bytes(), write_config1_reg(), write_status_reg(), and writeBytes().
The documentation for this class was generated from the following files:
drv/spi/mram.h
drv/spi/mram.cpp