AXO X1: Mbox Class Reference
Mbox Class Reference
RTOS wrapper for mailbox support.
#include <mbox.h>
Detailed Description
RTOS wrapper for mailbox support.
Detailed Description
The MBox class implements a C++ wrapper for mailbox support using the kernel message queue API provided by the Zephyr operating system. See details in Zephyr message queue documentation or in API documentation. The Mbox class provides methods to read (receive) objects of type PoolElem from the mailbox and to write (send) PoolElem objects to the mailbox. It provides an enumeration with all maibox ID's of the system, methods to register a mailbox by storing the pointer to the mailbox in an array, to retrieve the mailbox pointer by given ID Furthermore it provides a method to count the number of objects in the queue and to print statistics.
Definition at line 62 of file mbox.h.
Public Types
enum MboxId {
eMain = 0 , eLteConnector , eMqttConnector , eHttpConnector ,
eLteMonitor , eSi705xTask , eShtcxTask , eBme68xTask ,
eAdxl37xTask , eAdxlStore , eRmsStore , eAdxlRms ,
eADConverter , eNTC , eBattMgr , eDataManager ,
ePowerManager , eBoostConverter , eMetrics , eFwUpd ,
eFwUpdCtrl , eResetCtrl , eDemoTask , eHwMetrics ,
eDispTask , eMbReceive , eMboxMax
}
Enumeration with all maibox ID's of the system.
Public Member Functions
Mbox (const char *name="??")
Mbox class constructor.
Mbox ()=delete
virtual ~Mbox ()
Mbox class destructor.
void write (PoolElem *elem)
PoolElem * read ()
Mbox read function.
uint32_t count ()
void stats ()
uint32_t getMaxSlots ()
Static Public Member Functions
static void send (PoolElem *elem, MboxId toWhom)
Mbox send function.
static void registerMbox (Mbox *me, MboxId myId)
Mbox register function.
static Mbox * getMboxById (MboxId id)
Getter function to retrieve the mailbox pointer by given ID.
static void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId)
Message send convinience function.
static void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, uint8_t u8DataByte)
Message send convinience function.
static void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, int8_t s8DataByte)
Message send convinience function.
static void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, uint8_t *pData, uint16_t dataLen)
Message send convinience function.
static void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, const std::string &str)
Message send convinience function.
Private Attributes
char myName [16]
The name of the mailbox.
MQueue< PoolElem, max_slots > pQueue
The message queue object for masseges of type PoolElem.
Static Private Attributes
static const uint32_t max_slots
The number of message slots in the mailbox.
static Mbox * mBoxAll [eMboxMax]
Member Enumeration Documentation
MboxId
enum MboxId
Enumeration with all maibox ID's of the system.
Enumerator
eMain
ID of the main process, only used as sender ID, e.g. for shell input
eLteConnector
ID of the LTE connector task.
eMqttConnector
ID of the MQTT connector task.
eHttpConnector
ID of the HTTP connector task.
eLteMonitor
ID of the LTE monitor task.
eSi705xTask
ID of the Si705x temperature sensor task (5)
eShtcxTask
ID of the Shtcx temperature and humidity sensor task.
eBme68xTask
ID of the Bme68x temperature sensor task.
eAdxl37xTask
ID of the Adxl37x acceleration sensor task.
eAdxlStore
ID of the ADXL store task.
eRmsStore
ID of the RMS store task (10)
eAdxlRms
ID of the ADXL RMS task.
eADConverter
ID of the AD converter task.
eNTC
ID of the NTC task.
eBattMgr
ID of the battery manager task.
eDataManager
ID of the data manager task (15)
ePowerManager
ID of the power manager task.
eBoostConverter
ID of the boost converter task.
eMetrics
ID of the metrics task.
eFwUpd
ID of the firmware update task.
eFwUpdCtrl
ID of the firmware update control task.
eResetCtrl
ID of the reset control task (20)
eDemoTask
ID of the demo task.
eHwMetrics
ID of the HW metrics task.
eDispTask
ID of the displacement task.
eMbReceive
ID of the modbus message receiver task.
eMboxMax
Last entry, indicating the number of mailboxes in the system
Definition at line 65 of file mbox.h.
Constructor & Destructor Documentation
Mbox() [1/2]
Mbox (const char * name = "??") explicit
Mbox class constructor.
Parameters
name The name of the mailbox
The constructor store the name of the mailbox in private member variable myName.
Definition at line 40 of file mbox.cpp.
References myName.
Mbox() [2/2]
Mbox () delete
~Mbox()
~Mbox () virtual
Mbox class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 52 of file mbox.cpp.
Member Function Documentation
write()
void write (PoolElem * elem)
Definition at line 54 of file mbox.cpp.
References PoolElem::Dump(), myName, pQueue, and MQueue::put().
Referenced by PowerMgrX1::AdxlWakeupTimer_expired(), PowerMgrX1::BoostCtrlTimer_expired(), HttpConnector::delayTimer_expired(), PowerMgrX1::LteStartDelayTimer_expired(), PowerMgr::MetricsTxTimer_expired(), LteConnector::notify(), ADConverter::notifyListener(), HttpConnector::oneDayTimer_expired(), send(), DataManager::timer1_expired(), RmsTask::timer1_expired(), Shtcx::timer1_expired(), BoostConverter::timer1_expired(), Adxl37x::timer1_expired(), LteMonitor::timer1_expired(), LteConnector::timer1_expired(), MqttConnector::timer1_expired(), ResetCtrl::timer1_expired(), FwUpdCtrl::timer1_expired(), and ADConverter::timer1_expired().
send()
void send (PoolElem * elem, MboxId toWhom) static
Mbox send function.
Parameters
elem The message to be send
toWhom The ID of the receiver mailbox
The function retrieve the pointer to the receiver mailbox by calling member function getMboxById and uses the pointer to call the function write with message elem of the receiver mailbox object.
Definition at line 76 of file mbox.cpp.
References getMboxById(), and write().
Referenced by Adxl37x::fifo_handler(), FwDownload::handle_DlComplete(), FwDownload::handle_DlFailed(), FwTriggered::handle_FwInfo(), sendMsg(), AdxlDataStore::task(), HwMetrics::task(), Adxl37x::task(), HttpConnector::task(), MqttConnector::task(), DataManager::task(), RmsStore::task(), and BatteryMgr::task().
read()
PoolElem * read ()
Mbox read function.
Returns
Pointer to the received (read) message of type PoolElem
The function receive (read) the message of type PoolElem by calling the get function of the message queue class MQueue. Finally it returns a pointer to the received message.
Definition at line 98 of file mbox.cpp.
References MQueue::get(), and pQueue.
Referenced by RmsTask::task(), AdxlDataStore::task(), HwMetrics::task(), DispTask::task(), ADConverter::task(), Shtcx::task(), BoostConverter::task(), Adxl37x::task(), HttpConnector::task(), MqttConnector::task(), PowerMgr::task(), ResetCtrl::task(), FwUpd::task(), FwUpdCtrl::task(), DataManager::task(), RmsStore::task(), BatteryMgr::task(), LteMonitor::task(), and LteConnector::task().
count()
uint32_t count () inline
Definition at line 102 of file mbox.h.
References MQueue::count(), and pQueue.
stats()
void stats () inline
Definition at line 103 of file mbox.h.
References pQueue, and MQueue::stats().
getMaxSlots()
uint32_t getMaxSlots () inline
Definition at line 104 of file mbox.h.
References max_slots.
registerMbox()
void registerMbox (Mbox * me, MboxId myId) static
Mbox register function.
Parameters
me Pointer to the maibox to be registered
myId The ID of the mailbox to be registered
The function register the pointer to the mailbox by storing it in the array mBoxAll at index myId.
Definition at line 115 of file mbox.cpp.
References eMboxMax, and mBoxAll.
Referenced by ADConverter::ADConverter(), Adxl37x::Adxl37x(), AdxlDataStore::AdxlDataStore(), BatteryMgr::BatteryMgr(), BoostConverter::BoostConverter(), DataManager::DataManager(), DispTask::DispTask(), FwUpd::FwUpd(), FwUpdCtrl::FwUpdCtrl(), HttpConnector::HttpConnector(), HwMetrics::HwMetrics(), LteConnector::LteConnector(), LteMonitor::LteMonitor(), MqttConnector::MqttConnector(), PowerMgr::PowerMgr(), ResetCtrl::ResetCtrl(), RmsStore::RmsStore(), RmsTask::RmsTask(), and Shtcx::Shtcx().
getMboxById()
Mbox * getMboxById (MboxId id) static
Getter function to retrieve the mailbox pointer by given ID.
Parameters
id The ID of the mailbox
Returns
Pointer to the mailbox
The function retrieve the pointer to the mailbox by read it from array mBoxAll at index id and returns the pointer.
Definition at line 133 of file mbox.cpp.
References eMboxMax, and mBoxAll.
Referenced by send().
sendMsg() [1/5]
void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId) static
Message send convinience function.
Parameters
mType The message type
senderId The ID of the sender task
receiverId The ID of the receiver task
The function request a message from message pool, set message type to parameter mType, set senderId as sender and send message to mailbox indicated by parameter receiverId by calling static member function send.
Definition at line 154 of file mbox.cpp.
References PoolElem::from, MsgPool::getNewElem(), MsgPool::inst(), PoolElem::mtype, and send().
Referenced by MeasurementBuilder::addRmsData(), LteMonitor::at_ecsq_handler(), FwUpd::download_failed(), FwUpd::download_success(), DispTask::filt_dump(), FwTriggered::handle_timer_exp(), FwDownload::handle_timer_exp(), HttpConnector::HandleAdxlIdleInd(), MqttConnector::HandleBoostOffReq(), MqttConnector::HandleBoostOnReq(), DispTask::HandleCalcDisplacementReq(), MqttConnector::HandleColdStartReq(), MqttConnector::HandleDisableADXL(), DispTask::HandleDispFirstEntries(), MqttConnector::HandleEnableADXL(), DispTask::HandleRawDataStatus(), HttpConnector::HandleRcvdDispData(), HttpConnector::HandleRcvdRawData(), HttpConnector::HttpDispDataSend(), HttpConnector::HttpRawDataSend(), PowerMgrX1::message_handler(), PowerMgr::metricProviderNotify(), AdxlDataStore::notifyRawDataStatus(), AdxlDataStore::notifySender(), AdxlDataStore::notifyStorageFull(), MqttConnector::on_connack(), MqttConnector::on_disconnect(), MqttConnector::on_publish(), FwUpdCtrl::otaFwConfirm(), FwUpdCtrl::otaFwReject(), FwUpdCtrl::otaStartConfirm(), FwUpdCtrl::otaStartReject(), DataManager::publishMeasurements(), DataManager::publishMetrics(), HwMetrics::report(), Adxl37x::report(), LteMonitor::reportBattVoltage(), PowerMgr::reportBootCnt(), LteMonitor::reportFwVersion(), Shtcx::reportHumidity(), Adxl37x::reportHwStatus(), LteMonitor::reportIMEI(), LteMonitor::reportIMSI(), LteMonitor::reportLinkQuality(), FwFsm::ReportOtaUpdateActive(), LteMonitor::reportPsmAct(), PowerMgr::reportResetCause(), Shtcx::reportTemperature(), LteMonitor::reportTemperature(), BatteryMgr::reqAdcReport(), PowerMgrX1::reqBoostConverter(), DispTask::reqBwFiltData(), HttpConnector::reqData(), DispTask::reqDResultWrite(), DispTask::reqFiltResultWrite(), DispTask::reqFwFiltData(), DispTask::reqRawData(), HttpConnector::reqRawDataStatus(), PowerMgr::reqRmsReport(), DispTask::reqSResultData(), DispTask::reqSResultWrite(), FwUpdCtrl::requestDownload(), AdxlDataStore::sendBwFiltData(), AdxlDataStore::sendDispData(), DispTask::sendDispStatistics(), AdxlDataStore::sendFwFiltData(), LteConnector::sendMsg2OwnMbox(), AdxlDataStore::sendRawData(), AdxlDataStore::sendSResultData(), AdxlDataStore::shell_dump(), RmsStore::shell_dump(), AdxlDataStore::shell_dump_bytes(), AdxlDataStore::shell_dump_disp(), AdxlDataStore::shell_dump_filt(), HttpConnector::StartHttpDispDataTransmission(), HttpConnector::StartHttpRawDataTransmission(), AdxlDataStore::storeBackwardFilt(), AdxlDataStore::storeDResult(), AdxlDataStore::storeForwardFilt(), AdxlDataStore::storeSResult(), RmsTask::task(), AdxlDataStore::task(), DispTask::task(), HttpConnector::task(), MqttConnector::task(), and RmsTask::update_rms().
sendMsg() [2/5]
void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, uint8_t u8DataByte) static
Message send convinience function.
Parameters
mType The message type
senderId The ID of the sender task
receiverId The ID of the receiver task
u8DataByte The 1 byte unsigned data to be send to receiver
The function request a message from message pool, set message type to parameter mType, set senderId as sender, copy the data byte in arbitrary byte parameter p1 and send message to mailbox indicated by parameter receiverId by calling static member function send.
Definition at line 176 of file mbox.cpp.
References PoolElem::from, MsgPool::getNewElem(), MsgPool::inst(), PoolElem::mtype, PoolElem::p1, and send().
sendMsg() [3/5]
void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, int8_t s8DataByte) static
Message send convinience function.
Parameters
mType The message type
senderId The ID of the sender task
receiverId The ID of the receiver task
s8DataByte The 1 byte signed data to be send to receiver
The function request a message from message pool, set message type to parameter mType, set senderId as sender, copy the data byte in arbitrary byte parameter p2 and send message to mailbox indicated by parameter receiverId by calling static member function send.
Definition at line 200 of file mbox.cpp.
References PoolElem::from, MsgPool::getNewElem(), MsgPool::inst(), PoolElem::mtype, PoolElem::p2, and send().
sendMsg() [4/5]
void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, uint8_t * pData, uint16_t dataLen) static
Message send convinience function.
Parameters
mType The message type
senderId The ID of the sender task
receiverId The ID of the receiver task
pData Pointer to the data to be send to receiver
dataLen Length of the data to be send to receiver in byte
The function request a message from message pool, set message type to parameter mType, set senderId as sender, copy the data in the payload of the message by calling function putData provided by the PoolElem class and send message to mailbox indicated by parameter receiverId by calling static member function send.
Definition at line 226 of file mbox.cpp.
References PoolElem::from, MsgPool::getNewElem(), MsgPool::inst(), PoolElem::mtype, PoolElem::putData(), and send().
sendMsg() [5/5]
void sendMsg (enum msgType mType, MboxId senderId, MboxId receiverId, const std::string & str) static
Message send convinience function.
Parameters
mType The message type
senderId The ID of the sender task
receiverId The ID of the receiver task
str String to be send to receiver
The function request a message from message pool, set message type to parameter mType, set senderId as sender, copy the string in the payload of the message by calling function putString provided by the PoolElem class and send message to mailbox indicated by parameter receiverId by calling static member function send.
Definition at line 251 of file mbox.cpp.
References PoolElem::from, MsgPool::getNewElem(), MsgPool::inst(), PoolElem::mtype, PoolElem::putString(), and send().
Field Documentation
myName
char myName[16] private
The name of the mailbox.
Definition at line 120 of file mbox.h.
Referenced by Mbox(), and write().
max_slots
const uint32_t max_slots static private
Initial value:
=
        8
The number of message slots in the mailbox.
Definition at line 121 of file mbox.h.
Referenced by getMaxSlots().
pQueue
MQueue<PoolElem, max_slots> pQueue private
The message queue object for masseges of type PoolElem.
Definition at line 124 of file mbox.h.
Referenced by count(), read(), stats(), and write().
mBoxAll
Mbox * mBoxAll static private
Array with all registered Mbox pointers, index = ID of enumerator MboxId
Definition at line 127 of file mbox.h.
Referenced by getMboxById(), and registerMbox().
The documentation for this class was generated from the following files:
rtos/mbox.h
rtos/mbox.cpp