AXO X1: spifram Class Reference
spifram Class Reference
SPI FRAM class implemented according to C++ singleton design pattern.
#include <fram.h>
Detailed Description
SPI FRAM class implemented according to C++ singleton design pattern.
Detailed Description
The SPI FRAM class handle the storage of the acceleration raw data in FRAM. It provides methods to initialize and erase FRAM, to read and write the data, to push FRAM into power saving mode or release from it, to dump the data and to read and ship the devcie ID. Furthermore it provides a private method to test the integrity of the FRAM at startup of the system.
Definition at line 71 of file fram.h.
Public Member Functions
~spifram ()
SPI FRAM class destructor.
void init ()
The initialization function of the SPI FRAM class.
void erase ()
Function to erase the content of the FRAM.
void erase (void *from, int32_t len)
void dump (uint32_t from, int32_t len)
Function to print the content of the FRAM in a terminal.
int readDeviceId ()
Function to read the device ID if the FRAM chip.
int sleep ()
Function to enter deep power down mode of FRAM.
int wakeup ()
Function to wake up FRAM from deep power down mode.
int power_on ()
Function to switch on FRAM.
int power_off ()
Function to switch off FRAM.
uint8_t * getDeviceId ()
Getter function to retrieve the device ID.
int writeBytes (uint32_t addr, uint8_t *data, uint32_t num_bytes)
Function to write multiple bytes into FRAM.
int readBytes (uint32_t addr, uint8_t *data, uint32_t num_bytes)
Function to read multiple bytes from FRAM.
Static Public Member Functions
static spifram * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Data Fields
uint8_t id [4]
const struct device * spi_dev
SPI controller device.
struct spi_config * spi_cfg
SPI controller configuration.
Private Member Functions
spifram ()
SPI FRAM class constructor.
int dpd_enter (const struct device *spi, struct spi_config *spi_cfg)
Function to enter deep power down mode of FRAM.
int dpd_exit (const struct device *spi, struct spi_config *spi_cfg)
Function to wake up FRAM from deep power down mode.
int read_device_id (const struct device *spi, struct spi_config *spi_cfg)
Function to read the device ID from FRAM.
int fram_access (const struct device *spi, struct spi_config *spi_cfg, uint8_t cmd, uint32_t addr, void *data, size_t len)
Function to access FRAM for reading and writing.
int write_bytes (const struct device *spi, struct spi_config *spi_cfg, uint32_t addr, uint8_t *data, uint32_t num_bytes)
Function to write multiple bytes to FRAM.
int read_bytes (const struct device *spi, struct spi_config *spi_cfg, uint32_t addr, uint8_t *data, uint32_t num_bytes)
Function to read multiple bytes to FRAM.
bool selftest ()
Private Attributes
bool dpd_active
Constructor & Destructor Documentation
~spifram()
~spifram ()
SPI FRAM class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 56 of file fram.cpp.
spifram()
spifram () private
SPI FRAM class constructor.
The constructor is declared as private according to singleton pattern. It is called in the static inst function to create the exclusiv only instance of the class. It initializes the private member variable dpd_active with false.
Definition at line 46 of file fram.cpp.
Member Function Documentation
inst()
spifram * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 66 of file fram.cpp.
Referenced by init().
init()
void init ()
The initialization function of the SPI FRAM class.
The function initialize the private member variables spi_dev (SPI controller device) and spi_cfg (SPI controller configuration) by calling the functions getController and getConfig of the spibus instance spibus::inst(), Afterwards self test of the class will be performed by calling function selftest. In case of a failure an error message will be printed.
In Zephyr devicetree FRAM SPI is SPI bus 3.
Definition at line 82 of file fram.cpp.
References spibus::getConfig(), spibus::getController(), spibus::init(), spibus::inst(), inst(), selftest(), spi_cfg, and spi_dev.
erase() [1/2]
void erase ()
Function to erase the content of the FRAM.
Function initialize an array of size 1 KByte with 0 and write every this array into FRAM by calling function writeBytes 512 times.
Definition at line 120 of file fram.cpp.
References writeBytes().
erase() [2/2]
void erase (void * from, int32_t len)
dump()
void dump (uint32_t from, int32_t len)
Function to print the content of the FRAM in a terminal.
Parameters
from Start point of data to be printed
len Length (number of bytes) of data to be printed
Function read every single byte from start point until end point (from + len) by calling function readBytes. After every call a short delay of 5 ms will be performed and the data will be printed out by call of macro LOG_PRINTK.
Definition at line 138 of file fram.cpp.
References readBytes().
readDeviceId()
int readDeviceId ()
Function to read the device ID if the FRAM chip.
Returns
rc: 0 if no error, otherwise error code
The public method read device ID by calling the private member function read_device_id In case of a failure an error message will be printed.
Definition at line 104 of file fram.cpp.
References read_device_id(), spi_cfg, and spi_dev.
Referenced by selftest().
sleep()
int sleep ()
Function to enter deep power down mode of FRAM.
Returns
returns return value of method dpd_enter (0 no error, otherwise error code)
Function enters deep power down mode by calling private method dpd_enter.
Definition at line 169 of file fram.cpp.
References dpd_enter(), spi_cfg, and spi_dev.
wakeup()
int wakeup ()
Function to wake up FRAM from deep power down mode.
Returns
returns return value of method dpd_enter (0 no error, otherwise error code)
Function returns from deep power down mode by calling private method dpd_exit.
Definition at line 180 of file fram.cpp.
References dpd_exit(), spi_cfg, and spi_dev.
Referenced by selftest().
power_on()
int power_on ()
Function to switch on FRAM.
Returns
returns return allways 0
Dummy implementation for compatibility with mram module
Definition at line 189 of file fram.cpp.
power_off()
int power_off ()
Function to switch off FRAM.
Returns
returns return allways 0
Dummy implementation for compatibility with mram module
Definition at line 198 of file fram.cpp.
getDeviceId()
uint8_t * getDeviceId ()
Getter function to retrieve the device ID.
Returns
returns the device ID as 8-bit unsigned interger pointer
Function returns a pointer to public array id[4].
Definition at line 156 of file fram.cpp.
References id.
Referenced by selftest().
writeBytes()
int writeBytes (uint32_t addr, uint8_t * data, uint32_t num_bytes)
Function to write multiple bytes into FRAM.
Parameters
addr Startaddress for writing the data in FRAM
data Pointer to array with the data to be written
num_bytes Number of bytes to be written
Returns
returns return value of method write_bytes (0 no error, otherwise error code)
Function writes num_bytes from array data into FRAM starting at address addr by calling private method write_bytes.
Definition at line 214 of file fram.cpp.
References spi_cfg, spi_dev, and write_bytes().
Referenced by erase(), and selftest().
readBytes()
int readBytes (uint32_t addr, uint8_t * data, uint32_t num_bytes)
Function to read multiple bytes from FRAM.
Parameters
addr Startaddress for reading the data from FRAM
data Pointer to array for the data to be read
num_bytes Number of bytes to be read
Returns
returns return value of method read_bytes (0 no error, otherwise error code)
Function read num_bytes into array data from FRAM starting at address addr by calling private method read_bytes.
Definition at line 234 of file fram.cpp.
References read_bytes(), spi_cfg, and spi_dev.
Referenced by dpd_exit(), dump(), and selftest().
dpd_enter()
int dpd_enter (const struct device * spi, struct spi_config * spi_cfg) private
Function to enter deep power down mode of FRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
Returns
returns 0 on success, otherwise error code
Function initializes transmit buffer, set the enter deep power down OP code command MB85SR4MTY_DPD_CMD and pass transmit buffer to FRAM by calling function spi_write. In case of success the private member variable dpd_active is set to true and the function returns 0 for success indication. In case of an error function returns error code EIO. See MB85RS4MTY data sheet, page 7.
Definition at line 459 of file fram.cpp.
References dpd_active, MB85SR4MTY_DPD_CMD, and spi_cfg.
Referenced by sleep().
dpd_exit()
int dpd_exit (const struct device * spi, struct spi_config * spi_cfg) private
Function to wake up FRAM from deep power down mode.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
Returns
returns 0 on success, otherwise error code
Function wakes up FRAM by pulling Chip Select CS to low and after a delay of 10 usec to high. In case of an error function returns error code EIO.Afterwards a dummy read of one byte is performed at address 0 og FRAM by calling function readBytes. Finally the private member variable dpd_active is set to false and function returns 0 for success indication. See MB85RS4MTY data sheet, page 22.
Definition at line 496 of file fram.cpp.
References dpd_active, readBytes(), and spi_cfg.
Referenced by wakeup().
read_device_id()
int read_device_id (const struct device * spi, struct spi_config * spi_cfg) private
Function to read the device ID from FRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
Returns
returns return value of method spi_transceive (0 no error, otherwise error code)
Function initializes transmit and receive buffer, set the read Device ID OP code command MB85RS4MTY_MANUFACTURER_ID_CMD and read the device ID by calling function spi_transceive. See MB85RS4MTY data sheet, page 7 for OP code commands and page 11 for device ID.
Definition at line 314 of file fram.cpp.
References id, MB85RS4MTY_MANUFACTURER_ID_CMD, and spi_cfg.
Referenced by readDeviceId().
fram_access()
int fram_access (const struct device * spi, struct spi_config * spi_cfg, uint8_t cmd, uint32_t addr, void * data, size_t len) private
Function to access FRAM for reading and writing.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
cmd OP code command
addr Startaddress for reading or writing the data from / in FRAM
data Pointer to array for the data to be read or to be written
len Number of bytes to be read or to be written
Returns
returns return value of method spi_transceive in case of reading or of method spi_write in case of writing (0 no error, otherwise error code)
Function initializes transmit buffer an set the OP code command cmd and start address in array access. In case of reading the receive buffer is initialized and read the data by calling function spi_transceive. In case of writing the data will be written by calling function spi_write. Finally the return value of function spi_transceive or spi_write will be returned to calling function. See MB85RS4MTY data sheet, page 7.
Definition at line 353 of file fram.cpp.
References MB85RS4MTY_READ_CMD, and spi_cfg.
Referenced by read_bytes(), and write_bytes().
write_bytes()
int write_bytes (const struct device * spi, struct spi_config * spi_cfg, uint32_t addr, uint8_t * data, uint32_t num_bytes) private
Function to write multiple bytes to FRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
addr Startaddress for writing the data in FRAM
data Pointer to array for the data to be written
num_bytes Number of bytes to be written
Returns
returns return 0 on success, otherwise error code
Function enable writing by calling function fram_access with OP code command MB85RS4MTY_WRITE_ENABLE_CMD. In case of an error function returns immediately with error code EIO, otherwise the data will be written by calling function fram_access with OP code command MB85RS4MTY_WRITE_CMD. In case of an error function returns error code EIO, otherwise returns 0 for indication success. See MB85RS4MTY data sheet, page 7.
Definition at line 396 of file fram.cpp.
References fram_access(), MB85RS4MTY_WRITE_CMD, MB85RS4MTY_WRITE_ENABLE_CMD, and spi_cfg.
Referenced by writeBytes().
read_bytes()
int read_bytes (const struct device * spi, struct spi_config * spi_cfg, uint32_t addr, uint8_t * data, uint32_t num_bytes) private
Function to read multiple bytes to FRAM.
Parameters
spi Pointer to the SPI device node identifier of type struct device
spi_cfg Pointer to the SPI controller configuration structure of type struct spi_config
addr Startaddress for reading the data from FRAM
data Pointer to array for the data to be read
num_bytes Number of bytes to be read
Returns
returns return 0 on success, otherwise error code
Function read the data calling function fram_access with OP code command MB85RS4MTY_READ_CMD. In case of an error function returns error code EIO, otherwise returns 0 for success indication. See MB85RS4MTY data sheet, page 7.
Definition at line 433 of file fram.cpp.
References fram_access(), MB85RS4MTY_READ_CMD, and spi_cfg.
Referenced by readBytes().
selftest()
bool selftest () private
Definition at line 519 of file fram.cpp.
References FRAM_DEVICE_ID_1, FRAM_DEVICE_ID_2, FRAM_DEVICE_ID_3, FRAM_DEVICE_ID_4, getDeviceId(), readBytes(), readDeviceId(), wakeup(), and writeBytes().
Referenced by init().
Field Documentation
id
uint8_t id[4]
Definition at line 89 of file fram.h.
Referenced by getDeviceId(), and read_device_id().
spi_dev
const struct device* spi_dev
SPI controller device.
Definition at line 90 of file fram.h.
Referenced by init(), readBytes(), readDeviceId(), sleep(), wakeup(), and writeBytes().
spi_cfg
struct spi_config* spi_cfg
SPI controller configuration.
Definition at line 91 of file fram.h.
Referenced by dpd_enter(), dpd_exit(), fram_access(), init(), read_bytes(), read_device_id(), readBytes(), readDeviceId(), sleep(), wakeup(), write_bytes(), and writeBytes().
dpd_active
bool dpd_active private
Definition at line 113 of file fram.h.
Referenced by dpd_enter(), and dpd_exit().
The documentation for this class was generated from the following files:
drv/spi/fram.h
drv/spi/fram.cpp