AXO X1: KeyGen Class Reference
KeyGen Class Reference
TLS key generation class implemented according to C++ singleton design pattern.
#include <keygen.h>
Detailed Description
TLS key generation class implemented according to C++ singleton design pattern.
The KeyGen class use the mbedtls crypto library. See details in Mbed TLS API documentation It provide a init method which generate the TLS key pair if not exisiting,
a method to check if keys are generated, a method to check if public key is transfered to backend, methods to retrieve public and private key, methods to priont out a key, a method to set the indicator that public key is transfered and a methos to delete all key related files. This last function is only for development purposes.
Definition at line 66 of file keygen.h.
Public Member Functions
~KeyGen ()
TLS key generation class destructor.
void init ()
The init function.
bool bIsKeyTransfered ()
Function to check if public key is still done.
void setKeyTransfered ()
Function to mark that public key is still done.
void resetKeyTransfered ()
Function to reset flag transfer_done.
uint16_t getPublicKey (unsigned char *pBuf, size_t len)
Function to retrieve the public key from file system.
std::string getPrivateKey ()
Function to retrieve the private key from file system.
void deleteKeyFiles ()
Function to delete all key related files.
void printKey (std::string key)
Function to print a key to terminal.
Static Public Member Functions
static KeyGen * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
KeyGen ()
TLS key generation class constructor.
void printKey (unsigned char *pBuf, size_t len)
Function to print a key to terminal.
Private Attributes
bool keygen_done
Flag indicating that key generation has been done.
bool transfer_done
Flag indicating that key transfer has been done.
Constructor & Destructor Documentation
~KeyGen()
~KeyGen ()
TLS key generation class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 206 of file keygen.cpp.
KeyGen()
KeyGen () private
TLS key generation class constructor.
The constructor simply triggers a debug message on info debug level.
Definition at line 194 of file keygen.cpp.
References keygen_done, and transfer_done.
Member Function Documentation
init()
void init ()
The init function.
The function checks if both TLS key files still exist. If yes the member variable keygen_done will be set to true. Aftwards the function checks if the "key tranferred" file exist and in this case it set member variable transfer_done. If key generation is still done, indicated by flag keygen_done the function returns immediately.
If key generation is not done, the key generation will be initialized by call of the function mbedtls_ctr_drbg_init provided by mbedtls crypto library, which initializes the CTR_DRBG context and prepare it for seed generation. Afterwards the entropy controller device structure will be retrieved from device tree by calling macro DEVICE_DT_GET and the function checks if the device is ready for usage with call of function device_is_ready. If device is not ready a debug message at error level will be printed, otherwise seed will be generated by call of function mbedtls_ctr_drbg_seed, which also set up the CTR_DRBG entropy source for future reseeds.
With call of the functions mbedtls_pk_init and mbedtls_pk_setup provided by the mbedtls crypto library the mbedTLS structure of type mbedtls_pk_context will be initialized. Calling function mbedtls_ecp_gen_key generates the TLS keypair. Calling function mbedtls_pk_write_key_pem extract the private key into a string, which will than be stored into file system. Calling function mbedtls_pk_write_key_pem extract the public key into a string, which will than also be stored into file system. Finally the called functions mbedtls_pk_free and mbedtls_ctr_drbg_free release the components of the context variables.
Definition at line 92 of file keygen.cpp.
References entropy_func2(), FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_write(), FlashFS::inst(), KEY_TRANSFERED_FILENAME, keygen_done, PRIVATE_KEY_FILENAME, PUBLIC_KEY_FILENAME, and transfer_done.
Referenced by main().
inst()
KeyGen * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 183 of file keygen.cpp.
Referenced by DataManager::configure(), HttpConnector::configure(), MqttConnector::HandleFactoryDefault(), main(), and MqttConnector::task().
bIsKeyTransfered()
bool bIsKeyTransfered ()
Function to check if public key is still done.
Returns
Return true if key transfer is done, false otherwise
Function to check if the public key is still transfered to backend.
Definition at line 217 of file keygen.cpp.
References transfer_done.
setKeyTransfered()
void setKeyTransfered ()
Function to mark that public key is still done.
The function write the file KEY_TRANSFERED_FILENAME in file system as persistent indicator that the public key is still transfered to backend. Additionally the non persistent flag transfer_done is set to true.
Definition at line 237 of file keygen.cpp.
References FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_write(), FlashFS::inst(), KEY_TRANSFERED_FILENAME, and transfer_done.
Referenced by MqttConnector::task().
resetKeyTransfered()
void resetKeyTransfered ()
Function to reset flag transfer_done.
Function set flag transfer_done to false
Definition at line 226 of file keygen.cpp.
References transfer_done.
getPublicKey()
uint16_t getPublicKey (unsigned char * pBuf, size_t len)
Function to retrieve the public key from file system.
Parameters
pBuf Pointer to the buffer for the public key
len Desired length of the pubilc key
Returns
Return the real (read) len of the public key
The function read the public key from file PUBLIC_KEY_FILENAME in file system and store it in buffer pBuf. Length of the key will be returned.
Definition at line 261 of file keygen.cpp.
References FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_read(), FlashFS::inst(), and PUBLIC_KEY_FILENAME.
Referenced by DataManager::configure(), and MqttConnector::task().
getPrivateKey()
std::string getPrivateKey ()
Function to retrieve the private key from file system.
Returns
Return a std::string containing the private key
The function read the private key from file PRIVATE_KEY_FILENAME in file system and store it in a std::string, which finally will be returned.
Definition at line 283 of file keygen.cpp.
References FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_read(), FlashFS::inst(), PRIVATE_KEY_FILENAME, and READ_BUF_LEN.
Referenced by HttpConnector::configure().
deleteKeyFiles()
void deleteKeyFiles ()
Function to delete all key related files.
The function checks if file PRIVATE_KEY_FILENAME exist and in this case the file will be deleted by call of function remove provided by class FlashFS.
The function checks if file PUBLIC_KEY_FILENAME exist and in this case the file will be deleted by call of function remove provided by class FlashFS.
The function checks if file KEY_TRANSFERED_FILENAME exist and in this case the file will be deleted by call of function remove provided by class FlashFS.
Definition at line 350 of file keygen.cpp.
References FlashFS::inst(), KEY_TRANSFERED_FILENAME, PRIVATE_KEY_FILENAME, PUBLIC_KEY_FILENAME, and FlashFS::remove().
Referenced by MqttConnector::HandleFactoryDefault().
printKey() [1/2]
void printKey (std::string key)
Function to print a key to terminal.
Parameters
key sts::string with the key
In a loop over the length of the key each character will be printed.
Definition at line 330 of file keygen.cpp.
printKey() [2/2]
void printKey (unsigned char * pBuf, size_t len) private
Function to print a key to terminal.
Parameters
pBuf Pointer to the buffer with the key
len The length of the key
In a loop over the length of the key each character will be printed.
Definition at line 313 of file keygen.cpp.
Field Documentation
keygen_done
bool keygen_done private
Flag indicating that key generation has been done.
Definition at line 85 of file keygen.h.
Referenced by init(), and KeyGen().
transfer_done
bool transfer_done private
Flag indicating that key transfer has been done.
Definition at line 86 of file keygen.h.
Referenced by bIsKeyTransfered(), init(), KeyGen(), resetKeyTransfered(), and setKeyTransfered().
The documentation for this class was generated from the following files:
util/keygen.h
util/keygen.cpp