AXO X1: HwMetrics Class Reference
HwMetrics Class Reference
HwMetrics class derived from task base class.
#include <hw_metrics.h>
Detailed Description
HwMetrics class derived from task base class.
Detailed Description
The HwMetrics class is responsible to collect status informations from HW modules and to provide them to data manager. It provides a report method to send HW metrics data to data manager task and a method to translate incomming status information from Adxl37x task into HW metrics structure. Message Interaction:
Receive
Power manager task
Adxl37x task
Transmit
Data manager task
Adxl37x task
Definition at line 73 of file hw_metrics.h.
Public Member Functions
HwMetrics (const char *name="??")
HW metrics task constructor.
virtual ~HwMetrics ()
HW metrics task destructor.
virtual void task (void)
Adxl37x task function.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Data Fields
Mbox * pInMbox
Mailbox of the HW metrics task.
struct hw_metrics metrics
Structure containing the HW Metrics.
Private Member Functions
void HandleHwStatusAdxl37x (PoolElem *pElem)
Handler function for incoming message eHwStatusAdxl37x.
void report ()
Function to send a HW metrics message to data manager task.
Additional Inherited Members
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
HwMetrics()
HwMetrics (const char * name = "??") explicit
HW metrics task constructor.
Parameters
name The name of the class
The constructor allocate and register the tasks mailbox.
Definition at line 84 of file hw_metrics.cpp.
References Mbox::eHwMetrics, pInMbox, and Mbox::registerMbox().
~HwMetrics()
~HwMetrics () virtual
HW metrics task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 98 of file hw_metrics.cpp.
Member Function Documentation
task()
void task (void) virtual
Adxl37x task function.
The task function directly enter the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eHwReport: Request a HW status report. The message will be forwarded to Adxl37x task. Pointer to the pool element will be set to 0 to prevent the releasing of the message back to the pool.
eHwStatusAdxl37x: Status indication from Adxl37x task. Error counter will be reset to 0, message payload will be translated in HW metrics structure by calling function HandleHwStatusAdxl37x and this structure will be send to data manager task by call of funtion report.
Implements Task.
Definition at line 120 of file hw_metrics.cpp.
References Mbox::eAdxl37xTask, eHwReport, eHwStatusAdxl37x, PoolElem::free(), HandleHwStatusAdxl37x(), metrics, PoolElem::mtype, Task::myName, hw_metrics::num_errors, pInMbox, Mbox::read(), report(), Mbox::send(), and UNIT_TEST_STOP_LOOP.
HandleHwStatusAdxl37x()
void HandleHwStatusAdxl37x (PoolElem * pElem) private
Handler function for incoming message eHwStatusAdxl37x.
Parameters
pElem Pointer incoming to the message
Message payload will be extracted and translated in HW metrics structure. In case of an error the error counter within the structure will be incremented by 1,in case of self test ot no error the error counter remains as is.
Definition at line 64 of file hw_metrics.cpp.
References eHwFailure, PoolElem::getBuffer(), hw_metrics::hw_status, metrics, and hw_metrics::num_errors.
Referenced by task().
report()
void report () private
Function to send a HW metrics message to data manager task.
The function request a pointer to the mailbox of data manager task and a message from message pool, set message type to eHwStatusAdxl37x, set Adxl37x task as sender, copy the HW metrics structure into payload of the message and send it to data manager's mailbox.
Definition at line 44 of file hw_metrics.cpp.
References eHwMetrics, metrics, and Mbox::sendMsg().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the HW metrics task.
Definition at line 78 of file hw_metrics.h.
Referenced by HwMetrics(), and task().
metrics
struct hw_metrics metrics
Structure containing the HW Metrics.
Definition at line 78 of file hw_metrics.h.
Referenced by HandleHwStatusAdxl37x(), report(), and task().
The documentation for this class was generated from the following files:
data/hw_metrics.h
data/hw_metrics.cpp