AXO X1: Timer Class Reference
Timer Class Reference
RTOS wrapper for software timer support.
#include <timer.h>
Detailed Description
RTOS wrapper for software timer support.
Detailed Description
The timer class implements a C++ wrapper of the timer API provided by the Zephyr operating system. See details in Zephyr
timer documentation or in API documentation. The timer class provides methods to start and stop timers.
Definition at line 36 of file timer.h.
Public Member Functions
Timer (k_timer_expiry_t cb, void *pUser, uint32_t duration, uint32_t period=0)
Timer class constructor.
Timer ()=delete
virtual ~Timer ()
Destructor.
void start ()
Timer start function.
void start (uint32_t duration, uint32_t period)
Timer start function.
void stop ()
Timer stop function.
void restart ()
Timer restart function.
void reconfigure (uint32_t duration, uint32_t period)
Timer reconfigure function.
Protected Attributes
struct k_timer timer_handle
Timer administration structure.
uint32_t duration
Timer duration in seconds.
uint32_t period
Timer period for cyclic timer in seconds.
Constructor & Destructor Documentation
Timer() [1/2]
Timer (k_timer_expiry_t cb, void * pUser, uint32_t duration, uint32_t period = 0)
Timer class constructor.
Parameters
cb The expiry callback function of type k_timer_expiry_t
pUser Pointer to the owner of the timer (normally this pointer of task)
duration Timer duration in seconds
period Timer period in seconds for cyclic timer, default is 0 (not a cyclic timer)
The constructor initializes a timer, prior to its first use by calling function k_timer_init provided by the operating system, which assign the expiry callback function and returns the timer administration structure timer_handle. It set the owner of the timer by calling function k_timer_user_data_set also provided by the operating system and initializes the protected varaibles duration and period.
Definition at line 51 of file timer.cpp.
References duration, period, and timer_handle.
Timer() [2/2]
Timer () delete
~Timer()
virtual ~Timer () inline virtual
Destructor.
Definition at line 41 of file timer.h.
Member Function Documentation
start() [1/2]
void start (void)
Timer start function.
The function starts a timer by calling function k_timer_start provided by the operating system, with the protected varaibles duration and period assigned by the constructor.
Definition at line 69 of file timer.cpp.
References duration, period, and timer_handle.
Referenced by MqttConnector::connect(), HttpConnector::HandleAdxlIdleInd(), HttpConnector::HttpConnector(), PowerMgrX1::message_handler(), restart(), FwUpdCtrl::startRebootTimer(), FwUpdCtrl::startRetryTimer(), FwUpdCtrl::startTimeout(), RmsTask::task(), BoostConverter::task(), Adxl37x::task(), MqttConnector::task(), ResetCtrl::task(), LteMonitor::task(), LteConnector::task(), and PowerMgrX1::taskInit().
start() [2/2]
void start (uint32_t duration, uint32_t period)
Timer start function.
Parameters
duration Timer duration
period Timer period for cyclic timer
The function starts a timer by calling function k_timer_start provided by the operating system. Duration and period will be overloaded by the parameter of the function and stored the protected varaibles duration and period.
Definition at line 86 of file timer.cpp.
References duration, period, and timer_handle.
stop()
void stop (void)
Timer stop function.
The function stops a timer by calling function k_timer_stop provided by the operating system.
Definition at line 101 of file timer.cpp.
References timer_handle.
Referenced by restart(), RmsTask::task(), BoostConverter::task(), Adxl37x::task(), and MqttConnector::task().
restart()
void restart (void)
Timer restart function.
The function restarts a timer by calling the member functions stop and start.
Definition at line 111 of file timer.cpp.
References start(), and stop().
reconfigure()
void reconfigure (uint32_t duration, uint32_t period)
Timer reconfigure function.
Parameters
duration New timer duration
period New timer period for cyclic timer
The function reconfigure the values for duration and period with the given parameter values.
Definition at line 126 of file timer.cpp.
References duration, and period.
Referenced by PowerMgr::configure().
Field Documentation
timer_handle
struct k_timer timer_handle protected
Timer administration structure.
Definition at line 46 of file timer.h.
Referenced by start(), stop(), and Timer().
duration
uint32_t duration protected
Timer duration in seconds.
Definition at line 50 of file timer.h.
Referenced by reconfigure(), start(), and Timer().
period
uint32_t period protected
Timer period for cyclic timer in seconds.
Definition at line 51 of file timer.h.
Referenced by reconfigure(), start(), and Timer().
The documentation for this class was generated from the following files:
rtos/timer.h
rtos/timer.cpp