AXO X1: ResetReason Class Reference
ResetReason Class Reference
Reset Reason class implemented according to C++ singleton design pattern.
#include <reset_reason.h>
Detailed Description
Reset Reason class implemented according to C++ singleton design pattern.
Detailed Description
The class provides methods to handle the reset reason, which is determined at startup by reading register RESETREAS. Register value and reset reason string are stored outside of this class in context of the caller of getter function.
Definition at line 47 of file reset_reason.h.
Public Member Functions
~ResetReason ()
Reset Reason destructor.
void get (unsigned int *mask, std::string *reason_str)
Getter function to retrieve the reset reason.
Static Public Member Functions
static ResetReason * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
ResetReason ()
Reset Reason constructor.
Constructor & Destructor Documentation
~ResetReason()
~ResetReason ()
Reset Reason destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 68 of file reset_reason.cpp.
ResetReason()
ResetReason () private
Reset Reason constructor.
The constructor is declared as private according to singleton pattern. It is called in the static inst function to create the exclusiv only instance of the class. The constructor simply triggers a debug message on info debug level.
Definition at line 58 of file reset_reason.cpp.
Member Function Documentation
inst()
ResetReason * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 44 of file reset_reason.cpp.
Referenced by PowerMgr::task().
get()
void get (unsigned int * mask, std::string * reason_str)
Getter function to retrieve the reset reason.
Parameters
mask Pointer to unsigned int variable to store content of register RESETREAS
reason_str Reset reason as string representation
Function retrieve the reset reason from register RESETREAS by calling function nrfx_reset_reason_get and store the value in variable reason and assign it to pointer mask. It count the number of reasons by calling function popcount and clear register RESETREAS by calling function nrfx_reset_reason_clear. According to the content of variable reason a string variable will be filled, in case of more than one reset reasons string will be expanded. Finally string will be assigned to pointer reason_str. Both parameter will be passed to caller of this function.
Definition at line 88 of file reset_reason.cpp.
References popcount32().
Referenced by PowerMgr::task().
The documentation for this class was generated from the following files:
pm/reset_reason.h
pm/reset_reason.cpp