AXO X1: BootCnt Class Reference
BootCnt Class Reference
Boot count class implemented according to C++ singleton design pattern.
#include <boot_cnt.h>
Detailed Description
Boot count class implemented according to C++ singleton design pattern.
Detailed Description
The class provides methods to handle the boot counter which is stored persitently in flash file system. Boot count is read at startup and is stored in private variable boot_count.
Definition at line 39 of file boot_cnt.h.
Public Member Functions
~BootCnt ()
Boot Count destructor.
int32_t get ()
Getter function to retrieve the boot count.
Static Public Member Functions
static BootCnt * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
BootCnt (const char *fname="/lfs/boot_count")
Boot Count constructor.
Private Attributes
int32_t boot_count
the boot count
Constructor & Destructor Documentation
~BootCnt()
~BootCnt ()
Boot Count destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 90 of file boot_cnt.cpp.
BootCnt()
BootCnt (const char * fname = "/lfs/boot_count") explicit private
Boot Count constructor.
Parameters
fname Filename of the boot counter file
The constructor is declared as private according to singleton pattern. It is called in the static inst function to create the exclusiv only instance of the class. fname "/lfs/boot_count" is defined as default parameter in declaration of the constructor. The constructor open the file and the boot count will than be read from file. In case boot count is negative it will be set to 0. Afterwards boot count will be incremented by 1 and stored in file.
Definition at line 62 of file boot_cnt.cpp.
References boot_count, FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_read(), FlashFS::file_seek(), FlashFS::file_sync(), FlashFS::file_write(), and FlashFS::inst().
Member Function Documentation
inst()
BootCnt * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 43 of file boot_cnt.cpp.
Referenced by PowerMgr::PowerMgr().
get()
int32_t get ()
Getter function to retrieve the boot count.
Function returns the private variable boot_count.
Definition at line 97 of file boot_cnt.cpp.
References boot_count.
Referenced by PowerMgr::PowerMgr().
Field Documentation
boot_count
int32_t boot_count private
the boot count
Definition at line 48 of file boot_cnt.h.
Referenced by BootCnt(), and get().
The documentation for this class was generated from the following files:
pm/boot_cnt.h
pm/boot_cnt.cpp