AXO X1: MuxController Class Reference
MuxController Class Reference
MUX Controller driver class.
#include <mux_controller.h>
Detailed Description
MUX Controller driver class.
Detailed Description
The MUX Controller driver class handle the selection of the connected analog inputs and connect the selcted channel to the drain pin, which acts as output and is connected to the analog input pin 14 / AIN1 of the NRF9160. The class provides methods to select the analog input channel, to enable or disable the analog input, to print the status and to retrieve the nuimber of attached analog input signals.
Definition at line 48 of file mux_controller.h.
Public Member Functions
MuxController (const struct gpio_dt_spec *mux_gpios, size_t num_mux, const struct gpio_dt_spec *enable_gpio=nullptr)
The MUX Controller constructor.
int init ()
The MUX Controller init function.
int selectChannel (uint8_t ch)
Function to select a single ADC channel.
void enableLoad (bool enable)
Function to enable or disable the muxer.
void printStatus (const struct shell *shell) const
Function to print the muxer status.
size_t numMuxPins () const
Private Attributes
const struct gpio_dt_spec * mux_gpios_
size_t num_mux_
The number of mux select lines.
const struct gpio_dt_spec * enable_gpio_
uint8_t current_channel_ = 0
The current active channel.
bool load_enabled_ = false
load enabled flag
Constructor & Destructor Documentation
MuxController()
MuxController (const struct gpio_dt_spec * mux_gpios, size_t num_mux, const struct gpio_dt_spec * enable_gpio = nullptr)
The MUX Controller constructor.
Parameters
mux_gpios Array with gpio information for muxer select lines
num_mux The number of muxer select lines
enable_gpio Structure with gpio information for muxer enable pin
The function initializes the GPIO pins of the muxer select lines with array mux_gpios of type struct gpio_dt_spec, the number of muxer select lines with parameter num_mux and mux enable pin with structure enable_gpio of type struct gpio_dt_spec.
Definition at line 45 of file mux_controller.cpp.
Member Function Documentation
init()
int init ()
The MUX Controller init function.
Returns
Returns 0 in case of success, error code ENODEV otherwise
The function enters a loop over the array of muxer select lines and checks if the GPIO at index i is ready for usage with call of function device_is_ready. If a GPIO is not ready, the function returns immediately with error code ENODEV. Afterwards it checks if the muxer is enabled and the enable GPIO is not ready for usage. In this case the function returns with error code ENODEV, otherwise enable GPIO is set to inactive and functions returns 0.
Definition at line 63 of file mux_controller.cpp.
References enable_gpio_, mux_gpios_, and num_mux_.
Referenced by ADConverter::task().
selectChannel()
int selectChannel (uint8_t ch)
Function to select a single ADC channel.
Parameters
ch The ADC channel to select
Returns
Returns 0 in case of success, error code EINVAL otherwise
The function checks validity of the parameter ch. In case it is not in valid, the function returns immediately with error code EINVAL. Otherwise ADC channel is selected by call of function gpio_pin_set_dt and member variable current_channel_ is set to parameter ch.
Definition at line 98 of file mux_controller.cpp.
References current_channel_, mux_gpios_, and num_mux_.
Referenced by cmd_mux_select(), cmd_mux_sweep(), and ADConverter::sample().
enableLoad()
void enableLoad (bool enable)
Function to enable or disable the muxer.
Parameters
enable enable flag
The function checks if the GPIO pin specification of type struct gpio_dt_spec of the is initialized and in this case it set the desired GPIO according to parameter enable by calling function gpio_pin_set_dt provided by the zephyr library and set the provate member flag load_enabled_ to the value of parameter enable.
Definition at line 124 of file mux_controller.cpp.
References enable_gpio_, and load_enabled_.
Referenced by cmd_mux_enable(), and cmd_mux_sweep().
printStatus()
void printStatus (const struct shell * shell) const
Function to print the muxer status.
Parameters
shell the used shell
The function prints the muxer status by calling function shell_print.
Definition at line 139 of file mux_controller.cpp.
References current_channel_, and load_enabled_.
Referenced by cmd_mux_status().
numMuxPins()
size_t numMuxPins () const inline
Definition at line 57 of file mux_controller.h.
References num_mux_.
Referenced by cmd_mux_sweep().
Field Documentation
mux_gpios_
const struct gpio_dt_spec* mux_gpios_ private
The GPIO pin specification of type struct gpio_dt_spec of the muxer select lines
Definition at line 62 of file mux_controller.h.
Referenced by init(), and selectChannel().
num_mux_
size_t num_mux_ private
The number of mux select lines.
Definition at line 64 of file mux_controller.h.
Referenced by init(), numMuxPins(), and selectChannel().
enable_gpio_
const struct gpio_dt_spec* enable_gpio_ private
The GPIO pin specification of type struct gpio_dt_spec of the mux enable pin
Definition at line 67 of file mux_controller.h.
Referenced by enableLoad(), and init().
current_channel_
uint8_t current_channel_ = 0 private
The current active channel.
Definition at line 69 of file mux_controller.h.
Referenced by printStatus(), and selectChannel().
load_enabled_
bool load_enabled_ = false private
load enabled flag
Definition at line 71 of file mux_controller.h.
Referenced by enableLoad(), and printStatus().
The documentation for this class was generated from the following files:
drv/adc/mux_controller.h
drv/adc/mux_controller.cpp