AXO X1: MqttConnector Class Reference
MqttConnector Class Reference
MQTT connector class derived from task base class.
#include <mqtt_connector.h>
Detailed Description
MQTT connector class derived from task base class.
Detailed Description
MQTT connector task handle the connection to the MQTT broker. It receives messages from the broker via static callback member functions, which needs to be registered in MQTT helper layer provided by the nRF IoT library.
See details of nRF library
See details of MQTT Client library API The MqttConnector class provides five handler functions to receive MQTT broker events, methods to request connection, disconnection and subsciption, to abort connection to broker and to publish topics to the broker. Furthermore it provides a method to read the hardware device ID (modem's IMEI). Message Interaction:
Receive
External PDN and LTE Link events
Timer interrupt callback
MQTT connector task (self)
Firmware update task
Firmware update control task
LTE connector task
Data manager task
Transmit
MQTT connector task (self)
Firmware update control task
MQTT connector task
Definition at line 207 of file mqtt_connector.h.
Public Member Functions
MqttConnector (const char *name="??")
MqttConnector task constructor.
MqttConnector ()=delete
virtual ~MqttConnector ()
MqttConnector task destructor.
virtual void configure ()
MqttConnector virtual task configure function.
void task (void)
MQTT connector task function.
void timer1_expired ()
Timer expired function for the reconnect timer.
void connect ()
Function to send a connect request to the MQTT broker.
void disconnect ()
Function to send a disconnect request to the MQTT broker.
void abort ()
Function to send a abort request to the MQTT broker.
void publish (struct payload *payload, struct topic *topic)
The publish method of MQTT connector class.
void getDeviceId ()
Getter function to retrieve the device ID (the modem's IMEI)
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the reconnect timer.
static void on_connack (enum mqtt_conn_return_code return_code)
Callback handlers from MQTT helper library for connack from broker.
static void on_disconnect (int result)
Callback handlers from MQTT helper library for disconnect indication from broker.
static void on_publish (struct mqtt_helper_buf topic, struct mqtt_helper_buf payload)
Callback handlers from MQTT helper library for a subscribed topic from broker.
static void on_suback (uint16_t message_id, int result)
Callback handlers from MQTT helper library for suback from broker.
static void on_puback (uint16_t message_id, int result)
Callback handlers from MQTT helper library for puback from broker.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the LTE connector.
Timer * myTimer
Cyclic reconnect timer.
Private Member Functions
void PublishData (const char *pTopic, unsigned char *pPayload)
Function to publish data to the MQTT broker.
void PublishResponse (const char *pTopic, unsigned char *pPayload, const char *pRespType)
Function to publish a response to the MQTT broker.
void PublishAcceptedResponse (const char *pTopic, unsigned char *pPayload)
Function to publish a accepted response to the MQTT broker.
void PublishAcceptedResponse (PoolElem *pElem, const char *pTopic)
Function to publish a accepted response to the MQTT broker.
void PublishRejectedResponse (const char *pTopic, unsigned char *pPayload)
Function to publish a rejected response to the MQTT broker.
void PublishRejectedResponse (PoolElem *pElem, const char *pTopic)
Function to publish a rejected response to the MQTT broker.
void PublishDlResult (PoolElem *pElem, const char *pTopic)
Function to publish a download finished indication to the MQTT broker.
void HandleNewConfiguration (PoolElem *pElem)
Handler function for new incoming JSON configuration.
void HandleFactoryDefault (PoolElem *pElem)
Handler function for handling of a factory default request.
void HandleColdStartReq (PoolElem *pElem)
Handler function for handling of cold start request.
void HandleBoostOnReq (PoolElem *pElem)
Handler function for handling of boost converter on request.
void HandleBoostOffReq (PoolElem *pElem)
Handler function for handling of boost converter off request.
void HandleFsErase (PoolElem *pElem)
Handler function for handling of file system erase request.
void HandleFsStatus ()
Handler function for handling of file system status request.
void HandleDisableADXL (PoolElem *pElem)
Handler function for handling disable ADXL request.
void HandleEnableADXL (PoolElem *pElem)
Handler function for handling enable ADXL request.
void HandleGetConfig ()
Handler function for handling get configuration request.
Static Private Member Functions
static void subscribe (const uint8_t *topic)
Function to send a subscribe request to the MQTT broker.
static void cmd_subscribe ()
Function to send a subscribe request for the command topic to the MQTT broker.
static void ota_subscribe ()
Function to send a subscribe request for the OTA topic to the MQTT broker.
static void config_subscribe ()
Function to send a subscribe request for the config topic to the
MQTT broker.
Private Attributes
bool connected
bool lte_connected
int32_t last_msg_id
ID of the last message published to MQTT broker.
uint8_t numConnectRetries
Number of MQTT connect retries.
uint32_t metricsInterval
Metrics interval from config class.
Static Private Attributes
static char device_id [DEV_ID_LEN]
static char host_name [MAX_MQTT_HOSTNAME_LEN] = DEFAULT_MQTT_HOSTNAME
The MQTT host name.
static char measurement_topic [MEP_MEASUREMENT_TOPIC_LEN]
static char metrics_topic [MEP_METRICS_TOPIC_LEN]
static char pubkey_topic [MEP_PUBKEY_TOPIC_LEN]
static char command_topic [MEP_COMMAND_TOPIC_LEN]
static char ota_topic [MEP_OTA_TOPIC_LEN]
static char event_topic [MEP_EVENT_TOPIC_LEN]
static char config_topic [MEP_CONFIG_TOPIC_LEN]
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
MqttConnector() [1/2]
MqttConnector (const char * name = "??") explicit
MqttConnector task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocates and initialize the cyclic reconnect timer with duration of 60 ms and period of 300 ms. It read the IMEI of the modem by calling member function getDeviceId and complete the topic strings with the IMEI.
Definition at line 535 of file mqtt_connector.cpp.
References command_topic, config_topic, CONNECT_RETRY_DURATION, device_id, Mbox::eMqttConnector, event_topic, getDeviceId(), measurement_topic, MEP_COMMAND_TOPIC, MEP_CONFIG_TOPIC, MEP_EVENT_TOPIC, MEP_MEASUREMENT_TOPIC, MEP_METRICS_TOPIC, MEP_OTA_TOPIC, MEP_PUBKEY_TOPIC, metrics_topic, myTimer, numConnectRetries, ota_topic, pInMbox, pubkey_topic, Mbox::registerMbox(), and timer_cb().
MqttConnector() [2/2]
MqttConnector () delete
~MqttConnector()
~MqttConnector () virtual
MqttConnector task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 590 of file mqtt_connector.cpp.
Member Function Documentation
configure()
void configure () virtual
MqttConnector virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to metrics by call of the function getCfgMetrics provided by the Config class, convert the timeout intervall in seconds and initialize member variabel metricsInterval with this value.
Reimplemented from Task.
Definition at line 603 of file mqtt_connector.cpp.
References Config::getCfgMetrics(), Config::inst(), _stCfgMetrics::interval, and metricsInterval.
Referenced by main().
task()
void task (void) virtual
MQTT connector task function.
Initially the function register the callback functions for MQTT broker events by assigning them in structure cfg of type mqtt_helper_cfg and calling the function mqtt_helper_init provided by the nRF IoT library.
Afterwards the function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On timer expiry the function checks if a LTE connection is established and MQTT connection was lost. In this case the member function connect will be called to send a new connect request to the MQTT broker. Afterwards the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static.
eCmdAccept: If MQTT broker is connected, a accepted response will be send to the MQTT broker by call of the private member function PublishAcceptedResponse.
eCmdReject: If MQTT broker is connected, a rejected response will be send to the MQTT broker by call of the private member function PublishRejectedResponse.
eOtaStart: If MQTT broker is connected, a accepted response will be send to the MQTT broker by call of the private member function PublishAcceptedResponse. Finally a subscribe request will be send to MQTT broker by calling the member function ota_subscribe.
eFwAccept: If MQTT broker is connected, a accepted response will be send to the MQTT broker by call of the private member function PublishAcceptedResponse.
eFwReject: If MQTT broker is connected, a rejected response will be send to the MQTT broker by call of the private member function PublishRejectedResponse.
eFwDlSuccess: If MQTT broker is connected, a accepted response will be send to the MQTT broker by call of the private member function PublishDlResult.
eFwDlFailed: If MQTT broker is connected, a rejected response will be send to the MQTT broker by call of the private member function PublishDlResult.
eMqttConnected: Message will be forwarded to power manager task, the pointer pElem will be set to 0, to prevent releasing the message. The flag connected will be set to true and the reconnect timer will be stopped by calling stop function of the timer class. Afterwards the function checks if public TLS key is already send to backend. In this case a debug message at warning level will be printed, otherwise the key transfer to backend will be iniatialized y sending message eKeyTransferReq to its own (MQTT connectors) mailbox.
eMqttDisconnected: The flag connected will be set to false, to prevent inconsistent library states the member function abort will be called and in cast LTE is connected the reconnect timer will be started by calling start function of the timer class.
eLteSleepEnter: Will be ignored, only debug message at info level will be printed.
eLteSleepExit: Will be ignored, only debug message at info level will be printed.
eKeyTransferReq: If MQTT broker is connected, the public key will be retrieved by call of function getPublicKey provided by class KeyGen and the key will be send to MQTT broken in pubkey topic by calling private member function PublishData. Finally by key transfered indicator will be set by call of function setKeyTransfered, also provided by class KeyGen
eMetrics: If MQTT broker is connected, the message payload will be copied to topic payload structure and send to MQTT broker in metrics topic by call of private member function PublishData
eMeasurements: If MQTT broker is connected, the message payload will be copied to topic payload structure and send to MQTT broker in measurement topic by call of private member function PublishData
eLteConnected: If LTE is not connected, the flag lte_connected will be set to true and if MQTT broker is not connected, the member function connect will be called to send a new connect request to the MQTT broker.
eLteDisconnected: The flag lte_connected will be set to false, the reconnect timer will be stopped by calling stop function of the timer class and the member function disconnect will be called to send a disconnect request to the MQTT broker.
eJsonConfig: Call of member function HandleNewConfiguration.
eFactoryDefault: Call of member function HandleFactoryDefault.
eColdStartReq: Call of member function HandleColdStartReq.
eBoostOnReq: Call of member function HandleBoostOnReq.
eBoostOffReq: Call of member function HandleBoostOffReq.
eFsErase: Call of member function HandleFsErase
eFsStatus: Call of member function HandleFsStatus
eDisableADXL: Call of member function HandleDisableADXL
eEnableADXL: Call of member function HandleEnableADXL
eGetConfig: Call of member function HandleGetConfig
Implements Task.
Definition at line 1368 of file mqtt_connector.cpp.
References abort(), certmgr::ClearBrokerSwitchRequested(), command_topic, connect(), connected, disconnect(), eBoostOffReq, eBoostOnReq, eCertJovia1, eCertJovia2, eCertJoviaKey, eCertThingsboard1, eCertThingsboard2, eCertThingsboardKey, eCmdAccept, eCmdReject, eColdStartReq, eConnectJovia, eConnectThingsboard, eDisableADXL, eEnableADXL, eFactoryDefault, eFsErase, eFsStatus, eFwAccept, eFwDlFailed, eFwDlSuccess, eFwReject, eGetConfig, eJsonConfig, eKeyTransferReq, eLteConnected, eLteDisconnected, eLteSleepEnter, eLteSleepExit, eMeasurements, eMetrics, eMqttConnected, eMqttDisconnected, eOtaStart, Mbox::ePowerManager, eTimerExpired, event_topic, PoolElem::free(), PoolElem::getBuffer(), KeyGen::getPublicKey(), HandleBoostOffReq(), HandleBoostOnReq(), HandleColdStartReq(), HandleDisableADXL(), HandleEnableADXL(), HandleFactoryDefault(), HandleFsErase(), HandleFsStatus(), HandleGetConfig(), HandleNewConfiguration(), certmgr::inst(), KeyGen::inst(), lte_connected, measurement_topic, metrics_topic, PoolElem::mtype, Task::myName, myTimer, on_connack(), on_disconnect(), on_puback(), on_publish(), on_suback(), ota_subscribe(), ota_topic, pInMbox, pubkey_topic, PublishAcceptedResponse(), PublishData(), PublishDlResult(), PublishRejectedResponse(), Mbox::read(), Mbox::send(), Mbox::sendMsg(), KeyGen::setKeyTransfered(), Timer::start(), Timer::stop(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the reconnect timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call MQTT connector timer expired function timer1_expired.
Definition at line 621 of file mqtt_connector.cpp.
References timer1_expired().
Referenced by MqttConnector().
timer1_expired()
void timer1_expired ()
Timer expired function for the reconnect timer.
The function initializes the static pool element e1 with message type eTimerExpired, set LTE connector as sender and put message into own (LTE connector's) mailbox.
Definition at line 636 of file mqtt_connector.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
connect()
void connect ()
Function to send a connect request to the MQTT broker.
The function copy host name and device ID in structure of type mqtt_helper_conn_params provided by nRF IoT library and send this structure with a connect request to the broker by calling function mqtt_helper_connect also provided by nRF IoT library. To prevent inconsistent library states the member function abort will be called in case of an error. Finally the reconnect timer will be started to schedule reconnection attempts.
Definition at line 449 of file mqtt_connector.cpp.
References abort(), CONNECT_RETRY_DURATION, device_id, eBroker_JOVIA, eBroker_THINGSBOARD, certmgr::getCurrentBroker(), host_name, certmgr::inst(), JOVIA_MQTT_HOSTNAME, MAX_NUM_CONNECT_RETRIES, metricsInterval, myTimer, numConnectRetries, ResetCtrl::performSwReset(), Timer::start(), THINGSBOARD_MQTT_HOSTNAME, and certmgr::writeBrokerCfg().
Referenced by task().
disconnect()
void disconnect ()
Function to send a disconnect request to the MQTT broker.
The function send a disconnect request to the broker by calling function mqtt_helper_disconnect provided by nRF IoT library.
Definition at line 506 of file mqtt_connector.cpp.
Referenced by task().
abort()
void abort ()
Function to send a abort request to the MQTT broker.
To abort the MQTT connection the function send a disconnect request to the broker by calling function mqtt_helper_disconnect provided by nRF IoT library.
Definition at line 519 of file mqtt_connector.cpp.
Referenced by connect(), and task().
publish()
void publish (struct payload * payload, struct topic * topic)
The publish method of MQTT connector class.
Parameters
payload The payload of the topic
topic The topic to be published
The function copy topic, payload and status information in a MQTT message of type struct mqtt_publish_param, which is provided by Zephyr MQTT Client library API. Afterwards it publish the topic by calling function mqtt_helper_publish provided by nRF IoT library. In case of an error a debug message at warning level will be printed.
The MQTT helper functions are implemented on top of the Zephyr library API.
Definition at line 336 of file mqtt_connector.cpp.
References last_msg_id, payload::string, and topic::string.
Referenced by HandleNewConfiguration(), PublishData(), and PublishResponse().
getDeviceId()
void getDeviceId ()
Getter function to retrieve the device ID (the modem's IMEI)
The function read the device id (the modem's IMEI) in a buffer by calling function hw_id_get provided by nRF library API and store it in private member variable device_id.
Definition at line 429 of file mqtt_connector.cpp.
References DEV_ID_LEN, and device_id.
Referenced by MqttConnector().
on_connack()
void on_connack (enum mqtt_conn_return_code return_code) static
Callback handlers from MQTT helper library for connack from broker.
Parameters
return_code connection ackknowledge return value of enumeration type mqtt_conn_return_code
The function is called when MQTT connection ackknowledge packet has been received from the broker. In case of an connection error the return_code is unequal to 0 and the function returns immediately. In case connection is established the MQTT connector request a subscription of command topic by calling member function cmd_subscribe and of configuration topic by calling member function config_subscribe. Finally a message type to eMqttConnected will be send to its own (MQTT connector's) mailbox by call of function SendMsg provided by class Mbox.
Definition at line 87 of file mqtt_connector.cpp.
References cmd_subscribe(), config_subscribe(), eMqttConnected, and Mbox::sendMsg().
Referenced by task().
on_disconnect()
void on_disconnect (int result) static
Callback handlers from MQTT helper library for disconnect indication from broker.
The function is called when MQTT disconnect indication packet has been received from the broker. It send a message of type eMqttDisconnected to its own (MQTT connector's) mailbox by call of function SendMsg provided by class Mbox.
Definition at line 112 of file mqtt_connector.cpp.
References eMqttDisconnected, and Mbox::sendMsg().
Referenced by task().
on_publish()
void on_publish (struct mqtt_helper_buf topic, struct mqtt_helper_buf payload) static
Callback handlers from MQTT helper library for a subscribed topic from broker.
Parameters
topic The topic MQTT connector is subscribed
payload The payload of the topic
The function is called when MQTT connection has received a subscribed topic from the broker. Topic and payload will be casted to strings and the command in payload string will be identified with string find method.
In case command is OTA_START from topic /device/{device_id}/command and a firmware update is requested the function request a message from message pool, set message type to eOtaStart, set eMqttConnector as sender and send message to firmware update control task's mailbox.
In case the string fw_version is found in the payload of topic /device/{device_id}/ota/update the function also request a message from message pool, set message type to eFwInfo, set eMqttConnector as sender and send message to firmware update control task's mailbox.
In case command is RESET a reset will be performed by calling function performSwReset provided by class ResetCtrl.
In case command is CFG_FACTORY_DEFAULT a message of type eFactoryDefault will be send to the MQTT Connector mailbox. In case command is COLDSTART a message of type eColdStartReq will be send to the MQTT Connector mailbox. In case command is BOOST_ON a message of type eBoostOnReq will be send to the MQTT Connector mailbox. In case command is BOOST_OFF a message of type eBoostOffReq will be send to the MQTT Connector mailbox. In case command is FS_ERASE a message of type eFsErase will be send to the MQTT Connector mailbox. In case command is FS_STAT a message of type eFsStatus will be send to the MQTT Connector mailbox. In case command is DISABLE_ADXL a message of type eDisableADXL will be send to the MQTT Connector mailbox. In case command is ENABLE_ADXL a message of type eEnableADXL will be send to the MQTT Connector mailbox. In case command is GET_CONFIG a message of type eGetConfig will be send to the MQTT Connector mailbox. In case command is SEND_PUBLIC_KEY a message of type eKeyTransferReq will be send to the MQTT Connector mailbox.
Definition at line 163 of file mqtt_connector.cpp.
References eBoostOffReq, eBoostOnReq, eCertJovia1, eCertJovia2, eCertJoviaKey, eCertThingsboard1, eCertThingsboard2, eCertThingsboardKey, eColdStartReq, eConnectJovia, eConnectThingsboard, eDisableADXL, eEnableADXL, eFactoryDefault, eFsErase, eFsStatus, eFwInfo, eGetConfig, eJsonConfig, eKeyTransferReq, eOtaStart, ResetCtrl::performSwReset(), and Mbox::sendMsg().
Referenced by task().
on_suback()
void on_suback (uint16_t message_id, int result) static
Callback handlers from MQTT helper library for suback from broker.
Parameters
message_id The message ID of the subscribe packet
result The result code
The function is called when MQTT subscribe ackknowledge packet has been received from the broker. This message will be ignored, only a debug message at info level will be printed in case result signal success, a debug message at error level will be printed in case result signal failure and a debug message at warning level will be printed in case of unknown topic.
Definition at line 312 of file mqtt_connector.cpp.
References SUBSCRIBE_TOPIC_ID.
Referenced by task().
on_puback()
void on_puback (uint16_t message_id, int result) static
Callback handlers from MQTT helper library for puback from broker.
The function is called when MQTT publish ackknowledge packet has been received from the broker. This message will be ignored, only a debug message at info level will be printed.
Definition at line 296 of file mqtt_connector.cpp.
Referenced by task().
subscribe()
void subscribe (const uint8_t * topic) static private
Function to send a subscribe request to the MQTT broker.
Parameters
topic Pointer to the topic (string) to be subscribed
The function copy topic and length in structure of type mqtt_topic, and put these in a structure of type mqtt_subscription_list together with the topic ID. Both structures are provided by Zephyr MQTT Client library API. Afterwards it send the subscribe request with the subscription list to the broker by calling function mqtt_helper_subscribe provided by nRF IoT library.
Definition at line 370 of file mqtt_connector.cpp.
References SUBSCRIBE_TOPIC_ID.
Referenced by cmd_subscribe(), config_subscribe(), and ota_subscribe().
cmd_subscribe()
void cmd_subscribe () static private
Function to send a subscribe request for the command topic to the MQTT broker.
The function call private member function subscribe to subscribe to the command topic.
Definition at line 393 of file mqtt_connector.cpp.
References command_topic, and subscribe().
Referenced by on_connack().
ota_subscribe()
void ota_subscribe () static private
Function to send a subscribe request for the OTA topic to the MQTT broker.
The function call private member function subscribe to subscribe to the over the air update (OTA) topic.
Definition at line 405 of file mqtt_connector.cpp.
References ota_topic, and subscribe().
Referenced by task().
config_subscribe()
void config_subscribe () static private
Function to send a subscribe request for the config topic to the
MQTT broker.
The function call private member function subscribe to subscribe to the configuration topic.
Definition at line 417 of file mqtt_connector.cpp.
References config_topic, and subscribe().
Referenced by on_connack().
PublishData()
void PublishData (const char * pTopic, unsigned char * pPayload) private
Function to publish data to the MQTT broker.
Parameters
pTopic Pointer to the topic to be send
pPayload Pointer to the data to be send
The function copy the data in parameter pPayload to topic payload structure in variable msg, initialize the topic t with the topic of parameter pTopic and publish the topic by call of member function publish.
Definition at line 697 of file mqtt_connector.cpp.
References publish(), payload::string, and topic::string.
Referenced by PublishDlResult(), and task().
PublishResponse()
void PublishResponse (const char * pTopic, unsigned char * pPayload, const char * pRespType) private
Function to publish a response to the MQTT broker.
Parameters
pTopic Pointer to the topic to be send
pPayload Pointer to the data to be send
pRespType Pointer to the response string "/accepted" or "/rejected"
The function copy the data in parameter pPayload to topic payload structure in variable msg, initialize the string target with the topic of parameter pTopic, append the response string "/accepted" or "/rejected" and copy the final string target in topic structure t. Finally it publish the topic by call of member function publish.
Definition at line 722 of file mqtt_connector.cpp.
References publish(), payload::string, and topic::string.
Referenced by PublishAcceptedResponse(), and PublishRejectedResponse().
PublishAcceptedResponse() [1/2]
void PublishAcceptedResponse (const char * pTopic, unsigned char * pPayload) private
Function to publish a accepted response to the MQTT broker.
Parameters
pTopic Pointer to the topic to be send
pPayload Pointer to the data to be send
By call of private member function PublishResponse the function publishs a accepted response to the MQTT broker.
Definition at line 747 of file mqtt_connector.cpp.
References PublishResponse().
Referenced by HandleBoostOffReq(), HandleBoostOnReq(), HandleColdStartReq(), HandleDisableADXL(), HandleEnableADXL(), HandleFactoryDefault(), HandleFsErase(), HandleFsStatus(), HandleGetConfig(), PublishAcceptedResponse(), and task().
PublishAcceptedResponse() [2/2]
void PublishAcceptedResponse (PoolElem * pElem, const char * pTopic) private
Function to publish a accepted response to the MQTT broker.
Parameters
pElem Pointer to the received message
pTopic Pointer to the topic to be send
By call of private member function PublishAcceptedResponse the function publishs a accepted response to the MQTT broker with the data of the received message pElem in the payload.
Definition at line 778 of file mqtt_connector.cpp.
References PoolElem::getBuffer(), and PublishAcceptedResponse().
PublishRejectedResponse() [1/2]
void PublishRejectedResponse (const char * pTopic, unsigned char * pPayload) private
Function to publish a rejected response to the MQTT broker.
Parameters
pTopic Pointer to the topic to be send
pPayload Pointer to the data to be send
By call of private member function PublishResponse the function publishs a rejected response to the MQTT broker.
Definition at line 762 of file mqtt_connector.cpp.
References PublishResponse().
Referenced by PublishRejectedResponse(), and task().
PublishRejectedResponse() [2/2]
void PublishRejectedResponse (PoolElem * pElem, const char * pTopic) private
Function to publish a rejected response to the MQTT broker.
Parameters
pElem Pointer to the received message
pTopic Pointer to the topic to be send
By call of private member function PublishRejectedResponse the function publishs a rejected response to the MQTT broker with the data of the received message pElem in the payload.
Definition at line 794 of file mqtt_connector.cpp.
References PoolElem::getBuffer(), and PublishRejectedResponse().
PublishDlResult()
void PublishDlResult (PoolElem * pElem, const char * pTopic) private
Function to publish a download finished indication to the MQTT broker.
Parameters
pElem Pointer to the received message
pTopic Pointer to the topic to be send
By call of private member function PublishData the function publishs a download finished indication to the MQTT broker with the data of the received message pElem in the payload.
Definition at line 810 of file mqtt_connector.cpp.
References PoolElem::getBuffer(), and PublishData().
Referenced by task().
HandleNewConfiguration()
void HandleNewConfiguration (PoolElem * pElem) private
Handler function for new incoming JSON configuration.
Parameters
pElem Pointer to the received message
The function copy the message payload of pElem to topic payload structure, initialize the topic with the config topic and extract the JSON configuration string in variable rx. Afterwards the function checks if the configuration is valid by calling method isValid provided by the Config class. If configuration is valid, the topic will be enhanced with string "/accepted" and published by call of the member function publish. Afterwards configuration will be stored in file system by calling function saveToFile also provided by Config class, before a reset is performed by calling calling function performSwReset provided by class ResetCtrl. If configuration is invalid, the topic will be enhanced with string "/rejected" and published by call of the member function publish.
Definition at line 662 of file mqtt_connector.cpp.
References Config::Autocorrection(), config_topic, PoolElem::getBuffer(), Config::inst(), ResetCtrl::performSwReset(), publish(), Config::saveToFile(), payload::string, and topic::string.
Referenced by task().
HandleFactoryDefault()
void HandleFactoryDefault (PoolElem * pElem) private
Handler function for handling of a factory default request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it deletes all files from flash file system by calling the functions deleteConfigFile and deleteKeyFiles. Finally performs a reset by calling function performSwReset provided by class ResetCtrl.
Definition at line 828 of file mqtt_connector.cpp.
References command_topic, Config::deleteConfigFile(), KeyGen::deleteKeyFiles(), Config::inst(), KeyGen::inst(), ResetCtrl::performSwReset(), and PublishAcceptedResponse().
Referenced by task().
HandleColdStartReq()
void HandleColdStartReq (PoolElem * pElem) private
Handler function for handling of cold start request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it send a message of type eColdStartReq to the reset control task by calling function sendMsg provided by class Mbox.
Definition at line 850 of file mqtt_connector.cpp.
References command_topic, eColdStartReq, PublishAcceptedResponse(), and Mbox::sendMsg().
Referenced by task().
HandleBoostOnReq()
void HandleBoostOnReq (PoolElem * pElem) private
Handler function for handling of boost converter on request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it send a message of type eBoostOnReq to the boost converter task by calling function sendMsg provided by class Mbox.
Definition at line 870 of file mqtt_connector.cpp.
References command_topic, eBoostOnReq, PublishAcceptedResponse(), and Mbox::sendMsg().
Referenced by task().
HandleBoostOffReq()
void HandleBoostOffReq (PoolElem * pElem) private
Handler function for handling of boost converter off request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it send a message of type eBoostOffReq to the boost converter task by calling function sendMsg provided by class Mbox.
Definition at line 890 of file mqtt_connector.cpp.
References command_topic, eBoostOffReq, PublishAcceptedResponse(), and Mbox::sendMsg().
Referenced by task().
HandleFsErase()
void HandleFsErase (PoolElem * pElem) private
Handler function for handling of file system erase request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it unmount the files system and delete the complete content by calling the functions unmount and eraseFs provided by class FlashFS. Finally it performs a reset by calling function performSwReset provided by class ResetCtrl.
Definition at line 912 of file mqtt_connector.cpp.
References command_topic, FlashFS::eraseFs(), FlashFS::inst(), ResetCtrl::performSwReset(), PublishAcceptedResponse(), and FlashFS::unmount().
Referenced by task().
HandleFsStatus()
void HandleFsStatus () private
Handler function for handling of file system status request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the file system status data in JSON format in the payload. File system status data will be retrieved by call of function getConfigJson provided by class FlashFS.
Definition at line 992 of file mqtt_connector.cpp.
References command_topic, FlashFS::inst(), and PublishAcceptedResponse().
Referenced by task().
HandleDisableADXL()
void HandleDisableADXL (PoolElem * pElem) private
Handler function for handling disable ADXL request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it send a message of type eDisableADXL to the ADXL37x task by calling function sendMsg provided by class Mbox.
Definition at line 933 of file mqtt_connector.cpp.
References command_topic, eDisableADXL, PublishAcceptedResponse(), and Mbox::sendMsg().
Referenced by task().
HandleEnableADXL()
void HandleEnableADXL (PoolElem * pElem) private
Handler function for handling enable ADXL request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the data of the received message pElem in the payload. Afterwards it send a message of type eEnableADXL to the ADXL37x task by calling function sendMsg provided by class Mbox.
Definition at line 954 of file mqtt_connector.cpp.
References command_topic, eEnableADXL, PublishAcceptedResponse(), and Mbox::sendMsg().
Referenced by task().
HandleGetConfig()
void HandleGetConfig () private
Handler function for handling get configuration request.
Parameters
pElem Pointer to the received message
By call of private member function PublishAcceptedResponse the function publishs a accepted response for the commad topic to the MQTT broker with the configuration data in JSON format in the payload. Configuration data will be retrieved by call of function getConfigJson provided by class Config.
Definition at line 975 of file mqtt_connector.cpp.
References command_topic, Config::inst(), and PublishAcceptedResponse().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the LTE connector.
Definition at line 217 of file mqtt_connector.h.
Referenced by main(), MqttConnector(), task(), and timer1_expired().
myTimer
Timer* myTimer
Cyclic reconnect timer.
Definition at line 218 of file mqtt_connector.h.
Referenced by connect(), MqttConnector(), and task().
device_id
char device_id static private
The hardware device ID, which is the modem's IMEI
Definition at line 236 of file mqtt_connector.h.
Referenced by connect(), getDeviceId(), and MqttConnector().
host_name
char host_name = DEFAULT_MQTT_HOSTNAME static private
The MQTT host name.
Definition at line 238 of file mqtt_connector.h.
Referenced by connect().
measurement_topic
char measurement_topic static private
device/${device_id}/measurement/update
Device publishes measurement data to platform.
Definition at line 242 of file mqtt_connector.h.
Referenced by MqttConnector(), and task().
metrics_topic
char metrics_topic static private
device/${device_id}/metric/update
Device publishes internal metric information to the platform.
Definition at line 246 of file mqtt_connector.h.
Referenced by MqttConnector(), and task().
pubkey_topic
char pubkey_topic static private
device/${device_id}/pubkey
Device publishes public TLS key to the platform.
Definition at line 250 of file mqtt_connector.h.
Referenced by MqttConnector(), and task().
command_topic
char command_topic static private
Device commands
/device/{device_id}/command
Definition at line 255 of file mqtt_connector.h.
Referenced by cmd_subscribe(), HandleBoostOffReq(), HandleBoostOnReq(), HandleColdStartReq(), HandleDisableADXL(), HandleEnableADXL(), HandleFactoryDefault(), HandleFsErase(), HandleFsStatus(), HandleGetConfig(), MqttConnector(), and task().
ota_topic
char ota_topic static private
device/${device_id}/ota/update
Device receives OTA update information from the platform.
Definition at line 261 of file mqtt_connector.h.
Referenced by MqttConnector(), ota_subscribe(), and task().
event_topic
char event_topic static private
Device Events
/device/{device_id}/event
Definition at line 267 of file mqtt_connector.h.
Referenced by MqttConnector(), and task().
config_topic
char config_topic static private
device/${device_id}/config/update
Device receives configuration update information from the platform.
Definition at line 271 of file mqtt_connector.h.
Referenced by config_subscribe(), HandleNewConfiguration(), and MqttConnector().
connected
bool connected private
Flag indicating that connection to MQTT broker is established
Definition at line 276 of file mqtt_connector.h.
Referenced by task().
lte_connected
bool lte_connected private
Flag indicating that connection to LTE modem broker is established
Definition at line 278 of file mqtt_connector.h.
Referenced by task().
last_msg_id
int32_t last_msg_id private
ID of the last message published to MQTT broker.
Definition at line 281 of file mqtt_connector.h.
Referenced by publish().
numConnectRetries
uint8_t numConnectRetries private
Number of MQTT connect retries.
Definition at line 283 of file mqtt_connector.h.
Referenced by connect(), and MqttConnector().
metricsInterval
uint32_t metricsInterval private
Metrics interval from config class.
Definition at line 284 of file mqtt_connector.h.
Referenced by configure(), and connect().
The documentation for this class was generated from the following files:
net/mqtt_connector.h
net/mqtt_connector.cpp