AXO X1: Hash Class Reference
Hash Class Reference
Hash class to calculate SHA1 or SHA256 checksum implemented according to C++ singleton design pattern.
#include <hash.h>
Detailed Description
Hash class to calculate SHA1 or SHA256 checksum implemented according to C++ singleton design pattern.
The Hash class provides methods to init, updata and finalize a SHA1 or SHA256 hash checksum. Furthermore getter functions to retrieve calculated hash checksum and their length and a method to print out the checksum as string in a terminal window.
Definition at line 64 of file hash.h.
Public Member Functions
~Hash ()
Hash class destructor.
void init ()
The init function to start SHA checksum calculation.
void update (uint8_t *pBuf, size_t len)
The update function of SHA1 checksum calculation.
void finalize ()
Function to finalize SHA1 checksum calculation.
void print ()
Function to print the SHA1 checksum at terminal window.
uint8_t * getHash ()
Getter function to retrieve the hash checksum.
uint16_t getHashLen ()
Getter function to retrieve the hash checksum length.
Static Public Member Functions
static Hash * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
Hash ()
Hash class constructor.
Private Attributes
mbedtls_sha256_context sha_ctx
Context for SHA256 calculation
uint8_t hash [SHA_HASH_SIZE]
The calculated SHA1 or SHA256 checksum.
Constructor & Destructor Documentation
~Hash()
~Hash ()
Hash class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 55 of file hash.cpp.
Hash()
Hash () private
Hash class constructor.
The constructor simply triggers a debug message on info debug level.
Definition at line 47 of file hash.cpp.
Member Function Documentation
inst()
Hash * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 36 of file hash.cpp.
Referenced by HttpConnector::HandleRawDataStatus(), HttpConnector::HandleRcvdData(), and HttpConnector::StartHttpDispDataTransmission().
init()
void init ()
The init function to start SHA checksum calculation.
The function starts the SHA checksum calculation with call of the functions mbedtls_sha1_init and mbedtls_sha1_starts or mbedtls_sha256_init and mbedtls_sha256_starts provided by mbedtls crypto library with SHA context variable sha_ctx.
Definition at line 65 of file hash.cpp.
References sha_ctx.
Referenced by HttpConnector::HandleRawDataStatus(), and HttpConnector::StartHttpDispDataTransmission().
update()
void update (uint8_t * pBuf, size_t len)
The update function of SHA1 checksum calculation.
Parameters
pBuf Buffer containing the data
len Length of the data buffer in bytes
The SHA1 checksum will be updated with the data in input buffer pBuf with length len by calling function mbedtls_sha1_update provided by mbedtls crypto library.
Definition at line 86 of file hash.cpp.
References sha_ctx.
Referenced by HttpConnector::HandleRawDataStatus(), HttpConnector::HandleRcvdData(), and HttpConnector::StartHttpDispDataTransmission().
finalize()
void finalize (void)
Function to finalize SHA1 checksum calculation.
Initially the hash will be cleared with call of funtion memset. Afterwards the SHA1 hash checksum will be finalized by calling function mbedtls_sha1_finish and the context variable sha1_ctx will be released by call of function mbedtls_sha1_free, both provided by mbedtls crypto library.
Definition at line 105 of file hash.cpp.
References hash, sha_ctx, and SHA_HASH_SIZE.
Referenced by HttpConnector::HandleRcvdData().
print()
void print (void)
Function to print the SHA1 checksum at terminal window.
The function transform the binary hash value into a character array by calling function bin2hex, add the terminating zero and print the string with debug message at debug level.
Definition at line 125 of file hash.cpp.
References hash, and SHA_HASH_SIZE.
Referenced by HttpConnector::HandleRcvdData().
getHash()
uint8_t * getHash ()
Getter function to retrieve the hash checksum.
Returns
Returns the calculated SHA checksum
The function returns the calculated SHA checksum
Definition at line 141 of file hash.cpp.
References hash.
getHashLen()
uint16_t getHashLen ()
Getter function to retrieve the hash checksum length.
Returns
Returns the length of the SHA checksum
The function returns the length of the SHA checksum
Definition at line 152 of file hash.cpp.
References SHA_HASH_SIZE.
Field Documentation
sha_ctx
mbedtls_sha256_context sha_ctx private
Context for SHA256 calculation
Definition at line 84 of file hash.h.
Referenced by finalize(), init(), and update().
hash
uint8_t hash[SHA_HASH_SIZE] private
The calculated SHA1 or SHA256 checksum.
Definition at line 87 of file hash.h.
Referenced by finalize(), getHash(), and print().
The documentation for this class was generated from the following files:
util/hash.h
util/hash.cpp