AXO X1: PoolElem Class Reference
PoolElem Class Reference
The pool element class that provides the messages to be send or received.
#include <mpelem.h>
Detailed Description
The pool element class that provides the messages to be send or received.
Detailed Description
A pool element is a messages which will be send to or received from tasks. A pool element is allways allocated from an existing message pool of type MsgPool. The private variable pool held the pointer to the originating pool. The pool element class provides methods for setting and getting the content of the message and for freeing itself, furthermore getter functions to retrieve the pointer to the message content and the buffer size and methods to clear the buffer content and to put data into the buffer.
Definition at line 174 of file mpelem.h.
Public Types
enum { maxAlloc = 2048 }
Public Member Functions
void free ()
The pool element free function.
uint8_t * getBuffer (void)
Getter function to retrieve the pointer to message buffer content.
uint16_t getBufferSize (void)
Getter function to retrieve the buffer size.
void clearBuffer ()
Function to clear the buffer content.
void putString (const char *s)
Function to copy a string in the buffer content.
void putData (const void *pdata, size_t len)
Function to copy data in the buffer content.
PoolElem ()
PoolElem class constructor.
PoolElem (msgType type, uint8_t sender, uint8_t para1=0, int8_t para2=0)
PoolElem class constructor.
~PoolElem ()
PoolElem class destructor.
void Dump ()
Dump function for debug purposes.
void DumpAsString ()
Dump function for debug purposes.
void DumpAsStringHex (size_t min_len=0)
Dump function for debug purposes.
Data Fields
uint8_t mtype
message/event type/name
uint8_t from
ID of sender/task.
uint8_t p1
arbitrary byte parameter
int8_t p2
arbitrary byte parameter
Private Attributes
bool inPool
true after free()
MsgPool * pool
pointer to message originating pool
uint8_t(* buf)[maxAlloc]
uint16_t bufLen
Length of the buffer.
uint16_t dataLen
Length of the data.
friend MsgPool
allow message pool access to private members
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
maxAlloc
Definition at line 183 of file mpelem.h.
Constructor & Destructor Documentation
PoolElem() [1/2]
PoolElem () inline
PoolElem class constructor.
Definition at line 188 of file mpelem.h.
PoolElem() [2/2]
PoolElem (msgType type, uint8_t sender, uint8_t para1 = 0, int8_t para2 = 0) inline
PoolElem class constructor.
Parameters
type The message type of enumerator type msgType
sender The sender ID
para1 8-bit unsigned int parameter, default value is 0
para2 8-bit unsigned int parameter, default value is 0
The constructor initializes member variables mtype, from, p1 and p2.
Definition at line 202 of file mpelem.h.
~PoolElem()
~PoolElem () inline
PoolElem class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 213 of file mpelem.h.
Member Function Documentation
free()
void free ()
The pool element free function.
The function release the message to the pool from which it was allocated by calling the method free of the originating pool.
Definition at line 165 of file mpelem.cpp.
References MsgPool::freeElem(), and pool.
Referenced by RmsTask::task(), AdxlDataStore::task(), HwMetrics::task(), DispTask::task(), ADConverter::task(), Shtcx::task(), BoostConverter::task(), Adxl37x::task(), HttpConnector::task(), MqttConnector::task(), PowerMgr::task(), ResetCtrl::task(), FwUpd::task(), FwUpdCtrl::task(), DataManager::task(), RmsStore::task(), BatteryMgr::task(), LteMonitor::task(), and LteConnector::task().
getBuffer()
uint8_t * getBuffer (void)
Getter function to retrieve the pointer to message buffer content.
Returns
returns the pointer to the message buffer content
The function return the pointer to message buffer content in private member variable buf.
Definition at line 43 of file mpelem.cpp.
References buf.
Referenced by MetricsBuilder::addBootCnt(), MeasurementBuilder::addDispStatistics(), MetricsBuilder::addHumidity(), MetricsBuilder::addHwMetrics(), MetricsBuilder::addIMSI(), MeasurementBuilder::addMaxXYZ(), MetricsBuilder::addModemBattV(), MetricsBuilder::addModemPsmAct(), MetricsBuilder::addModemTemp(), MetricsBuilder::addResetCause(), MeasurementBuilder::addRmsData(), MetricsBuilder::addTemperature(), FwInfo::FwInfo(), DispTask::HandleBwFiltData(), DispTask::HandleDispFirstEntries(), DispTask::HandleDispLastEntries(), DispTask::HandleFwFiltData(), HwMetrics::HandleHwStatusAdxl37x(), MqttConnector::HandleNewConfiguration(), DispTask::HandleRawData(), DispTask::HandleRawDataStatus(), HttpConnector::HandleRawDataStatus(), HttpConnector::HandleRcvdData(), DispTask::HandleSResultData(), MqttConnector::PublishAcceptedResponse(), MqttConnector::PublishDlResult(), MqttConnector::PublishRejectedResponse(), AdxlDataStore::sendBwFiltData(), AdxlDataStore::sendDispData(), AdxlDataStore::sendFwFiltData(), AdxlDataStore::sendRawData(), AdxlDataStore::sendSResultData(), AdxlDataStore::storeBackwardFilt(), AdxlDataStore::storeDResult(), AdxlDataStore::storeForwardFilt(), AdxlDataStore::storeSResult(), AdxlDataStore::task(), HttpConnector::task(), MqttConnector::task(), RmsStore::task(), BatteryMgr::task(), and RmsTask::update_rms().
getBufferSize()
uint16_t getBufferSize (void)
Getter function to retrieve the buffer size.
Returns
returns the size of message buffer
The function return the buffer size in private member variable bufLen.
Definition at line 53 of file mpelem.cpp.
References bufLen.
clearBuffer()
void clearBuffer ()
Function to clear the buffer content.
The function clear the buffer content by setting a value of 0 for all bytes of the buffer and set private member varaible dataLen to 0.
Definition at line 62 of file mpelem.cpp.
References buf, bufLen, and dataLen.
putString()
void putString (const char * s)
Function to copy a string in the buffer content.
Parameters
s The string to put in the buffer content
The function copy a string in the buffer content and assign the string length to member variable dataLen.
Definition at line 76 of file mpelem.cpp.
References buf, bufLen, and dataLen.
Referenced by Mbox::sendMsg().
putData()
void putData (const void * pdata, size_t len)
Function to copy data in the buffer content.
Parameters
pdata A pointer to the data to put in the buffer content
len Length of the data
The function copy data in the buffer content and assign the length of the data to member variable dataLen.
Definition at line 101 of file mpelem.cpp.
References buf, bufLen, and dataLen.
Referenced by Mbox::sendMsg().
Dump()
void Dump ()
Dump function for debug purposes.
The function print out statistics of the pool element
Definition at line 116 of file mpelem.cpp.
References buf, bufLen, dataLen, from, mtype, p1, and p2.
Referenced by Mbox::write().
DumpAsString()
void DumpAsString ()
Dump function for debug purposes.
The function print out the buffer content as string
Definition at line 133 of file mpelem.cpp.
References buf.
DumpAsStringHex()
void DumpAsStringHex (size_t min_len = 0)
Dump function for debug purposes.
The function print out the buffer content as hexadecimal values
Definition at line 144 of file mpelem.cpp.
References buf.
Field Documentation
mtype
uint8_t mtype
message/event type/name
Definition at line 220 of file mpelem.h.
Referenced by MeasurementBuilder::add(), MetricsBuilder::add(), Dump(), PowerMgrX1::message_handler(), LteConnector::notify(), AdxlDataStore::sendBwFiltData(), AdxlDataStore::sendDispData(), AdxlDataStore::sendFwFiltData(), Mbox::sendMsg(), AdxlDataStore::sendRawData(), AdxlDataStore::sendSResultData(), RmsTask::task(), AdxlDataStore::task(), HwMetrics::task(), DispTask::task(), ADConverter::task(), Shtcx::task(), BoostConverter::task(), Adxl37x::task(), HttpConnector::task(), MqttConnector::task(), ResetCtrl::task(), FwUpd::task(), FwUpdCtrl::task(), DataManager::task(), RmsStore::task(), BatteryMgr::task(), LteMonitor::task(), and LteConnector::task().
from
uint8_t from
ID of sender/task.
Definition at line 221 of file mpelem.h.
Referenced by Dump(), LteConnector::notify(), AdxlDataStore::sendBwFiltData(), AdxlDataStore::sendDispData(), AdxlDataStore::sendFwFiltData(), Mbox::sendMsg(), AdxlDataStore::sendRawData(), AdxlDataStore::sendSResultData(), AdxlDataStore::task(), DataManager::task(), and LteMonitor::task().
p1
uint8_t p1
arbitrary byte parameter
Definition at line 222 of file mpelem.h.
Referenced by Dump(), HttpConnector::HandleAdxlIdleInd(), Mbox::sendMsg(), ADConverter::task(), BoostConverter::task(), and ADConverter::timer1_expired().
p2
int8_t p2
arbitrary byte parameter
Definition at line 223 of file mpelem.h.
Referenced by MetricsBuilder::addModemLinkQuality(), Dump(), Mbox::sendMsg(), and LteMonitor::task().
inPool
bool inPool private
true after free()
Definition at line 228 of file mpelem.h.
Referenced by MsgPool::freeElem(), and MsgPool::getNewElem().
pool
MsgPool* pool private
pointer to message originating pool
Definition at line 229 of file mpelem.h.
Referenced by free(), and MsgPool::getNewElem().
buf
uint8_t(* buf)[maxAlloc] private
Definition at line 231 of file mpelem.h.
Referenced by clearBuffer(), Dump(), DumpAsString(), DumpAsStringHex(), MsgPool::freeElem(), getBuffer(), MsgPool::getNewElem(), putData(), and putString().
bufLen
uint16_t bufLen private
Length of the buffer.
Definition at line 232 of file mpelem.h.
Referenced by clearBuffer(), Dump(), MsgPool::freeElem(), getBufferSize(), MsgPool::getNewElem(), putData(), and putString().
dataLen
uint16_t dataLen private
Length of the data.
Definition at line 233 of file mpelem.h.
Referenced by clearBuffer(), Dump(), MsgPool::getNewElem(), putData(), and putString().
MsgPool
friend MsgPool private
allow message pool access to private members
Definition at line 235 of file mpelem.h.
The documentation for this class was generated from the following files:
rtos/mpelem.h
rtos/mpelem.cpp