AXO X1: BoostConverter Class Reference
BoostConverter Class Reference
Boost converter class derived from task base class.
#include <boost.h>
Detailed Description
Boost converter class derived from task base class.
Detailed Description
The boost converter class switches boost converter on and off. It provides methods to set GPIO pin P0.21 in active and inactive state to switch boost converter on and off and a timer to control the duration of boost controller activity. Message Interaction:
Receive
Timer interrupt callback
Boost converter task (self)
Power manager task
Transmit
Boost converter task (self)
Definition at line 71 of file boost.h.
Public Member Functions
BoostConverter (const char *name="??")
Boost converter task constructor.
virtual ~BoostConverter ()
Boost converter task destructor.
virtual void task (void)
Boost converter task function.
void timer1_expired ()
Timer expired function for the timer to control the maximum activation time period.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the timer to control the maximum activation time period.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the boost converter task.
Timer * myTimer
Timer to control the maximum activation time period.
Private Member Functions
void on ()
Function to switch on boost converter.
void off ()
Function to switch off boost converter.
BoostConverter ()=delete
Private Attributes
bool isEnabled
Flag indicating that boost converter is en- or disbled.
bool isOn
Flag indicating that boost converter is activated.
int maxTimeOn
The maximum activation time period.
int refcnt
Reserved for future use.
struct gpio_dt_spec gpio
GPIO pin information structure.
bool device_good
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
BoostConverter() [1/2]
BoostConverter (const char * name = "??") explicit
Boost converter task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocate the timer to supervise the maximum activation time period. By calling macro GPIO_DT_SPEC_GET it retrieves the GPIO pin information structure gpio from devicetree and checks with call of function device_is_ready if the gpio is ready for use. The private flag device_good, indicating that hardware initialization was successful, will be set according to the return value of function device_is_ready. If initialization was not successful an error message will be printed.
Flag isEnabled will be set to false, in case file BOOST_ENABLED_FILENAME exists, flag will be set to true.
Definition at line 101 of file boost.cpp.
References BOOST_ENABLED_FILENAME, BOOST_NODE, device_good, Mbox::eBoostConverter, gpio, FlashFS::inst(), isEnabled, myTimer, pInMbox, Mbox::registerMbox(), and timer_cb().
~BoostConverter()
~BoostConverter () virtual
Boost converter task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 173 of file boost.cpp.
BoostConverter() [2/2]
BoostConverter () private delete
Member Function Documentation
task()
void task (void) virtual
Boost converter task function.
The function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On timer expiry the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static. Finally boost converter is switched off by calling function off().
eResume: On reciving the resume message from power manager the timeout value for the maximum activation time period will be extracted from message payload and the timer will be started with this timeout value. Afterwards boost converter is switched on by calling function on().
eSuspend: On reciving the suspend message from power manager, timer will be stopped and boost converter is switched off by calling function off().
eBoostOnReq: Boost converter will be enabled by setting flag isEnabled to true and file BOOST_ENABLED_FILENAME will be written to file system as persistent indication.
eBoostOffReq: Boost converter will be enabled by setting flag isEnabled to false and file BOOST_ENABLED_FILENAME will be deleted.
Implements Task.
Definition at line 203 of file boost.cpp.
References BOOST_ENABLED_FILENAME, eBoostOffReq, eBoostOnReq, eResume, eSuspend, eTimerExpired, FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_seek(), FlashFS::file_sync(), FlashFS::file_write(), PoolElem::free(), FlashFS::inst(), isEnabled, PoolElem::mtype, Task::myName, myTimer, off(), on(), PoolElem::p1, pInMbox, Mbox::read(), FlashFS::remove(), Timer::start(), Timer::stop(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the timer to control the maximum activation time period.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call boost converter timer expired function timer1_expired.
Definition at line 61 of file boost.cpp.
References timer1_expired().
Referenced by BoostConverter().
timer1_expired()
void timer1_expired ()
Timer expired function for the timer to control the maximum activation time period.
The function initializes the static pool element e1 with message type eTimerExpired, set reset control as sender and put message into own (boost converter's) mailbox.
Definition at line 77 of file boost.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
on()
void on () private
Function to switch on boost converter.
By calling function gpio_pin_configure_dt boost enable pin will be forced to active state to switch on the boost converter. Flag isOn indicating that boost converter is activated will be set to true.
Definition at line 142 of file boost.cpp.
References gpio, and isOn.
Referenced by task().
off()
void off () private
Function to switch off boost converter.
By calling function gpio_pin_configure_dt boost enable pin will be forced to inactive state to switch off the boost converter. Flag isOn indicating that boost converter is activated will be set to false.
Definition at line 158 of file boost.cpp.
References gpio, and isOn.
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the boost converter task.
Definition at line 80 of file boost.h.
Referenced by BoostConverter(), task(), and timer1_expired().
myTimer
Timer* myTimer
Timer to control the maximum activation time period.
Definition at line 81 of file boost.h.
Referenced by BoostConverter(), and task().
isEnabled
bool isEnabled private
Flag indicating that boost converter is en- or disbled.
Definition at line 86 of file boost.h.
Referenced by BoostConverter(), and task().
isOn
bool isOn private
Flag indicating that boost converter is activated.
Definition at line 87 of file boost.h.
Referenced by off(), and on().
maxTimeOn
int maxTimeOn private
The maximum activation time period.
Definition at line 88 of file boost.h.
refcnt
int refcnt private
Reserved for future use.
Definition at line 89 of file boost.h.
gpio
struct gpio_dt_spec gpio private
GPIO pin information structure.
Definition at line 89 of file boost.h.
Referenced by BoostConverter(), off(), and on().
device_good
bool device_good private
Flag indicating that hardware initialization was successful
Definition at line 91 of file boost.h.
Referenced by BoostConverter().
The documentation for this class was generated from the following files:
drv/pm/boost.h
drv/pm/boost.cpp