AXO X1: MemoryPool< T, num_blocks > Class Template Reference
MemoryPool< T, num_blocks > Class Template Reference
RTOS wrapper for memory pool support.
#include <mempool.h>
Detailed Description
template<typename T, uint32_t num_blocks>
class MemoryPool< T, num_blocks >
RTOS wrapper for memory pool support.
Detailed Description
The sema class implements a C++ wrapper of the Memory Slab API provided by the Zephyr operating system. See details in Zephyr Memory Slab documentation or in API documentation. The sema class provides methods to allocate and free fixed size memory blocks of concretized type T. It furthermore provides a method to print out statistics.
Definition at line 60 of file mempool.h.
Public Member Functions
MemoryPool ()
MemoryPool class constructor.
T * alloc ()
MemoryPool allocation function.
void free (void *block_ptr)
MemoryPool free function.
void stats ()
MemoryPool status function.
uint32_t size ()
uint32_t blocksize ()
uint32_t used ()
uint32_t maxused ()
uint32_t available ()
Private Member Functions
char __aligned (4) my_slab_buffer[sizeof(T) *num_blocks]
Private Attributes
struct k_mem_slab my_slab
Memory slab administration structure.
Constructor & Destructor Documentation
MemoryPool()
MemoryPool () inline
MemoryPool class constructor.
The constructor initializes the memory slab by calling RTOS function k_msgq_init. This function initializes the memory slab object, prior to its first use. It returns the memory slab administration structure my_slab.
Definition at line 71 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Member Function Documentation
alloc()
T* alloc () inline
MemoryPool allocation function.
Returns
A pointer to the memory block of template type T
This function allocates a memory slab object by calling function k_mem_slab_alloc provided by the operating system, which return the pointer to the memory block block_ptr and a pointer to the memory slab administration structure my_slab. Afterwards allocated memory is cleared by setting the conplete content to 0.
Definition at line 93 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::getNewElem().
free()
void free (void * block_ptr) inline
MemoryPool free function.
Parameters
block_ptr A pointer to the memory slab object to be released
This function release the memory slab object by calling function k_mem_slab_free provided by the operating system.
Definition at line 116 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::freeElem().
stats()
void stats () inline
MemoryPool status function.
This function print out statistics of the memory pool.
Definition at line 127 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::stats().
size()
uint32_t size () inline
Definition at line 136 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::available(), and MsgPool::bufpool_size().
blocksize()
uint32_t blocksize () inline
Definition at line 137 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
used()
uint32_t used () inline
Definition at line 138 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::available(), MsgPool::bufpool_used(), and MsgPool::used().
maxused()
uint32_t maxused () inline
Definition at line 139 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::bufpool_maxused(), and MsgPool::maxused().
available()
uint32_t available () inline
Definition at line 140 of file mempool.h.
References MemoryPool< T, num_blocks >::my_slab.
Referenced by MsgPool::bufpool_available().
__aligned()
char __aligned (4) private
Reserved memory to store the memory objects
Field Documentation
my_slab
struct k_mem_slab my_slab private
Memory slab administration structure.
Definition at line 140 of file mempool.h.
Referenced by MemoryPool< T, num_blocks >::alloc(), MemoryPool< T, num_blocks >::available(), MemoryPool< T, num_blocks >::blocksize(), MemoryPool< T, num_blocks >::free(), MemoryPool< T, num_blocks >::maxused(), MemoryPool< T, num_blocks >::MemoryPool(), MemoryPool< T, num_blocks >::size(), MemoryPool< T, num_blocks >::stats(), and MemoryPool< T, num_blocks >::used().
The documentation for this class was generated from the following file:
rtos/mempool.h