AXO X1: PowerMgr Class Reference
PowerMgr Class Reference abstract
Power Manager base class derived from task base class.
#include <power_mgr.h>
Detailed Description
Power Manager base class derived from task base class.
Detailed Description
The power manager task provides a timer to control the metrics TX interval (MetricsTxTimer). It provides methods to report reset cause and boot counter to the data manager task, to switch UART on and off, to register and notify the metrics providing tasks, to configure the metrics transmission interval and the task function. It furthermore declares a task init and a message handler function as pure virtual. These function must be implemented in all derived classes. Both are called in the task function, task init function at the beginning of the task function before entering the endless loop, the message handler function in the endless loop, directly after reading the message from the tasks mailbox.
Definition at line 56 of file power_mgr.h.
Public Types
enum PmState { eOff = 0 , eOn , kNumStates }
Power manager states.
enum PmTmo { eMetricsTmo = 2 * 60 * 60 , kNumTimerEvents }
Power manager timeout values.
Public Member Functions
PowerMgr (const char *name="??")
Power manager task constructor.
virtual ~PowerMgr ()
Power manager task destructor.
virtual void task (void)
virtual void taskInit (void)=0
virtual PoolElem * message_handler (PoolElem *pElem)=0
virtual void configure ()
Power Manager virtual task configure function.
void MetricsTxTimer_expired ()
Timer expired function for metrics TX interval timer.
void reqRmsReport ()
Send request accelerometer data message to RMS store task.
void reportResetCause ()
Send reset reason message to data manager task.
void reportBootCnt ()
Send boot count message to data manager task.
void registerMetricProvider (uint8_t mboxId, uint16_t mtype)
Register a task that contributes to device metrics for callback.
void metricProviderNotify (uint8_t mboxId, uint16_t mtype)
Send metric request message to a task that contributes to metrics.
void metricProviderNotifyAll ()
Send metric request message to all registered mailboxes.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static void MetricsTxTimer_cb (k_timer *timer)
Timer callback function for metrics TX interval timer.
static void uart0_off ()
Function to disable UART.
static void uart0_set_enable (bool enable)
Function to enable or disable UART.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the power manager.
Timer * MetricsTxTimer
Timer to control metrics TX interval.
uint32_t metricsTmo
timeout for metrics tx request (e.g. 2h)
uint32_t reason
Reset reason.
std::string reason_str
Reset reason string.
int32_t boot_cnt
Boot counter.
std::vector< uint8_t > metricProviders
report request receivers
std::vector< uint16_t > metricType
message type in report request
Private Member Functions
PowerMgr ()=delete
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Member Enumeration Documentation
PmState
enum PmState
Power manager states.
Enumerator
eOff
Power manager state Off.
eOn
Power manager state On.
kNumStates
Indicator for the number of power manager states.
Definition at line 59 of file power_mgr.h.
PmTmo
enum PmTmo
Power manager timeout values.
Enumerator
eMetricsTmo
Timeout for metrics tx request (e.g. 2h) NOTE: eMetricsTmo is only used for creation in constructor, real timeout value is set in configure function
kNumTimerEvents
Indicator for the number of timeout events.
Definition at line 66 of file power_mgr.h.
Constructor & Destructor Documentation
PowerMgr() [1/2]
PowerMgr (const char * name = "??") explicit
Power manager task constructor.
Parameters
name The name of the class
The constructor updates boot count by calling the getter function of class BootCnt, allocate and register a mailbox and allocates the timer for metrics TX interval.
Definition at line 149 of file power_mgr.cpp.
References boot_cnt, eMetricsTmo, Mbox::ePowerManager, BootCnt::get(), BootCnt::inst(), MetricsTxTimer, MetricsTxTimer_cb(), pInMbox, and Mbox::registerMbox().
~PowerMgr()
~PowerMgr () virtual
Power manager task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 176 of file power_mgr.cpp.
PowerMgr() [2/2]
PowerMgr () private delete
Member Function Documentation
task()
void task (void) virtual
Implements Task.
Definition at line 237 of file power_mgr.cpp.
References PoolElem::free(), ResetReason::get(), ResetReason::inst(), message_handler(), Task::myName, pInMbox, Mbox::read(), reason, reason_str, taskInit(), and UNIT_TEST_STOP_LOOP.
taskInit()
virtual void taskInit (void) pure virtual
Implemented in PowerMgrX1.
Referenced by task().
message_handler()
virtual PoolElem* message_handler (PoolElem * pElem) pure virtual
Implemented in PowerMgrX1.
Referenced by task().
configure()
void configure () virtual
Power Manager virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to metrics by call of the function getCfgMetrics provided by the Config class, convert the timeout intervall in seconds and reconfigure the metrics wakeup interval with this value.
Reimplemented from Task.
Definition at line 268 of file power_mgr.cpp.
References Config::getCfgMetrics(), Config::inst(), _stCfgMetrics::interval, metricsTmo, MetricsTxTimer, and Timer::reconfigure().
Referenced by main().
MetricsTxTimer_cb()
void MetricsTxTimer_cb (k_timer * timer) static
Timer callback function for metrics TX interval timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call power manager timer expired function MetricsTxTimer_expired.
Definition at line 118 of file power_mgr.cpp.
References MetricsTxTimer_expired().
Referenced by PowerMgr().
MetricsTxTimer_expired()
void MetricsTxTimer_expired ()
Timer expired function for metrics TX interval timer.
The function initializes the static pool element e1 with message type eMetricsTxTimerExpired, set power manager as sender and put message into own (powermanager's) mailbox.
Definition at line 133 of file power_mgr.cpp.
References eMetricsTxTimerExpired, pInMbox, and Mbox::write().
Referenced by MetricsTxTimer_cb().
uart0_off()
void uart0_off () static
Function to disable UART.
The function disable UART by calling power manager function uart0_set_enable
Definition at line 47 of file power_mgr.cpp.
References uart0_set_enable().
Referenced by PowerMgrX1::message_handler().
uart0_set_enable()
void uart0_set_enable (bool enable) static
Function to enable or disable UART.
Parameters
enable true = enable UART, false = disable UART
The function enable or disable UART according to input parameter enable
Definition at line 56 of file power_mgr.cpp.
Referenced by uart0_off().
reqRmsReport()
void reqRmsReport ()
Send request accelerometer data message to RMS store task.
The function send a message of type eRmsReport to RMS store mailbox by calling function sendMsg provided by Mbox class.
This request is the trigger to send accelerometer RMS data to the cloud.
Definition at line 76 of file power_mgr.cpp.
References eRmsReport, and Mbox::sendMsg().
Referenced by PowerMgrX1::message_handler().
reportResetCause()
void reportResetCause ()
Send reset reason message to data manager task.
The function send a message of type eResetCause with the attached reset reason string to data manager mailbox by calling function sendMsg provided by Mbox class.
Definition at line 89 of file power_mgr.cpp.
References eResetCause, reason_str, and Mbox::sendMsg().
Referenced by PowerMgrX1::message_handler().
reportBootCnt()
void reportBootCnt ()
Send boot count message to data manager task.
The function send a message of type eBootCnt with the attached boot counter to data manager mailbox by calling function sendMsg provided by Mbox class.
Definition at line 102 of file power_mgr.cpp.
References boot_cnt, eBootCnt, and Mbox::sendMsg().
Referenced by PowerMgrX1::message_handler().
registerMetricProvider()
void registerMetricProvider (uint8_t mboxId, uint16_t mtype)
Register a task that contributes to device metrics for callback.
Parameters
mboxId The ID of the mailbox, must be ID from enum MboxId
mtype The message type for the request, must be from enum msgType
The function expects the Mailbox ID of the task and the expected message type to use in the request.
Definition at line 187 of file power_mgr.cpp.
References metricProviders, and metricType.
Referenced by PowerMgrX1::PowerMgrX1().
metricProviderNotify()
void metricProviderNotify (uint8_t mboxId, uint16_t mtype)
Send metric request message to a task that contributes to metrics.
Parameters
mboxId The ID of the mailbox, must be ID from enum MboxId
mtype The message type for the request, must be from enum msgType
The function send a message of type mtype to mboxId mailbox by calling function sendMsg provided by Mbox class.
Definition at line 203 of file power_mgr.cpp.
References Mbox::sendMsg().
Referenced by metricProviderNotifyAll().
metricProviderNotifyAll()
void metricProviderNotifyAll ()
Send metric request message to all registered mailboxes.
In a loop over all registered mailboxes the function calls member function metricProviderNotify with mailbox ID and message type from register lists.
Definition at line 216 of file power_mgr.cpp.
References metricProviderNotify(), metricProviders, and metricType.
Referenced by PowerMgrX1::message_handler().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the power manager.
Definition at line 95 of file power_mgr.h.
Referenced by PowerMgrX1::AdxlWakeupTimer_expired(), PowerMgrX1::BoostCtrlTimer_expired(), PowerMgrX1::LteStartDelayTimer_expired(), main(), MetricsTxTimer_expired(), PowerMgr(), and task().
MetricsTxTimer
Timer* MetricsTxTimer
Timer to control metrics TX interval.
Definition at line 96 of file power_mgr.h.
Referenced by configure(), PowerMgrX1::message_handler(), and PowerMgr().
metricsTmo
uint32_t metricsTmo
timeout for metrics tx request (e.g. 2h)
Definition at line 97 of file power_mgr.h.
Referenced by configure().
reason
uint32_t reason
Reset reason.
Definition at line 98 of file power_mgr.h.
Referenced by task().
reason_str
std::string reason_str
Reset reason string.
Definition at line 99 of file power_mgr.h.
Referenced by reportResetCause(), and task().
boot_cnt
int32_t boot_cnt
Boot counter.
Definition at line 100 of file power_mgr.h.
Referenced by PowerMgr(), and reportBootCnt().
metricProviders
std::vector<uint8_t> metricProviders
report request receivers
Definition at line 102 of file power_mgr.h.
Referenced by metricProviderNotifyAll(), and registerMetricProvider().
metricType
std::vector<uint16_t> metricType
message type in report request
Definition at line 103 of file power_mgr.h.
Referenced by metricProviderNotifyAll(), and registerMetricProvider().
The documentation for this class was generated from the following files:
pm/power_mgr.h
pm/power_mgr.cpp