AXO X1: FwFsm Class Reference
FwFsm Class Reference
Firmware update state machine class implemented according to C++ state machine design pattern.
#include <fsm.h>
Detailed Description
Firmware update state machine class implemented according to C++ state machine design pattern.
Detailed Description
The class provides the four states Idle, Triggered, Firmware download and Ready and handler functions for the events OtaStart, FwInfo, DlComplete, DlFailed and timer expired.
Definition at line 56 of file fsm.h.
Public Types
enum StateId {
eNoChange = -1 , eIdle = 0 , eTriggered , eDownload ,
eReady , kNumFwStates
}
Enumeration defining the state ID's.
Public Member Functions
FwFsm (void *context, FwFsm::StateId initialState)
Firmware update state machine constructor.
FwFsm ()=delete
virtual ~FwFsm ()
Firmware update state machine destructor.
void setState (FwFsm::StateId newStateId)
Function to perform state transition to old state to new state.
int getStateId (void)
Getter function to retrieve the current state ID.
void handle_OtaStart ()
State machine handler function for OtaStart events.
void handle_FwInfo (PoolElem **pElem)
State machine handler function for FwInfo events.
void handle_DlComplete (PoolElem **pElem)
State machine handler function for DlComplete events.
void handle_Restart ()
State machine handler function for restart events.
void handle_DlFailed (PoolElem **pElem)
State machine handler function for DlFailed events.
void handle_timer_exp ()
State machine handler function for timer expired events.
Static Public Member Functions
static uint16_t getTriggerTimeout ()
Getter function to retrieve the trigger timeout.
static uint16_t getDownloadTimeout ()
Getter function to retrieve the download timeout.
Protected Attributes
class FwState * myState
Pointer to the class instance of the current state.
int myStateId
ID of the current state.
fwStateCreator stateTbl [kNumFwStates]
void * pd
Private Member Functions
void ReportOtaUpdateActive (void)
Send firmware update active message to Adxl37x task.
Static Private Attributes
static const uint16_t triggerTimeout
The trigger timeout value in s.
static const uint16_t downloadTimeout
The download timeout value in s.
Member Enumeration Documentation
StateId
enum StateId
Enumeration defining the state ID's.
Enumerator
eNoChange
Indicating that state has not been changed.
eIdle
ID of Idle state.
eTriggered
OTA cmd received, awaiting firmware info.
eDownload
Download started.
eReady
Download complete, ready to apply update on restart.
kNumFwStates
Last entry indicationg the number of states.
Definition at line 59 of file fsm.h.
Constructor & Destructor Documentation
FwFsm() [1/2]
FwFsm (void * context, FwFsm::StateId initialState)
Firmware update state machine constructor.
Parameters
initialState The initial state of the state machine
context Pointer to context, normally this pointer of owner class instance
The constructor initializes the member variable myStateId with the ID of the initial state and the pointer pd with context pointer. The array stateTbl will be filled with the state creator functions in order of the state IDs and finally the current state pointer myState will be assigned to instance of the initial state.
Definition at line 110 of file fsm.cpp.
References FwStateList::createDownload(), FwStateList::createIdle(), FwStateList::createReady(), FwStateList::createTriggered(), eDownload, eIdle, eReady, eTriggered, myState, myStateId, pd, and stateTbl.
FwFsm() [2/2]
FwFsm () delete
~FwFsm()
~FwFsm () virtual
Firmware update state machine destructor.
The destructor deletes the state instance of the current state.
Definition at line 125 of file fsm.cpp.
References myState.
Member Function Documentation
setState()
void setState (FwFsm::StateId newStateId)
Function to perform state transition to old state to new state.
Parameters
newStateId The ID of the desired new state
If the state has not changed, indicated by state ID eNoChange the function returns immediately. Otherwise the state instance of the current (old) state will be deleted and with the creator function in array stateTbl an instance of the new state will be allocated and assigned to the current state pointer myState. Also myStateId will be assigned to the ID of the new state. If the new state is not eIdle Adxl37x task will be informed that the update process is active.
Definition at line 143 of file fsm.cpp.
References eIdle, eNoChange, myState, myStateId, pd, ReportOtaUpdateActive(), and stateTbl.
Referenced by handle_DlComplete(), handle_DlFailed(), handle_FwInfo(), handle_OtaStart(), handle_Restart(), and handle_timer_exp().
getStateId()
int getStateId (void)
Getter function to retrieve the current state ID.
Returns
Returns the ID of the current state
The function returns the ID of the current state.
Definition at line 164 of file fsm.cpp.
References myStateId.
handle_OtaStart()
void handle_OtaStart ()
State machine handler function for OtaStart events.
The function call the handler function of the current state of the statemachine for OtaStart events. The returned state ID will be input parameter of setState mwember function and perform the state transition if necessary.
Definition at line 187 of file fsm.cpp.
References FwState::handle_OtaStart(), myState, and setState().
Referenced by FwUpdCtrl::task().
handle_FwInfo()
void handle_FwInfo (PoolElem ** pElem)
State machine handler function for FwInfo events.
The function call the handler function of the current state of the statemachine for FwInfo events. The returned state ID will be input parameter of setState mwember function and perform the state transition if necessary.
Definition at line 200 of file fsm.cpp.
References FwState::handle_FwInfo(), myState, and setState().
Referenced by FwUpdCtrl::task().
handle_DlComplete()
void handle_DlComplete (PoolElem ** pElem)
State machine handler function for DlComplete events.
The function call the handler function of the current state of the statemachine for DlComplete events. The returned state ID will be input parameter of setState mwember function and perform the state transition if necessary.
Definition at line 214 of file fsm.cpp.
References FwState::handle_DlComplete(), myState, and setState().
Referenced by FwUpdCtrl::task().
handle_Restart()
void handle_Restart ()
State machine handler function for restart events.
UNUSED! AXO_MUH added the handle_OtaStart for now just staring the OTA(Later it will be modified) just used in Developer Test
Definition at line 226 of file fsm.cpp.
References FwState::handle_OtaStart(), myState, myStateId, and setState().
handle_DlFailed()
void handle_DlFailed (PoolElem ** pElem)
State machine handler function for DlFailed events.
The function call the handler function of the current state of the statemachine for DlFailed events. The returned state ID will be input parameter of setState mwember function and perform the state transition if necessary.
Definition at line 240 of file fsm.cpp.
References FwState::handle_DlFailed(), myState, and setState().
Referenced by FwUpdCtrl::task().
handle_timer_exp()
void handle_timer_exp ()
State machine handler function for timer expired events.
The function call the handler function of the current state of the statemachine for timer expired events. The returned state ID will be input parameter of setState mwember function and perform the state transition if necessary.
Definition at line 254 of file fsm.cpp.
References FwState::handle_timer_exp(), myState, and setState().
Referenced by FwUpdCtrl::task().
getTriggerTimeout()
static uint16_t getTriggerTimeout () inline static
Getter function to retrieve the trigger timeout.
Returns
Returns the trigger timeout value in ms
Definition at line 84 of file fsm.h.
References triggerTimeout.
Referenced by FwIdle::handle_OtaStart().
getDownloadTimeout()
static uint16_t getDownloadTimeout () inline static
Getter function to retrieve the download timeout.
Returns
Returns the download timeout value in ms
Definition at line 90 of file fsm.h.
References downloadTimeout.
Referenced by FwTriggered::handle_FwInfo().
ReportOtaUpdateActive()
void ReportOtaUpdateActive (void) private
Send firmware update active message to Adxl37x task.
The function retrieve a pointer to the mailbox of the Adxl37x task, request a message from message pool, set message type to eFwUpdateActive, set eFwUpdCtrl as sender and send message to Adxl37x task's mailbox.
Definition at line 173 of file fsm.cpp.
References eFwUpdateActive, and Mbox::sendMsg().
Referenced by setState().
Field Documentation
myState
class FwState* myState protected
Pointer to the class instance of the current state.
Definition at line 94 of file fsm.h.
Referenced by FwFsm(), handle_DlComplete(), handle_DlFailed(), handle_FwInfo(), handle_OtaStart(), handle_Restart(), handle_timer_exp(), setState(), and ~FwFsm().
myStateId
int myStateId protected
ID of the current state.
Definition at line 95 of file fsm.h.
Referenced by FwFsm(), getStateId(), handle_Restart(), and setState().
stateTbl
fwStateCreator stateTbl[kNumFwStates] protected
Array of state creator functions, ordered by state ID
Definition at line 96 of file fsm.h.
Referenced by FwFsm(), and setState().
pd
void* pd protected
Pointer to data object, normally the this pointer of the owner class instance
Definition at line 98 of file fsm.h.
Referenced by FwFsm(), and setState().
triggerTimeout
const uint16_t triggerTimeout static private
Initial value:
=
        300
The trigger timeout value in s.
Definition at line 104 of file fsm.h.
Referenced by getTriggerTimeout().
downloadTimeout
const uint16_t downloadTimeout static private
Initial value:
=
        300
The download timeout value in s.
Definition at line 106 of file fsm.h.
Referenced by getDownloadTimeout().
The documentation for this class was generated from the following files:
update/fsm.h
update/fsm.cpp