AXO X1: WakeupCnt Class Reference
WakeupCnt Class Reference
Wakeup count class implemented according to C++ singleton design pattern.
#include <wakeup_cnt.h>
Detailed Description
Wakeup count class implemented according to C++ singleton design pattern.
Detailed Description
The class provides methods to handle the wakeup counter which is stored persitently in flash file system. Wakeup count is read at startup and
Todo:
is stored in private variable boot_count.
Definition at line 43 of file wakeup_cnt.h.
Public Member Functions
~WakeupCnt ()
Boot Count destructor.
void init ()
void update ()
Getter function to retrieve the boot count.
void incSleepExitCount ()
void incPublishMetricsCount ()
void incPublishMeasCount ()
uint32_t getSleepExitCount ()
uint32_t getPublishMeasCount ()
uint32_t getLteMeasWakeupCnt ()
uint32_t getLteWakeupCnt ()
Static Public Member Functions
static WakeupCnt * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
WakeupCnt ()
Private Attributes
uint32_t sleepExitCount
uint32_t publishMeasCount
Constructor & Destructor Documentation
~WakeupCnt()
~WakeupCnt ()
Boot Count destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 98 of file wakeup_cnt.cpp.
WakeupCnt()
WakeupCnt () explicit private
Todo:
Boot Count constructor
Parameters
fname Filename of the boot counter file
The constructor is declared as private according to singleton pattern. It is called in the static inst function to create the exclusiv only instance of the class. fname "/lfs/boot_count" is defined as default parameter in declaration of the constructor. The constructor open the file and the boot count will than be read from file. In case boot count is negative it will be set to 0. Afterwards boot count will be incremented by 1 and stored in file.
Definition at line 62 of file wakeup_cnt.cpp.
References publishMeasCount, and sleepExitCount.
Member Function Documentation
inst()
WakeupCnt * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 43 of file wakeup_cnt.cpp.
Referenced by MetricsBuilder::finalize(), main(), and MqttConnector::task().
init()
void init ()
Definition at line 68 of file wakeup_cnt.cpp.
References FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_read(), FlashFS::inst(), publishMeasCount, sleepExitCount, update(), and WAKEUP_CNT_FILENAME.
Referenced by main().
update()
void update ()
Getter function to retrieve the boot count.
Function returns the private variable boot_count.
Definition at line 110 of file wakeup_cnt.cpp.
References FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_seek(), FlashFS::file_sync(), FlashFS::file_write(), FlashFS::inst(), publishMeasCount, sleepExitCount, and WAKEUP_CNT_FILENAME.
Referenced by incPublishMeasCount(), incSleepExitCount(), and init().
incSleepExitCount()
void incSleepExitCount ()
Definition at line 125 of file wakeup_cnt.cpp.
References sleepExitCount, and update().
Referenced by MqttConnector::task().
incPublishMetricsCount()
void incPublishMetricsCount ()
incPublishMeasCount()
void incPublishMeasCount ()
Definition at line 131 of file wakeup_cnt.cpp.
References publishMeasCount, and update().
Referenced by MqttConnector::task().
getSleepExitCount()
uint32_t getSleepExitCount ()
Definition at line 137 of file wakeup_cnt.cpp.
References sleepExitCount.
getPublishMeasCount()
uint32_t getPublishMeasCount ()
Definition at line 141 of file wakeup_cnt.cpp.
References publishMeasCount.
getLteMeasWakeupCnt()
uint32_t getLteMeasWakeupCnt ()
Definition at line 145 of file wakeup_cnt.cpp.
References publishMeasCount.
getLteWakeupCnt()
uint32_t getLteWakeupCnt ()
Definition at line 149 of file wakeup_cnt.cpp.
References publishMeasCount, and sleepExitCount.
Field Documentation
sleepExitCount
uint32_t sleepExitCount private
Definition at line 64 of file wakeup_cnt.h.
Referenced by getLteWakeupCnt(), getSleepExitCount(), incSleepExitCount(), init(), update(), and WakeupCnt().
publishMeasCount
uint32_t publishMeasCount private
Definition at line 65 of file wakeup_cnt.h.
Referenced by getLteMeasWakeupCnt(), getLteWakeupCnt(), getPublishMeasCount(), incPublishMeasCount(), init(), update(), and WakeupCnt().
The documentation for this class was generated from the following files:
pm/wakeup_cnt.h
pm/wakeup_cnt.cpp