AXO X1: RmsTask Class Reference
RmsTask Class Reference
RMS task class derived from task base class.
#include <rms.h>
Detailed Description
RMS task class derived from task base class.
Detailed Description
The RMS task receives the acceleration raw data from ADXL data store task, calculate RMS and with the help of class HitDetector hit values. RMS, medium and critical hit values will be send to RMS store task together with a timestamp. The class provides an idle detection timer, and for medium and critical hit detection an instance of class HitDetector. It provides the function update_rms to calculate RMS and hit values and to send them to the RMS store task.
Receive
Timer interrupt callback
RMS task (self)
ADXL data store task
Transmit
RMS store task
RMS task (self, transmission in timer callback)
Definition at line 72 of file rms.h.
Public Member Functions
RmsTask (const char *name="??", uint8_t num_seconds=1, uint16_t samples_per_sec=4400)
RMS task constructor.
virtual ~RmsTask ()
RMS storage task destructor.
virtual void task ()
RMS task function.
void init ()
Initialization function for the RMS task.
void update_rms (PoolElem *pElem)
Function to update the RMS and hit values and send result to RMS storage task.
void timer1_expired ()
Timer expired function for the idle detection timer.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the idle detection timer.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Timer * myTimer
Timer used for idle detection.
Mbox * pInMbox
Mailbox of the RMS task.
HitDetector * myDetectorMed
HitDetector * myDetectorCrit
Private Member Functions
RmsTask ()=delete
Private Attributes
uint32_t samples_per_sec
Expected samples per second (sample rate in Hz)
uint32_t n_seconds
Calculated result over n seconds.
uint32_t n_sample
Current sample, range 1..(samples per second)
float x_square_sum
Current sum of x^2.
float y_square_sum
Current sum of y^2.
float z_square_sum
Current sum of z^2.
float x_rms
float y_rms
float z_rms
bool idle
uint32_t rx_cnt
Indicator that we are receiving data.
uint32_t rx_cnt_prev
Previous data count to allow change detection.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
RmsTask() [1/2]
RmsTask (const char * name = "??", uint8_t num_seconds = 1, uint16_t samples_per_sec = 4400) explicit
RMS task constructor.
Parameters
name The name of the class
num_seconds Number of seconds the result shall be calculated
samples_per_sec The sample rate in Hz
The constructor initializes the member variables samples_per_sec and n_seconds with parameter num_seconds and samples_per_sec, the idle flag with true and the variables n_sample, x_square_sum, y_square_sum, z_square_sum, rx_cnt and rx_cnt_prev with 0. It allocate and register a mailbox and allocates and initialize the cyclic idle detection timer with duration of 1 ms and period of 1 ms. Finally it allocates and initialize two instances of the class HitDetector for medium and critical hit detection.
Definition at line 63 of file rms.cpp.
References Mbox::eAdxlRms, myDetectorCrit, myDetectorMed, myTimer, pInMbox, Mbox::registerMbox(), samples_per_sec, and timer_cb().
~RmsTask()
~RmsTask () virtual
RMS storage task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 95 of file rms.cpp.
RmsTask() [2/2]
RmsTask () private delete
Member Function Documentation
task()
void task (void) virtual
RMS task function.
The function directly enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eAdxl37xSensorData: Member function update_rms will be callled to process the received raw data samples from acceleration sensor. Afterwards function checks if RMS task is in idle state, indicated by flag idle. If RMS task is not in idle state receive count rx_cnt will be incremented by 1, the message released back to the pool and the function returns. If RMS task is in idle state, the message is the first data message after sensor wake up. The flag idle will be set to false and the idle detection timer will be started. The power manager task will be informed by sending message eAdxl37xWake from sender eAdxlRms to power manager mailbox, before incrementing rx_cnt and releasing received message to the pool.
eTimerExpired: The pointer pElem will be set to 0, to prevent releasing the message because it is allocated static. The function checks the idle condition, which will be true, if no new data has been received within the last timer period of 1 ms. In this case the flag idle will be set to true, the timer will be stopped and sample task will be informed by sending message eAdxl37xIdle from sender eAdxlRms to eAdxl37xTask mailbox. Finally the function set the previous receive counter rx_cnt_prev to the value of the current receive counter rx_cnt.
eFwUpdateActive: For testing purposes only, print out debug message at warning level.
For more details see also message sequence charts in section Measurement
Implements Task.
Definition at line 315 of file rms.cpp.
References eAdxl37xIdle, eAdxl37xSensorData, eAdxl37xWake, eFwUpdateActive, eTimerExpired, PoolElem::free(), idle, init(), PoolElem::mtype, Task::myName, myTimer, pInMbox, Mbox::read(), rx_cnt, rx_cnt_prev, Mbox::sendMsg(), Timer::start(), Timer::stop(), UNIT_TEST_STOP_LOOP, and update_rms().
init()
void init ()
Initialization function for the RMS task.
The function initializes the private member variables x_square_sum, y_square_sum, z_square_sum and n_sample with 0 and clear medium and critical hit counter by calling the function reset for the two instances of class HitDetector.
Definition at line 139 of file rms.cpp.
References myDetectorCrit, myDetectorMed, n_sample, HitDetector::reset(), x_square_sum, y_square_sum, and z_square_sum.
Referenced by task(), and update_rms().
update_rms()
void update_rms (PoolElem * pElem)
Function to update the RMS and hit values and send result to RMS storage task.
Parameters
pElem Pointer to the received message
The function extracts the acceleration raw data of type struct adxl37x_sensor_value from the payload of the message and enter a loop over the number of raw data samples. In the loop the x, y and z raw values will be converted to micro meter per squared seconds. These calculated values will be powered by 2 and added to the current square sums x_square_sum, y_square_sum and z_square_sum. Afterwards the calculated z-value will be passed into function inpit of the two hit detector instances. If n_sample reached the maximum of samples_per_sec * n_seconds, the final result will be calculated by dividing the square sum values through the number of samples and extracting the root by calling function sqrt for x, y and z axis. The result are the x, y and z RMS values. The number of medium and critical hits will be retrieved by calling the getter function getNumHits for both hit detector instances.
Afterwards a message of type eAdxl37xRmsData with attached structure of type struct adxl_rms_data with the calculated RMS and hit values and a timestamp will be send to RMS store mailbox by calling function sendMsg provided by Mbox class.
After processing of the loop, the function checks if all samples has been processed and in this case the functions returns. Otherwise square sum and maximum values will be set to 0 and the hit counter will be reset by calling member function init before entering a new loop over the remaining raw data samples where again x, y and z raw values will be converted to micro meter per squared seconds, the maximum in x, y and z direction calculated, also powered by 2 and added to the current square sums x_square_sum, y_square_sum and z_square_sum, before sample counter n_sample will be incremented by 1.
Definition at line 180 of file rms.cpp.
References adxl37x_sensor_value::cnt, eAdxl37xRmsData, PoolElem::getBuffer(), HitDetector::getNumHits(), init(), HitDetector::input(), myDetectorCrit, myDetectorMed, n_sample, n_seconds, pow2, adxl37x_sensor_value::samples, samples_per_sec, Mbox::sendMsg(), adxl372_xyz_accel_data::x, x_rms, x_square_sum, adxl372_xyz_accel_data::y, y_rms, y_square_sum, adxl372_xyz_accel_data::z, z_rms, and z_square_sum.
Referenced by task().
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the idle detection timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call MQTT connector timer expired function timer1_expired.
Definition at line 106 of file rms.cpp.
References timer1_expired().
Referenced by RmsTask().
timer1_expired()
void timer1_expired ()
Timer expired function for the idle detection timer.
The function initializes the static pool element e1 with message type eTimerExpired, set eAdxlRms as sender and put message into own (RMS task's) mailbox.
Definition at line 121 of file rms.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
Field Documentation
myTimer
Timer* myTimer
Timer used for idle detection.
Definition at line 84 of file rms.h.
Referenced by RmsTask(), and task().
pInMbox
Mbox* pInMbox
Mailbox of the RMS task.
Definition at line 85 of file rms.h.
Referenced by RmsTask(), task(), and timer1_expired().
myDetectorMed
HitDetector* myDetectorMed
Pointer to instance of class HitDetector for medium hit detection
Definition at line 86 of file rms.h.
Referenced by init(), RmsTask(), and update_rms().
myDetectorCrit
HitDetector* myDetectorCrit
Pointer to instance of class HitDetector for critical hit detection
Definition at line 88 of file rms.h.
Referenced by init(), RmsTask(), and update_rms().
samples_per_sec
uint32_t samples_per_sec private
Expected samples per second (sample rate in Hz)
Definition at line 93 of file rms.h.
Referenced by RmsTask(), and update_rms().
n_seconds
uint32_t n_seconds private
Calculated result over n seconds.
Definition at line 94 of file rms.h.
Referenced by update_rms().
n_sample
uint32_t n_sample private
Current sample, range 1..(samples per second)
Definition at line 95 of file rms.h.
Referenced by init(), and update_rms().
x_square_sum
float x_square_sum private
Current sum of x^2.
Definition at line 96 of file rms.h.
Referenced by init(), and update_rms().
y_square_sum
float y_square_sum private
Current sum of y^2.
Definition at line 97 of file rms.h.
Referenced by init(), and update_rms().
z_square_sum
float z_square_sum private
Current sum of z^2.
Definition at line 98 of file rms.h.
Referenced by init(), and update_rms().
x_rms
float x_rms private
RMS result in longitudinal direction at sample rate (samples per second) processed
Definition at line 100 of file rms.h.
Referenced by update_rms().
y_rms
float y_rms private
RMS result in transversal direction at sample rate (samples per second) processed
Definition at line 102 of file rms.h.
Referenced by update_rms().
z_rms
float z_rms private
RMS result in vertical direction at sample rate (samples per second) processed
Definition at line 104 of file rms.h.
Referenced by update_rms().
idle
bool idle private
Flag indicating, that no data received for more than 1 second
Definition at line 107 of file rms.h.
Referenced by task().
rx_cnt
uint32_t rx_cnt private
Indicator that we are receiving data.
Definition at line 109 of file rms.h.
Referenced by task().
rx_cnt_prev
uint32_t rx_cnt_prev private
Previous data count to allow change detection.
Definition at line 110 of file rms.h.
Referenced by task().
The documentation for this class was generated from the following files:
data/rms.h
data/rms.cpp