AXO X1: FwUpdCtrl Class Reference
FwUpdCtrl Class Reference
Firmware update control task class derived from task base class.
#include <update_ctrl.h>
Detailed Description
Firmware update control task class derived from task base class.
Detailed Description
The firmware update control task implements the logic for handling OTA commands and firmware update confirmation or rejection. Furthermore it manages the retry mechanism for firmware downloads in case of an error. The class provides a Finite State Machine (FSM) for coordinating different stages of the update process, a timer used for delay reboot and download retry interval and functions to start the timer for the different purposes. It provides a function to request a download retry and functions to send JSON strings to the MQTT broker for confirmation and rejection.
Receive
Timer interrupt callback
Firmware update control task (self)
Firmware update task
MQTT connector task
Transmit
Firmware update task
MQTT connector task
Adxl37x task
Firmware update control task (self, transmission in timer callback)
Definition at line 76 of file update_ctrl.h.
Public Member Functions
FwUpdCtrl (const char *name="??")
Firmware update control task constructor.
virtual ~FwUpdCtrl ()
Firmware update control task destructor.
virtual void task (void)
Firmware update control task function.
void timer1_expired ()
Timer expired function of the timer for delay reboot and download retry interval.
void otaStartConfirm ()
Send OTA_START command message to MQTT connector task.
void otaStartReject ()
Send OTA_START reject message to MQTT connector task.
void otaFwConfirm ()
Send firmware confirm message to MQTT connector task.
void otaFwReject ()
Send firmware reject message to MQTT connector task.
void startRebootTimer ()
Function to start one-shot reboot timer.
void startRetryTimer ()
Function to start one-shot retry timer.
void requestDownload ()
Send download request message to firmware update task.
void startTimeout (uint16_t)
Function to start one-shot timer with specified timeout value.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function of the timer for delay reboot and download retry interval.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the firmware update control task.
FwFsm * s1
Pointer to instance of the finite state machine.
Timer * myTimer
Timer used to delay reboot and in download retry interval.
uint16_t retryCnt
Retry counter: Retry attempt on donwload failure.
uint8_t maxRetries
Maximum number of retries.
Private Member Functions
FwUpdCtrl ()=delete
Private Attributes
uint16_t retryTmoCur
Current retry interval.
uint16_t retryTmoInit
Initial retry interval.
uint16_t retryTmoMax
Maximum retry interval.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
FwUpdCtrl() [1/2]
FwUpdCtrl (const char * name = "??") explicit
Firmware update control task constructor.
Parameters
name The name of the class
The constructor initializes the member variables retryCnt and retryTmoCur with 0, maxRetries with 5, retryTmoInit wirh 10 and retryTmoMax with 60. It allocate and register a mailbox and allocates and initialize the timer for delay reboot and download retry interval with a duration of 3 ms. Finally it allocates and initialize a state machine instance of class FwFsm to control the update process.
Definition at line 265 of file update_ctrl.cpp.
References Mbox::eFwUpdCtrl, myTimer, pInMbox, Mbox::registerMbox(), s1, and timer_cb().
~FwUpdCtrl()
~FwUpdCtrl () virtual
Firmware update control task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 292 of file update_ctrl.cpp.
FwUpdCtrl() [2/2]
FwUpdCtrl () private delete
Member Function Documentation
task()
void task (void) virtual
Firmware update control task function.
The function directly enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: The pointer pElem will be set to 0, to prevent releasing the message because it is allocated static. Afterwards handle_timer_exp method of the state machine instance is called.
eOtaStart: Method handle_OtaStart of the state machine instance is called.
eFwInfo: Method handle_FwInfo of the state machine instance is called.
eFwDlSuccess: Method handle_DlComplete of the state machine instance is called.
eFwDlFailed: Method handle_DlFailed of the state machine instance is called.
Implements Task.
Definition at line 316 of file update_ctrl.cpp.
References eFwDlFailed, eFwDlSuccess, eFwInfo, eOtaStart, eTimerExpired, PoolElem::free(), FwFsm::handle_DlComplete(), FwFsm::handle_DlFailed(), FwFsm::handle_FwInfo(), FwFsm::handle_OtaStart(), FwFsm::handle_timer_exp(), PoolElem::mtype, Task::myName, pInMbox, Mbox::read(), s1, and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function of the timer for delay reboot and download retry interval.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call MQTT connector timer expired function timer1_expired.
Definition at line 63 of file update_ctrl.cpp.
References timer1_expired().
Referenced by FwUpdCtrl().
timer1_expired()
void timer1_expired ()
Timer expired function of the timer for delay reboot and download retry interval.
The function initializes the static pool element e1 with message type eTimerExpired, set eFwUpdCtrl as sender and put message into own (Firmware update control task's) mailbox.
Definition at line 79 of file update_ctrl.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
otaStartConfirm()
void otaStartConfirm ()
Send OTA_START command message to MQTT connector task.
The function defines the JSON command string, request a message from message pool, set message type to eOtaStart, set eFwUpdCtrl as sender, copy the command string in the message payload, retrieve a pointer to the mailbox of the MQTT connector task and send message to MQTT connector task's mailbox.
Definition at line 154 of file update_ctrl.cpp.
References eOtaStart, and Mbox::sendMsg().
otaStartReject()
void otaStartReject ()
Send OTA_START reject message to MQTT connector task.
The function defines the JSON command string, append an error code, an error description and a timestamp to the JSON string, request a message from message pool, set message type to eCmdReject, set eFwUpdCtrl as sender, copy the JSON string in the message payload, retrieve a pointer to the mailbox of the MQTT connector task and send message to MQTT connector task's mailbox.
Definition at line 175 of file update_ctrl.cpp.
References eCmdReject, and Mbox::sendMsg().
otaFwConfirm()
void otaFwConfirm ()
Send firmware confirm message to MQTT connector task.
The function defines an empty JSON string, request a message from message pool, set message type to eFwAccept, set eFwUpdCtrl as sender, copy the JSON string in the message payload, retrieve a pointer to the mailbox of the MQTT connector task and send message to MQTT connector task's mailbox.
Definition at line 208 of file update_ctrl.cpp.
References eFwAccept, and Mbox::sendMsg().
otaFwReject()
void otaFwReject ()
Send firmware reject message to MQTT connector task.
The function defines the JSON string with an error code, an error description and a timestamp, request a message from message pool, set message type to eFwReject, set eFwUpdCtrl as sender, copy the JSON string in the message payload, retrieve a pointer to the mailbox of the MQTT connector task and send message to MQTT connector task's mailbox.
Definition at line 229 of file update_ctrl.cpp.
References eFwReject, and Mbox::sendMsg().
startRebootTimer()
void startRebootTimer ()
Function to start one-shot reboot timer.
The function start the one-shot reboot timer with a duration of 3 ms. On timer expiry reboot will be performed.
Definition at line 93 of file update_ctrl.cpp.
References myTimer, and Timer::start().
startRetryTimer()
void startRetryTimer ()
Function to start one-shot retry timer.
The function checks the retry counter, if it is the first retry timeout value is set to initial retry interval, otherwise current retry timeout will be multipied by 2. If current retry timeout is higher than maximum retry interval it will be limited to maximum retry interval. Finally the one-shot retry timer will be started with a duration of current retry timeout and the retry counter will be incremented by one.
Definition at line 108 of file update_ctrl.cpp.
References myTimer, retryCnt, retryTmoCur, retryTmoInit, retryTmoMax, and Timer::start().
requestDownload()
void requestDownload ()
Send download request message to firmware update task.
The function send a message of type eFwDownload, with eFwUpdCtrl as sender to firmware update task by calling function sendMsg provided by class Mbox.
Definition at line 139 of file update_ctrl.cpp.
References eFwDownload, and Mbox::sendMsg().
startTimeout()
void startTimeout (uint16_t timeout)
Function to start one-shot timer with specified timeout value.
Parameters
timeout The specified timeout value
The function start a one-shot reboot timer with a duration of timeout ms.
Definition at line 127 of file update_ctrl.cpp.
References myTimer, and Timer::start().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the firmware update control task.
Definition at line 88 of file update_ctrl.h.
Referenced by FwUpdCtrl(), task(), and timer1_expired().
s1
FwFsm* s1
Pointer to instance of the finite state machine.
Definition at line 89 of file update_ctrl.h.
Referenced by FwUpdCtrl(), and task().
myTimer
Timer* myTimer
Timer used to delay reboot and in download retry interval.
Definition at line 91 of file update_ctrl.h.
Referenced by FwUpdCtrl(), startRebootTimer(), startRetryTimer(), and startTimeout().
retryCnt
uint16_t retryCnt
Retry counter: Retry attempt on donwload failure.
Definition at line 98 of file update_ctrl.h.
Referenced by startRetryTimer().
maxRetries
uint8_t maxRetries
Maximum number of retries.
Definition at line 99 of file update_ctrl.h.
Referenced by FwDownload::handle_timer_exp().
retryTmoCur
uint16_t retryTmoCur private
Current retry interval.
Definition at line 104 of file update_ctrl.h.
Referenced by startRetryTimer().
retryTmoInit
uint16_t retryTmoInit private
Initial retry interval.
Definition at line 105 of file update_ctrl.h.
Referenced by startRetryTimer().
retryTmoMax
uint16_t retryTmoMax private
Maximum retry interval.
Definition at line 106 of file update_ctrl.h.
Referenced by startRetryTimer().
The documentation for this class was generated from the following files:
update/update_ctrl.h
update/update_ctrl.cpp