AXO X1: spibus Class Reference
spibus Class Reference
SPI bus driver class implemented according to C++ singleton design pattern.
#include <spibus.h>
Detailed Description
SPI bus driver class implemented according to C++ singleton design pattern.
Detailed Description
The SPI bus class handles the initialization of the attached SPI slave and the communication over the SPI bus. Major part of configuration and initialization is located in the device tree, other parts are located in the init function of this class. storage of the acceleration raw See details in Device Driver Model documentation and in API documentation
The spibus class provides the init method.
Definition at line 83 of file spibus.h.
Public Member Functions
~spibus ()
SPI bus class destructor.
void init ()
The init function.
const struct device * getController ()
struct spi_config * getConfig ()
Static Public Member Functions
static spibus * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Data Fields
const struct device * spi_dev
SPI controller device structure.
struct spi_config spi_cfg
SPI controller configuration structure.
struct spi_cs_control cs_ctrl
SPI Chip Select control.
Private Member Functions
spibus ()
SPI bus class constructor.
Private Attributes
bool init_done
Flag indicating that the initalization has been done.
bool device_good
Constructor & Destructor Documentation
~spibus()
~spibus ()
SPI bus class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 104 of file spibus.cpp.
spibus()
spibus () private
SPI bus class constructor.
The constructor simply triggers a debug message on info debug level.
Definition at line 96 of file spibus.cpp.
Member Function Documentation
inst()
spibus * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 85 of file spibus.cpp.
Referenced by spifram::init(), spimram::init(), and AdxlDataStore::task().
init()
void init ()
The init function.
In case initialization still has been performed, indicated by flag init_done the function returns immediately, otherwise chip select gpios will be assigned by call of macro GPIO_DT_SPEC_GET and delay set to 0. The SPI controller device structure will be retrieved by calling macro DEVICE_DT_GET and function checks if the device is ready for usage with call of function device_is_ready. The return value of this function will be assigned to flag device_good. In case of an error a debug message at error level will be printed. Finally operation mode is set to loop mode, clock frequency is set to 8 MHz and chip select configuration is assigned before init_done flag is set to true.
Note
Adjustment of clock frequency for FRAM SPI is done here with line spi_cfg.frequency = 8000000U; The value must be unsigned integer in Hz.
Definition at line 52 of file spibus.cpp.
References cs_ctrl, device_good, init_done, spi_cfg, and spi_dev.
Referenced by spifram::init(), spimram::init(), and AdxlDataStore::task().
getController()
const struct device* getController () inline
Definition at line 89 of file spibus.h.
References spi_dev.
Referenced by spifram::init(), and spimram::init().
getConfig()
struct spi_config* getConfig () inline
Definition at line 90 of file spibus.h.
References spi_cfg.
Referenced by spifram::init(), and spimram::init().
Field Documentation
spi_dev
const struct device* spi_dev
SPI controller device structure.
Definition at line 92 of file spibus.h.
Referenced by getController(), and init().
spi_cfg
struct spi_config spi_cfg
SPI controller configuration structure.
Definition at line 92 of file spibus.h.
Referenced by getConfig(), and init().
cs_ctrl
struct spi_cs_control cs_ctrl
SPI Chip Select control.
Definition at line 92 of file spibus.h.
Referenced by init().
init_done
bool init_done private
Flag indicating that the initalization has been done.
Definition at line 98 of file spibus.h.
Referenced by init().
device_good
bool device_good private
Flag indicating that hardware initalization was successful
Definition at line 99 of file spibus.h.
Referenced by init().
The documentation for this class was generated from the following files:
bus/spi/spibus.h
bus/spi/spibus.cpp