AXO X1: MetricsBuilder Class Reference
MetricsBuilder Class Reference
Metrics builder helper class.
#include <metric.h>
Detailed Description
Metrics builder helper class.
Detailed Description
The metrics builder helper class provides methods to create the metrics JSON string, which will be send via LTE with topic /device/DEVICE_ID/metric/update to the MQTT broker.
Definition at line 49 of file metric.h.
Public Member Functions
MetricsBuilder ()
Metric builder constructor.
~MetricsBuilder ()
Metric builder destructor.
void addModemTemp (PoolElem *pElem)
Add function to append modem temeperature to metrics JSON string.
void addModemBattV (PoolElem *pElem)
Add function to append modem battery voltage to metrics JSON string.
void addModemLinkQuality (PoolElem *pElem)
Add function to append modem link quality to metrics JSON string.
void addModemPsmAct (PoolElem *pElem)
Add function to append modem battery voltage to metrics JSON string.
void addIMSI (PoolElem *pElem)
Add function to append modem DRX to metrics JSON string.
void addResetCause (PoolElem *pElem)
Add function to append reset cause to metrics JSON string.
void addBootCnt (PoolElem *pElem)
Add function to append boot counter to metrics JSON string.
void addBattV (PoolElem *pElem)
void addTemperature (PoolElem *pElem)
Add function to append temperature of external sensor to metrics JSON string.
void addHumidity (PoolElem *pElem)
Add function to append humidity of external sensor to metrics JSON string.
void addHwMetrics (PoolElem *pElem)
Add function to append HW status information to metrics JSON string.
void add (PoolElem *pElem)
Add function to append prepared metrics data to the metrics JSON string.
void setConfigVersion (std::string &s)
Setter function to set private string variable config_version.
void setActivationThres (std::string &s)
Setter function to set private string variable act_thres.
void setDeactivationThres (std::string &s)
Setter function to set private string variable deact_thres.
void setDispModeOffFlag (std::string &s)
Setter function to set private string variable disp_mode_off.
void setRawTransferOnFlag (std::string &s)
Setter function to set private string variable raw_transfer_on.
void setDispTransferOnFlag (std::string &s)
Setter function to set private string variable disp_transfer_on.
void setPublicKey (std::string &s)
Setter function to set private string variable pubkey.
void setMetricsInterval (std::string &s)
Setter function to set Metrics transmission interval.
void set_Z_RmsThres (std::string &s)
Setter function to set private string variable raw_thres.
void set_max_raw_per_day (std::string &s)
Setter function to set private string variable max_raw_per_day.
int scaleBattIn (int32_t ad_in)
Scaling of incoming battery voltage from AD converter.
void finalize (void)
Function to finalize the metrics JSON string.
void reset ()
Function clear all private string variables related to metrics JSON string.
bool isComplete ()
isComplete function to check if the metrics JSON string is completly filled
void print (void)
Print function to output the metrics JSON string.
std::string & getPayload (void)
Getter function to retrieve the metrics JSON string.
Private Member Functions
MetricsBuilder (const MetricsBuilder &)=delete
MetricsBuilder & operator= (const MetricsBuilder &)=delete
Private Attributes
std::string reset_cause
std::string vbat1
Battery Voltage 1 [mV] V = mV * (10 + 4.7) / 4.7.
std::string vbat2
Battery Voltage 2 [mV] V = mV * (10 + 4.7) / 4.7.
std::string vdd_det
[mV] VDD dectection V = mV * (10 + 4.7) / 4.7
std::string vdd_int
[mV] internal ADC VDD
std::string mdm_batv
[mV]
std::string mdm_temp
[degrees celsius]
std::string mdm_link
[dBm]
std::string psm_tau
[sec]
std::string psm_active
[sec]
std::string edrx_time
[sec]
std::string edrx_ptw
[sec]
std::string uptime
[msec]
std::string heap_free
[bytes]
std::string heap_used
[bytes]
std::string heap_max_used
[bytes]
std::string payload
the metrics JSON string
std::string temperature
external sensor [degrees celsius]
std::string humidity
external sensor [RH]
std::string imsi
15-digit IMSI number
std::string boot_cnt
the boot count
std::string num_hw_errors
The counted HW errors.
std::string adxl_status
The error status of the acceleration sensor.
std::string config_version
Version of the configuration.
std::string act_thres
Activation threshold for ADXL37x sensor.
std::string deact_thres
std::string disp_mode_off
Flag indicating that displacement calculation is disabled (15 sec raw data storage)
std::string raw_transfer_on
Flag indicating that raw data transfer to backend is enabled.
std::string disp_transfer_on
Flag indicating that displacement data transfer to backend is enabled.
std::string pubkey
Pulic key for raw and displacement data transfer to backend.
std::string interval
std::string rms_thres
std::string max_raw_per_day
Maximum raw data transmissions per day.
Constructor & Destructor Documentation
MetricsBuilder() [1/2]
MetricsBuilder ()
Metric builder constructor.
The constructor initiates the private variable payload, representing the metrics JSON string with opening curly bracket.
Definition at line 79 of file metric.cpp.
~MetricsBuilder()
~MetricsBuilder ()
Metric builder destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 90 of file metric.cpp.
MetricsBuilder() [2/2]
MetricsBuilder (const MetricsBuilder &) private delete
Member Function Documentation
addModemTemp()
void addModemTemp (PoolElem * pElem)
Add function to append modem temeperature to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to 32 bit integer value, converted to a string and stored in private member variable mdm_temp. Writing the variable value into JSON string is part of member function finalize.
Definition at line 370 of file metric.cpp.
References PoolElem::getBuffer(), and mdm_temp.
Referenced by add().
addModemBattV()
void addModemBattV (PoolElem * pElem)
Add function to append modem battery voltage to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to 32 bit integer value, converted to a string and stored in private member variable mdm_batv. Writing the variable value into JSON string is part of member function finalize.
Definition at line 126 of file metric.cpp.
References PoolElem::getBuffer(), and mdm_batv.
Referenced by add().
addModemLinkQuality()
void addModemLinkQuality (PoolElem * pElem)
Add function to append modem link quality to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, converted to a string and stored in private member variable mdm_link. Writing the variable value into JSON string is part of member function finalize.
Definition at line 387 of file metric.cpp.
References mdm_link, and PoolElem::p2.
Referenced by add().
addModemPsmAct()
void addModemPsmAct (PoolElem * pElem)
Add function to append modem battery voltage to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure psm_timer and stored in local varaible psm_act. The variable psm_act->tau will be converted to a string and stored in private member variable psm_tau. The variable psm_act->active_time will be converted to a string and stored in private member variable psm_active. Writing the variable value into JSON string is part of member function finalize.
Definition at line 405 of file metric.cpp.
References psm_timer::active_time, PoolElem::getBuffer(), psm_active, psm_tau, and psm_timer::tau.
Referenced by add().
addIMSI()
void addIMSI (PoolElem * pElem)
Add function to append modem DRX to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure lte_lc_edrx_cfg and stored in local varaible eDRX. The variable eDRX->edrx will be converted to a string and stored in private member variable edrx_time. The variable eDRX->ptw will be converted to a string and stored in private member variable edrx_ptw. Writing the variable value into JSON string is part of member function finalize.
NOT USED
Add function to append IMSI to metrics JSON string
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, converted to a string and stored in private member variable imsi. Writing the variable value into JSON string is part of member function finalize.
Definition at line 478 of file metric.cpp.
References PoolElem::getBuffer(), and imsi.
Referenced by add().
addResetCause()
void addResetCause (PoolElem * pElem)
Add function to append reset cause to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, converted to a string and stored in private member variable reset_cause. Writing the variable value into JSON string is part of member function finalize.
Definition at line 493 of file metric.cpp.
References PoolElem::getBuffer(), and reset_cause.
Referenced by add().
addBootCnt()
void addBootCnt (PoolElem * pElem)
Add function to append boot counter to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to 32 bit integer value, converted to a string and stored in private member variable boot_cnt. Writing the variable value into JSON string is part of member function finalize.
Definition at line 508 of file metric.cpp.
References boot_cnt, and PoolElem::getBuffer().
Referenced by add().
addBattV()
void addBattV (PoolElem * pElem)
Referenced by add().
addTemperature()
void addTemperature (PoolElem * pElem)
Add function to append temperature of external sensor to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure sensor_value and stored in local varaible val. The variable val will be converted to a float value by calling function sensor_value_to_double, converted to a string and stored in private member variable temperature. Writing the variable value into JSON string is part of member function finalize.
Definition at line 527 of file metric.cpp.
References PoolElem::getBuffer(), and temperature.
Referenced by add().
addHumidity()
void addHumidity (PoolElem * pElem)
Add function to append humidity of external sensor to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure sensor_value and stored in local varaible val. The variable val will be converted to a float value by calling function sensor_value_to_double, converted to a string and stored in private member variable humidity. Writing the variable value into JSON string is part of member function finalize.
Definition at line 552 of file metric.cpp.
References PoolElem::getBuffer(), and humidity.
Referenced by add().
addHwMetrics()
void addHwMetrics (PoolElem * pElem)
Add function to append HW status information to metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
The message payload will be extracted, casted to structure hw_metrics and stored in local varaible hw_m. The variable hw_m-> num_errors will be converted to a string and stored in private member variable num_hw_errors. The variable hw_m->hw_status will be will be checked if the value is enumeration eHwOK. In this case the the string "adxl37x_ok" will be assigned to private member variable adxl_status. If the value is not eHwOK, the string "adxl37x_fail" will be assigned to private member variable adxl_status. Writing the variable value into JSON string is part of member function finalize.
Definition at line 430 of file metric.cpp.
References adxl_status, eHwOK, eHwSelftestFailed, PoolElem::getBuffer(), hw_metrics::hw_status, hw_metrics::num_errors, and num_hw_errors.
Referenced by add().
add()
void add (PoolElem * pElem)
Add function to append prepared metrics data to the metrics JSON string.
Parameters
pElem Pointer to the received message (pool element)
According to the message type of the message one of the specific add functions of the class will be called.
Definition at line 574 of file metric.cpp.
References addBattV(), addBootCnt(), addHumidity(), addHwMetrics(), addIMSI(), addModemBattV(), addModemLinkQuality(), addModemPsmAct(), addModemTemp(), addResetCause(), addTemperature(), eAdcData, eBootCnt, eHwMetrics, eLteBattVoltage, eLteFwVersion, eLteIMSI, eLteLinkQuality, eLtePsmAct, eLteTemperature, eResetCause, eShtcxHumidity, eShtcxTemperature, and PoolElem::mtype.
Referenced by DataManager::task().
setConfigVersion()
void setConfigVersion (std::string & s)
Setter function to set private string variable config_version.
Parameters
s The string to be set
The function set the private string variable config_version to value of parameter s.
Definition at line 159 of file metric.cpp.
References config_version.
Referenced by DataManager::configure().
setActivationThres()
void setActivationThres (std::string & s)
Setter function to set private string variable act_thres.
Parameters
s The string to be set
The function set the private string variable act_thres to value of parameter s.
Definition at line 171 of file metric.cpp.
References act_thres.
Referenced by DataManager::configure().
setDeactivationThres()
void setDeactivationThres (std::string & s)
Setter function to set private string variable deact_thres.
Parameters
s The string to be set
The function set the private string variable deact_thres to value of parameter s.
Definition at line 183 of file metric.cpp.
References deact_thres.
Referenced by DataManager::configure().
setDispModeOffFlag()
void setDispModeOffFlag (std::string & s)
Setter function to set private string variable disp_mode_off.
Parameters
s The string to be set
The function set the private string variable disp_mode_off to value of parameter s.
Definition at line 195 of file metric.cpp.
References disp_mode_off.
Referenced by DataManager::configure().
setRawTransferOnFlag()
void setRawTransferOnFlag (std::string & s)
Setter function to set private string variable raw_transfer_on.
Parameters
s The string to be set
The function set the private string variable raw_transfer_on to value of parameter s.
Definition at line 207 of file metric.cpp.
References raw_transfer_on.
Referenced by DataManager::configure().
setDispTransferOnFlag()
void setDispTransferOnFlag (std::string & s)
Setter function to set private string variable disp_transfer_on.
Parameters
s The string to be set
The function set the private string variable disp_transfer_on to value of parameter s.
Definition at line 219 of file metric.cpp.
References disp_transfer_on.
Referenced by DataManager::configure().
setPublicKey()
void setPublicKey (std::string & s)
Setter function to set private string variable pubkey.
Parameters
s The string to be set
The function set the private string variable pubkey to value of parameter s.
Definition at line 231 of file metric.cpp.
References pubkey.
Referenced by DataManager::configure().
setMetricsInterval()
void setMetricsInterval (std::string & s)
Setter function to set Metrics transmission interval.
Parameters
s The string to be set
The function set the private string variable interval to value of parameter s.
Definition at line 243 of file metric.cpp.
References interval.
Referenced by DataManager::configure().
set_Z_RmsThres()
void set_Z_RmsThres (std::string & s)
Setter function to set private string variable raw_thres.
Parameters
s The string to be set
The function set the private string variable raw_thres to value of parameter s.
Definition at line 255 of file metric.cpp.
References rms_thres.
Referenced by DataManager::configure().
set_max_raw_per_day()
void set_max_raw_per_day (std::string & s)
Setter function to set private string variable max_raw_per_day.
Parameters
s The string to be set
The function set the private string variable max_raw_per_day to value of parameter s.
Definition at line 267 of file metric.cpp.
References max_raw_per_day.
Referenced by DataManager::configure().
scaleBattIn()
int scaleBattIn (int32_t ad_in)
Scaling of incoming battery voltage from AD converter.
Parameters
ad_in incoming battery voltage from AD converter
Returns
returns the scaled battery voltage
The function scales the incoming battery voltage from AD converter with following formula:
res = ad_in * VOLTAGE_DIVIDER_FACTOR
Result will be casted to 32 bit integer and returned
Definition at line 145 of file metric.cpp.
finalize()
void finalize (void)
Function to finalize the metrics JSON string.
The function retrieves the current system uptime by calling function k_uptime_get and convert it to seconds. Then the key value pairs will be appended to private string variable payload, which represents the metrics JSON string. Finally the metrics JSON string will be terminated with closing curly bracket.
Definition at line 640 of file metric.cpp.
References act_thres, adxl_status, BOOST_ENABLED_FILENAME, boot_cnt, config_version, deact_thres, disp_mode_off, disp_transfer_on, getFwVersion(), humidity, imsi, FlashFS::inst(), interval, max_raw_per_day, mdm_batv, mdm_link, mdm_temp, num_hw_errors, psm_active, psm_tau, pubkey, raw_transfer_on, reset_cause, rms_thres, temperature, vbat1, vbat2, and vdd_det.
Referenced by DataManager::task().
reset()
void reset ()
Function clear all private string variables related to metrics JSON string.
The function clear all private string variables related to metrics JSON string, except mdm_link and psm_tau, because there will be no update if the if values remains stable. Variable payload will be reinitializes with opening curly bracket.
Definition at line 736 of file metric.cpp.
References humidity, mdm_batv, mdm_temp, temperature, vbat1, vbat2, vdd_det, and vdd_int.
Referenced by DataManager::task().
isComplete()
bool isComplete ()
isComplete function to check if the metrics JSON string is completly filled
Returns
returns true if metrics JSON string is complete, false otherwise
The function checks if the metrics JSON string is completly filled and all metrics data is present. Therefor it checks if battery voltage, temperature and internal supply voltage is present by checking taht size is greater than 0. Firthermore it checks the size of LTE temperature and humidity. Other requested metrics will not be checked. Here the implcit knowledge that LTE temperature and humidity request are the last requests, so that every other requested data still must be received.
Attention
Changing the order of requested metrics information can result in lost of metrics data.
Definition at line 108 of file metric.cpp.
References humidity, mdm_batv, mdm_temp, temperature, and vdd_int.
Referenced by DataManager::task().
print()
void print (void)
Print function to output the metrics JSON string.
The function prints the private string variable payload, using debug message with debug level INFO.
Definition at line 722 of file metric.cpp.
Referenced by DataManager::task().
getPayload()
std::string & getPayload (void)
Getter function to retrieve the metrics JSON string.
Returns
Returns the private string variable payload
The function returns the private string variable payload, which represents the metrics JSON string.
Definition at line 711 of file metric.cpp.
References payload.
Referenced by DataManager::publishMetrics().
operator=()
MetricsBuilder& operator= (const MetricsBuilder &) private delete
Field Documentation
reset_cause
std::string reset_cause private
Reset cause string "POR"|"PIN"|"WDT"|"SWR"|"LCK"|"OFF"|"DBG"
Definition at line 91 of file metric.h.
Referenced by addResetCause(), and finalize().
vbat1
std::string vbat1 private
Battery Voltage 1 [mV] V = mV * (10 + 4.7) / 4.7.
Definition at line 93 of file metric.h.
Referenced by finalize(), and reset().
vbat2
std::string vbat2 private
Battery Voltage 2 [mV] V = mV * (10 + 4.7) / 4.7.
Definition at line 94 of file metric.h.
Referenced by finalize(), and reset().
vdd_det
std::string vdd_det private
[mV] VDD dectection V = mV * (10 + 4.7) / 4.7
Definition at line 95 of file metric.h.
Referenced by finalize(), and reset().
vdd_int
std::string vdd_int private
[mV] internal ADC VDD
Definition at line 96 of file metric.h.
Referenced by isComplete(), and reset().
mdm_batv
std::string mdm_batv private
[mV]
Definition at line 97 of file metric.h.
Referenced by addModemBattV(), finalize(), isComplete(), and reset().
mdm_temp
std::string mdm_temp private
[degrees celsius]
Definition at line 98 of file metric.h.
Referenced by addModemTemp(), finalize(), isComplete(), and reset().
mdm_link
std::string mdm_link private
[dBm]
Definition at line 99 of file metric.h.
Referenced by addModemLinkQuality(), and finalize().
psm_tau
std::string psm_tau private
[sec]
Definition at line 100 of file metric.h.
Referenced by addModemPsmAct(), and finalize().
psm_active
std::string psm_active private
[sec]
Definition at line 101 of file metric.h.
Referenced by addModemPsmAct(), and finalize().
edrx_time
std::string edrx_time private
[sec]
Definition at line 102 of file metric.h.
edrx_ptw
std::string edrx_ptw private
[sec]
Definition at line 103 of file metric.h.
uptime
std::string uptime private
[msec]
Definition at line 104 of file metric.h.
heap_free
std::string heap_free private
[bytes]
Definition at line 105 of file metric.h.
heap_used
std::string heap_used private
[bytes]
Definition at line 106 of file metric.h.
heap_max_used
std::string heap_max_used private
[bytes]
Definition at line 107 of file metric.h.
payload
std::string payload private
the metrics JSON string
Definition at line 108 of file metric.h.
Referenced by getPayload().
temperature
std::string temperature private
external sensor [degrees celsius]
Definition at line 109 of file metric.h.
Referenced by addTemperature(), finalize(), isComplete(), and reset().
humidity
std::string humidity private
external sensor [RH]
Definition at line 110 of file metric.h.
Referenced by addHumidity(), finalize(), isComplete(), and reset().
imsi
std::string imsi private
15-digit IMSI number
Definition at line 111 of file metric.h.
Referenced by addIMSI(), and finalize().
boot_cnt
std::string boot_cnt private
the boot count
Definition at line 112 of file metric.h.
Referenced by addBootCnt(), and finalize().
num_hw_errors
std::string num_hw_errors private
The counted HW errors.
Definition at line 113 of file metric.h.
Referenced by addHwMetrics(), and finalize().
adxl_status
std::string adxl_status private
The error status of the acceleration sensor.
Definition at line 114 of file metric.h.
Referenced by addHwMetrics(), and finalize().
config_version
std::string config_version private
Version of the configuration.
Definition at line 115 of file metric.h.
Referenced by finalize(), and setConfigVersion().
act_thres
std::string act_thres private
Activation threshold for ADXL37x sensor.
Definition at line 116 of file metric.h.
Referenced by finalize(), and setActivationThres().
deact_thres
std::string deact_thres private
Deactivation threshold for ADXL37x sensor
Definition at line 117 of file metric.h.
Referenced by finalize(), and setDeactivationThres().
disp_mode_off
std::string disp_mode_off private
Flag indicating that displacement calculation is disabled (15 sec raw data storage)
Definition at line 119 of file metric.h.
Referenced by finalize(), and setDispModeOffFlag().
raw_transfer_on
std::string raw_transfer_on private
Flag indicating that raw data transfer to backend is enabled.
Definition at line 121 of file metric.h.
Referenced by finalize(), and setRawTransferOnFlag().
disp_transfer_on
std::string disp_transfer_on private
Flag indicating that displacement data transfer to backend is enabled.
Definition at line 123 of file metric.h.
Referenced by finalize(), and setDispTransferOnFlag().
pubkey
std::string pubkey private
Pulic key for raw and displacement data transfer to backend.
Definition at line 125 of file metric.h.
Referenced by finalize(), and setPublicKey().
interval
std::string interval private
Metrics transmission interval
Definition at line 126 of file metric.h.
Referenced by finalize(), and setMetricsInterval().
rms_thres
std::string rms_thres private
Activation threshold for displacement calculation and raw/displacement data transmission
Definition at line 129 of file metric.h.
Referenced by finalize(), and set_Z_RmsThres().
max_raw_per_day
std::string max_raw_per_day private
Maximum raw data transmissions per day.
Definition at line 130 of file metric.h.
Referenced by finalize(), and set_max_raw_per_day().
The documentation for this class was generated from the following files:
data/metric.h
data/metric.cpp