AXO X1: BatteryMgr Class Reference
BatteryMgr Class Reference
Battery manager class derived from task base class.
#include <batt_mgr.h>
Detailed Description
Battery manager class derived from task base class.
Detailed Description
The Battery manager task received report requests from power manager, which trigger an ADC request from battery manager to AD converter task. The measured values will than received from AD converter task, which send them to data manager task. There they will be added to metrics JSON string. See also Message Sequence Chart Cyclic Metrics.
The AD converter class provides methods specify the ADC channels used for battery management, to retrieve the specified ADC channels and to request an report with measured values from AD converter task. Message Interaction:
Receive
Power manager task
Transmit
AD converter task
Data manager task
Definition at line 64 of file batt_mgr.h.
Public Member Functions
BatteryMgr (const char *name="??")
Battery manager task constructor.
BatteryMgr ()=delete
virtual ~BatteryMgr ()
Battery manager task destructor.
void task (void) override
Battery manager task function.
uint8_t getAdcChannels ()
void setAdcChannels (uint8_t chmask)
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Data Fields
Mbox * pInMbox
Mailbox of the battery manager task.
Private Member Functions
void reqAdcReport (uint8_t chmask)
Request ADC report of battery channels from AD converter task.
Private Attributes
uint8_t adcChannels
Additional Inherited Members
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
BatteryMgr() [1/2]
BatteryMgr (const char * name = "??") explicit
Battery manager task constructor.
Parameters
name The name of the class
The constructor allocate and register the mailbox of the battery manager task. Finally the ADC channels responsible for battery management are specified and stored in channel bitmask adcChannels.
Definition at line 46 of file batt_mgr.cpp.
References adcChannels, Mbox::eBattMgr, pInMbox, and Mbox::registerMbox().
BatteryMgr() [2/2]
BatteryMgr () delete
~BatteryMgr()
~BatteryMgr () virtual
Battery manager task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 78 of file batt_mgr.cpp.
Member Function Documentation
task()
void task (void) override virtual
Battery manager task function.
The function enters directly the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: Unused, only debug message at debug level will be printed.
eAdcData: Received sensor data from AD converter task. Will forward as it is to data manager task mailbox.
eBattReport: Received report request frm power manager task. Battery manager request than an ADC report for the related ADC channels from AD converter task by calling member function reqAdcReport.
Todo:
should be deleted: Battery manager not uses timers
Implements Task.
Definition at line 114 of file batt_mgr.cpp.
References adcChannels, ADInput::channel, eAdcData, eBattReport, Mbox::eDataManager, eTimerExpired, PoolElem::free(), PoolElem::getBuffer(), PoolElem::mtype, ADInput::mv, Task::myName, pInMbox, ADInput::raw, Mbox::read(), reqAdcReport(), Mbox::send(), and UNIT_TEST_STOP_LOOP.
getAdcChannels()
uint8_t getAdcChannels () inline
Definition at line 71 of file batt_mgr.h.
References adcChannels.
Referenced by main().
setAdcChannels()
void setAdcChannels (uint8_t chmask) inline
Definition at line 72 of file batt_mgr.h.
References adcChannels.
reqAdcReport()
void reqAdcReport (uint8_t chmask) private
Request ADC report of battery channels from AD converter task.
Parameters
chmask The channel bitmask, specifying the channels which shall be sampled
The function send a message of type eAdcReport with attached channel bitmask to AD converter mailbox by calling function sendMsg provided by Mbox class.
Definition at line 90 of file batt_mgr.cpp.
References eAdcReport, and Mbox::sendMsg().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the battery manager task.
Definition at line 70 of file batt_mgr.h.
Referenced by BatteryMgr(), main(), and task().
adcChannels
uint8_t adcChannels private
The channel bitmask specifying the ADC channels used for battery management
Definition at line 76 of file batt_mgr.h.
Referenced by BatteryMgr(), getAdcChannels(), setAdcChannels(), and task().
The documentation for this class was generated from the following files:
drv/adc/batt_mgr.h
drv/adc/batt_mgr.cpp