AXO X1: Config Class Reference
Config Class Reference
Configuration class implemented according to C++ singleton design pattern.
#include <config.h>
Detailed Description
Configuration class implemented according to C++ singleton design pattern.
Detailed Description
The Config class handle the dynamic configuration of the AXO device basecd on a JSON configuration file located at the Jovia server. For each AXO device one configuration file is present on the server. On changing the content of the configuration file the server send the configuration via MQTT topic /device/{device_id}/config/update to the device if it is connected via LTE. On receiving the configuration, the device check if the configuration is valid and in this case store the new configuration in file system under /lfs/config.json and perform a reset.
On startup the device read the configuration file and provide the configuration values to the related modules in defined configuration structures. In case no configuration file is available in file system, the device store a default configuration before reading.
The config class uses the cJSON library, which is part of the Zephyr delivery.
The class provides methods for initialization of the class instance, to read the configuration file from file system, to parse the configuration JSON string into configuration structures, to print the JSON string, to retrieve group and key existence and the number of group entries and to get a specific configuration value. Furthermore it provides getter functions to retrieve every singe configuration structure.
Definition at line 229 of file config.h.
Public Member Functions
void init ()
Initialization function of the Config class.
int loadFromFile (std::string &CfgDefault)
Function to read JSON file into input string.
int parse (struct cJSON **jsonObj, std::string &jsonStr)
Function to parse a JSON configuration string.
void dump ()
Function to print the JSON string.
int save ()
Function to write object representation from memory to input string.
int saveToFile ()
Function to store JSON configuration string in file system.
int saveToFile (std::string config)
Function to store JSON configuration string in file system.
void parseAllValues ()
Function copy all configuration values in the provided configuration structures.
bool groupExists (struct cJSON *jsonObj, std::string group)
Function to check if a group with given name exist in JSON object.
int getGroupEntries (std::string group)
Function to retrieve the number of items in a JSON group object.
bool keyExists (struct cJSON *jsonObj, std::string group, int index, std::string key)
Function to check if a key with given name exist in given group in the JSON object.
std::string getValue (std::string group, int index, std::string key)
Function to retrieve a single value from a JSON group object.
std::string getValue (struct cJSON *jsonObj, std::string group, int index, std::string key)
Function to retrieve a single value from a JSON group object.
int setValue (std::string group, int index, std::string key, std::string val)
Function to store a single value in a JSON group object.
int setValue (struct cJSON *jsonObj, std::string group, int index, std::string key, std::string val)
Function to store a single value in a JSON group object.
bool isValid (const char *buf)
Function to check if a received configuration is valid.
void Autocorrection ()
Function to automatically correct invalid configuration values.
virtual ~Config ()
Config class destructor.
Config (const Config &)=delete
Config & operator= (const Config &)=delete
stCfgGeneral * getCfgGeneral ()
Getter function to retrieve the configuration structure of the general group.
stCfgMetrics * getCfgMetrics ()
Getter function to retrieve the configuration structure of the metrics group.
stCfgDatalog * getCfgDatalog ()
Getter function to retrieve the configuration structure of the datalog group.
stCfgDisplacement * getCfgDisplacement ()
Getter function to retrieve the configuration structure of the displacement group.
stCfgSensor * getCfgSensor (enCfgSensorId id)
Getter function to retrieve the configuration structure of a sensor.
unsigned char * getConfigJson ()
Function to retrieve the configuration in JSON format.
void deleteConfigFile ()
Function to delete configuration file.
Static Public Member Functions
static Config * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
Config ()
Config class constructor.
int getArraySize (struct cJSON *array_obj)
Function to retrieve the array size of a JSON object.
bool isVersionValid (struct cJSON *jsonObj)
Function to check if the version is valid.
void mergeConfig (struct cJSON *rootObj, struct cJSON *loadObj)
Function to merge existing configuration values in file system into the current JSON structure.
bool areValuesStrings (std::string group)
Function to check if the values in a group are strings.
bool strIsInt (std::string &strInput)
Function to check if a string contains a valid integer string.
bool strIsFloat (std::string &strInput)
Function to check if a string contains a valid floating point number string.
bool strIsBool (std::string &strInput)
Function to check if a string contains a valid boolean string.
Private Attributes
std::string input
The content of the JSON config file.
struct cJSON * root_obj
The JSON root object.
stCfgGeneral cfgGeneral
Instance of general related configuration.
stCfgMetrics cfgMetrics
Instance of metrics related configuration.
stCfgDatalog cfgDatalog
stCfgDisplacement cfgDisplacement
Instance of displacement related configuration.
stCfgSensor cfgSensor [eSensor_MAX]
Instance of sensor related configuration.
Constructor & Destructor Documentation
~Config()
~Config () virtual
Config class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on debug level.
Definition at line 95 of file config.cpp.
Config() [1/2]
Config (const Config &) delete
Config() [2/2]
Config () private
Config class constructor.
The constructor simply triggers a debug message on debug level.
Definition at line 85 of file config.cpp.
Member Function Documentation
inst()
Config * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 74 of file config.cpp.
Referenced by AdxlDataStore::configure(), DataManager::configure(), DispTask::configure(), Adxl37x::configure(), HttpConnector::configure(), MqttConnector::configure(), PowerMgr::configure(), MqttConnector::HandleFactoryDefault(), MqttConnector::HandleGetConfig(), MqttConnector::HandleNewConfiguration(), and main().
init()
void init ()
Initialization function of the Config class.
The method define the default configuration as string, replaces the dummy entries in the default configuration, load the JSON configuration file from the file system and extract the the JSON string and store it in member variable input by calling member function loadFromFile. Afterwards the member function parse is called to retrieve a JSON root object from input string and store it in variable load_obj. Than the function checks if the loaded configuration is compatible to the version and structure of the default configuration by call of function isVersionValid. If compatible member function parse is called again to retrieve a JSON root object from input string and store it in member variable root_obj for further processing. Otherwise the default configuration string will be parssed in member variable root_obj and all existing configuration values from loaded configuration will be taken over from loaded configuration in variable load_obj in default configuration in member variable root_obj by call of member function mergeConfig and the default configuration than will be stored in file system by call of function saveToFile. Finally, by call of the member function parseAllValues the configuration values will be
extracted and stored into the provided configuration structures.
Definition at line 1362 of file config.cpp.
References CONFIG_ACCEL_SENS_NAME, CONFIG_ACCEL_SENS_TYPE, CONFIG_DEVICE_NAME, CONFIG_DEVICE_TYPE, CONFIG_VERSION, groupExists(), input, isVersionValid(), loadFromFile(), mergeConfig(), parse(), parseAllValues(), root_obj, and saveToFile().
Referenced by main().
loadFromFile()
int loadFromFile (std::string & CfgDefault)
Function to read JSON file into input string.
Parameters
pCfgDefault Pointer to the default configuration in JSON format
Returns
Returns allways 0
By calling Zephyr file system API file_exists the method check if the JSON configuration file is not existing and in this case it create the file and open it for reading and writing by call of function file_open provided by flash file system controller. Afterwards file position is set to 0 and the default configuration in parameter pCfgDefault will be written to file before file will be synchronized and closed by call of the functions file_seek, file_write, file_sync and file_close. Afterwards it is ensured, that the JSON configuration file exists. File will be opend for reading by call of API function file_open and content will be read into array inbuf by calling function file_read. Finally file will be closed by call of API function file_close and content of inbuf will be assigned to member variable input of type std:string, before function returns with value 0.
Definition at line 121 of file config.cpp.
References CONFIG_FILENAME, CONFIG_JSON_SIZE, FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_read(), FlashFS::file_seek(), FlashFS::file_sync(), FlashFS::file_write(), input, and FlashFS::inst().
Referenced by init().
parse()
int parse (struct cJSON ** jsonObj, std::string & jsonStr)
Function to parse a JSON configuration string.
Parameters
jsonObj Pointer pointer to a JSON root object
jsonStr String containing a configuration in JSON format
Returns
Returns allways 0
The method checks, if a root object of type struct cJSON still exist. In this case it will be deleted with call of function cJSON_Delete, provided by the cJSON library. Afterwards the configuration string will be parsed by calling function cJSON_Parse, also provided by the cJSON library. Return value of this function is a JSON root object. Finally the method returns 0.
Definition at line 300 of file config.cpp.
Referenced by init(), and isValid().
dump()
void dump ()
Function to print the JSON string.
The method extracts a JSON C-string from the root object with call of function cJSON_PrintUnformatted, provided by the cJSON library. Afterwards the string will be printed as debug message on info level. Finally the method release the string by calling function cJSON_free, also provided by the cJSON library.
Definition at line 319 of file config.cpp.
References root_obj.
save()
int save ()
Function to write object representation from memory to input string.
Returns
Returns allways 0
By calling Zephyr function cJSON_PrintUnformatted the JSON configuration string will be extracted from cJSON structure root_obj and stored in variable input. Afterwards the allocated buffer str will be released by call of function cJSON_free.
Definition at line 275 of file config.cpp.
References input, and root_obj.
Referenced by Autocorrection().
saveToFile() [1/2]
int saveToFile ()
Function to store JSON configuration string in file system.
Returns
Returns allways 0
By calling Zephyr function cJSON_PrintUnformatted the JSON configuration string will be extracted from cJSON structure root_obj and stored in variable input, which will be passed to member function saveToFile.
Definition at line 236 of file config.cpp.
References input, and root_obj.
Referenced by MqttConnector::HandleNewConfiguration(), and init().
saveToFile() [2/2]
int saveToFile (std::string config)
Function to store JSON configuration string in file system.
Parameters
config The JSON configuration string
Returns
Returns allways 0
To reduce memory consumption, the function remove all blanks and line feeds from configuration JSON string. By calling Zephyr file system API file_exists the method check if the JSON configuration file is existing and in this case it delete the file from file system by calling function remove provided by flash file system controller. By calling function file_exists again, the method check if the JSON configuration file is not existing and in this case it create the file and open it for reading and writing by call of function file_open provided by flash file system controller. Afterwards file position is set to 0 and the default configuration in static member variable cfgDefault will be written to file before file will be synchronized and closed by call of the functions file_seek, file_write, file_sync and file_close.
Definition at line 191 of file config.cpp.
References CONFIG_FILENAME, FlashFS::file_close(), FlashFS::file_open(), FlashFS::file_seek(), FlashFS::file_sync(), FlashFS::file_write(), FlashFS::inst(), and FlashFS::remove().
parseAllValues()
void parseAllValues ()
Function copy all configuration values in the provided configuration structures.
The method extract all configuration values from all groups of the JSON object by calling member getValue function for every single value. It copies the extracted values in the provided configuration structures of class Config. Name and version of the general group will be checked against the expected values. In case of inconsistencies a debug message at error level will be printed. If displacement calculation and displacement data transfer are disabled, the configuration is corrected to displacement data transfer disabled.
Definition at line 414 of file config.cpp.
References _stCfgSensor::actthres, _stCfgDisplacement::b1, cfgDatalog, cfgDisplacement, cfgGeneral, cfgMetrics, cfgSensor, CONFIG_DEVICE_NAME, CONFIG_VERSION, _stCfgSensor::deactthres, _stCfgDatalog::dispmodeoff, _stCfgDatalog::disptransferon, eSensor_adxl372, getValue(), _stCfgMetrics::interval, MAX_ACT_THRESHOLD, MAX_ACT_THRESHOLD_STR, MAX_DEACT_THRESHOLD, MAX_DEACT_THRESHOLD_STR, MAX_METRICS_INTERVAL, _stCfgDatalog::max_raw_per_day, MAX_RAW_TRANSFERS_PER_DAY, MAX_RMS_THRESHOLD, MIN_ACT_THRESHOLD, MIN_ACT_THRESHOLD_STR, MIN_METRICS_INTERVAL, MIN_RAW_TRANSFERS_PER_DAY, MIN_RMS_THRESHOLD, _stCfgGeneral::name, _stCfgSensor::name, _stCfgDatalog::rawtransferon, _stCfgDatalog::rms_thres, _stCfgGeneral::type, _stCfgSensor::type, and _stCfgGeneral::version.
Referenced by init().
groupExists()
bool groupExists (struct cJSON * jsonObj, std::string group)
Function to check if a group with given name exist in JSON object.
Parameters
jsonObj Pointer to a JSON root object
group The name of the group to search for
Returns
true if group exist, false otherwise
The method check, if the group with name 'group' exist in the JSON root object by calling function cJSON_GetObjectItem, provided by the cJSON library. It than returns the return value of function cJSON_GetObjectItem.
Definition at line 355 of file config.cpp.
Referenced by init(), isValid(), isVersionValid(), and mergeConfig().
getGroupEntries()
int getGroupEntries (std::string group)
Function to retrieve the number of items in a JSON group object.
Parameters
group The name of the group
Returns
Number of items in the JSON group
The method retrieve the JSON object of the group by calling function cJSON_GetObjectItem, provided by the cJSON library. It returns 0, if the object is a NULL pointer, the return value of function getArraySize, which is the number of items in the group object otherwise.
Definition at line 393 of file config.cpp.
References getArraySize(), and root_obj.
keyExists()
bool keyExists (struct cJSON * jsonObj, std::string group, int index, std::string key)
Function to check if a key with given name exist in given group in the JSON object.
Parameters
jsonObj Pointer to a JSON root object
group The name of the group
index The index of the item with the key/value pair within the group
key The key to check
Returns
return the extracted value
The method retrieve the JSON object of the group by calling function cJSON_GetObjectItem, provided by the cJSON library. Afterwards it retrieve the JSON item within the group by calling function cJSON_GetArrayItem, also provided by the cJSON library. If the item is a NULL pointer, the method returns 0, otherwise it iterate over all child nodes with key/value pairs in a loop. If key has been found in child->string, the loop will be aborted and the value in child->valuestring will be stored in return value res.
Definition at line 550 of file config.cpp.
Referenced by mergeConfig().
getValue() [1/2]
std::string getValue (std::string group, int index, std::string key)
Function to retrieve a single value from a JSON group object.
Parameters
group The name of the group
index The index of the item with the key/value pair within the group
key The key to extract the value from
Returns
return the extracted value
The method calls member function method getValue with JSON root object root_obj.
Definition at line 589 of file config.cpp.
References root_obj.
Referenced by Autocorrection(), isValid(), isVersionValid(), mergeConfig(), and parseAllValues().
getValue() [2/2]
std::string getValue (struct cJSON * jsonObj, std::string group, int index, std::string key)
Function to retrieve a single value from a JSON group object.
Parameters
jsonObj Pointer to a JSON root object
group The name of the group
index The index of the item with the key/value pair within the group
key The key to extract the value from
Returns
return the extracted value
The method retrieve the JSON object of the group by calling function cJSON_GetObjectItem, provided by the cJSON library. Afterwards it retrieve the JSON item within the group by calling function cJSON_GetArrayItem, also provided by the cJSON library. If the item is a NULL pointer, the method returns 0, otherwise it iterate over all child nodes with key/value pairs in a loop. If key has been found in child->string, the loop will be aborted and the value in child->valuestring will be stored in return value res.
Definition at line 611 of file config.cpp.
setValue() [1/2]
int setValue (std::string group, int index, std::string key, std::string val)
Function to store a single value in a JSON group object.
Parameters
group The name of the group
index The index of the item with the key/value pair within the group
key The key to extract the value from
val The value to be stored
Returns
return 0 on success, -1 otherwise
The method calls member function method setValue with JSON root object root_obj.
Definition at line 652 of file config.cpp.
References root_obj.
Referenced by Autocorrection(), and mergeConfig().
setValue() [2/2]
int setValue (struct cJSON * jsonObj, std::string group, int index, std::string key, std::string val)
Function to store a single value in a JSON group object.
Parameters
jsonObj Pointer to a JSON root object
group The name of the group
index The index of the item with the key/value pair within the group
key The key to extract the value from
val The value to be stored
Returns
return 0 on success, -1 otherwise
The method retrieve the JSON object of the group by calling function cJSON_GetObjectItem, provided by the cJSON library. Afterwards it retrieve the JSON item within the group by calling function cJSON_GetArrayItem, also provided by the cJSON library. If the item is a NULL pointer, the method returns 0, otherwise it iterate over all child nodes with key/value pairs in a loop. If key has been found in child->string, value val will be stored in the child node by calling function cJSON_SetValuestring, before the loop will be aborted.
Definition at line 676 of file config.cpp.
isValid()
bool isValid (const char * buf)
Function to check if a received configuration is valid.
Parameters
buf The buffer containing the received configuration in JSON format
Returns
Returns true if configuration is valid, false otherwise
The function assign parameter buf to member variable input of type std:string, call the member function parse to retrieve the JSON root object from input string and check if all groups are present in JSON configuration, if all values of the key/value pairs are strings and if device name and configuration version matches with the expected ones. If all checks are passed the function returns true, otherwise false.
Definition at line 929 of file config.cpp.
References areValuesStrings(), CONFIG_ACCEL_SENS_NAME, CONFIG_ACCEL_SENS_TYPE, CONFIG_DEVICE_NAME, CONFIG_DEVICE_TYPE, CONFIG_VERSION, getValue(), groupExists(), input, parse(), root_obj, strIsBool(), strIsFloat(), and strIsInt().
Autocorrection()
void Autocorrection ()
Function to automatically correct invalid configuration values.
By calling the member function getValue the function retrieves the activation and deactivation threshold strings and convert them to integer. Afterwards the function checks if:
Activation threshold is lower than the minimum allowed value. In this case activation threshold is set to the minimum allowed value
Activation threshold is higher than the maximum allowed value. In this case activation threshold is set to the maximum allowed value
Deactivation threshold is higher than the maximum allowed value. In this case deactivation threshold is set to the maximum allowed value
Deactivation threshold is lower than activation threshold and minimum allowed difference. In this case the deactivation threshold is set to the activation threshold plus the minimum allowed difference Afterwards the function retrieves the flags dispmodeoff and disptransferon by calling the member function getValue and checks if displacement calculation is disabled (dispmodeoff = true") and displacement value transfer is enabled (disptransferon = true). In this case disptransferon will be set to false.
Definition at line 1111 of file config.cpp.
References cfgDatalog, eSensor_adxl372, getValue(), MAX_ACT_THRESHOLD, MAX_ACT_THRESHOLD_STR, MAX_DEACT_THRESHOLD, MAX_DEACT_THRESHOLD_STR, MAX_METRICS_INTERVAL, _stCfgDatalog::max_raw_per_day, MAX_RAW_TRANSFERS_PER_DAY, MAX_RMS_THRESHOLD, MIN_ACT_THRESHOLD, MIN_ACT_THRESHOLD_STR, MIN_METRICS_INTERVAL, MIN_RAW_TRANSFERS_PER_DAY, MIN_RMS_THRESHOLD, _stCfgDatalog::rms_thres, save(), and setValue().
Referenced by MqttConnector::HandleNewConfiguration().
operator=()
Config& operator= (const Config &) delete
getCfgGeneral()
stCfgGeneral * getCfgGeneral ()
Getter function to retrieve the configuration structure of the general group.
Returns
Returns a pointer to the configuration structure of the general group
The function returns a pointer to the configuration structure of the general group of type stCfgGeneral.
Definition at line 714 of file config.cpp.
References cfgGeneral.
Referenced by DataManager::configure().
getCfgMetrics()
stCfgMetrics * getCfgMetrics ()
Getter function to retrieve the configuration structure of the metrics group.
Returns
Returns a pointer to the configuration structure of the metrics group
The function returns a pointer to the configuration structure of the metrics group of type stCfgMetrics.
Definition at line 728 of file config.cpp.
References cfgMetrics.
Referenced by DataManager::configure(), MqttConnector::configure(), and PowerMgr::configure().
getCfgDatalog()
stCfgDatalog * getCfgDatalog ()
Getter function to retrieve the configuration structure of the datalog group.
Returns
Returns a pointer to the configuration structure of the datalog group
The function returns a pointer to the configuration structure of the datalog group of type stCfgDatalog.
Definition at line 756 of file config.cpp.
References cfgDatalog.
Referenced by AdxlDataStore::configure(), DataManager::configure(), and HttpConnector::configure().
getCfgDisplacement()
stCfgDisplacement * getCfgDisplacement ()
Getter function to retrieve the configuration structure of the displacement group.
Returns
Returns a pointer to the configuration structure of the displacement group
The function returns a pointer to the configuration structure of the displacement group of type stCfgDisplacement.
Definition at line 742 of file config.cpp.
References cfgDisplacement.
Referenced by DispTask::configure().
getCfgSensor()
stCfgSensor * getCfgSensor (enCfgSensorId id)
Getter function to retrieve the configuration structure of a sensor.
Parameters
id The id of the sensor of enumerator type enCfgSensorId
Returns
Returns a pointer to the configuration structure of sensor
The function returns a pointer to the configuration structure of a single sensor from the sensor group of type stCfgSensor.
Definition at line 769 of file config.cpp.
References cfgSensor, and eSensor_MAX.
Referenced by DataManager::configure(), and Adxl37x::configure().
getConfigJson()
unsigned char * getConfigJson ()
Function to retrieve the configuration in JSON format.
Returns
Returns a pointer to a static char array containing the configuration in JSON Format
By calling Zephyr function cJSON_PrintUnformatted the JSON configuration string will be extracted from cJSON structure root_obj and stored in variable str, which will be copied to static output string out.
Definition at line 784 of file config.cpp.
References root_obj.
deleteConfigFile()
void deleteConfigFile ()
Function to delete configuration file.
By calling Zephyr file system API file_exists the method check if the JSON configuration file is existing and in this case file will be deleted by call of function remove.
Definition at line 255 of file config.cpp.
References CONFIG_FILENAME, FlashFS::inst(), and FlashFS::remove().
Referenced by MqttConnector::HandleFactoryDefault().
getArraySize()
int getArraySize (struct cJSON * array_obj) private
Function to retrieve the array size of a JSON object.
Parameters
array_obj The JSON object to retrieve the array size
Returns
The array size of the JSON object
The method returns the array size (number of items in the array) of a JSON object by calling function cJSON_GetArraySize, provided by the cJSON library. It than returns the return value of function cJSON_GetArraySize.
Definition at line 337 of file config.cpp.
Referenced by getGroupEntries().
isVersionValid()
bool isVersionValid (struct cJSON * jsonObj) private
Function to check if the version is valid.
Parameters
jsonObj Pointer to a JSON root object
Returns
Returns true if version is valid, false otherwise
The function call the member function parse to retrieve the JSON root object from input string and check if all groups are present in JSON configuration and if the configuration version matches with the expected one. If all checks are passed the function returns true, otherwise false.
Definition at line 1232 of file config.cpp.
References CONFIG_VERSION, getValue(), and groupExists().
Referenced by init().
mergeConfig()
void mergeConfig (struct cJSON * rootObj, struct cJSON * loadObj) private
Function to merge existing configuration values in file system into the current JSON structure.
Parameters
rootObj Pointer to the JSON root object with default configuration
loadObj Pointer to the JSON root object with configuration loaded from file system
The method checks if a group and a key in group exist in the loaded configuration of file system. In this case the value will be extracted by call of member function getValue and will be stored in the corresponding key in the default configuration. The default configurations ensured, that the version and structure is allways valid. Following keys will be checked:
'actthres' in group 'sensors'
'deactthres' in group 'sensors'
'interval' in group 'metrics'
'b1' in group 'displacement'
'dispmodeoff' in group 'datalog'
'rawtransferon' in group 'datalog'
'disptransferon' in group 'datalog'
Definition at line 855 of file config.cpp.
References getValue(), groupExists(), keyExists(), and setValue().
Referenced by init().
areValuesStrings()
bool areValuesStrings (std::string group) private
Function to check if the values in a group are strings.
Parameters
group The name of the group
Returns
Returns true if all values are strings, false otherwise
The method retrieve the JSON object of the group by calling function cJSON_GetObjectItem, provided by the cJSON library. Afterwards it retrieve the JSON item within the group by calling function cJSON_GetArrayItem, also provided by the cJSON library. If the item is a NULL pointer, the method returns false, otherwise it iterate over all child nodes with key/value pairs in a loop. If a value is not a string, the loop will be aborted and the function returns false.
Definition at line 811 of file config.cpp.
References root_obj.
Referenced by isValid().
strIsInt()
bool strIsInt (std::string & strInput) private
Function to check if a string contains a valid integer string.
Parameters
strInput The string to check
Returns
Returns true if string contains valid integer, false otherwise
The function call the c library function strtol to check if string strInput contains a valid integer string. If pointer p points to the string end and if string is not empty the function returns true, otherwise false.
Definition at line 1291 of file config.cpp.
Referenced by isValid().
strIsFloat()
bool strIsFloat (std::string & strInput) private
Function to check if a string contains a valid floating point number string.
Parameters
strInput The string to check
Returns
Returns true if string contains valid floating point number, false otherwise
The function call the c library function strtof to check if string strInput contains a valid floating point number string. If pointer p points to the string end and if string is not empty the function returns true, otherwise false.
Definition at line 1311 of file config.cpp.
Referenced by isValid().
strIsBool()
bool strIsBool (std::string & strInput) private
Function to check if a string contains a valid boolean string.
Parameters
strInput The string to check
Returns
Returns true if string contains valid boolean string, false otherwise
The function call the c library function strcmp to check if string strInput contains a valid boolean string ("true" or "false"). In this case the
function returns true, otherwise false.
Definition at line 1329 of file config.cpp.
Referenced by isValid().
Field Documentation
input
std::string input private
The content of the JSON config file.
Definition at line 305 of file config.h.
Referenced by init(), isValid(), loadFromFile(), save(), and saveToFile().
root_obj
struct cJSON* root_obj private
The JSON root object.
Definition at line 306 of file config.h.
Referenced by areValuesStrings(), dump(), getConfigJson(), getGroupEntries(), getValue(), init(), isValid(), save(), saveToFile(), and setValue().
cfgGeneral
stCfgGeneral cfgGeneral private
Instance of general related configuration.
Definition at line 308 of file config.h.
Referenced by getCfgGeneral(), and parseAllValues().
cfgMetrics
stCfgMetrics cfgMetrics private
Instance of metrics related configuration.
Definition at line 309 of file config.h.
Referenced by getCfgMetrics(), and parseAllValues().
cfgDatalog
stCfgDatalog cfgDatalog private
Instance of datalog related configuration
Definition at line 310 of file config.h.
Referenced by Autocorrection(), getCfgDatalog(), and parseAllValues().
cfgDisplacement
stCfgDisplacement cfgDisplacement private
Instance of displacement related configuration.
Definition at line 312 of file config.h.
Referenced by getCfgDisplacement(), and parseAllValues().
cfgSensor
stCfgSensor cfgSensor[eSensor_MAX] private
Instance of sensor related configuration.
Definition at line 314 of file config.h.
Referenced by getCfgSensor(), and parseAllValues().
The documentation for this class was generated from the following files:
conf/config.h
conf/config.cpp