AXO X1: FwDownload Class Reference
FwDownload Class Reference
Firmware download state class derived from base class FwState.
#include <fsm.h>
Detailed Description
Firmware download state class derived from base class FwState.
Detailed Description
The firmware download state class overrides the handler function of DlComplete, DlFailed and timer expired events. In this state the download of the firmware binary file is ongoing.
Definition at line 179 of file fsm.h.
Public Member Functions
FwDownload (void *pd)
Constructor of firmware download state class.
virtual ~FwDownload ()
Destructor of firmware download state class.
FwFsm::StateId handle_DlComplete (PoolElem **pElem)
Firmware download state handler function for DlComplete events.
FwFsm::StateId handle_DlFailed (PoolElem **pElem)
Firmware download state handler function for DlFailed events.
FwFsm::StateId handle_timer_exp ()
Firmware download state handler function for timer expired events.
Public Member Functions inherited from FwState
FwState (void *pData)
Constructor of state base class.
virtual ~FwState ()
Destructor of state base class.
virtual FwFsm::StateId handle_OtaStart ()
State handler function of the state base class for OtaStart events.
virtual FwFsm::StateId handle_FwInfo (PoolElem **pElem)
State handler function of the state base class for FwInfo events.
Additional Inherited Members
Data Fields inherited from FwState
void * pd
Timestamp of download start in seconds.
uint32_t startDownloadTimestamp
Static Public Attributes inherited from FwState
static const uint32_t maxDownloadDelay = 10*60
Constructor & Destructor Documentation
FwDownload()
FwDownload (void * pData) explicit
Constructor of firmware download state class.
Parameters
pData Ponter to a data object
The constructor simply triggers a debug message on info level.
Definition at line 484 of file fsm.cpp.
References FwState::pd.
~FwDownload()
~FwDownload () virtual
Destructor of firmware download state class.
The destructor simply triggers a debug message on info level.
Definition at line 493 of file fsm.cpp.
Member Function Documentation
handle_DlComplete()
FwFsm::StateId handle_DlComplete (PoolElem ** pElem) virtual
Firmware download state handler function for DlComplete events.
Parameters
pElem Pointer to pointer to message of type PoolElem
Returns
Returns the state ID of the ready state
The function forward the download complete message to MQTT connector task. Finally function returns the state ID eReady.
Reimplemented from FwState.
Definition at line 505 of file fsm.cpp.
References Mbox::eMqttConnector, FwFsm::eReady, and Mbox::send().
handle_DlFailed()
FwFsm::StateId handle_DlFailed (PoolElem ** pElem) virtual
Firmware download state handler function for DlFailed events.
Parameters
pElem Pointer to pointer to message of type PoolElem
Returns
Returns the state ID of the idle state or eNoChange
The function checks if the maximum number of retries has not been reached. In this case the function start the retry timer by calling function startRetryTimer of the FwUpdCtrl class instance to schedule a firmware download retry and returns the state ID eNoChange. If the maximum number of retries has been reached the retry counter will be set to 0 and the DlFailed message will be forwarded to MQTT connector task. Afterwards the function performes a delay of 2 seconds to let other tasks take over process, before it performes a reset. Returning to the state ID eIdle will never be reached.
Reimplemented from FwState.
Definition at line 536 of file fsm.cpp.
References FwFsm::eIdle, Mbox::eMqttConnector, FwFsm::eNoChange, FwState::pd, and Mbox::send().
handle_timer_exp()
FwFsm::StateId handle_timer_exp () virtual
Firmware download state handler function for timer expired events.
Returns
The state ID eNoChange
The function calculated the time difference from the download start time to the current time. If the time difference is more than maxDownloadDelay or if the maximum number of retries has been reached the download will be expected as failed and message eFwDlFailed will be send to MQTT connector task with error CODE3 and after a delay of 2 seconds a reset will be performed.
Otherwise a new download attempt will be started by calling the method requestDownload of the FwUpdCtrl class instance. Pointer variable pd is assigned to FwUpdCtrl class instance.
Reimplemented from FwState.
Definition at line 589 of file fsm.cpp.
References eFwDlFailed, FwFsm::eNoChange, FwState::maxDownloadDelay, FwUpdCtrl::maxRetries, FwState::pd, Mbox::sendMsg(), and FwState::startDownloadTimestamp.
The documentation for this class was generated from the following files:
update/fsm.h
update/fsm.cpp