AXO X1: AdxlDataStore Class Reference
AdxlDataStore Class Reference
Adxl data store class derived from task base class.
#include <adxl_store.h>
Detailed Description
Adxl data store class derived from task base class.
Detailed Description
The adxl data store class reserves FRAM space capacity for samples within 15 seconds at expected sample rate of 4400 (samples per second). It provides methods to store the raw data, to reset/clear previously stored data, to dump the data and to indicate that storage is full or free for re-usage.
Message Interaction:
Receive
Adxl37x task
RMS task
Adxl data store (self, callback function for shell command 'd')
Transmit
Adxl37x task
RMS task
RMS store task
Adxl data store (self, callback function for shell command 'd')
Definition at line 126 of file adxl_store.h.
Public Member Functions
AdxlDataStore (const char *name="??", uint8_t num_seconds=1, uint16_t samples_per_sec=4400, bool have_http_connector=true)
Adxl data store task constructor.
virtual ~AdxlDataStore ()
Adxl data store task destructor.
virtual void task (void)
Adxl data store task function.
void store (adxl372_xyz_accel_data *src, uint32_t cnt)
Adxl data storage function.
void dump ()
Function prints out the data of the last second.
void dumpAll ()
Function prints out all the data stored in FRAM.
void dumpAllBytes ()
Function prints out all the data stored in FRAM.
void dumpAllFilt ()
Function prints out all the data stored in FRAM.
void dumpAllDisp ()
Function prints out all the data stored in FRAM.
void reset ()
Function reset FRAM to be empty.
void notifySender ()
Function notify Adxl37x task that processing is done.
void notifyStorageFull ()
Function notify Adxl37x task that FRAM is full.
virtual void configure ()
Adxl DataStore virtual task configure function.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static int shell_dump (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'd'.
static int shell_dump_bytes (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'db'.
static int shell_dump_filt (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'df'.
static int shell_dump_disp (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'dd'.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the adxl data store task.
Private Member Functions
AdxlDataStore ()=delete
void notifyRawDataStatus (Mbox::MboxId senderId)
Function notify HTTP Connector task the status of the raw data.
void sendRawData (PoolElem *pElem)
Function to send raw data to the requesting sender task.
void sendDispData (PoolElem *pElem)
Function to send displacement data to the requesting sender task.
void sendFwFiltData (PoolElem *pElem)
Function to send forward filtered data to the HTTP Connector task.
void sendBwFiltData (PoolElem *pElem)
Function to send backward filtered data to the HTTP Connector task.
void sendSResultData (PoolElem *pElem)
Function to send displacement data (SResult, not detrended) to the HTTP Connector task.
void storeForwardFilt (PoolElem *pElem)
Function to store forward filtered data in FRAM.
void storeBackwardFilt (PoolElem *pElem)
Function to store backward filtered data in FRAM.
void storeSResult (PoolElem *pElem)
Function to store S values (displacement before detrending) in FRAM.
void storeDResult (PoolElem *pElem)
Function to store D values (displacement after detrending) in FRAM. D values reoresent the final result of displacement calculation.
void storeSampleData ()
Helper function to store known defined acceleration data in FRAM.
void calcMaxXYZ (adxl372_xyz_accel_data *src, uint32_t cnt)
Function to calculate the maximum acceleration values in x, y and z direction.
Private Attributes
uint32_t capa
capacity in bytes, multiple of adxl372_xyz_accel_data
uint32_t bytes_per_sec
expected bytes per second
uint32_t samples_per_sec
expected samples per second
uint32_t rd
next read addr, for testing
uint32_t wr
next write addr
uint32_t level
current bytes written
uint32_t num_samples
current samples written
bool full
indicator for data storage is full
bool idle
no data received for more than 1 second
bool allow_wrap_around
flag to allow or forbid wrap around
PowerMgr::PmState pm_state
on/active or off/suspended/power down mode
bool have_http_connector
float x_max = 0
Current maximum x value.
float y_max = 0
Current maximum y value.
float z_max = 0
Current maximum z value.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
AdxlDataStore() [1/2]
AdxlDataStore (const char * name = "??", uint8_t num_seconds = 1, uint16_t samples_per_sec = 4400, bool have_http_connector = true) explicit
Adxl data store task constructor.
Parameters
name The name of the class
num_seconds Number of seconds to be stored within on measurement cycle
samples_per_sec sample rate
have_http_connector Flag indicationg if HTTP Connector is used (X1 devices) or not (MINI devices)
Task of the constructor is to reserve capacity for samples within n seconds at expected sample rate. It initializes the private member variables of the class, allocate and register a mailbox and calculate the total number of bytes needed for the storage of a complete measurement cycle stored in private variable capa. Finally it calculates the expected number of bytes per second and store it in private variable bytes_per_sec.
Definition at line 57 of file adxl_store.cpp.
References bytes_per_sec, capa, Mbox::eAdxlStore, have_http_connector, pInMbox, rd, Mbox::registerMbox(), samples_per_sec, wr, x_max, y_max, and z_max.
~AdxlDataStore()
~AdxlDataStore () virtual
Adxl data store task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 101 of file adxl_store.cpp.
AdxlDataStore() [2/2]
AdxlDataStore () private delete
Member Function Documentation
task()
void task (void) virtual
Adxl data store task function.
Initially the SPI bus instance andd the FRAM instance will be initialized by calling the functions spibus::inst()->init() and MEMORY_INST->init(). Afterwards FRAM instance will be forced in suspended/power saving mode by calling MEMORY_INST->sleep() and the power manger state will be set to off, before entering the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eAdxl37xSensorData: Sensor raw data. If in idle state flag idle is set to false and function reset is called to be able to overwrite old data from last measurement cycle. Payload of message will be extracted and casted to structure adxl37x_sensor_value before message is forwarded to RMS task, message pointer pElem is set to 0 to prevent free(). Afterwards the maximum acceleration values in x, y and z direction will be calculated by calling member function calcMaxXYZ. If power manager state is eOff, FRAM will be activated by calling function MEMORY_INST->wakeup and power manager state is set to eOn. Data is storen in FRAM by calling funtion store and Adxl37x task will be informed with message eAdxlStorageDone by calling funtion notifySender.
eAdxl37xIdle: Flag idle will be set to true, FRAM will be forced to low power state by calling function MEMORY_INST->sleep() and power manager state is set to eOff. Afterwards the received message will be forwarded to RMS store task and message pointer pElem is set to 0 to prevent free(). In case have_http_connector is true, the calculated maximum acceleration values in x, y and z direction will be send to data manager task and finally the HTTP connector will be informed, that raw data is available by sending message eAdxlIdleInd.
eAdxlStorageDumpAll: Implemented for testing purposes. In case user input the command 'd' on terminal raw data will be printed. FRAM will be activated by calling function MEMORY_INST->wakeup and raw data will be printed by calling function dumpAll.
eAdxlStorageDumpBytes: Implemented for testing purposes. In case user input the command 'db' on terminal raw data bytes will be printed. FRAM will be activated by calling function MEMORY_INST->wakeup and raw data will be printed by calling function dumpAllBytes.
eAdxlStorageDumpFilt: Implemented for testing purposes. In case user input the command 'df' on terminal filtered values will be printed. FRAM will be activated by calling function MEMORY_INST->wakeup and raw data will be printed by calling function dumpAllFilt.
Note
only for development phase, inactive for relaese versions.
eAdxlStorageDumpDisp: Implemented for testing purposes. In case user input the command 'dd' on terminal displacement data will be printed. FRAM will be activated by calling function MEMORY_INST->wakeup and raw data will be printed by calling function dumpAllDisp.
eAdxlIdleReq: The value of the idle flag will be send to HTTP Connector task with message of type eAdxlIdleInd and sender ID eAdxlStore.
eRawDataStatus: Call of handler function notifyRawDataStatus.
eRawData: Payload of the received message will be casted to structure of type AdxlRawDataProgress and function sendRawData will be called.
eDispFirstEntries: same as eRawData
eDispLastEntries: same as eRawData
eFwFiltData: Send forward filtered values to requesting task by calling member function sendFwFiltData
eBwFiltData: Send backward filtered values to requesting task by calling member function sendBwFiltData
eSResultData: Send S values (displacement before detrending) to requesting task by calling member function sendSResultData
eStoreFwFiltResult: Write forward filtered data into FRAM by calling member function storeForwardFilt
eStoreBwFiltResult: Write backward filtered data into FRAM by calling member function storeBackwardFilt
eStoreSResult: Write S values (displacement before detrending) into FRAM by calling member function storeSResult
eStoreDResult: Write D values (displacement after detrending) into FRAM by calling member function storeDResult (this is final displacement result)
eDispData: Send displacement data to the requesting sender task by calling member function sendDispData
Implements Task.
Definition at line 1126 of file adxl_store.cpp.
References calcMaxXYZ(), adxl37x_sensor_value::cnt, dumpAll(), dumpAllBytes(), dumpAllDisp(), dumpAllFilt(), eAdxl37xIdle, eAdxl37xSensorData, eAdxlIdleInd, eAdxlIdleReq, Mbox::eAdxlRms, eAdxlStorageDumpActive, eAdxlStorageDumpAll, eAdxlStorageDumpBytes, eAdxlStorageDumpComplete, eAdxlStorageDumpDisp, eAdxlStorageDumpFilt, eBwFiltData, eDispData, eDispFirstEntries, eDispLastEntries, eFwFiltData, eMaxXYZ, eRawData, eRawDataStatus, Mbox::eRmsStore, eSResultData, eStoreBwFiltResult, eStoreDResult, eStoreFwFiltResult, eStoreSResult, PoolElem::free(), PoolElem::from, PoolElem::getBuffer(), have_http_connector, idle, spibus::init(), spibus::inst(), PoolElem::mtype, Task::myName, notifyRawDataStatus(), notifySender(), pInMbox, pm_state, Mbox::read(), reset(), adxl37x_sensor_value::samples, Mbox::send(), sendBwFiltData(), sendDispData(), sendFwFiltData(), Mbox::sendMsg(), sendRawData(), sendSResultData(), store(), storeBackwardFilt(), storeDResult(), storeForwardFilt(), storeSampleData(), storeSResult(), UNIT_TEST_STOP_LOOP, x_max, y_max, and z_max.
store()
void store (adxl372_xyz_accel_data * src, uint32_t cnt)
Adxl data storage function.
Parameters
src pointer to sample data of type adxl372_xyz_accel_data
cnt number of samples
The function checks if FRAM is full with private member variable full. In this case the function returns immediatly. Otherwise the function calculates the needed number of bytes for the new samples. In case write position wr plus needed number of bytes for the new samples exceeds size of FRAM capacity only the number of samples fitting into FRAM will be written, write position wr and remaining bytes to be written in variable len will be actualized and the indicator that FRAM is full will be set to true. eAdxl37xTask will be informed with message eAdxlStorageFull by calling function notifyStorageFull. Furthermore write position wr will be set to 0.
If number of bytes to be written in variable len is greater 0 and FRAM is not full or allow_wrap_around is true, samples will be written to FRAM and write position wr will be actualized by adding number of written bytes len. For debug purposes a test is implemented, which check if 1 sec data is available.
Definition at line 125 of file adxl_store.cpp.
References allow_wrap_around, bytes_per_sec, capa, full, level, notifyStorageFull(), rd, and wr.
Referenced by task().
dump()
void dump ()
Function prints out the data of the last second.
The function enters a loop with current read position rd as start point. Read position will be incremented by size of one data entry sizeof(adxl372_xyz_accel_data) and loop ends if read and write position are equal. In the loop raw data will be read from FRAM at current read position by calling function MEMORY_INST->readBytes, data will be converted to x, y, z values and these values will be printed by calling function printk. Finally a sleep for 1 msec will be performed by calling function k_sleep.
Note
The function do not handle wrap around
Definition at line 442 of file adxl_store.cpp.
References rd, wr, adxl372_xyz_accel_data::x, adxl372_xyz_accel_data::y, and adxl372_xyz_accel_data::z.
dumpAll()
void dumpAll ()
Function prints out all the data stored in FRAM.
The function set current position pos and end position end. If FRAM is not full, all the written data shall be mentioned (pos is 0 and end is the current write position). If FRAM is full and wrap around is not allowed, complete FRAM shall be mentioned (pos is 0 and end is the size of FRAM capa). If FRAM is full and wrap around is allowed, also complete FRAM shall be mentioned (pos is the current write position and end is the current write position plus the size of FRAM, wrap around is handled in loop) Afterwards the function calculates the number of data entries and enters the loop over the number of data entries. After every loop cycle the current read position pos is incremented by size of one data entry sizeof(adxl372_xyz_accel_data) modulo size of the FRAM. The modulo operation realize the wrap around. In the loop raw data will be read from FRAM at current read position by calling function MEMORY_INST->readBytes, data will be converted to x, y, z values and these values will be printed by calling LOG_PRINTK. Finally a sleep for 4 msec will be performed by calling function k_sleep. *
Definition at line 493 of file adxl_store.cpp.
References allow_wrap_around, capa, Adxl37x::convert(), full, wr, adxl372_xyz_accel_data::x, adxl372_xyz_accel_data::y, and adxl372_xyz_accel_data::z.
Referenced by task().
dumpAllBytes()
void dumpAllBytes ()
Function prints out all the data stored in FRAM.
The function set current position pos and end position end. If FRAM is not full, all the written data shall be mentioned (pos is 0 and end is the current write position). If FRAM is full and wrap around is not allowed, complete FRAM shall be mentioned (pos is 0 and end is the size of FRAM capa). If FRAM is full and wrap around is allowed, also complete FRAM shall be mentioned (pos is the current write position and end is the current write position plus the size of FRAM, wrap around is handled in loop) Afterwards the function calculates the number of data entries and enters the loop over the number of data entries. After every loop cycle the current read position pos is incremented by size of one data entry sizeof(adxl372_xyz_accel_data) modulo size of the FRAM. The modulo operation realize the wrap around. In the loop raw data will be read from FRAM at current read position by calling function MEMORY_INST->readBytes and the read bytes of the x, y, z values will be printed by calling LOG_PRINTK. Finally a sleep for 8 msec will be performed by calling function k_sleep.
Definition at line 569 of file adxl_store.cpp.
References allow_wrap_around, capa, full, and wr.
Referenced by task().
dumpAllFilt()
void dumpAllFilt ()
Function prints out all the data stored in FRAM.
The function set current positions pos to the start address of reserved memory for forward filtered and S (displacement data before detrending) values and pos2 to the start address of reserved memory for backward filtered and D (displacement data after detrending / final displacement result) values. Afterwards the function enters the loop over the number of samples. After every loop cycle the current read positions pos and pos3 are incremented by size of one data entry sizeof(double). In the loop forward and backward filtered data values will be read from FRAM at current read position by calling function MEMORY_INST->readBytes, data will be converted to double and printed by calling LOG_PRINTK. Finally a sleep for 10 msec will be performed by calling function k_sleep.
Note
Function is only for testing purposes during development!
Definition at line 634 of file adxl_store.cpp.
References BW_D_START_ADDR, FW_S_START_ADDR, and num_samples.
Referenced by task().
dumpAllDisp()
void dumpAllDisp ()
Function prints out all the data stored in FRAM.
The function set current positions pos to the start address of reserved memory for forward filtered and S (displacement data before detrending) values and pos2 to the start address of reserved memory for backward filtered and D (displacement data after detrending / final displacement result) values. Afterwards the function enters the loop over the number of samples. After every loop cycle the current read positions pos and pos3 are incremented by size of one data entry sizeof(double). In the loop S and D data values will be read from FRAM at current read position by calling function MEMORY_INST->readBytes, data will be converted to double and printed by calling LOG_PRINTK. Finally a sleep for 10 msec will be performed by calling function k_sleep.
Definition at line 688 of file adxl_store.cpp.
References BW_D_START_ADDR, FW_S_START_ADDR, and num_samples.
Referenced by task().
reset()
void reset ()
Function reset FRAM to be empty.
Read and write position will be set to 0, flag full will be set to false.
Definition at line 740 of file adxl_store.cpp.
References full, rd, wr, x_max, y_max, and z_max.
Referenced by task().
notifySender()
void notifySender ()
Function notify Adxl37x task that processing is done.
Function send message eAdxlStorageDone with sender id eAdxlStore to Adxl37x task by calling function sendMsg provided by Mbox class. This indicates that processing is done and data buffer is free for reuse.
Definition at line 756 of file adxl_store.cpp.
References eAdxlStorageDone, and Mbox::sendMsg().
Referenced by task().
notifyStorageFull()
void notifyStorageFull ()
Function notify Adxl37x task that FRAM is full.
Function send message eAdxlStorageFull with sender id eAdxlStore to Adxl37x task by calling function sendMsg provided by Mbox class.
Definition at line 767 of file adxl_store.cpp.
References eAdxlStorageFull, and Mbox::sendMsg().
Referenced by store().
configure()
void configure () virtual
Adxl DataStore virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to ADXLDataStore by call of the function getCfgDatalog provided by the Config class, checks if the displacement calculation is configured to be disabled and set the number of FRAM storage time to 15 seconds in this case, otherwise FRAM storage time is set to 5 seconds. Finally the total number of required bytes are calculated and stored in member variable capa.
Reimplemented from Task.
Definition at line 1335 of file adxl_store.cpp.
References capa, _stCfgDatalog::dispmodeoff, FRAM_15_SEC_RAW_DATA_SPACE, FRAM_5_SEC_RAW_DATA_SPACE, Config::getCfgDatalog(), Config::inst(), rd, samples_per_sec, and wr.
Referenced by main().
shell_dump()
int shell_dump (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'd'.
The function request a message from message pool, set message type to eAdxlStorageDumpAll, set eAdxl37xTask as sender and send message to Adxl-Store mailbox.
Note
For testing only: trigger dump via shell command
Definition at line 1362 of file adxl_store.cpp.
References eAdxlStorageDumpAll, and Mbox::sendMsg().
shell_dump_bytes()
int shell_dump_bytes (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'db'.
The function send a message of type eAdxlStorageDumpBytes to its own (Adxl-Store) mailbox.
Note
For testing only: trigger byte dump via shell command
Definition at line 1380 of file adxl_store.cpp.
References eAdxlStorageDumpBytes, and Mbox::sendMsg().
shell_dump_filt()
int shell_dump_filt (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'df'.
The function send a message of type eAdxlStorageDumpFilt to its own (Adxl-Store) mailbox.
Note
For testing only: trigger dump of filtered data via shell command
only for development purposes
Definition at line 1397 of file adxl_store.cpp.
References eAdxlStorageDumpFilt, and Mbox::sendMsg().
shell_dump_disp()
int shell_dump_disp (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'dd'.
The function send a message of type eAdxlStorageDumpDisp to its own (Adxl-Store) mailbox.
Note
For testing only: trigger by dump of displacement data via shell command
Definition at line 1414 of file adxl_store.cpp.
References eAdxlStorageDumpDisp, and Mbox::sendMsg().
notifyRawDataStatus()
void notifyRawDataStatus (Mbox::MboxId senderId) private
Function notify HTTP Connector task the status of the raw data.
Parameters
senderId The ID of the sender task
Function send message eRawDataStatus with sender id eAdxlStore back to sender task. Status includes the start and end position in FRAM and the total number of raw data entries.
Definition at line 781 of file adxl_store.cpp.
References allow_wrap_around, capa, AdxlRawDataStatus::entries, eRawDataStatus, full, num_samples, Mbox::sendMsg(), AdxlRawDataStatus::startRd, and wr.
Referenced by task().
sendRawData()
void sendRawData (PoolElem * pElem) private
Function to send raw data to the requesting sender task.
Parameters
pElem The received message of type PoolElem pointer
Function calculate the read start position in FRAM, enter a loop and copy the number of requested entries from FRAM to array accel by calling function readBytes, provided by spi(f/m)ram class. Afterwards it send a message with received message type back to the requesting sender task with array accel in payload of the message.
Definition at line 817 of file adxl_store.cpp.
References capa, PoolElem::from, PoolElem::getBuffer(), MAX_NUM_REQ_ENTRIES, PoolElem::mtype, AdxlRawDataProgress::rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), and AdxlRawDataProgress::startRd.
Referenced by task().
sendDispData()
void sendDispData (PoolElem * pElem) private
Function to send displacement data to the requesting sender task.
Parameters
pElem The received message of type PoolElem pointer
Function calculate the read start position in FRAM, enter a loop and copy the number of requested entries from FRAM to array disp by calling function readBytes, provided by spi(f/m)ram class. Afterwards it send a message with received message type back to the requesting sender task with array disp in payload of the message.
Definition at line 858 of file adxl_store.cpp.
References PoolElem::from, PoolElem::getBuffer(), MAX_NUM_REQ_ENTRIES, PoolElem::mtype, AdxlRawDataProgress::rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), and AdxlRawDataProgress::startRd.
Referenced by task().
sendFwFiltData()
void sendFwFiltData (PoolElem * pElem) private
Function to send forward filtered data to the HTTP Connector task.
Parameters
pElem The received message of type PoolElem pointer
Function calculate the read start position in FRAM, enter a loop and copy the number of requested entries from FRAM to array data by calling function readBytes, provided by spi(f/m)ram class. Afterwards it send a message with received message type back to the requesting sender task with array data in payload of the message.
Definition at line 899 of file adxl_store.cpp.
References PoolElem::from, FW_S_START_ADDR, PoolElem::getBuffer(), MAX_NUM_REQ_ENTRIES, PoolElem::mtype, AdxlRawDataProgress::rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), and AdxlRawDataProgress::startRd.
Referenced by task().
sendBwFiltData()
void sendBwFiltData (PoolElem * pElem) private
Function to send backward filtered data to the HTTP Connector task.
Parameters
pElem The received message of type PoolElem pointer
Function calculate the read start position in FRAM, enter a loop and copy the number of requested entries from FRAM to array data by calling function readBytes, provided by spi(f/m)ram class. Afterwards it send a message with received message type back to the requesting sender task with array data in payload of the message. NOTE Function completly equal to sendFwFiltData (join together?) NOTE also equal to sendRawData !!!
Definition at line 942 of file adxl_store.cpp.
References BW_D_START_ADDR, PoolElem::from, PoolElem::getBuffer(), MAX_NUM_REQ_ENTRIES, PoolElem::mtype, AdxlRawDataProgress::rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), and AdxlRawDataProgress::startRd.
Referenced by task().
sendSResultData()
void sendSResultData (PoolElem * pElem) private
Function to send displacement data (SResult, not detrended) to the HTTP Connector task.
Parameters
pElem The received message of type PoolElem pointer
Function calculate the read start position in FRAM, enter a loop and copy the number of requested entries from FRAM to array data by calling function readBytes, provided by spi(f/m)ram class. Afterwards it send a message with received message type back to the requesting sender task with array data in payload of the message. NOTE Function completly equal to sendFwFiltData (join together?) NOTE also equal to sendRawData !!!
Definition at line 986 of file adxl_store.cpp.
References PoolElem::from, FW_S_START_ADDR, PoolElem::getBuffer(), MAX_NUM_REQ_ENTRIES, PoolElem::mtype, AdxlRawDataProgress::rcvdEntries, AdxlRawDataProgress::requestedEntries, Mbox::sendMsg(), and AdxlRawDataProgress::startRd.
Referenced by task().
storeForwardFilt()
void storeForwardFilt (PoolElem * pElem) private
Function to store forward filtered data in FRAM.
Parameters
pElem The received message of type PoolElem
The function extracts structure of type AdxlFilterDataProgress from message payload, wake up SPI bus by calling function wakeup of class spi(f/m)ram, assign the write position wr and enter a loop over the number of requested entries. In the loop every single entry is written to write position by call of function writeBytes of class spi(f/m)ram and write position will be incremented by sizeof(double). If forward filtered data is completely written, indicated by num_samples Disp Task will be informed with message of type eStoredFwFiltVals.
Definition at line 202 of file adxl_store.cpp.
References allow_wrap_around, AdxlFilterDataProgress::data, eStoredFwFiltVals, PoolElem::getBuffer(), num_samples, AdxlFilterDataProgress::requestedEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, AdxlFilterDataProgress::startWr, and wr.
Referenced by task().
storeBackwardFilt()
void storeBackwardFilt (PoolElem * pElem) private
Function to store backward filtered data in FRAM.
Parameters
pElem The received message of type PoolElem
The function extracts structure of type AdxlFilterDataProgress from message payload, wake up SPI bus by calling function wakeup of class spi(f/m)ram, assign the write position wr and enter a loop over the number of requested entries. In the loop every single entry is written to write position by call of function writeBytes of class spi(f/m)ram and write position will be incremented by sizeof(double). If backward filtered data is completely written, indicated by num_samples Disp Task will be informed with message of type eStoredBwFiltVals.
Definition at line 253 of file adxl_store.cpp.
References allow_wrap_around, AdxlFilterDataProgress::data, eStoredBwFiltVals, PoolElem::getBuffer(), num_samples, AdxlFilterDataProgress::requestedEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, AdxlFilterDataProgress::startWr, and wr.
Referenced by task().
storeSResult()
void storeSResult (PoolElem * pElem) private
Function to store S values (displacement before detrending) in FRAM.
Parameters
pElem The received message of type PoolElem
The function extracts structure of type AdxlFilterDataProgress from message payload, wake up SPI bus by calling function wakeup of class spi(f/m)ram, assign the write position wr and enter a loop over the number of requested entries. In the loop every single entry is written to write position by call of function writeBytes of class spi(f/m)ram and write position will be incremented by sizeof(double). If S values are completely written, indicated by num_samples Disp Task will be informed with message of type eStoredSResultVals.
Definition at line 304 of file adxl_store.cpp.
References allow_wrap_around, AdxlFilterDataProgress::data, eStoredSResultVals, PoolElem::getBuffer(), num_samples, AdxlFilterDataProgress::requestedEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, AdxlFilterDataProgress::startWr, and wr.
Referenced by task().
storeDResult()
void storeDResult (PoolElem * pElem) private
Function to store D values (displacement after detrending) in FRAM. D values reoresent the final result of displacement calculation.
Parameters
pElem The received message of type PoolElem
The function extracts structure of type AdxlFilterDataProgress from message payload, wake up SPI bus by calling function wakeup of class spi(f/m)ram, assign the write position wr and enter a loop over the number of requested entries. In the loop every single entry is written to write position by call of function writeBytes of class spi(f/m)ram and write position will be incremented by sizeof(double). If D values are completely written, indicated by num_samples Disp Task will be informed with message of type eStoredDResultVals.
Definition at line 356 of file adxl_store.cpp.
References allow_wrap_around, AdxlFilterDataProgress::data, eStoredDResultVals, PoolElem::getBuffer(), num_samples, AdxlFilterDataProgress::requestedEntries, Mbox::sendMsg(), AdxlFilterDataProgress::sentEntries, AdxlFilterDataProgress::startWr, and wr.
Referenced by task().
storeSampleData()
void storeSampleData () private
Helper function to store known defined acceleration data in FRAM.
The function includes the known defined acceleration data in header file input_accel_bin.h, wake up SPI bus by calling function wakeup of class spi(f/m)ram, assign the write position wr to address 0 and enter a loop over the number of samples to be written. In the loop every single entry is written to write position by call of function writeBytes of class spi(f/m)ram and write position will be incremented by sizeof(adxl372_xyz_accel_data).
Note
Only the values in z direction will be written
This funtion is implemented only for development purposes. In release version of the firmware the function is never called.
Definition at line 405 of file adxl_store.cpp.
References allow_wrap_around, full, input_bytes, num_samples, and wr.
Referenced by task().
calcMaxXYZ()
void calcMaxXYZ (adxl372_xyz_accel_data * src, uint32_t cnt) private
Function to calculate the maximum acceleration values in x, y and z direction.
Parameters
src pointer to sample data of type adxl372_xyz_accel_data
cnt number of samples
The function enter a loop over the number of raw data samples. In the loop the x, y and z raw values will be converted to micro meter per squared seconds. These calculated values will be checked if they are greater than the current maximum values. If yes, the current maximum value will be set to the calculated acceleration value.
Definition at line 1031 of file adxl_store.cpp.
References adxl372_xyz_accel_data::x, x_max, adxl372_xyz_accel_data::y, y_max, adxl372_xyz_accel_data::z, and z_max.
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the adxl data store task.
Definition at line 133 of file adxl_store.h.
Referenced by AdxlDataStore(), and task().
capa
uint32_t capa private
capacity in bytes, multiple of adxl372_xyz_accel_data
Definition at line 158 of file adxl_store.h.
Referenced by AdxlDataStore(), configure(), dumpAll(), dumpAllBytes(), notifyRawDataStatus(), sendRawData(), and store().
bytes_per_sec
uint32_t bytes_per_sec private
expected bytes per second
Definition at line 159 of file adxl_store.h.
Referenced by AdxlDataStore(), and store().
samples_per_sec
uint32_t samples_per_sec private
expected samples per second
Definition at line 160 of file adxl_store.h.
Referenced by AdxlDataStore(), and configure().
rd
uint32_t rd private
next read addr, for testing
Definition at line 161 of file adxl_store.h.
Referenced by AdxlDataStore(), configure(), dump(), reset(), and store().
wr
uint32_t wr private
next write addr
Definition at line 162 of file adxl_store.h.
Referenced by AdxlDataStore(), configure(), dump(), dumpAll(), dumpAllBytes(), notifyRawDataStatus(), reset(), store(), storeBackwardFilt(), storeDResult(), storeForwardFilt(), storeSampleData(), and storeSResult().
level
uint32_t level private
current bytes written
Definition at line 163 of file adxl_store.h.
Referenced by store().
num_samples
uint32_t num_samples private
current samples written
Definition at line 164 of file adxl_store.h.
Referenced by dumpAllDisp(), dumpAllFilt(), notifyRawDataStatus(), storeBackwardFilt(), storeDResult(), storeForwardFilt(), storeSampleData(), and storeSResult().
full
bool full private
indicator for data storage is full
Definition at line 167 of file adxl_store.h.
Referenced by dumpAll(), dumpAllBytes(), notifyRawDataStatus(), reset(), store(), and storeSampleData().
idle
bool idle private
no data received for more than 1 second
Definition at line 168 of file adxl_store.h.
Referenced by task().
allow_wrap_around
bool allow_wrap_around private
flag to allow or forbid wrap around
Definition at line 169 of file adxl_store.h.
Referenced by dumpAll(), dumpAllBytes(), notifyRawDataStatus(), store(), storeBackwardFilt(), storeDResult(), storeForwardFilt(), storeSampleData(), and storeSResult().
pm_state
PowerMgr::PmState pm_state private
on/active or off/suspended/power down mode
Definition at line 170 of file adxl_store.h.
Referenced by task().
have_http_connector
bool have_http_connector private
flag deciding if indications are sent to http connector
Definition at line 171 of file adxl_store.h.
Referenced by AdxlDataStore(), and task().
x_max
float x_max = 0 private
Current maximum x value.
Definition at line 173 of file adxl_store.h.
Referenced by AdxlDataStore(), calcMaxXYZ(), reset(), and task().
y_max
float y_max = 0 private
Current maximum y value.
Definition at line 174 of file adxl_store.h.
Referenced by AdxlDataStore(), calcMaxXYZ(), reset(), and task().
z_max
float z_max = 0 private
Current maximum z value.
Definition at line 175 of file adxl_store.h.
Referenced by AdxlDataStore(), calcMaxXYZ(), reset(), and task().
The documentation for this class was generated from the following files:
data/adxl_store.h
data/adxl_store.cpp