AXO X1: RmsStore Class Reference
RmsStore Class Reference
RmsStore class derived from task base class.
#include <rms_store.h>
Detailed Description
RmsStore class derived from task base class.
Detailed Description
The RMS storage class is responsible to store the received RMS and hit values from RMS task and to forward them to the data manager task. On receiving a RMS report request from power manager task, the request shall be also forwarded to the data manager task. The RMS storage class provides a store and reset method and methods to print out the data for testing purposes. Message Interaction:
Receive
RMS task
Power manager task
RMS storage (self, callback function for shell command 'r')
Transmit
Data manager task
RMS storage (self, callback function for shell command 'r')
Definition at line 74 of file rms_store.h.
Public Member Functions
RmsStore (const char *name="??", uint8_t num_seconds=10)
RMS storage task constructor.
virtual ~RmsStore ()
RMS storage task destructor.
void task (void) override
RMS storage task function.
void store (const adxl_rms_data &src)
Function to store data of type struct adxl_rms_data.
void dump ()
Function to print out last stored data.
void dumpAll ()
Function to print out stored data.
void reset ()
Function to delete the stored data.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static int shell_dump (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'r'.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the RMS storage task.
Private Member Functions
RmsStore ()=delete
Private Attributes
uint8_t capacity
Store RMS and hit values for 'capacity' seconds.
bool full
Flag indicating, that the reserved memory is full.
bool idle
std::vector< adxl_rms_data > v
The reserved memory, a vector of type struct adxl_rms_data.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
RmsStore() [1/2]
RmsStore (const char * name = "??", uint8_t num_seconds = 10) explicit
RMS storage task constructor.
Parameters
name The name of the class
num_seconds Number of seconds the memory shall be reserved for
The constructor initializes the member variables capacity with parameter num_seconds, full with false and idle with true. It allocate and register a mailbox and reserve num_seconds entries for storing the data in vector v by calling vector class method reserve.
Definition at line 45 of file rms_store.cpp.
References Mbox::eRmsStore, pInMbox, Mbox::registerMbox(), and v.
~RmsStore()
~RmsStore () virtual
RMS storage task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 66 of file rms_store.cpp.
RmsStore() [2/2]
RmsStore () private delete
Member Function Documentation
task()
void task (void) override virtual
RMS storage task function.
The function directly enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eAdxl37xRmsData: If RMS storage task is in idle state, indicated by flag idle, flag idle is set to false and stored data will be deleted by calling member function reset. Afterwards the received data will be extracted from messages payload into structure of type struct adxl_rms_data and stored in vector by calling member function store. If the vector was not full, indicated by flag full, the data will be forwarded as it is to the data manager task and the pointer to message pElem is set to 0 to prevent releasing the message back to the pool.
eAdxl37xIdle: The flag idle will be set to true and the last entry of the currently stored data will be printed out by call of member function dump.
eRmsReport: The message will be forwarded as it is to the data manager task and the pointer to message pElem is set to 0 to prevent releasing the message back to the pool.
eAdxlStorageDumpAll: All currently stored data will be printed out by call of member function dumpAll.
For more details see also message sequence charts in section Measurement
Implements Task.
Definition at line 159 of file rms_store.cpp.
References dump(), dumpAll(), eAdxl37xIdle, eAdxl37xRmsData, eAdxlStorageDumpAll, Mbox::eDataManager, Mbox::eHttpConnector, eRmsReport, PoolElem::free(), full, PoolElem::getBuffer(), idle, PoolElem::mtype, Task::myName, pInMbox, Mbox::read(), reset(), Mbox::send(), store(), and UNIT_TEST_STOP_LOOP.
store()
void store (const adxl_rms_data & src)
Function to store data of type struct adxl_rms_data.
Parameters
src The data to be stored of type struct adxl_rms_data
The function checks, if vector v is still full, in this case flag full is set to true and the function returns immediately. Oterwise the data will be stored in vector v by calling vector class method push_back.
Definition at line 77 of file rms_store.cpp.
References capacity, adxl_rms_data::critical_hits, full, adxl_rms_data::medium_hits, v, adxl_rms_data::x, adxl_rms_data::y, and adxl_rms_data::z.
Referenced by task().
dump()
void dump ()
Function to print out last stored data.
If vector v is empty, the function returns immediately, otherwise it prints out the last stored data in vector v of type struct adxl_rms_data.
Definition at line 109 of file rms_store.cpp.
References adxl_rms_data::critical_hits, adxl_rms_data::medium_hits, v, adxl_rms_data::x, adxl_rms_data::y, and adxl_rms_data::z.
Referenced by task().
dumpAll()
void dumpAll ()
Function to print out stored data.
The function prints out all the stored data in vector v.
Definition at line 96 of file rms_store.cpp.
References v.
Referenced by task().
reset()
void reset ()
Function to delete the stored data.
The function deletes all the stored data in vector v by calling vector class method clear.
Definition at line 125 of file rms_store.cpp.
References full, and v.
Referenced by task().
shell_dump()
int shell_dump (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'r'.
The function request a message from message pool, set message type to eAdxlStorageDumpAll, set eMain as sender and send message to RMS storage mailbox.
Note
For testing only: trigger dump via shell command
Definition at line 226 of file rms_store.cpp.
References eAdxlStorageDumpAll, and Mbox::sendMsg().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the RMS storage task.
Definition at line 80 of file rms_store.h.
Referenced by RmsStore(), and task().
capacity
uint8_t capacity private
Store RMS and hit values for 'capacity' seconds.
Definition at line 92 of file rms_store.h.
Referenced by store().
full
bool full private
Flag indicating, that the reserved memory is full.
Definition at line 93 of file rms_store.h.
Referenced by reset(), store(), and task().
idle
bool idle private
Flag indicating, that no data has been received for more than 1 second
Definition at line 94 of file rms_store.h.
Referenced by task().
v
std::vector<adxl_rms_data> v private
The reserved memory, a vector of type struct adxl_rms_data.
Definition at line 97 of file rms_store.h.
Referenced by dump(), dumpAll(), reset(), RmsStore(), and store().
The documentation for this class was generated from the following files:
data/rms_store.h
data/rms_store.cpp