AXO X1: LteConnector Class Reference
LteConnector Class Reference
LTE connector class derived from task base class.
#include <lte_connector.h>
Detailed Description
LTE connector class derived from task base class.
Detailed Description
LTE connector task handle the connection to the LTE modem, modem wake up and sleep behaviour and inform its listener tasks (power manager and MQTT connector) about these events. It uses the nRF PDN library API and LTE Link API via AT commands to communicate with LTE modem and to receive PDN and LTE Link events. See details in LTE Link API documentation and for PDN library API in PDN library API documentation
The LteConnector class provides two handler functions to receive LTE link and PDN events, a method to send messages to its own (LTE connector's) mailbox, which is used by the handler functions to transform external events to internal messages of type PoolElem. It provide a timer callback function and a timer expired function, used to transform external timer expiry event from interrupt context to internal timer expired message of type PoolElem. Furthermore it provide methods to register listener tasks, to notify listener tasks about received external events and to report eDRX values to data manager task. Message Interaction:
Receive
External PDN and LTE Link events
Timer interrupt callback
LTE connector task (self)
Power manager task
Transmit
LTE connector task (self)
Power manager task
MQTT connector task
Data manager task
Definition at line 112 of file lte_connector.h.
Public Member Functions
LteConnector (const char *name="??")
LteConnector task constructor.
LteConnector ()=delete
virtual ~LteConnector ()
LteConnector task destructor.
void task (void) override
LTE connector task function.
void timer1_expired ()
Timer expired function for unused cyclic timer.
void registerListener (Mbox *listener)
Function to register a listener.
void notify (msgType msg)
Send message to all registered listeners.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for unused cyclic timer.
static void sendMsg2OwnMbox (msgType msg)
Send message to its own (LTE connectors) mailbox.
static void lte_event_handler (const struct lte_lc_evt *const evt)
LteConnector LTE link event handler function.
static void pdn_event_handler (uint8_t cid, enum pdn_event event, int reason)
LteConnector PDN event handler function.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Timer * myTimer
One shot timer to control connection timeout and connection retry.
Private Attributes
bool bLteConnected
Flag indicating if LTE is connected or not.
bool bConnectRetry
Mbox * listeners [max_listeners]
Static Private Attributes
static const uint32_t connectTimeout = 15*60
static const uint32_t connectRetryTime = 24*60*60
static const uint8_t max_listeners
Maximum number of listener tasks.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
LteConnector() [1/2]
LteConnector (const char * name = "??") explicit
LteConnector task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocates and initialize the one shot timer with duration of 15 min to control connection timeout and connection retry. Finally the flags bLteConnected and bConnectRetry will be set to false.
Definition at line 230 of file lte_connector.cpp.
References bConnectRetry, bLteConnected, connectTimeout, Mbox::eLteConnector, listeners, max_listeners, myTimer, pInMbox, Mbox::registerMbox(), and timer_cb().
LteConnector() [2/2]
LteConnector () delete
~LteConnector()
~LteConnector () virtual
LteConnector task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 251 of file lte_connector.cpp.
Member Function Documentation
task()
void task (void) override virtual
LTE connector task function.
Initially the function register the callback functions for PDN events by calling the function pdn_default_ctx_cb_reg from nRF PDN library API and for LTE events by calling function lte_lc_register_handler from nRF public API for the LTE Link Controller. With call of function lte_lc_modem_events_enable the LTE connector enable the modem domain events, which will be handled by LTE link event handler lte_event_handler. LTE module will be initialized and modem will be configured by call of function lte_lc_init and modem's functional mode is set to LTE_LC_FUNC_MODE_ACTIVATE_UICC by calling function lte_lc_func_mode_set, which activate UICC (Universal Integrated Circuit Card) notifications and is required to read IMSI without network connection.
Afterwards the function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On timer expiry the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static. Afterwards the function checks if flag bConnectRetry is true and in this case it triggers a reset by call of function sys_reboot. If flag bConnectRetry is not true, the function checks if LTE is still connected (flag bLteConnected is false). In this case the function switch of LTE modem by calling the functions lte_lc_offline, lte_lc_deinit and lte_lc_power_off. Than timer will be sterted with duration of connectRetryTime (24 hours) and flag bConnectRetry is set to true.
eLteConnected: Listeners will be informed by calling member function notify with message of type eLteConnected and flag bLteConnected will be set to true.
eLteDisconnected: Listeners will be informed by calling member function notify with message of type eLteDisconnected and flag bLteConnected will be set to false.
eLteSleepEnter: Listeners will be informed by calling member function notify with message of type eLteSleepEnter.
eLteSleepExit: Listeners will be informed by calling member function notify with message of type eLteSleepExit and a timer will be started with duration connectTimeout (15 min).
eIp6Up: Will be ignored, only debug message at info level will be printed.
eIp6Down: Will be ignored, only debug message at info level will be printed.
eResume: With call of function lte_lc_normal modem will be switched to full functionality. Power Saving Mode will be enabled enabled by calling function lte_lc_psm_req and a LTE connection will be established by calling function lte_lc_connect_async.
eSuspend: Will be ignored, only debug message at info level will be printed
Implements Task.
Definition at line 405 of file lte_connector.cpp.
References bConnectRetry, bLteConnected, connectRetryTime, connectTimeout, eIp6Down, eIp6Up, eLteConnected, eLteDisconnected, eLteSleepEnter, eLteSleepExit, eResume, eSuspend, eTimerExpired, PoolElem::free(), lte_event_handler(), PoolElem::mtype, Task::myName, myTimer, notify(), pdn_event_handler(), pInMbox, Mbox::read(), Timer::start(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for unused cyclic timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call LTE connector timer expired function timer1_expired.
Definition at line 264 of file lte_connector.cpp.
References timer1_expired().
Referenced by LteConnector().
sendMsg2OwnMbox()
void sendMsg2OwnMbox (msgType msg) static
Send message to its own (LTE connectors) mailbox.
Parameters
msg The message type
The function send a message of type msg to to its own (LTE connectors) mailbox by calling function sendMsg provided by Mbox class.
Definition at line 294 of file lte_connector.cpp.
References Mbox::sendMsg().
Referenced by lte_event_handler(), and pdn_event_handler().
timer1_expired()
void timer1_expired ()
Timer expired function for unused cyclic timer.
The function initializes the static pool element e1 with message type eTimerExpired, set LTE connector as sender and put message into own (LTE connector's) mailbox.
Definition at line 279 of file lte_connector.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
registerListener()
void registerListener (Mbox * listener)
Function to register a listener.
Parameters
listener Pointer to the mailbox of the listener
The function enter a loop over the maximum number of listeners and if there is no listener registered at index i of array listeners (pointer to mailbox is NULL), it register the listener by copy the pointer to the mailbox in array listeners at index i, before leaving the function.
Definition at line 340 of file lte_connector.cpp.
References listeners, and max_listeners.
Referenced by main().
notify()
void notify (msgType msg)
Send message to all registered listeners.
Parameters
msg The message type
The function enter a loop over the maximum number of listeners and if a listener is registered (pointer to listener mailbox in array listeners not NULL) it requests for every registered listener a message from message pool, set message type to parameter msg, set eLteConnector as sender and send message to the listener's mailbox.
Definition at line 312 of file lte_connector.cpp.
References PoolElem::from, MsgPool::getNewElem(), MsgPool::inst(), listeners, max_listeners, PoolElem::mtype, and Mbox::write().
Referenced by task().
lte_event_handler()
void lte_event_handler (const struct lte_lc_evt *const evt) static
LteConnector LTE link event handler function.
Parameters
evt Pointer to the received LTE link event of type struct lte_lc_evt
The handler function notifies the application of sleep, wakeup and DRX events from LTE modem. These events will be mapped to internal message types and send to LTE connectors own or data manager mailbox before function returns.
Mapping is as follows:
LTE_LC_EVT_MODEM_SLEEP_ENTER -> eLteSleepEnter to own mailbox
LTE_LC_EVT_MODEM_SLEEP_EXIT -> eLteSleepExit to own mailbox
all other LTE link events: will be ignored (only debug message) In case of unexpected events the function print an error debug message returns immediatly.
Definition at line 68 of file lte_connector.cpp.
References LteMonitor::cereg_str_get(), eLteSleepEnter, eLteSleepExit, and sendMsg2OwnMbox().
Referenced by task().
pdn_event_handler()
void pdn_event_handler (uint8_t cid, enum pdn_event event, int reason) static
LteConnector PDN event handler function.
Parameters
cid The cell ID
event The received PDN event
reason error code
The handler function notifies the application of events related to the default PDN context, CID 0. The PDN events will be mapped to internal message types and send to LTE connectors own mailbox before function returns. Mapping is as follows:
PDN_EVENT_CNEC_ESM: will be ignored (only debug message)
PDN_EVENT_ACTIVATED -> eLteConnected
PDN_EVENT_DEACTIVATED -> eLteDisconnected
PDN_EVENT_IPV6_UP -> eIp6Up
PDN_EVENT_IPV6_DOWN -> eIp6Down In case of unexpected events the function print an error debug message returns immediatly
Definition at line 179 of file lte_connector.cpp.
References eIp6Down, eIp6Up, eLteConnected, eLteDisconnected, pdn_esm_strerror(), and sendMsg2OwnMbox().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the LTE connector
Definition at line 133 of file lte_connector.h.
Referenced by LteConnector(), task(), and timer1_expired().
myTimer
Timer* myTimer
One shot timer to control connection timeout and connection retry.
Definition at line 135 of file lte_connector.h.
Referenced by LteConnector(), and task().
bLteConnected
bool bLteConnected private
Flag indicating if LTE is connected or not.
Definition at line 138 of file lte_connector.h.
Referenced by LteConnector(), and task().
bConnectRetry
bool bConnectRetry private
Flag indicating if connect retry is active or not
Definition at line 139 of file lte_connector.h.
Referenced by LteConnector(), and task().
connectTimeout
const uint32_t connectTimeout = 15*60 static private
The connection timeout, if there is no LTE connection established after this specified time (15 minutes) the device shall deactivate LTE modem and switch to sleep mode
Definition at line 143 of file lte_connector.h.
Referenced by LteConnector(), and task().
connectRetryTime
const uint32_t connectRetryTime = 24*60*60 static private
If LTE modem is switched off and device is in sleep mode, it shall wake up after this time (24 hours) to try LTE connect again. This functionality is realized by reset of the device.
Definition at line 147 of file lte_connector.h.
Referenced by task().
max_listeners
const uint8_t max_listeners static private
Initial value:
=
        3
Maximum number of listener tasks.
Definition at line 149 of file lte_connector.h.
Referenced by LteConnector(), notify(), and registerListener().
listeners
Mbox* listeners[max_listeners] private
Array with pointer to the mailboxes of the listener tasks
Definition at line 151 of file lte_connector.h.
Referenced by LteConnector(), notify(), and registerListener().
The documentation for this class was generated from the following files:
net/lte_connector.h
net/lte_connector.cpp