AXO X1: ECDSASigner Class Reference
ECDSASigner Class Reference
ECDSASigner class to sign SHA checksum implemented according to C++ singleton design pattern.
#include <ecdsasign.h>
Detailed Description
ECDSASigner class to sign SHA checksum implemented according to C++ singleton design pattern.
The ECDSASigner class provides functions to store a private key, to sign a SHA256 hash checksum with that key and to print out the generated signature. The class is used to sign the hash checksum calculated over the raw or displacement data to be transfered via HTTP. The calculated signature will be attached and is sended as the last HTTP frame. Because the length of the signature can vary, the length is sended as first byte of the frame, followed by the signature. If the resulting length is less than 73 byte, the rest of the frame is filled with zeros.
Definition at line 64 of file ecdsasign.h.
Public Member Functions
~ECDSASigner ()
ECDSASigner class destructor.
void setPrivateKey (const std::string &pemKey)
Function to store a private key in PEM format.
std::string signHash (const unsigned char *hash, size_t hashLen)
Function to sign a SHA256 hash checksum.
void printSignature (const std::string &signature)
Function to print the signature to a terminal window.
Static Public Member Functions
static ECDSASigner * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
ECDSASigner ()
ECDSASigner class constructor.
std::string string_to_hex (const std::string &input)
Helper function to transform a string into its hexadecimal representation.
Private Attributes
mbedtls_pk_context pk
Context varaible.
mbedtls_ctr_drbg_context ctr_drbg
Context varaible.
std::string privateKeyPEM
The private key in PEM format.
Constructor & Destructor Documentation
~ECDSASigner()
~ECDSASigner ()
ECDSASigner class destructor.
The destructor releases the context variables of the MBEDTLS library by calling the functions mbedtls_pk_free and mbedtls_ctr_drbg_free.
Definition at line 126 of file ecdsasign.cpp.
References ctr_drbg, and pk.
ECDSASigner()
ECDSASigner () private
ECDSASigner class constructor.
The constructor initialize the context variables of the MBEDTLS library by calling the functions mbedtls_pk_init and mbedtls_ctr_drbg_init. Afterwards it enables the the entropy hardware for the usage of the random subsystem with the entropy API. By calling the function mbedtls_ctr_drbg_seed with an entropy function a seed will be generated for the further usage by the cryptografic services.
Definition at line 97 of file ecdsasign.cpp.
References ctr_drbg, entropy_func(), and pk.
Member Function Documentation
inst()
ECDSASigner * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 81 of file ecdsasign.cpp.
Referenced by HttpConnector::configure(), and HttpConnector::HandleRcvdData().
setPrivateKey()
void setPrivateKey (const std::string & pemKey)
Function to store a private key in PEM format.
Parameters
pemKey The key to be stored
The function store a private key in PEM format by calling function pmbedtls_pk_parse_key provided by the MBEDTLS library. Coding of PEM keys is Base64.
Definition at line 144 of file ecdsasign.cpp.
References entropy_func(), pk, and privateKeyPEM.
Referenced by HttpConnector::configure().
signHash()
std::string signHash (const unsigned char * hash, size_t hashLen)
Function to sign a SHA256 hash checksum.
Parameters
hash The SHA256 hash checksum to be signed
hashLen The length of the SHA256 hash checksum
Returns
Return the signature as std::string
The function sign the SHA256 hash checksum by calling function mbedtls_pk_sign provided by the MBEDTLS library and save the signature in an unsigned char array. The array will be converted in a std::string and returned.
Definition at line 167 of file ecdsasign.cpp.
References ctr_drbg, and pk.
Referenced by HttpConnector::HandleRcvdData().
printSignature()
void printSignature (const std::string & signature)
Function to print the signature to a terminal window.
Parameters
signature The string containing the signature
The function transform the string into its hexadecimal representation and print the hexadecimal representation with debug message at warning level.
Definition at line 212 of file ecdsasign.cpp.
References string_to_hex().
Referenced by HttpConnector::HandleRcvdData().
string_to_hex()
std::string string_to_hex (const std::string & input) private
Helper function to transform a string into its hexadecimal representation.
Parameters
input The input string
The function transform a string into its hexadecimal representation.
Definition at line 191 of file ecdsasign.cpp.
Referenced by printSignature().
Field Documentation
pk
mbedtls_pk_context pk private
Context varaible.
Definition at line 79 of file ecdsasign.h.
Referenced by ECDSASigner(), setPrivateKey(), signHash(), and ~ECDSASigner().
ctr_drbg
mbedtls_ctr_drbg_context ctr_drbg private
Context varaible.
Definition at line 80 of file ecdsasign.h.
Referenced by ECDSASigner(), signHash(), and ~ECDSASigner().
privateKeyPEM
std::string privateKeyPEM private
The private key in PEM format.
Definition at line 81 of file ecdsasign.h.
Referenced by setPrivateKey().
The documentation for this class was generated from the following files:
util/ecdsasign.h
util/ecdsasign.cpp