AXO X1: PowerMgrX1 Class Reference
PowerMgrX1 Class Reference
Power Manager class for AXO X1 devices derived from Power Manager base class.
#include <power_mgr_x1.h>
Detailed Description
Power Manager class for AXO X1 devices derived from Power Manager base class.
Detailed Description
The power manager X1 class provides the following timer:
BoostCtrlTimer: Timer to control boost on before initial metrics tx (eLteWakeTmo)
myTLteStartDelayTimerimer3: Timer to control inital LTE start delay (eLteStartTmo)
AdxlWakeupTimer: Timer to control adxl wakeup to measurements tx (eLteWakeTmo) It provides a method to request switching on and off the boost converter, methods to request RMS, environment, battery, HW and LTE reports for metrics collection and methods to report reset cause and boot counter to the data manager task. It furthermore implements the from base class required methods taskInit and message_handler, which are called in the task function provided by the base class. Message Interaction:
Receive
Timer interrupt callback
LTE connector task
MQTT connector task
RMS store task
Power manager task
Transmit
Boost converter task
RMS store task
SHTCX task
Battery manager task
HW Metrics task
Data manager task
Power manager task (self, transmission in timer callback)
Definition at line 85 of file power_mgr_x1.h.
Public Types
enum PmX1Tmo { eLteStartTmo = 30 , eLteWakeTmo = 30 , kNumTimerEvents }
Power manager timeout values.
Public Types inherited from PowerMgr
enum PmState { eOff = 0 , eOn , kNumStates }
Power manager states.
enum PmTmo { eMetricsTmo = 2 * 60 * 60 , kNumTimerEvents }
Power manager timeout values.
Public Member Functions
PowerMgrX1 (const char *name="??")
Power manager X1 task constructor.
virtual ~PowerMgrX1 ()
Power manager X1 task destructor.
virtual void taskInit (void)
virtual PoolElem * message_handler (PoolElem *pElem)
void BoostCtrlTimer_expired ()
Timer expired function for initial boost on timer.
void LteStartDelayTimer_expired ()
Timer expired function for inital LTE start delay timer.
void AdxlWakeupTimer_expired ()
Timer expired function for adxl wakeup to measurements tx timer.
void reqBoostConverter (bool on=false)
Send resume or suspend message to boost converter task.
Public Member Functions inherited from PowerMgr
PowerMgr (const char *name="??")
Power manager task constructor.
virtual ~PowerMgr ()
Power manager task destructor.
virtual void task (void)
virtual void configure ()
Power Manager virtual task configure function.
void MetricsTxTimer_expired ()
Timer expired function for metrics TX interval timer.
void reqRmsReport ()
Send request accelerometer data message to RMS store task.
void reportResetCause ()
Send reset reason message to data manager task.
void reportBootCnt ()
Send boot count message to data manager task.
void registerMetricProvider (uint8_t mboxId, uint16_t mtype)
Register a task that contributes to device metrics for callback.
void metricProviderNotify (uint8_t mboxId, uint16_t mtype)
Send metric request message to a task that contributes to metrics.
void metricProviderNotifyAll ()
Send metric request message to all registered mailboxes.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static void BoostCtrlTimer_cb (k_timer *timer)
Timer callback function for initial boost on timer.
static void LteStartDelayTimer_cb (k_timer *timer)
Timer callback function for inital LTE start delay timer.
static void AdxlWakeupTimer_cb (k_timer *timer)
Timer callback function for adxl wakeup to measurements tx timer.
Static Public Member Functions inherited from PowerMgr
static void MetricsTxTimer_cb (k_timer *timer)
Timer callback function for metrics TX interval timer.
static void uart0_off ()
Function to disable UART.
static void uart0_set_enable (bool enable)
Function to enable or disable UART.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Timer * BoostCtrlTimer
Timer to control boost on before initial metrics tx (eLteWakeTmo)
Timer * LteStartDelayTimer
Timer to control inital LTE start delay (eLteStartTmo)
Timer * AdxlWakeupTimer
bool lte_connected
Flag indicating LTE is connected or not.
Data Fields inherited from PowerMgr
Mbox * pInMbox
Mailbox of the power manager.
Timer * MetricsTxTimer
Timer to control metrics TX interval.
uint32_t metricsTmo
timeout for metrics tx request (e.g. 2h)
uint32_t reason
Reset reason.
std::string reason_str
Reset reason string.
int32_t boot_cnt
Boot counter.
std::vector< uint8_t > metricProviders
report request receivers
std::vector< uint16_t > metricType
message type in report request
Private Member Functions
PowerMgrX1 ()=delete
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Member Enumeration Documentation
PmX1Tmo
enum PmX1Tmo
Power manager timeout values.
Enumerator
eLteStartTmo
initial timeout for boost on to lte start (e.g. 30 sec)
eLteWakeTmo
timeout for boost on to lte wake by tx (e.g. 30 sec)
kNumTimerEvents
Indicator for the number of timeout events.
Definition at line 88 of file power_mgr_x1.h.
Constructor & Destructor Documentation
PowerMgrX1() [1/2]
PowerMgrX1 (const char * name = "??") explicit
Power manager X1 task constructor.
Parameters
name The name of the class
The constructor register all provider tasks for metric updates by calling function registerMetricProvider provided by the power manager base class. The provider tasks are:
The shtcx task for temperature and humidity
The battery manager task for battery metrics
The HW metrics task for hardware metrics
The data manager task for LTE metrics Afterwards it allocates the timer for initial boost on, inital LTE start delay and adxl wakeup to measurements transmission.
Definition at line 171 of file power_mgr_x1.cpp.
References AdxlWakeupTimer, AdxlWakeupTimer_cb(), BoostCtrlTimer, BoostCtrlTimer_cb(), eBattReport, eHwMetrics, eHwReport, eLteReport, eLteWakeTmo, eShtcxReport, LteStartDelayTimer, LteStartDelayTimer_cb(), and PowerMgr::registerMetricProvider().
~PowerMgrX1()
~PowerMgrX1 () virtual
Power manager X1 task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 206 of file power_mgr_x1.cpp.
PowerMgrX1() [2/2]
PowerMgrX1 () private delete
Member Function Documentation
taskInit()
void taskInit (void) virtual
Implements PowerMgr.
Definition at line 219 of file power_mgr_x1.cpp.
References LteStartDelayTimer, reqBoostConverter(), and Timer::start().
message_handler()
PoolElem * message_handler (PoolElem * pElem) virtual
Implements PowerMgr.
Definition at line 283 of file power_mgr_x1.cpp.
References AdxlWakeupTimer, BoostCtrlTimer, eAdxl37xWake, eAdxlWakeupTimerExpired, eBoostCtrlTimerExpired, eLteConnected, eLteDisconnected, eLteSleepEnter, eLteSleepExit, eLteStartDelayTimerExpired, eLteStartTmo, eMetricsTxTimerExpired, eMqttConnected, eResume, lte_connected, PowerMgr::metricProviderNotifyAll(), PowerMgr::MetricsTxTimer, PoolElem::mtype, PowerMgr::reportBootCnt(), PowerMgr::reportResetCause(), reqBoostConverter(), PowerMgr::reqRmsReport(), Mbox::sendMsg(), Timer::start(), and PowerMgr::uart0_off().
BoostCtrlTimer_cb()
void BoostCtrlTimer_cb (k_timer * timer) static
Timer callback function for initial boost on timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call power manager timer expired function BoostCtrlTimer_expired.
Definition at line 71 of file power_mgr_x1.cpp.
References BoostCtrlTimer_expired().
Referenced by PowerMgrX1().
BoostCtrlTimer_expired()
void BoostCtrlTimer_expired ()
Timer expired function for initial boost on timer.
The function initializes the static pool element e1 with message type eBoostCtrlTimerExpired, set power manager as sender and put message into own (powermanager's) mailbox.
Definition at line 86 of file power_mgr_x1.cpp.
References eBoostCtrlTimerExpired, PowerMgr::pInMbox, and Mbox::write().
Referenced by BoostCtrlTimer_cb().
LteStartDelayTimer_cb()
void LteStartDelayTimer_cb (k_timer * timer) static
Timer callback function for inital LTE start delay timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call power manager timer expired function LteStartDelayTimer_expired.
Definition at line 102 of file power_mgr_x1.cpp.
References LteStartDelayTimer_expired().
Referenced by PowerMgrX1().
LteStartDelayTimer_expired()
void LteStartDelayTimer_expired ()
Timer expired function for inital LTE start delay timer.
The function initializes the static pool element e1 with message type eLteStartDelayTimerExpired, set power manager as sender and put message into own (powermanager's) mailbox.
Definition at line 117 of file power_mgr_x1.cpp.
References eLteStartDelayTimerExpired, PowerMgr::pInMbox, and Mbox::write().
Referenced by LteStartDelayTimer_cb().
AdxlWakeupTimer_cb()
void AdxlWakeupTimer_cb (k_timer * timer) static
Timer callback function for adxl wakeup to measurements tx timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call power manager timer expired function AdxlWakeupTimer_expired.
Definition at line 134 of file power_mgr_x1.cpp.
References AdxlWakeupTimer_expired().
Referenced by PowerMgrX1().
AdxlWakeupTimer_expired()
void AdxlWakeupTimer_expired ()
Timer expired function for adxl wakeup to measurements tx timer.
The function initializes the static pool element e1 with message type eAdxlWakeupTimerExpired, set power manager as sender and put message into own (powermanager's) mailbox.
Definition at line 149 of file power_mgr_x1.cpp.
References eAdxlWakeupTimerExpired, PowerMgr::pInMbox, and Mbox::write().
Referenced by AdxlWakeupTimer_cb().
reqBoostConverter()
void reqBoostConverter (bool on = false)
Send resume or suspend message to boost converter task.
Parameters
on bool parameter to select message type eResume or eSuspend
The function send a resume or suspend message to the boost converter task by calling function sendMsg provided by class Mbox. The message type is set according to input parameter 'on' (eResume if on = true, eSuspend if on = false). This request is the trigger to switch boost converter on or off.
Definition at line 55 of file power_mgr_x1.cpp.
References eResume, eSuspend, and Mbox::sendMsg().
Referenced by message_handler(), and taskInit().
Field Documentation
BoostCtrlTimer
Timer* BoostCtrlTimer
Timer to control boost on before initial metrics tx (eLteWakeTmo)
Definition at line 114 of file power_mgr_x1.h.
Referenced by message_handler(), and PowerMgrX1().
LteStartDelayTimer
Timer* LteStartDelayTimer
Timer to control inital LTE start delay (eLteStartTmo)
Timer to control adxl wakeup to measurements tx (eLteWakeTmo)
Definition at line 116 of file power_mgr_x1.h.
Referenced by PowerMgrX1(), and taskInit().
AdxlWakeupTimer
Timer* AdxlWakeupTimer
Definition at line 118 of file power_mgr_x1.h.
Referenced by message_handler(), and PowerMgrX1().
lte_connected
bool lte_connected
Flag indicating LTE is connected or not.
Definition at line 120 of file power_mgr_x1.h.
Referenced by message_handler().
The documentation for this class was generated from the following files:
pm/power_mgr_x1.h
pm/power_mgr_x1.cpp