AXO X1: DataManager Class Reference
DataManager Class Reference
DataManager class derived from task base class.
#include <pdata.h>
Detailed Description
DataManager class derived from task base class.
Detailed Description
The data manager class is responsible to collect metrics and measurement data, to construct the metrics and measurement JSON strings with support of the metrics builder class and the measurement builder class and to publish metrics and measurement JSON strings by sending them to the MQTT connector task. It provides two publish methods, one for metrics and the other one for measurement data. Message Interaction:
Receive
LTE monitor task
LTE connector task
Power manager task
AD converter task
Shtcx task
HW metrics task
Transmit
MQTT connector task
Definition at line 62 of file pdata.h.
Public Member Functions
DataManager (const char *name="??", bool have_mqtt_connector=true)
Data manager task constructor.
DataManager ()=delete
virtual ~DataManager ()
Data manager task destructor.
void task (void) override
Data manager task function.
void timer1_expired ()
Timer expired function for the timer (UNUSED)
virtual void configure ()
Data manager virtual task configure function.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the timer (UNUSED)
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Private Member Functions
void publishMeasurements ()
Send function to publish measurement JSON string to MQTT connector task.
void publishMetrics ()
Send function to publish metrics JSON string to MQTT connector task.
Private Attributes
Timer * myTimer
Timer (UNUSED)
Mbox * pInMbox
Mailbox of the data manager task.
MetricsBuilder metrics
Instance of metrics builder helper class.
MeasurementBuilder measurements
Instance of measurement builder helper class.
bool have_mqtt_connector
flag deciding if data are sent to http connector
bool bDispModeOff
double rms_z_thres
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
DataManager() [1/2]
DataManager (const char * name = "??", bool have_mqtt_connector = true) explicit
Data manager task constructor.
Parameters
name The name of the class
have_mqtt_connector Flag indicationg if MQTT Connector is used (X1 devices) or not (MINI devices)
The constructor allocate and register the mailbox of the AD converter task and allocates and initialize the cyclic timer for
Todo:
with duration of 10 ms and period of 20 ms.
Definition at line 96 of file pdata.cpp.
References Mbox::eDataManager, have_mqtt_connector, myTimer, pInMbox, Mbox::registerMbox(), and timer_cb().
DataManager() [2/2]
DataManager () delete
~DataManager()
~DataManager () virtual
Data manager task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 114 of file pdata.cpp.
Member Function Documentation
task()
void task (void) override virtual
Data manager task function.
The function directly enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eLteReport: Received report request, change sender to eDataManager and forward request to LTE monitor task. The pointer pElem will be set to 0, to prevent releasing the message.
eLteLinkQuality: Add payload to metrics JSON string by calling function add provided by metricsBuilder class. In case metrics JSON string is complete, finalize and publish it by calling function finalize of metricsBuilder class and member function publishMetrics. Finally metrics JSON string will be cleared by calling function reset also provided by metricsBuilder class.
eLteBattVoltage: same as eLteLinkQuality
eLteTemperature: same as eLteLinkQuality
eLtePsmAct: same as eLteLinkQuality
eResetCause: same as eLteLinkQuality
eBootCnt: same as eLteLinkQuality
eAdcData: same as eLteLinkQuality
eShtcxTemperature: same as eLteLinkQuality
eShtcxHumidity: same as eLteLinkQuality
eLteIMSI: same as eLteLinkQuality
eLteFwVersion: same as eLteLinkQuality
eHwMetrics: same as eLteLinkQuality
eAdxl37xRmsData: Add RMS values to payload variable of class measurement and store hit values in member varaibles of this class
eDispStatistics: same as eRmsReport
eMaxXYZ: Add x, y and z maximum values to member variables of measurement class
eRmsReport: In case measurement JSON string is complete, finalize and publish it by calling function finalize of measurementBuilder class and member function publishMeasurements. Finally measurement JSON string will be cleared by calling function reset also provided by measurementBuilder class.
eDispStatistics: In case measurement JSON string is complete, finalize and publish it by calling function finalize of measurementBuilder class and member function publishMeasurements. Finally measurement JSON string will be cleared by calling function reset also provided by measurementBuilder class.
Todo:
remove unused timer ?
Implements Task.
Definition at line 267 of file pdata.cpp.
References MeasurementBuilder::add(), MetricsBuilder::add(), bDispModeOff, eAdcData, eAdxl37xRmsData, eBootCnt, Mbox::eDataManager, eDispStatistics, eHwMetrics, eLteBattVoltage, eLteFwVersion, eLteIMSI, eLteLinkQuality, Mbox::eLteMonitor, eLtePsmAct, eLteReport, eLteTemperature, eMaxXYZ, eResetCause, eRmsReport, eShtcxHumidity, eShtcxTemperature, eTimerExpired, MeasurementBuilder::finalize(), MetricsBuilder::finalize(), PoolElem::free(), PoolElem::from, MetricsBuilder::isComplete(), MeasurementBuilder::isComplete(), measurements, metrics, PoolElem::mtype, Task::myName, pInMbox, MetricsBuilder::print(), publishMeasurements(), publishMetrics(), Mbox::read(), MeasurementBuilder::reset(), MetricsBuilder::reset(), rms_z_thres, Mbox::send(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the timer (UNUSED)
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call timer expired member function timer1_expired with the channel bitmask as parameter extracted from the user-specific data of type AdcTimerInfo.
Definition at line 60 of file pdata.cpp.
References timer1_expired().
Referenced by DataManager().
timer1_expired()
void timer1_expired ()
Timer expired function for the timer (UNUSED)
Parameters
chmask Channel bitmask
The function initializes the static pool element e1 with message type eTimerExpired, set AD converter task as sender, copy channel bitmask chmask in the payload of the message and put message into own (data managers's) mailbox.
Definition at line 78 of file pdata.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
configure()
void configure () virtual
Data manager virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to sensors by call of the function getCfgSensor to get the sensor threshold values, retrieve the configuration version by call of function getCfgGeneral, retrieve the configuration related to datalog by call of function getCfgDatalog and retrieve the configuration related to metrics by call of function getCfgMetrics. Configuration version, metrics interval, thresholds and activation flags will be stored in internal string variables of the MetricsBuilder class by calling its related setter functions.
Private variable bDispModeOff will be set according to configuration string dispmodeoff and private variable rms_z_thres according to rms_thres.
Reimplemented from Task.
Definition at line 134 of file pdata.cpp.
References _stCfgSensor::actthres, bDispModeOff, _stCfgSensor::deactthres, _stCfgDatalog::dispmodeoff, _stCfgDatalog::disptransferon, eSensor_adxl372, Config::getCfgDatalog(), Config::getCfgGeneral(), Config::getCfgMetrics(), Config::getCfgSensor(), KeyGen::getPublicKey(), Config::inst(), KeyGen::inst(), _stCfgMetrics::interval, _stCfgDatalog::max_raw_per_day, metrics, _stCfgDatalog::rawtransferon, _stCfgDatalog::rms_thres, rms_z_thres, MetricsBuilder::set_max_raw_per_day(), MetricsBuilder::set_Z_RmsThres(), MetricsBuilder::setActivationThres(), MetricsBuilder::setConfigVersion(), MetricsBuilder::setDeactivationThres(), MetricsBuilder::setDispModeOffFlag(), MetricsBuilder::setDispTransferOnFlag(), MetricsBuilder::setMetricsInterval(), MetricsBuilder::setPublicKey(), MetricsBuilder::setRawTransferOnFlag(), and _stCfgGeneral::version.
Referenced by main().
publishMeasurements()
void publishMeasurements () private
Send function to publish measurement JSON string to MQTT connector task.
The function retrieve the measurement JSON string from the MeasurementBuilder class, request a message from message pool, copy the measurement JSON string in the payload of the message by calling function putString of the PoolElem class, set message type to eMeasurements, set eDataManager as sender and send message to MQTT connector mailbox.
Definition at line 207 of file pdata.cpp.
References eMeasurements, MeasurementBuilder::getPayload(), have_mqtt_connector, measurements, and Mbox::sendMsg().
Referenced by task().
publishMetrics()
void publishMetrics () private
Send function to publish metrics JSON string to MQTT connector task.
The function retrieve the metrics JSON string from the MetricsBuilder class, request a message from message pool, copy the metrics JSON string in the payload of the message by calling function putString of the PoolElem class, set message type to eMetrics, set eDataManager as sender and send message to MQTT connector mailbox.
Definition at line 184 of file pdata.cpp.
References eMetrics, MetricsBuilder::getPayload(), metrics, and Mbox::sendMsg().
Referenced by task().
Field Documentation
myTimer
Timer* myTimer private
Timer (UNUSED)
Definition at line 75 of file pdata.h.
Referenced by DataManager().
pInMbox
Mbox* pInMbox private
Mailbox of the data manager task.
Definition at line 76 of file pdata.h.
Referenced by DataManager(), task(), and timer1_expired().
metrics
MetricsBuilder metrics private
Instance of metrics builder helper class.
Definition at line 79 of file pdata.h.
Referenced by configure(), publishMetrics(), and task().
measurements
MeasurementBuilder measurements private
Instance of measurement builder helper class.
Definition at line 81 of file pdata.h.
Referenced by publishMeasurements(), and task().
have_mqtt_connector
bool have_mqtt_connector private
flag deciding if data are sent to http connector
Definition at line 83 of file pdata.h.
Referenced by DataManager(), and publishMeasurements().
bDispModeOff
bool bDispModeOff private
Flag indicating that displacement calculation is disabled (15 sec raw data storage)
Definition at line 86 of file pdata.h.
Referenced by configure(), and task().
rms_z_thres
double rms_z_thres private
RMS Z Threshold to enable / disable Raw/Displacement data transmission and displacement calculation
Definition at line 89 of file pdata.h.
Referenced by configure(), and task().
The documentation for this class was generated from the following files:
data/pdata.h
data/pdata.cpp