AXO X1: ResetCtrl Class Reference
ResetCtrl Class Reference
Reset Control class derived from task base class.
#include <reset_ctrl.h>
Detailed Description
Reset Control class derived from task base class.
Detailed Description
The Reset Control class implements the cyclic power cycle reset (cold start). It controls Pin P0.01 of nRF9160 which can trigger the reset. The cycle period is controlled by a timer.
The Reset Control class provide a timer callback function and a timer expired function, used to transform external timer expiry event from interrupt context to internal timer expired message of type PoolElem. Furthermore an initialization function and a trigger function, which perform the cold start reset. Message Interaction:
Receive
Timer interrupt callback
Reset control task (self)
Transmit
Reset control task (self)
Definition at line 68 of file reset_ctrl.h.
Public Member Functions
ResetCtrl (const char *name="??")
Reset control task constructor.
ResetCtrl ()=delete
virtual ~ResetCtrl ()
Reset control task destructor.
virtual void task (void)
Reset control task function.
void timer1_expired ()
Timer expired function for the cyclic timer for power cycle reset.
void initDevice ()
Function initDevice to initialize Pin P0.01.
void trigger ()
Function trigger initiates the power cycle reset (cold start)
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the cyclic timer for power cycle reset.
static void performSwReset ()
Convenience function to perform a SW reset.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the reset control task.
Timer * myTimer
Timer to control cold start cycle period.
Private Attributes
struct gpio_dt_spec trigger_gpio
Container for GPIO pin information.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
ResetCtrl() [1/2]
ResetCtrl (const char * name = "??") explicit
Reset control task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocate the cyclic timer for power cycle reset (cold start). Finally Pin P0.01 of nRF9160 will be initialized by calling function initDevice.
Definition at line 132 of file reset_ctrl.cpp.
References Mbox::eResetCtrl, initDevice(), myTimer, pInMbox, Mbox::registerMbox(), and timer_cb().
ResetCtrl() [2/2]
ResetCtrl () delete
~ResetCtrl()
~ResetCtrl () virtual
Reset control task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 152 of file reset_ctrl.cpp.
Member Function Documentation
task()
void task (void) virtual
Reset control task function.
Initially the cyclic timer for power cycle reset (cold start) will be started. Afterwards the function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On metrics TX interval timer expiry the pointer pElem will be set to 0, to prevent releasing the message because it is allocated static. Finally cold start will be initiated by calling function trigger. Since FW 1.74 cold start has been replaced by SW reset.
eColdStartReq: A cold start will be initiated by calling function trigger.
Implements Task.
Definition at line 210 of file reset_ctrl.cpp.
References eColdStartReq, eTimerExpired, PoolElem::free(), PoolElem::mtype, Task::myName, myTimer, pInMbox, Mbox::read(), Timer::start(), trigger(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the cyclic timer for power cycle reset.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call reset control timer expired function timer1_expired.
Definition at line 83 of file reset_ctrl.cpp.
References timer1_expired().
Referenced by ResetCtrl().
timer1_expired()
void timer1_expired ()
Timer expired function for the cyclic timer for power cycle reset.
The function initializes the static pool element e1 with message type eTimerExpired, set reset control as sender and put message into own (reset control's) mailbox.
Definition at line 116 of file reset_ctrl.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
initDevice()
void initDevice ()
Function initDevice to initialize Pin P0.01.
The function retrieve the static initializer for a gpio_dt_spec structure for Pin P0.01 and configure the pin to input and output inactive. Afterwards pin will be pulled to high (inactive) level. For verification current pin level is read back.
Definition at line 55 of file reset_ctrl.cpp.
References trigger_gpio, and ZEPHYR_USER_NODE.
Referenced by ResetCtrl().
trigger()
void trigger ()
Function trigger initiates the power cycle reset (cold start)
The function trigger the power cycle reset by pulling Pin P0.01 low for at least 7.5 seconds. For verification current pin level is read back.
Definition at line 97 of file reset_ctrl.cpp.
References trigger_gpio.
Referenced by task().
performSwReset()
void performSwReset () static
Convenience function to perform a SW reset.
The function disconnect from MQTT broker by calling function mqtt_helper_disconnect provided by NRF MQTT helper library, followed by two calls of function nrf_modem_at_printf provided by nrfxlib API with the AT commands 'AT+CFUN=0' and 'ATXFACTORYRESET=0' to disable the reset loop detection temporarily. Finally a SW reset will be performed by call of function sys_reboot.
Definition at line 169 of file reset_ctrl.cpp.
Referenced by FlashFS::clear_fs(), MqttConnector::connect(), MqttConnector::HandleFactoryDefault(), MqttConnector::HandleFsErase(), MqttConnector::HandleNewConfiguration(), and MqttConnector::on_publish().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the reset control task.
Definition at line 78 of file reset_ctrl.h.
Referenced by ResetCtrl(), task(), and timer1_expired().
myTimer
Timer* myTimer
Timer to control cold start cycle period.
Definition at line 79 of file reset_ctrl.h.
Referenced by ResetCtrl(), and task().
trigger_gpio
struct gpio_dt_spec trigger_gpio private
Container for GPIO pin information.
Definition at line 81 of file reset_ctrl.h.
Referenced by initDevice(), and trigger().
The documentation for this class was generated from the following files:
pm/reset_ctrl.h
pm/reset_ctrl.cpp