AXO X1: CFilter Class Reference
CFilter Class Reference
Digital filter class implemented according to C++ singleton design pattern.
#include <filter.h>
Detailed Description
Digital filter class implemented according to C++ singleton design pattern.
Detailed Description
The CFilter class handle digital zero phase filtering of recoreded acceleration data. It is implemented to filter the data sequentially and piecewise as the data is received from FRAM. For zero phase filtering the data will be filtered forward and backwards. The class provides methods to initialize forward and backward filtering, to filter the data in first, Nth and last iteration and functions to provide the filter order nfilt and the length of edge transients nfact. It also provides methods to calculate the initial conditions for forward and backward filtering.
Definition at line 55 of file filter.h.
Public Member Functions
virtual ~CFilter ()
CFilter class destructor.
void prepare_leftpad (vectord &leftpad, vectord InputStart)
Function to calculate initial conditions for forward filtering.
void prepare_rightpad (vectord &rightpad, vectord InputEnd)
Function to calculate initial conditions for forward filtering.
void fwfilter_init (double leftpad_0)
Function to prepair the forward filtering.
void bwfilter_init (double rightpad_reverse_0)
Function to prepair the backward filtering.
void filterFirstIter (const vectord &X, vectord &Y)
Function to start forward or backward filtering with first iteration.
void filterNthIter (vectord &X, vectord &Y)
Function to resume forward or backward filtering with next iteration.
void filterLastIter (vectord &X, vectord &Y)
Function to finish forward or backward filtering with last iteration.
void filtfilt_init (vectord B, vectord A)
Initialization of the filtfilt method.
int getNfact ()
Getter function to retrieve the length of edge transients.
int getNfilt ()
Getter function to retrieve the filter order.
Static Public Member Functions
static CFilter * inst ()
The inst function to retrieve the exclusiv only instance of the class.
Private Member Functions
CFilter ()
CFilter class constructor.
void add_index_range (vectori &indices, int beg, int end, int inc=1)
Function to add index values in vector.
void add_index_const (vectori &indices, int value, size_t numel)
Function to add constant values in vector.
void append_vector (vectord &vec, const vectord &tail)
Function to append a vector to another vector.
vectord subvector_reverse (const vectord &vec, int idx_end, int idx_start)
Function to reverse a sub-vector.
int max_val (const vectori &vec)
Function to retrieve the maximum value from a vector.
void filter_initialize (vectord B, vectord A, vectord &Zi)
Sub-Function to prepair the forward filtering.
Private Attributes
vectord b_coeff
vectord a_coeff
Vector of type double with B filter coefficents.
int nfilt
Vector of type double with A filter coefficents.
int nfact
length of edge transients
vectord zzi
vectord zi
Vector of type double with intermediate result.
size_t filter_order
Vector of type double with intermediate result.
const double * b
Poiter to B filter coefficents.
const double * a
Poiter to A filter coefficents.
double * z
Poiter to intermediate result vector.
vectord n_B
vectord n_A
Vector of type double with B filter coefficents.
vectord n_zi
Vector of type double with A filter coefficents.
vectord X_old
Vector of type double with intermediate result.
vectord Y_old
previous calculated Y values Y(n-1) .. Y(n-4)
Constructor & Destructor Documentation
~CFilter()
~CFilter () virtual
CFilter class destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 51 of file filter.cpp.
CFilter()
CFilter () private
CFilter class constructor.
The constructor is declared as private according to singleton pattern. It is called in the static inst function to create the exclusiv only instance of the class.
Definition at line 41 of file filter.cpp.
Member Function Documentation
inst()
CFilter * inst () static
The inst function to retrieve the exclusiv only instance of the class.
Returns
Returns a pointer to the class instance
In case there is no instance created, the constructor will be called to create the instance. Finally a pointer to the instance is returned.
Definition at line 61 of file filter.cpp.
Referenced by DispTask::DispTask(), DispTask::HandleDispFirstEntries(), DispTask::HandleDispLastEntries(), DispTask::HandleFwFiltData(), DispTask::HandleRawData(), DispTask::HandleRawDataStatus(), and DispTask::InitBwFiltering().
prepare_leftpad()
void prepare_leftpad (vectord & leftpad, vectord InputStart)
Function to calculate initial conditions for forward filtering.
Parameters
leftpad The output vector of type double
InputStart The input vector of type double
The function calculate initial conditions for forward filtering and store it in output vector leftpad.
Definition at line 485 of file filter.cpp.
References subvector_reverse().
Referenced by DispTask::HandleDispFirstEntries().
prepare_rightpad()
void prepare_rightpad (vectord & rightpad, vectord InputEnd)
Function to calculate initial conditions for forward filtering.
Parameters
rightpad The output vector of type double
InputEnd The input vector of type double
The function calculate initial conditions for backward filtering and store it in output vector rightpad.
Definition at line 501 of file filter.cpp.
References subvector_reverse().
Referenced by DispTask::HandleDispLastEntries().
fwfilter_init()
void fwfilter_init (double leftpad_0)
Function to prepair the forward filtering.
Parameters
leftpad_0 The value of leftpad vector at index 0
The function prepairs the forward filtering. It shall be called before start of forward filtering with function filterFirstIter.
Definition at line 244 of file filter.cpp.
References a_coeff, b_coeff, filter_initialize(), zi, and zzi.
Referenced by DispTask::HandleDispFirstEntries().
bwfilter_init()
void bwfilter_init (double rightpad_reverse_0)
Function to prepair the backward filtering.
Parameters
rightpad_reverse_0 The value of rightpad reversed vector at index 0
The function prepairs the backward filtering. It shall be called before start of backward filtering with function filterFirstIter.
Definition at line 259 of file filter.cpp.
References filter_order, n_zi, z, zi, and zzi.
Referenced by DispTask::InitBwFiltering().
filterFirstIter()
void filterFirstIter (const vectord & X, vectord & Y)
Function to start forward or backward filtering with first iteration.
Parameters
X The input vector of type double
Y The output vector of type double
The function resize output vector Y with the same size as input vector X and initialize pointer variables to these vectors. It than initialize the vectors with the previous X and Y values with size 4 and initial values 0. Afterwards the function enters a loop over all input samples and calculate the filtered result values, store it in output vector and store the previous X and Y values for the calculation in the next iteration.
Definition at line 322 of file filter.cpp.
References a, b, filter_order, X_old, Y_old, and z.
Referenced by DispTask::HandleDispFirstEntries(), and DispTask::InitBwFiltering().
filterNthIter()
void filterNthIter (vectord & X, vectord & Y)
Function to resume forward or backward filtering with next iteration.
Parameters
X The input vector of type double
Y The output vector of type double
The function resize output vector Y with the same size as input vector X, insert the previous X and Y values from last iteration at the beginning of input and output vector by< call of function insert and initialize pointer variables to these vectors. Afterwards the function enters a loop over all input samples and calculate the filtered result values, store it in output vector and store the previous X and Y values for the calculation in the next iteration.
Definition at line 381 of file filter.cpp.
References a, b, filter_order, X_old, Y_old, and z.
Referenced by DispTask::HandleFwFiltData(), and DispTask::HandleRawData().
filterLastIter()
void filterLastIter (vectord & X, vectord & Y)
Function to finish forward or backward filtering with last iteration.
Parameters
X The input vector of type double
Y The output vector of type double
The function resize output vector Y with the same size as input vector X, insert the previous X and Y values from last iteration at the beginning of input and output vector by< call of function insert and initialize pointer variables to these vectors. Afterwards the function enters a loop over all input samples and calculate the filtered result values and store it in output vector.
Definition at line 441 of file filter.cpp.
References a, b, filter_order, X_old, Y_old, and z.
Referenced by DispTask::HandleFwFiltData(), and DispTask::HandleRawData().
filtfilt_init()
void filtfilt_init (vectord B, vectord A)
Initialization of the filtfilt method.
Parameters
B The B filter coefficients
A The A filter coefficients
The function assign parameter A and B to the member vector variables b_coeff and a_coeff, calculate the filter order and length of edge transients and store them in member variables. Afterwards it set up and calculate the filter's initial conditions to remove DC offset problems at the beginning and end of the sequence.
Definition at line 79 of file filter.cpp.
References a_coeff, add_index_const(), add_index_range(), b_coeff, CMatrix::getInverse(), CMatrix::mult(), nfact, nfilt, CMatrix::setVal(), CMatrix::substract(), zi, and zzi.
Referenced by DispTask::DispTask().
getNfact()
int getNfact ()
Getter function to retrieve the length of edge transients.
Returns
The length of edge transients
The function returns the length of edge transients
Definition at line 567 of file filter.cpp.
References nfact.
Referenced by DispTask::HandleRawDataStatus().
getNfilt()
int getNfilt ()
Getter function to retrieve the filter order.
Returns
The filter order
The function returns the filter order
Definition at line 578 of file filter.cpp.
References nfilt.
Referenced by DispTask::HandleRawDataStatus().
add_index_range()
void add_index_range (vectori & indices, int beg, int end, int inc = 1) private
Function to add index values in vector.
Parameters
indices The output vector with the indices
beg Start index
end End index
inc Increment value
In a loop the function add current index to the vector indices from start to end index with an increment of parameter inc.
Definition at line 158 of file filter.cpp.
Referenced by filtfilt_init().
add_index_const()
void add_index_const (vectori & indices, int value, size_t numel) private
Function to add constant values in vector.
Parameters
indices The output vector with the constants
value The constant value
numel Number of elements in vector, also used as index
In a loop over the number of elements in the vector the function add the constant value at current index to the vector indices.
Definition at line 176 of file filter.cpp.
Referenced by filtfilt_init().
append_vector()
void append_vector (vectord & vec, const vectord & tail) private
Function to append a vector to another vector.
Parameters
vec The joined output vector
tail The vector to be appended
With call of function insert vector tail of type double will be appended to vector vec also of type double.
Definition at line 193 of file filter.cpp.
subvector_reverse()
vectord subvector_reverse (const vectord & vec, int idx_end, int idx_start) private
Function to reverse a sub-vector.
Parameters
vec The vector
idx_end The end index
idx_start The start index
Returns
Returns the reversed vector
The function copies the sub-vector from vector vec using start and end index to vector result, reverse it by calling method reverse and return it to calling function.
Definition at line 211 of file filter.cpp.
Referenced by prepare_leftpad(), and prepare_rightpad().
max_val()
int max_val (const vectori & vec) inline private
Function to retrieve the maximum value from a vector.
Parameters
vec The vector
Returns
Returns the maximum value of the vector
The function retrieve the maximum value of the vector of the vector by calling function max_element and return it to calling function.
Definition at line 231 of file filter.cpp.
filter_initialize()
void filter_initialize (vectord B, vectord A, vectord & Zi) private
Sub-Function to prepair the forward filtering.
Parameters
B The B filter coefficients
A The A filter coefficients
Zi Intermediate result
The function prepairs the forward filtering. It shall be called before start of forward filtering with function filterFirstIter.
Definition at line 278 of file filter.cpp.
References a, b, filter_order, n_A, n_B, n_zi, and z.
Referenced by fwfilter_init().
Field Documentation
b_coeff
vectord b_coeff private
Definition at line 79 of file filter.h.
Referenced by filtfilt_init(), and fwfilter_init().
a_coeff
vectord a_coeff private
Vector of type double with B filter coefficents.
Definition at line 80 of file filter.h.
Referenced by filtfilt_init(), and fwfilter_init().
nfilt
int nfilt private
Vector of type double with A filter coefficents.
filter order
Definition at line 83 of file filter.h.
Referenced by filtfilt_init(), and getNfilt().
nfact
int nfact private
length of edge transients
Definition at line 84 of file filter.h.
Referenced by filtfilt_init(), and getNfact().
zzi
vectord zzi private
Definition at line 85 of file filter.h.
Referenced by bwfilter_init(), filtfilt_init(), and fwfilter_init().
zi
vectord zi private
Vector of type double with intermediate result.
Definition at line 86 of file filter.h.
Referenced by bwfilter_init(), filtfilt_init(), and fwfilter_init().
filter_order
size_t filter_order private
Vector of type double with intermediate result.
filter order
Definition at line 89 of file filter.h.
Referenced by bwfilter_init(), filter_initialize(), filterFirstIter(), filterLastIter(), and filterNthIter().
b
const double* b private
Poiter to B filter coefficents.
Definition at line 90 of file filter.h.
Referenced by filter_initialize(), filterFirstIter(), filterLastIter(), and filterNthIter().
a
const double* a private
Poiter to A filter coefficents.
Definition at line 91 of file filter.h.
Referenced by filter_initialize(), filterFirstIter(), filterLastIter(), and filterNthIter().
z
double* z private
Poiter to intermediate result vector.
Definition at line 92 of file filter.h.
Referenced by bwfilter_init(), filter_initialize(), filterFirstIter(), filterLastIter(), and filterNthIter().
n_B
vectord n_B private
Definition at line 93 of file filter.h.
Referenced by filter_initialize().
n_A
vectord n_A private
Vector of type double with B filter coefficents.
Definition at line 94 of file filter.h.
Referenced by filter_initialize().
n_zi
vectord n_zi private
Vector of type double with A filter coefficents.
Definition at line 95 of file filter.h.
Referenced by bwfilter_init(), and filter_initialize().
X_old
vectord X_old private
Vector of type double with intermediate result.
previous calculated X values X(n-1) .. X(n-4)
Definition at line 96 of file filter.h.
Referenced by filterFirstIter(), filterLastIter(), and filterNthIter().
Y_old
vectord Y_old private
previous calculated Y values Y(n-1) .. Y(n-4)
Definition at line 97 of file filter.h.
Referenced by filterFirstIter(), filterLastIter(), and filterNthIter().
The documentation for this class was generated from the following files:
disp/filter.h
disp/filter.cpp