AXO X1: Shtcx Class Reference
Shtcx Class Reference
Shtcx temperature sensor class derived from task base class.
#include <shtcx.h>
Detailed Description
Shtcx temperature sensor class derived from task base class.
Detailed Description
The Shtcx class handle the reception of the temperature and humidity data and report these values to the data manager class on request to add them to the metrics JSON string. Temperature and humidity data is sampled by request. For testing purposes a cyclic timer handling is implemented, but the timer is not started. It can be activated manually in the init function to initiate a cyclic sampling of the sensor data.
The Shtcx class provides methods to read temperature and humidity data from the sensor, to initialize the sensor and to report the data to the data manager task. It uses the public zephyr API for the sensor driver provided in file sensor.h. See details in Zephyr API documentation. Message Interaction:
Receive
Timer interrupt callback
Shctx task (self)
Power manager task
Transmit
Data manager task
Shctx task (self, transmission in timer callback)
Definition at line 77 of file shtcx.h.
Public Member Functions
Shtcx (const char *name="??")
Shtcx task constructor.
Shtcx ()=delete
virtual ~Shtcx ()
Shtcx task destructor.
virtual void task (void)
Shtcx task function.
void dump ()
Function to print out temperature and humidity data from sensor.
void timer1_expired ()
Timer expired function for the cyclic sample timer.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the cyclic sample timer.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the Shctx task.
Timer * myTimer
Cyclic timer to sample sensor data.
Private Member Functions
void initDevice ()
The init function.
void sample ()
Function to sample temperature and humidity data from sensor.
void readTemperature ()
Read function to retrieve temperature from internal driver buffer.
void readHumidity ()
Read function to retrieve humidity from internal driver buffer.
void reportTemperature ()
Send temperature data message to data manager task.
void reportHumidity ()
Send humidity data message to data manager task.
Private Attributes
struct device * sensorDev
Pointer to the sensor device driver structure.
struct shtcx_sensor_value temp
The measured temperature value.
struct shtcx_sensor_value hum
The measured humidity value.
time_t sample_ts
Timestamp at calling sample()
bool device_good
Static Private Attributes
static uint32_t i2c_cfg
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
Shtcx() [1/2]
Shtcx (const char * name = "??") explicit
Shtcx task constructor.
Parameters
name The name of the class
The constructor allocate and register a mailbox and allocate the cyclic sample timer.
Definition at line 249 of file shtcx.cpp.
References Mbox::eShtcxTask, myTimer, pInMbox, Mbox::registerMbox(), and timer_cb().
Shtcx() [2/2]
Shtcx () delete
~Shtcx()
~Shtcx () virtual
Shtcx task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 263 of file shtcx.cpp.
Member Function Documentation
task()
void task (void) virtual
Shtcx task function.
Initially the I2C bus will be initialized by calling init function provided by I2cBus instance. Then the sensor device will be initialized by call of member function initDevice. For testing purposes a cyclic timer can be activated by commenting in the start method of the timer to initiate a cyclic sampling of the sensor data.
Afterwards the function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On sample timer expiry sensor data will be sampled by calling function sample and the temperature and humidity data will be read out from internal driver buffer by calling the functions readTemperature and readHumidity. The pointer pElem will be set to 0, to prevent releasing the message because it is allocated static.
eShtcxReport: On report request sensor data will be sampled by calling function sample and the temperature and humidity data will be read out from internal driver buffer by calling the functions readTemperature and readHumidity. Afterwards the data will be send to data manager task by calling the functions reportTemperature and reportHumidity.
Implements Task.
Definition at line 291 of file shtcx.cpp.
References eShtcxReport, eTimerExpired, PoolElem::free(), I2cBus::init(), initDevice(), I2cBus::inst(), PoolElem::mtype, Task::myName, pInMbox, Mbox::read(), readHumidity(), readTemperature(), reportHumidity(), reportTemperature(), sample(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the cyclic sample timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call timer expired member function timer1_expired.
Definition at line 91 of file shtcx.cpp.
References timer1_expired().
Referenced by Shtcx().
dump()
void dump ()
Function to print out temperature and humidity data from sensor.
Temperature and humidity data will be printed out together with the timestamp with debug message at info level.
Definition at line 138 of file shtcx.cpp.
References hum, temp, and shtcx_sensor_value::ts.
timer1_expired()
void timer1_expired ()
Timer expired function for the cyclic sample timer.
The function initializes the static pool element e1 with message type eTimerExpired, set Shtcx task as sender and put message into own (Shtcx) mailbox.
Definition at line 106 of file shtcx.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
initDevice()
void initDevice () private
The init function.
The sensor driver controller device structure will be retrieved by calling macro DEVICE_DT_GET and function checks if the device is ready for usage with call of function device_is_ready. The return value ready of this function will be assigned to flag device_good. In case of an error a debug message at error level will be printed.
Definition at line 65 of file shtcx.cpp.
References device_good, MY_SENSOR, and sensorDev.
Referenced by task().
sample()
void sample () private
Function to sample temperature and humidity data from sensor.
With call of function sensor_sample_fetch provided by the zephyr API sample temperature and humidity data will be fetched from the sensor and stored it in an internal driver buffer. Afterwards the timestamp for this sample will be stored in private member variable sample_ts.
Definition at line 121 of file shtcx.cpp.
References sample_ts, and sensorDev.
Referenced by task().
readTemperature()
void readTemperature () private
Read function to retrieve temperature from internal driver buffer.
If device has not been initialized successfully, indicated by flag device_good a defined dummy value will be written into member variable temp by calling function sensor_value_from_double provided by the zephyr API, which converts a double value to struct sensor_value and the function returns immediately. Otherwise the temperature will be read out from internal driver buffer by call of function sensor_channel_get provided by the zephyr API and the stored timestamp will be copied into structure temp of type struct shtcx_sensor_value.
Definition at line 162 of file shtcx.cpp.
References device_good, sample_ts, sensorDev, temp, shtcx_sensor_value::ts, and VAL_NOT_INITIALIZED_FLOAT.
Referenced by task().
readHumidity()
void readHumidity () private
Read function to retrieve humidity from internal driver buffer.
If device has not been initialized successfully, indicated by flag device_good a defined dummy value will be written into member variable hum by calling function sensor_value_from_double provided by the zephyr API, which converts a double value to struct sensor_value and the function returns immediately. Otherwise the humidity will be read out from internal driver buffer by call of function sensor_channel_get provided by the zephyr API and the storedtimestamp will be copied into structure hum of type struct shtcx_sensor_value.
Definition at line 193 of file shtcx.cpp.
References device_good, hum, sample_ts, sensorDev, shtcx_sensor_value::ts, and VAL_NOT_INITIALIZED_FLOAT.
Referenced by task().
reportTemperature()
void reportTemperature () private
Send temperature data message to data manager task.
The function send a message of type eShtcxTemperature with attached temperature data to data manager mailbox by calling function sendMsg provided by Mbox class.
Definition at line 219 of file shtcx.cpp.
References eShtcxTemperature, Mbox::sendMsg(), and temp.
Referenced by task().
reportHumidity()
void reportHumidity () private
Send humidity data message to data manager task.
The function send a message of type eShtcxHumidity with attached humidity data to data manager mailbox by calling function sendMsg provided by Mbox class.
Definition at line 233 of file shtcx.cpp.
References eShtcxHumidity, hum, and Mbox::sendMsg().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the Shctx task.
Definition at line 86 of file shtcx.h.
Referenced by Shtcx(), task(), and timer1_expired().
myTimer
Timer* myTimer
Cyclic timer to sample sensor data.
Definition at line 87 of file shtcx.h.
Referenced by Shtcx().
i2c_cfg
uint32_t i2c_cfg static private
32-bit bit mask for the device runtime configuration of the I2C controller.
Definition at line 96 of file shtcx.h.
sensorDev
struct device* sensorDev private
Pointer to the sensor device driver structure.
Definition at line 99 of file shtcx.h.
Referenced by initDevice(), readHumidity(), readTemperature(), and sample().
temp
struct shtcx_sensor_value temp private
The measured temperature value.
Definition at line 99 of file shtcx.h.
Referenced by dump(), readTemperature(), and reportTemperature().
hum
struct shtcx_sensor_value hum private
The measured humidity value.
Definition at line 99 of file shtcx.h.
Referenced by dump(), readHumidity(), and reportHumidity().
sample_ts
time_t sample_ts private
Timestamp at calling sample()
Definition at line 102 of file shtcx.h.
Referenced by readHumidity(), readTemperature(), and sample().
device_good
bool device_good private
Flag indicating if hardware init was successful or not
Definition at line 103 of file shtcx.h.
Referenced by initDevice(), readHumidity(), and readTemperature().
The documentation for this class was generated from the following files:
drv/i2c/shtcx.h
drv/i2c/shtcx.cpp