AXO X1: CMatrix Class Reference
CMatrix Class Reference
Matrix helper class.
#include <matrix.h>
Detailed Description
Matrix helper class.
The matrix helper class provide the following fuctionality:
Getter function to retrieve the matrix inverse
Functions to print a matrix or a vector
Functions to initialize a matrix or a vector
Function to set a value at defined indices
Multiplication of matrix with vector
Substraction of vectors
Function to retrieve the matrix cofactors
Function to retrieve the transposed matrix
Function to retrieve the matrix determinant
Definition at line 48 of file matrix.h.
Static Public Member Functions
static std::vector< std::vector< double > > getInverse (const std::vector< std::vector< double >> vect)
Getter function to retrieve the inverse of a matrix.
static void printMatrix (const std::vector< std::vector< double >> vect)
Print a matrix.
static void printVector (const std::vector< double > vect)
Print a vector of type double.
static void printVector (const std::vector< int > vect)
Print a vector of type int.
static void initMatrix (MatrixT &mat, double val)
Function to initialize a matrix.
static void initVector (std::vector< double > &vec, double val)
Function to initialize a vector.
static void setVal (MatrixT &mat, unsigned int row, unsigned int col, double val)
Function to set a value in a matrix.
static std::vector< double > mult (MatrixT &mat, std::vector< double > vec)
Multiplication of matrix with vector.
static std::vector< double > substract (std::vector< double > vec1, std::vector< double > vec2)
Substraction of vectors.
Static Private Member Functions
static std::vector< std::vector< double > > getCofactor (const std::vector< std::vector< double >> vect)
Getter function to retrieve the matrix cofactors.
static std::vector< std::vector< double > > getTranspose (const std::vector< std::vector< double >> matrix1)
Getter function to retrieve the transposed matrix.
static double getDeterminant (const std::vector< std::vector< double >> vect)
Getter function to retrieve the matrix determinant.
Member Function Documentation
getInverse()
std::vector< std::vector< double > > getInverse (const std::vector< std::vector< double >> vect) static
Getter function to retrieve the inverse of a matrix.
Parameters
vect The input matrix
Returns
The inverse matrix
The function calculate and returns the inverse of a matrix
Definition at line 156 of file matrix.cpp.
References getCofactor(), getDeterminant(), and getTranspose().
Referenced by CFilter::filtfilt_init().
printMatrix()
void printMatrix (const std::vector< std::vector< double >> vect) static
Print a matrix.
Parameters
vect The input matrix
The function print a matrix.
Note
Only for developing purposes
Definition at line 271 of file matrix.cpp.
printVector() [1/2]
void printVector (const std::vector< double > vect) static
Print a vector of type double.
Parameters
vect The input vector
The function print a vector.
Note
Only for developing purposes
Definition at line 287 of file matrix.cpp.
printVector() [2/2]
void printVector (const std::vector< int > vect) static
Print a vector of type int.
Parameters
vect The input vector
The function print a vector.
Note
Only for developing purposes
Definition at line 301 of file matrix.cpp.
initMatrix()
void initMatrix (MatrixT & mat, double val) static
Function to initialize a matrix.
Parameters
mat The input matrix
val The initial value
The function initialize all elements of a matrix with initial value val
Definition at line 188 of file matrix.cpp.
initVector()
void initVector (std::vector< double > & vec, double val) static
Function to initialize a vector.
Parameters
vec The input vector
val The initial value
The function initialize all elements of a vector with initial value val
Definition at line 204 of file matrix.cpp.
Referenced by mult().
setVal()
void setVal (MatrixT & mat, unsigned int row, unsigned int col, double val) static
Function to set a value in a matrix.
Parameters
mat The input matrix
row The row position
col The column position
val The value
The function set an element of matrix at position [row, col] to value val
Definition at line 220 of file matrix.cpp.
Referenced by CFilter::filtfilt_init().
mult()
std::vector< double > mult (MatrixT & mat, std::vector< double > vec) static
Multiplication of matrix with vector.
Parameters
mat The input matrix
vec The input vector
Returns
Returns the resulting vector
The function multiply a matrix with a vector and return the resulting vector
Definition at line 234 of file matrix.cpp.
References initVector().
Referenced by CFilter::filtfilt_init().
substract()
std::vector< double > substract (std::vector< double > vec1, std::vector< double > vec2) static
Substraction of vectors.
Parameters
vec1 The first input vector
vec2 The second input vector
Returns
Returns the resulting vector
The function substract vector vec2 from vestor vec1 andreturn the resulting vector
Definition at line 256 of file matrix.cpp.
Referenced by CFilter::filtfilt_init().
getCofactor()
std::vector< std::vector< double > > getCofactor (const std::vector< std::vector< double >> vect) static private
Getter function to retrieve the matrix cofactors.
Parameters
vect The input matrix
Returns
Vector with the matrix cofactors
The function calculate and returns the matrix cofactors
Definition at line 115 of file matrix.cpp.
References getDeterminant().
Referenced by getInverse().
getTranspose()
std::vector< std::vector< double > > getTranspose (const std::vector< std::vector< double >> matrix1) static private
Getter function to retrieve the transposed matrix.
Parameters
matrix1 The input matrix
Returns
The transposed matrix
The function calculate and returns the transposed matrix
Definition at line 93 of file matrix.cpp.
Referenced by getInverse().
getDeterminant()
double getDeterminant (const std::vector< std::vector< double >> vect) static private
Getter function to retrieve the matrix determinant.
Parameters
vect The input matrix
Returns
The matrix determinant
The function calculate and returns the matrix determinant
Definition at line 42 of file matrix.cpp.
Referenced by getCofactor(), and getInverse().
The documentation for this class was generated from the following files:
disp/matrix.h
disp/matrix.cpp