AXO X1: FwTriggered Class Reference
FwTriggered Class Reference
Triggered state class derived from base class FwState.
#include <fsm.h>
Detailed Description
Triggered state class derived from base class FwState.
Detailed Description
The triggered state class overrides the handler function of OtaStart and timer expired events. In this state firmware update has been triggered by OTA start event and waits for the JSON firmware info.
Definition at line 162 of file fsm.h.
Public Member Functions
FwTriggered (void *pd)
Constructor of triggered state class.
virtual ~FwTriggered ()
Destructor of triggered state class.
FwFsm::StateId handle_FwInfo (PoolElem **pElem)
Triggered state handler function for FwInfo events.
FwFsm::StateId handle_timer_exp ()
Triggered state handler function for timer expired events.
Public Member Functions inherited from FwState
FwState (void *pData)
Constructor of state base class.
virtual ~FwState ()
Destructor of state base class.
virtual FwFsm::StateId handle_OtaStart ()
State handler function of the state base class for OtaStart events.
virtual FwFsm::StateId handle_DlComplete (PoolElem **pElem)
State handler function of the state base class for download complete events.
virtual FwFsm::StateId handle_DlFailed (PoolElem **pElem)
State handler function of the state base class for download failed events.
Additional Inherited Members
Data Fields inherited from FwState
void * pd
Timestamp of download start in seconds.
uint32_t startDownloadTimestamp
Static Public Attributes inherited from FwState
static const uint32_t maxDownloadDelay = 10*60
Constructor & Destructor Documentation
FwTriggered()
FwTriggered (void * pData) explicit
Constructor of triggered state class.
Parameters
pData Ponter to a data object
The constructor simply triggers a debug message on info level.
Definition at line 408 of file fsm.cpp.
References FwState::pd.
~FwTriggered()
~FwTriggered () virtual
Destructor of triggered state class.
The destructor simply triggers a debug message on info level.
Definition at line 417 of file fsm.cpp.
Member Function Documentation
handle_FwInfo()
FwFsm::StateId handle_FwInfo (PoolElem ** pElem) virtual
Triggered state handler function for FwInfo events.
Parameters
pElem Pointer to pointer to message of type PoolElem
Returns
Returns the state ID of the firmware download state
The function notify platform that command is accepted by calling function otaFwConfirm of the FwUpdCtrl class instance. Pointer variable pd is assigned to FwUpdCtrl class instance. Afterwards the message will be forwarded to firmware update task. Function start the download timeout timer by calling function startTimeout of the FwUpdCtrl class instance. Finally function returns the state ID eDownload.
Reimplemented from FwState.
Definition at line 449 of file fsm.cpp.
References FwFsm::eDownload, Mbox::eFwUpd, FwFsm::getDownloadTimeout(), FwState::pd, Mbox::send(), and FwState::startDownloadTimestamp.
handle_timer_exp()
FwFsm::StateId handle_timer_exp () virtual
Triggered state handler function for timer expired events.
Returns
Returns the state ID of the idle state
The function returns the state ID of the idle state.
Reimplemented from FwState.
Definition at line 428 of file fsm.cpp.
References eAdxlResumeMeas, FwFsm::eIdle, and Mbox::sendMsg().
The documentation for this class was generated from the following files:
update/fsm.h
update/fsm.cpp