AXO X1: main.cpp File Reference
main.cpp File Reference
Implementation of AXO Track main function.
Detailed Description
Implementation of AXO Track main function.
Project
AXO Track Firmware 2023
Copyright
(c) 2023 AXO Track GmbH, Berlin. All rights reserved.
Author
AXO Track GmbH, Berlin (Germany)
Detailed Description
This file defines the stack sizes for each tasks of the AXO Track software and allocate each task statically. The main function creates and starts the peviously allocated tasks before entering the endless loop.
Remarks
This source code is confidential and proprietary information of AXO Track GmbH, Berlin. You may not disclose, copy, or distribute this source code or any part thereof without the explicit permission of AXO Track GmbH, Berlin.
Definition in file main.cpp.
Macros
#define ARCH_STACK_PTR_ALIGN 4
#define PWR_MGR_STACK_SIZE 1024
#define BOOST_STACK_SIZE 2048
#define LTE_TASK_STACK_SIZE 2048
#define LTE_MON_STACK_SIZE 2048
#define SHTCX_TASK_STACK_SIZE 1024
#define MQTT_TASK_STACK_SIZE 2048
#define HTTP_TASK_STACK_SIZE 2048
#define PDATA_TASK_STACK_SIZE 2048
#define ADC_TASK_STACK_SIZE 1024
#define BATTERY_TASK_STACK_SIZE 1024
#define HW_METRICS_TASK_STACK_SIZE 1024
#define ADXL37X_STACK_SIZE 1024
#define ADXL_STORE_STACK_SIZE 2048
#define RMS_STORE_STACK_SIZE 1024
#define RMS_TASK_STACK_SIZE 1024
#define DISP_TASK_STACK_SIZE 4096
#define UPD_TASK_STACK_SIZE 4096
#define UPD_CTRL_STACK_SIZE 1024
#define RST_CTRL_STACK_SIZE 1024
#define BUZZER_NODE DT_ALIAS(buzzer)
#define POWERCYCLE_NODE DT_PATH(zephyr_user)
Typedefs
using fs = FlashFS
Functions
LOG_MODULE_REGISTER (main, AXO_DEFAULT_DEBUG_LEVEL)
K_THREAD_STACK_DEFINE (PWR_MGR_STACK, PWR_MGR_STACK_SIZE)
K_THREAD_STACK_DEFINE (BOOST_STACK, BOOST_STACK_SIZE)
K_THREAD_STACK_DEFINE (LTE_TASK_STACK, LTE_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (LTE_MON_STACK, LTE_MON_STACK_SIZE)
K_THREAD_STACK_DEFINE (SHTCX_TASK_STACK, SHTCX_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (MQTT_TASK_STACK, MQTT_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (HTTP_TASK_STACK, HTTP_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (PDATA_TASK_STACK, PDATA_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (ADC_TASK_STACK, ADC_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (BATTERY_TASK_STACK, BATTERY_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (HW_METRICS_TASK_STACK, HW_METRICS_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (ADXL37X_STACK, ADXL37X_STACK_SIZE)
K_THREAD_STACK_DEFINE (ADXL_STORE_STACK, ADXL_STORE_STACK_SIZE)
K_THREAD_STACK_DEFINE (RMS_STORE_STACK, RMS_STORE_STACK_SIZE)
K_THREAD_STACK_DEFINE (RMS_TASK_STACK, RMS_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE (DISP_TASK_STACK, DISP_TASK_STACK_SIZE)
static K_THREAD_STACK_DEFINE (UPD_TASK_STACK, UPD_TASK_STACK_SIZE)
static K_THREAD_STACK_DEFINE (UPD_CTRL_STACK, UPD_CTRL_STACK_SIZE)
static K_THREAD_STACK_DEFINE (RST_CTRL_STACK, RST_CTRL_STACK_SIZE)
int main ()
main function of AXO Track firmware
Variables
static PowerMgrX1 pwrmgr ("pwrmgr")
static BoostConverter boost ("boost")
static LteConnector lte ("lte")
static LteMonitor ltemon ("ltemon")
static Shtcx shtcx ("shtc3")
static MqttConnector mqtt ("mqtt")
static HttpConnector http ("http")
static DataManager dmgr ("dmgr")
static ADConverter adc ("adc")
static BatteryMgr battery ("battery")
static HwMetrics hwmetrics ("hwmetrics")
static Adxl37x adxlsample ("adxl37x")
static AdxlDataStore adxlstore ("adxlst", FRAM_5_SEC_RAW_DATA_SPACE, Adxl37x::odr)
static RmsStore rmsStore ("rmsst", 15)
static RmsTask adxlrms ("adxlrms", 1, Adxl37x::odr)
static DispTask disptask ("disp")
static FwUpd fwupd ("fwupd")
static FwUpdCtrl fwctrl ("fwctr")
static ResetCtrl resetctrl ("rstctr")
struct gpio_dt_spec buzzer_spec
struct gpio_dt_spec powercycle
Macro Definition Documentation
ARCH_STACK_PTR_ALIGN
#define ARCH_STACK_PTR_ALIGN 4
Definition at line 70 of file main.cpp.
PWR_MGR_STACK_SIZE
#define PWR_MGR_STACK_SIZE 1024
Definition at line 75 of file main.cpp.
BOOST_STACK_SIZE
#define BOOST_STACK_SIZE 2048
Definition at line 80 of file main.cpp.
LTE_TASK_STACK_SIZE
#define LTE_TASK_STACK_SIZE 2048
Definition at line 85 of file main.cpp.
LTE_MON_STACK_SIZE
#define LTE_MON_STACK_SIZE 2048
Definition at line 90 of file main.cpp.
SHTCX_TASK_STACK_SIZE
#define SHTCX_TASK_STACK_SIZE 1024
Definition at line 95 of file main.cpp.
MQTT_TASK_STACK_SIZE
#define MQTT_TASK_STACK_SIZE 2048
Definition at line 100 of file main.cpp.
HTTP_TASK_STACK_SIZE
#define HTTP_TASK_STACK_SIZE 2048
Definition at line 105 of file main.cpp.
PDATA_TASK_STACK_SIZE
#define PDATA_TASK_STACK_SIZE 2048
Definition at line 110 of file main.cpp.
ADC_TASK_STACK_SIZE
#define ADC_TASK_STACK_SIZE 1024
Definition at line 115 of file main.cpp.
BATTERY_TASK_STACK_SIZE
#define BATTERY_TASK_STACK_SIZE 1024
Definition at line 120 of file main.cpp.
HW_METRICS_TASK_STACK_SIZE
#define HW_METRICS_TASK_STACK_SIZE 1024
Definition at line 125 of file main.cpp.
ADXL37X_STACK_SIZE
#define ADXL37X_STACK_SIZE 1024
Definition at line 130 of file main.cpp.
ADXL_STORE_STACK_SIZE
#define ADXL_STORE_STACK_SIZE 2048
Definition at line 135 of file main.cpp.
RMS_STORE_STACK_SIZE
#define RMS_STORE_STACK_SIZE 1024
Definition at line 143 of file main.cpp.
RMS_TASK_STACK_SIZE
#define RMS_TASK_STACK_SIZE 1024
Definition at line 148 of file main.cpp.
DISP_TASK_STACK_SIZE
#define DISP_TASK_STACK_SIZE 4096
Definition at line 153 of file main.cpp.
UPD_TASK_STACK_SIZE
#define UPD_TASK_STACK_SIZE 4096
Definition at line 158 of file main.cpp.
UPD_CTRL_STACK_SIZE
#define UPD_CTRL_STACK_SIZE 1024
Definition at line 162 of file main.cpp.
RST_CTRL_STACK_SIZE
#define RST_CTRL_STACK_SIZE 1024
Definition at line 167 of file main.cpp.
BUZZER_NODE
#define BUZZER_NODE DT_ALIAS(buzzer)
Definition at line 171 of file main.cpp.
POWERCYCLE_NODE
#define POWERCYCLE_NODE DT_PATH(zephyr_user)
Definition at line 172 of file main.cpp.
Typedef Documentation
fs
using fs = FlashFS
Definition at line 65 of file main.cpp.
Function Documentation
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (main , AXO_DEFAULT_DEBUG_LEVEL)
K_THREAD_STACK_DEFINE() [1/19]
K_THREAD_STACK_DEFINE (PWR_MGR_STACK , PWR_MGR_STACK_SIZE)
K_THREAD_STACK_DEFINE() [2/19]
K_THREAD_STACK_DEFINE (BOOST_STACK , BOOST_STACK_SIZE)
K_THREAD_STACK_DEFINE() [3/19]
K_THREAD_STACK_DEFINE (LTE_TASK_STACK , LTE_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [4/19]
K_THREAD_STACK_DEFINE (LTE_MON_STACK , LTE_MON_STACK_SIZE)
K_THREAD_STACK_DEFINE() [5/19]
K_THREAD_STACK_DEFINE (SHTCX_TASK_STACK , SHTCX_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [6/19]
K_THREAD_STACK_DEFINE (MQTT_TASK_STACK , MQTT_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [7/19]
K_THREAD_STACK_DEFINE (HTTP_TASK_STACK , HTTP_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [8/19]
K_THREAD_STACK_DEFINE (PDATA_TASK_STACK , PDATA_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [9/19]
K_THREAD_STACK_DEFINE (ADC_TASK_STACK , ADC_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [10/19]
K_THREAD_STACK_DEFINE (BATTERY_TASK_STACK , BATTERY_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [11/19]
K_THREAD_STACK_DEFINE (HW_METRICS_TASK_STACK , HW_METRICS_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [12/19]
K_THREAD_STACK_DEFINE (ADXL37X_STACK , ADXL37X_STACK_SIZE)
K_THREAD_STACK_DEFINE() [13/19]
K_THREAD_STACK_DEFINE (ADXL_STORE_STACK , ADXL_STORE_STACK_SIZE)
K_THREAD_STACK_DEFINE() [14/19]
K_THREAD_STACK_DEFINE (RMS_STORE_STACK , RMS_STORE_STACK_SIZE)
K_THREAD_STACK_DEFINE() [15/19]
K_THREAD_STACK_DEFINE (RMS_TASK_STACK , RMS_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [16/19]
K_THREAD_STACK_DEFINE (DISP_TASK_STACK , DISP_TASK_STACK_SIZE)
K_THREAD_STACK_DEFINE() [17/19]
static K_THREAD_STACK_DEFINE (UPD_TASK_STACK , UPD_TASK_STACK_SIZE) static
K_THREAD_STACK_DEFINE() [18/19]
static K_THREAD_STACK_DEFINE (UPD_CTRL_STACK , UPD_CTRL_STACK_SIZE) static
K_THREAD_STACK_DEFINE() [19/19]
static K_THREAD_STACK_DEFINE (RST_CTRL_STACK , RST_CTRL_STACK_SIZE) static
main()
int main ()
main function of AXO Track firmware
The main function load dynamic configuration from file and initialize the config variables by call of function init provided by Config class, it call function init provided by KeyGen class to generate and store private and public TLS keys if not still done. Afterwards it creates and starts the static allocated tasks in following order:
create and start BoostConverter task (boost)
create and start PowerMgr task (pwrmgr)
create LteConnector task (lte)
register mqtt and power manager instances to listen to selected LTE events
create LteMonitor task (ltemon)
register notifications of link quality and network
create, configure and start MqttConnector task (mqtt)
create Shtcx (temperature + humidity sensor) task (shtcx)
create and start ADC task (adc)
create, configure and start battery manager task (battery)
create, configure and start data manager task (dmgr)
start LteMonitor task (ltemon)
create and start accelerometer task adxlrms
create, configure and start accelerometer task adxlstore
create and start accelerometer task rmsStore
create and start accelerometer task adxlsample
create and start firmware updata task (fwupd)
create and start firmware updata control task (fwctrl)
create and start reset control task (resetctrl)
start LteConnector task (lte)
call function displayFwVersion
disable UART (for release builds only)
enter endless loop
Returns
The main function never returns, defined return value is 0.
Definition at line 214 of file main.cpp.
References adc, ADC_TASK_STACK_SIZE, ADXL37X_STACK_SIZE, ADXL_STORE_STACK_SIZE, adxlrms, adxlsample, adxlstore, battery, BATTERY_TASK_STACK_SIZE, boost, BOOST_STACK_SIZE, FlashFS::CheckAvailableSpace(), AdxlDataStore::configure(), DataManager::configure(), DispTask::configure(), Adxl37x::configure(), HttpConnector::configure(), MqttConnector::configure(), PowerMgr::configure(), Task::create(), DISP_TASK_STACK_SIZE, displayFwVersion(), disptask, dmgr, fwctrl, fwupd, BatteryMgr::getAdcChannels(), http, HTTP_TASK_STACK_SIZE, HW_METRICS_TASK_STACK_SIZE, hwmetrics, Config::init(), WakeupCnt::init(), certmgr::init(), KeyGen::init(), Config::inst(), FlashFS::inst(), WakeupCnt::inst(), certmgr::inst(), KeyGen::inst(), lte, LTE_MON_STACK_SIZE, LTE_TASK_STACK_SIZE, ltemon, mqtt, MQTT_TASK_STACK_SIZE, PDATA_TASK_STACK_SIZE, BatteryMgr::pInMbox, HttpConnector::pInMbox, MqttConnector::pInMbox, PowerMgr::pInMbox, PWR_MGR_STACK_SIZE, pwrmgr, LteMonitor::register_link_quality_notifications(), LteMonitor::register_network_notifications(), LteConnector::registerListener(), ADConverter::registerListener(), resetctrl, LteMonitor::resume_link_quality_notifications(), LteMonitor::resume_network_notifications(), RMS_STORE_STACK_SIZE, RMS_TASK_STACK_SIZE, rmsStore, RST_CTRL_STACK_SIZE, shtcx, SHTCX_TASK_STACK_SIZE, Task::start(), UPD_CTRL_STACK_SIZE, and UPD_TASK_STACK_SIZE.
Variable Documentation
pwrmgr
PowerMgrX1 pwrmgr("pwrmgr") ("pwrmgr") static
Referenced by main().
boost
BoostConverter boost("boost") ("boost") static
Referenced by main().
lte
LteConnector lte("lte") ("lte") static
Referenced by main().
ltemon
LteMonitor ltemon("ltemon") ("ltemon") static
Referenced by main().
shtcx
Shtcx shtcx("shtc3") ("shtc3") static
Referenced by main().
mqtt
MqttConnector mqtt("mqtt") ("mqtt") static
Referenced by main().
http
HttpConnector http("http") ("http") static
Referenced by main().
dmgr
DataManager dmgr("dmgr") ("dmgr") static
Referenced by main().
adc
ADConverter adc("adc") ("adc") static
Referenced by main().
battery
BatteryMgr battery("battery") ("battery") static
Referenced by main().
hwmetrics
HwMetrics hwmetrics("hwmetrics") ("hwmetrics") static
Referenced by main().
adxlsample
Adxl37x adxlsample("adxl37x") ("adxl37x") static
Referenced by main().
adxlstore
AdxlDataStore adxlstore("adxlst", FRAM_5_SEC_RAW_DATA_SPACE, Adxl37x::odr) ("adxlst" , FRAM_5_SEC_RAW_DATA_SPACE , Adxl37x::odr) static
Referenced by main().
rmsStore
RmsStore rmsStore("rmsst", 15) ("rmsst" , 15) static
Referenced by main().
adxlrms
RmsTask adxlrms("adxlrms", 1, Adxl37x::odr) ("adxlrms" , 1 , Adxl37x::odr) static
Referenced by main().
disptask
DispTask disptask("disp") ("disp") static
Referenced by main().
fwupd
FwUpd fwupd("fwupd") ("fwupd") static
Referenced by main().
fwctrl
FwUpdCtrl fwctrl("fwctr") ("fwctr") static
Referenced by main().
resetctrl
ResetCtrl resetctrl("rstctr") ("rstctr") static
Referenced by main().
buzzer_spec
struct gpio_dt_spec buzzer_spec
Definition at line 169 of file main.cpp.
powercycle
struct gpio_dt_spec powercycle
Definition at line 169 of file main.cpp.
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/sys/__assert.h>
#include "./prj_config.h"
#include "./version.h"
#include "conf/config.h"
#include "data/adxl_store.h"
#include "data/hw_metrics.h"
#include "data/pdata.h"
#include "data/rms.h"
#include "data/rms_store.h"
#include "disp/disptask.h"
#include "drv/adc/adconverter.h"
#include "drv/adc/batt_mgr.h"
#include "drv/i2c/shtcx.h"
#include "drv/pm/boost.h"
#include "drv/spi/adxl37x.h"
#include "fs/flashfs.h"
#include "modem/lte_monitor.h"
#include "net/http_connector.h"
#include "net/lte_connector.h"
#include "net/mqtt_connector.h"
#include "pm/power_mgr_x1.h"
#include "pm/reset_ctrl.h"
#include "pm/wakeup_cnt.h"
#include "rtos/mbox.h"
#include "rtos/mempool.h"
#include "rtos/mpelem.h"
#include "rtos/mpool.h"
#include "rtos/mqueue.h"
#include "rtos/sema.h"
#include "rtos/task.h"
#include "update/update.h"
#include "update/update_ctrl.h"
#include "util/certmgr.h"
#include "util/keygen.h"