AXO X1: drv/adc/mux_controller.cpp File Reference
mux_controller.cpp File Reference
Implementation of MUX controller driver class.
Detailed Description
Implementation of MUX controller driver class.
Project
AXO Track Firmware 2023
Copyright
(c) 2023 AXO Track GmbH, Berlin. All rights reserved.
Author
AXO Track GmbH, Berlin (Germany)
Detailed Description
See description in muxcontroller header file
Remarks
This source code is confidential and proprietary information of AXO Track GmbH, Berlin. You may not disclose, copy, or distribute this source code or any part thereof without the explicit permission of AXO Track GmbH, Berlin.
Definition in file mux_controller.cpp.
Macros
#define MUX_NODE DT_NODELABEL(mux_adc)
#define ADC_NODE DT_NODELABEL(adc)
#define ADC_CHANNEL_ID 1
#define ADC_RESOLUTION 10
#define ADC_GAIN ADC_GAIN_1_6
#define ADC_REFERENCE ADC_REF_INTERNAL
#define ADC_VREF_MV 750
#define ADC_ACQUISITION_TIME ADC_ACQ_TIME_DEFAULT
Functions
LOG_MODULE_REGISTER (mux_ctrl, COMMON_DEFAULT_DEBUG_LEVEL)
MuxController mux (mux_gpios, ARRAY_SIZE(mux_gpios), &enable_gpio)
Declaration of the mux controller instance.
static int setup_adc ()
static int cmd_mux_select (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'select'.
static int cmd_mux_enable (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'enable'.
static int cmd_mux_status (const struct shell *shell, size_t, char **)
Callback function for console input command 'status'.
static int cmd_mux_sweep (const struct shell *shell, size_t argc, char **argv)
Callback function for console input command 'sweep'.
SHELL_STATIC_SUBCMD_SET_CREATE (sub_mux, SHELL_CMD(select, NULL, "Select mux channel", cmd_mux_select), SHELL_CMD(enable, NULL, "Enable or disable load", cmd_mux_enable), SHELL_CMD(status, NULL, "Show mux status", cmd_mux_status), SHELL_CMD(sweep, NULL, "Sweep all channels [enable]", cmd_mux_sweep), SHELL_SUBCMD_SET_END)
Registration of shell commands for MUX controller tests.
SHELL_CMD_REGISTER (mux, &sub_mux, "Mux controller commands", NULL)
Variables
static const struct gpio_dt_spec mux_gpios []
Devicetree setup for the muxer select lines.
static const struct gpio_dt_spec enable_gpio
Devicetree setup for the muxer enable pin.
static const struct device * adc_dev = DEVICE_DT_GET(ADC_NODE)
static int16_t adc_buffer
static int32_t val_mV
Macro Definition Documentation
MUX_NODE
#define MUX_NODE DT_NODELABEL(mux_adc)
Definition at line 145 of file mux_controller.cpp.
ADC_NODE
#define ADC_NODE DT_NODELABEL(adc)
Definition at line 160 of file mux_controller.cpp.
ADC_CHANNEL_ID
#define ADC_CHANNEL_ID 1
Definition at line 161 of file mux_controller.cpp.
ADC_RESOLUTION
#define ADC_RESOLUTION 10
Definition at line 162 of file mux_controller.cpp.
ADC_GAIN
#define ADC_GAIN ADC_GAIN_1_6
Definition at line 163 of file mux_controller.cpp.
ADC_REFERENCE
#define ADC_REFERENCE ADC_REF_INTERNAL
Definition at line 164 of file mux_controller.cpp.
ADC_VREF_MV
#define ADC_VREF_MV 750
Definition at line 165 of file mux_controller.cpp.
ADC_ACQUISITION_TIME
#define ADC_ACQUISITION_TIME ADC_ACQ_TIME_DEFAULT
Definition at line 166 of file mux_controller.cpp.
Function Documentation
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (mux_ctrl , COMMON_DEFAULT_DEBUG_LEVEL)
mux()
MuxController mux (mux_gpios , ARRAY_SIZE(mux_gpios) , & enable_gpio)
Declaration of the mux controller instance.
Referenced by cmd_mux_enable(), cmd_mux_select(), cmd_mux_status(), and cmd_mux_sweep().
setup_adc()
static int setup_adc () static
Definition at line 182 of file mux_controller.cpp.
References ADC_ACQUISITION_TIME, ADC_CHANNEL_ID, adc_dev, ADC_GAIN, and ADC_REFERENCE.
Referenced by cmd_mux_sweep().
cmd_mux_select()
static int cmd_mux_select (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'select'.
Function select a ADC channel by call of MuxController member function selectChannel
Note
For testing only: muxer configuration via shell command
Definition at line 204 of file mux_controller.cpp.
References mux(), and MuxController::selectChannel().
cmd_mux_enable()
static int cmd_mux_enable (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'enable'.
Function enable the muxer by call of MuxController member function enableLoad
Note
For testing only: muxer configuration via shell command
Definition at line 217 of file mux_controller.cpp.
References MuxController::enableLoad(), and mux().
cmd_mux_status()
static int cmd_mux_status (const struct shell * shell, size_t , char **) static
Callback function for console input command 'status'.
Function print the status by call of MuxController member function printStatus
Note
For testing only: muxer configuration via shell command
Definition at line 231 of file mux_controller.cpp.
References mux(), and MuxController::printStatus().
cmd_mux_sweep()
static int cmd_mux_sweep (const struct shell * shell, size_t argc, char ** argv) static
Callback function for console input command 'sweep'.
Function enable the muxer by calling MuxController member function enableLoad with parameter true and enters a loop over the number of configured channels. In the loop a channel is selected by call of MuxController member function selectChannel, the analog value at this channel is read by call of function adc_read, converted to milli volt by call of function adc_raw_to_millivolts and printed by call of function shell_print.
Finally the function enable the muxer by calling MuxController member function enableLoad with parameter false.
Note
For testing only: muxer configuration via shell command
Definition at line 249 of file mux_controller.cpp.
References adc_buffer, ADC_CHANNEL_ID, adc_dev, ADC_GAIN, ADC_RESOLUTION, ADC_VREF_MV, MuxController::enableLoad(), mux(), MuxController::numMuxPins(), MuxController::selectChannel(), setup_adc(), and val_mV.
SHELL_STATIC_SUBCMD_SET_CREATE()
SHELL_STATIC_SUBCMD_SET_CREATE (sub_mux , SHELL_CMD(select, NULL, "Select mux channel", cmd_mux_select) , SHELL_CMD(enable, NULL, "Enable or disable load", cmd_mux_enable) , SHELL_CMD(status, NULL, "Show mux status", cmd_mux_status) , SHELL_CMD(sweep, NULL, "Sweep all channels [enable]", cmd_mux_sweep) , SHELL_SUBCMD_SET_END)
Registration of shell commands for MUX controller tests.
SHELL_CMD_REGISTER()
SHELL_CMD_REGISTER (mux , & sub_mux, "Mux controller commands" , NULL)
Variable Documentation
mux_gpios
const struct gpio_dt_spec mux_gpios[] static
Initial value:
= {
    {.port = DEVICE_DT_GET(DT_NODELABEL(gpio0)),
     .pin = 2,
     .dt_flags = GPIO_ACTIVE_HIGH},
    {.port = DEVICE_DT_GET(DT_NODELABEL(gpio0)),
     .pin = 28,
     .dt_flags = GPIO_ACTIVE_HIGH},
    {.port = DEVICE_DT_GET(DT_NODELABEL(gpio0)),
     .pin = 15,
     .dt_flags = GPIO_ACTIVE_HIGH},
}
Devicetree setup for the muxer select lines.
Definition at line 139 of file mux_controller.cpp.
enable_gpio
const struct gpio_dt_spec enable_gpio static
Initial value:
= {
    .port = DEVICE_DT_GET(DT_NODELABEL(gpio0)),
    .pin = 16,
    .dt_flags = GPIO_ACTIVE_HIGH,
}
Devicetree setup for the muxer enable pin.
Definition at line 139 of file mux_controller.cpp.
adc_dev
const struct device* adc_dev = DEVICE_DT_GET(ADC_NODE) static
Definition at line 178 of file mux_controller.cpp.
Referenced by cmd_mux_sweep(), and setup_adc().
adc_buffer
int16_t adc_buffer static
Definition at line 179 of file mux_controller.cpp.
Referenced by cmd_mux_sweep().
val_mV
int32_t val_mV static
Definition at line 180 of file mux_controller.cpp.
Referenced by cmd_mux_sweep().
#include "drv/adc/mux_controller.h"
#include <zephyr/device.h>
#include <zephyr/drivers/adc.h>
#include <zephyr/drivers/gpio.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/shell/shell.h>
#include "./debug.h"
#include <string>