AXO X1: Adxl37x Class Reference
Adxl37x Class Reference
Adxl37x acceleration sensor class derived from task base class.
#include <adxl37x.h>
Detailed Description
Adxl37x acceleration sensor class derived from task base class.
Detailed Description
The Adxl37x class handle the reception of the acceleration data, delegate storage and further processing to Adxl data store task. It provides methods to receive the data from driver FIFO, to initialize the Adxl372 driver, to set the operating mode of the driver, to switch synchronization mode between internal and external, enable and clear driver FIFO, to convert and dump the received data and to inform Adxl data store task about new data.
Note
To avoid instabilities of the system when OTA Message Interaction:
Receive
Adxl data store task
RMS task
Firmware update control task
HTTP connector task
Adxl37x task (self, from callback function fifo_handler)
Transmit
Adxl data store task
HTTP connector task
Adxl37x task (self, transmission in callback function fifo_handler)
Definition at line 718 of file adxl37x.cpp.
Public Types
enum { odr = 4400 }
enum { odr_max = 6400 }
enum { max_samples = 170 }
enum { num_buffers = 2 }
Public Member Functions
Adxl37x (const char *name="??")
Adxl data store task constructor.
Adxl37x ()=delete
virtual ~Adxl37x ()
Adxl37x task destructor.
virtual void task (void)
Adxl37x task function.
void timer1_expired ()
Timer expired function for one shot suspend timeout timer.
virtual void configure ()
Adxl37x virtual task configure function.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for unused cyclic timer.
static void fifo_handler (const struct device *dev, const struct sensor_trigger *trigger)
The FIFO handler callback function.
static void setOpMode (enum adxl372_op_mode mode)
Function to set operation mode of the sensor device driver.
static void setExtSync (bool state)
Function to set synchronization mode of the sensor device driver.
static void setExtSyncClk (bool state)
Function to start or stop external synchronization clock.
static void setFifoBypass ()
Function to clears the FIFO data of the sensor device driver.
static void setFifoOn ()
Function to activate FIFO of the sensor device driver.
static void suspend ()
Function to suspend the sensor measurement.
static void resume ()
Function to resume the sensor measurement.
static void convert (struct sensor_value *val, int16_t value)
Conversion of received sensor value.
static void dump (adxl372_xyz_accel_data *s)
Function to dump received sensor values.
static enum hw_stat getHwStatus ()
Getter function to retrieve status information and number of FIFO entries.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Timer * myTimer
One shot timer to control suspend timeout and resume measurement.
Static Public Attributes
static const struct device * sensorDev = 0
Pointer to the sensor device driver structure.
static struct adxl372_status adxl372Status
Structure containing status information and number of FIFO entries.
static adxl372_xyz_accel_data samples [num_buffers][max_samples]
The measured raw data.
static bool dirty [num_buffers] = {0}
Indicates which buffer is currently in use.
static uint8_t cur_buf = 0
The current data buffer of the driver.
static uint16_t sample_cnt = 0
The sample counter.
static bool extSync = false
state of internal/external sync mode
Private Member Functions
void initDevice ()
Function to initialize the sensor device driver.
void report ()
Function to send received data to Adxl data store task.
void reportHwStatus ()
Function to send a HW status message to HW metrics task.
bool selftest ()
Static Private Member Functions
static void print ()
Print function.
Static Private Attributes
static const uint32_t suspendTimeout = 5*60
Maximal suspend time (5 minutes)
static bool device_good = false
Flag indicating if hardware init was successful or not.
static bool bSelftestPassed = false
Flag indicating that self test has been passed or not.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
odr
Definition at line 183 of file adxl37x.h.
anonymous enum
anonymous enum
Enumerator
odr_max
Definition at line 184 of file adxl37x.h.
anonymous enum
anonymous enum
Enumerator
max_samples
Definition at line 185 of file adxl37x.h.
anonymous enum
anonymous enum
Enumerator
num_buffers
Definition at line 186 of file adxl37x.h.
Constructor & Destructor Documentation
Adxl37x() [1/2]
Adxl37x (const char * name = "??") explicit
Adxl data store task constructor.
Parameters
name The name of the class
The constructor allocate and register the tasks mailbox and initializes the sensor device driver by calling member function initDevice.
Definition at line 461 of file adxl37x.cpp.
References Mbox::eAdxl37xTask, initDevice(), myTimer, pInMbox, Mbox::registerMbox(), samples, suspendTimeout, and timer_cb().
Adxl37x() [2/2]
Adxl37x () delete
~Adxl37x()
~Adxl37x () virtual
Adxl37x task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 480 of file adxl37x.cpp.
Member Function Documentation
task()
void task (void) virtual
Adxl37x task function.
The task function directly enter the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eAdxl37xFifo: Indication, that sensor raw data in FIFO available. The data will be send to Adxl data store task by calling function report. Afterwards pElem is set to 0 to avoid free() of statically allocated message.
eAdxl37xIdle: Operation mode of ADXL372 sensor will be set to Standby by calling function suspend. FIFO is cleared by calling setFifoBypass and activated for further receiption by calling setFifoOn. Finally Adxl data store task will be informed about idle state.
eAdxlStorageDone: Previous used buffer will be marked as clean
eAdxlStorageFull: Operation mode of ADXL372 sensor will be set to Standby by calling function suspend to supress measurements.
eAdxlResumeMeas: Operation mode of ADXL372 sensor will be set to WakeUp by calling function resume to enable further measurements.
eFwUpdateActive: Indication that an OTA firmaware update is started. Operation mode of ADXL372 sensor will be set to Standby by calling function suspend to supress measurements during SW update.
eRawDataTransferActive: Indication that transfer of raw data is running. Only informational, triggers a debug message.
eRawDataTransferComplete: Indication that transfer of raw data is finished. Only informational, triggers a debug message.
eDispDataTransferActive: Indication that transfer of displacement data is running. Only informational, triggers a debug message.
eDispDataTransferComplete: Indication that transfer of displacement data is finished. Only informational, triggers a debug message.
eAdxlStorageDumpActive: Indication that console data dump is running. Operation mode of ADXL372 sensor will be set to Standby by calling function suspend to supress measurements during data dump.
eAdxlStorageDumpComplete: Operation mode of ADXL372 sensor will be set to WakeUp by calling function resume to enable further measurements.
eHwReport: Report the HW status to the mailbox of HW metrics task
Implements Task.
Definition at line 603 of file adxl37x.cpp.
References cur_buf, dirty, eAdxl37xFifo, eAdxl37xIdle, eAdxlResumeMeas, eAdxlStorageDone, eAdxlStorageDumpActive, eAdxlStorageDumpComplete, eAdxlStorageFull, Mbox::eAdxlStore, eDisableADXL, eDispDataTransferActive, eDispDataTransferComplete, eEnableADXL, eFwUpdateActive, eHwReport, eRawDataTransferActive, eRawDataTransferComplete, eTimerExpired, PoolElem::free(), PoolElem::mtype, Task::myName, myTimer, num_buffers, pInMbox, Mbox::read(), report(), reportHwStatus(), resume(), Mbox::send(), setFifoBypass(), setFifoOn(), Timer::start(), Timer::stop(), suspend(), and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for unused cyclic timer.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call Adxl37x timer expired function timer1_expired.
Definition at line 491 of file adxl37x.cpp.
References timer1_expired().
Referenced by Adxl37x().
timer1_expired()
void timer1_expired ()
Timer expired function for one shot suspend timeout timer.
The function initializes the static pool element e1 with message type eTimerExpired, set Adxl37x task as sender and put message into own (Adxl37x's) mailbox.
Definition at line 506 of file adxl37x.cpp.
References eTimerExpired, pInMbox, and Mbox::write().
Referenced by timer_cb().
configure()
void configure () virtual
Adxl37x virtual task configure function.
The configure function overloads the configure function of the task base class. It retrieves the configuration related to sensors by call of the function getCfgSensor for the acceleration sensor ADXL372 provided by the Config class, convert the activation and deactivation thresholds to 32-bit
intervall in seconds and reconfigure the metrics wakeup interval with this value. integer values and set the thresholds by call of the function sensor_attr_set provided by Zephyr driver API for x, y and z direction.
Reimplemented from Task.
Definition at line 524 of file adxl37x.cpp.
References CONFIG_ACCEL_SENS_NAME, CONFIG_ACCEL_SENS_TYPE, eSensor_adxl372, Config::getCfgSensor(), Config::inst(), and sensorDev.
Referenced by main().
fifo_handler()
void fifo_handler (const struct device * dev, const struct sensor_trigger * trigger) static
The FIFO handler callback function.
Parameters
dev pointer to the sensor device driver structure
trigger unused parameter
On on first FIFO full interrupt synchronization clock is switched to externel clock by calling function setExtSync. Driver buffer will be switched to next free buffer and the acceleration data is retrieved by calling driver function adxl372_get_fifo_xyz_data and stored in array samples. Sample count will be adjusted by dividing through 3 (x, y, z) and own task will be informed about message receiption by message eAdxl37xFifo.
Definition at line 363 of file adxl37x.cpp.
References adxl372_get_fifo_xyz_data(), cur_buf, dirty, eAdxl37xFifo, Mbox::eAdxl37xTask, extSync, max_samples, num_buffers, sample_cnt, samples, Mbox::send(), and setExtSync().
Referenced by getHwStatus().
setOpMode()
void setOpMode (enum adxl372_op_mode mode) static
Function to set operation mode of the sensor device driver.
Function set operation mode by calling driver function adxl372_set_op_mode. On failure error debug message are printed. See ADXL372 datasheet, page 15.
Definition at line 243 of file adxl37x.cpp.
References adxl372_set_op_mode(), and sensorDev.
Referenced by getHwStatus(), resume(), and suspend().
setExtSync()
void setExtSync (bool state) static
Function to set synchronization mode of the sensor device driver.
Parameters
state true: synchronization with external clock, false: internal clock
Function set the synchronization mode according to parameter state. If mode is still active the function returns immediatly, otherwise external clock is started or stopped according to parameter state by calling function setExtSyncClk, sensor synchronization will be configured according to parameter state by calling function adxl372_set_ext_sync. On failure error debug message are printed. Finally flag extSync will be set to parameter state. See ADXL372 datasheet, page 27.
Definition at line 262 of file adxl37x.cpp.
References adxl372_set_ext_sync(), extSync, sensorDev, and setExtSyncClk().
Referenced by fifo_handler(), and suspend().
setExtSyncClk()
void setExtSyncClk (bool state) static
Function to start or stop external synchronization clock.
Parameters
state true: start external synchronization clock, false: stop clock
External clock is started or stopped according to parameter state by calling function Pwm::inst()->start() or Pwm::inst()->stop().
Definition at line 280 of file adxl37x.cpp.
References Pwm::inst(), Pwm::start(), and Pwm::stop().
Referenced by setExtSync().
setFifoBypass()
void setFifoBypass () static
Function to clears the FIFO data of the sensor device driver.
Function clear the FIFO data by calling driver function adxl372_configure_fifo. On failure error debug message are printed. FIFO will be disabled by setting mode to ADXL372_FIFO_BYPASSED, which clears any data in FIFO. See ADXL372 datasheet, page 23.
Definition at line 213 of file adxl37x.cpp.
References adxl372_configure_fifo(), ADXL372_FIFO_BYPASSED, ADXL372_XYZ_FIFO, and sensorDev.
Referenced by getHwStatus(), resume(), and task().
setFifoOn()
void setFifoOn () static
Function to activate FIFO of the sensor device driver.
Function activate FIFO by calling driver function adxl372_configure_fifo. On failure error debug message are printed. FIFO will be configued to stream mode (last N), 170 sample sets of concurrent 3-axis data with 128 x, y and z values (3 * 128 = 384). See ADXL372 datasheet, page 23.
Definition at line 229 of file adxl37x.cpp.
References adxl372_configure_fifo(), ADXL372_FIFO_STREAMED, ADXL372_XYZ_FIFO, and sensorDev.
Referenced by getHwStatus(), resume(), and task().
suspend()
void suspend () static
Function to suspend the sensor measurement.
To suspend the sensor measurement the ADXL372 sensor will be set to Standby by calling function setOpMode with parameter ADXL372_STANDBY. By calling function setExtSync synchronization is switched back to internal.
Definition at line 322 of file adxl37x.cpp.
References ADXL372_STANDBY, setExtSync(), and setOpMode().
Referenced by task().
resume()
void resume () static
Function to resume the sensor measurement.
FIFO is cleared by calling setFifoBypass and activated for further receiption by calling setFifoOn. All FIFO buffers will be marked as clean by setting dirty flags to false. Finally the operation mode of ADXL372 sensor will be set to WakeUp by calling function setOpMode with parameter ADXL372_WAKE_UP.
Definition at line 337 of file adxl37x.cpp.
References ADXL372_WAKE_UP, dirty, num_buffers, setFifoBypass(), setFifoOn(), and setOpMode().
Referenced by task().
convert()
void convert (struct sensor_value * val, int16_t value) static
Conversion of received sensor value.
Function converts received sensor value and store it in quasi floating point structure with integer and fractional part.
Definition at line 70 of file adxl37x.cpp.
Referenced by dump(), AdxlDataStore::dumpAll(), DispTask::HandleDispFirstEntries(), DispTask::HandleDispLastEntries(), and DispTask::HandleRawData().
dump()
void dump (adxl372_xyz_accel_data * s) static
Function to dump received sensor values.
Parameters
s measured sensor values in structure of type adxl372_xyz_accel_data
Dump the first 10 entries of the measured data. x, y and z data will be converted to floating point values of type struct sensor_value and afterward converted to float by calling function sensor_value_to_double before print out.
Definition at line 299 of file adxl37x.cpp.
References convert().
getHwStatus()
enum hw_stat getHwStatus () static
Getter function to retrieve status information and number of FIFO entries.
Function status information and number of FIFO entries by calling driver function adxl372_get_status. On failure error debug message are printed. See ADXL372 datasheet, page 34f.
Definition at line 118 of file adxl37x.cpp.
References ADXL372_FULL_BW_MEASUREMENT, ADXL372_STANDBY, bSelftestPassed, device_good, fifo_handler(), getSelftestSuccess(), Pwm::init(), Pwm::inst(), sensorDev, setFifoBypass(), setFifoOn(), setOpMode(), Pwm::setPeriod(), and Pwm::setPulseWidth().
Referenced by reportHwStatus().
initDevice()
void initDevice () private
Function to initialize the sensor device driver.
Function initializes the SPI bus by calling function spibus::inst()->init() and retrieves a pointer to the sensor device object by calling macro DEVICE_DT_GET_ANY and casting to pointer of type struct device. With call of function device_is_ready it checks if the sensor device is ready to use. Result is stored in private class variable device_good. If device is not ready an error message will be printed. Furthermore the operating mode of the device is set to STANDBY mode, trigger type and channel are assigned and set. Afterward external syncronization signal will be initialized with 4400 Hz and 80 usec pulse width by calling Pwm::inst()->init(), Pwm::inst()->setPeriod() and Pwm::inst()->setPulseWidth().
Afterwards FIFO will be cleared and activated and operation mode is set to FULL_BW_MEASUREMENT and STANDBY. This sequence triggers the initial calibration of the sensor to the current prevalent acceleration ratio in idle mode of the sensor.
Finally FIFO will be cleared and activated and operation mode is set to WAKE_UP. See ADXL372 datasheet, page 19ff for interrupt configuration, page 25 for interrupt configuration and page 29 for SPI support.
Note
SPI clock frequency has to be adjusted in file nrf9160dk_switch_common.dts with entry spi-max-frequency = <8000000>; The value must be unsigned integer in Hz.
In Zephyr devicetree ADXL SPI is SPI bus 2.
Definition at line 118 of file adxl37x.cpp.
Referenced by Adxl37x().
report()
void report () private
Function to send received data to Adxl data store task.
The function request a pointer to the mailbox of Adxl data store task and a message from message pool, set message type to eAdxl37xSensorData, set Adxl37x task as sender, copy timestamp, sample count and acceleration data into payload of the message and send to Adxl data store mailbox. Finally the currently used buffer will be marked in array dirty.
Definition at line 412 of file adxl37x.cpp.
References adxl37x_sensor_value::cnt, cur_buf, dirty, eAdxl37xSensorData, num_buffers, sample_cnt, adxl37x_sensor_value::samples, samples, Mbox::sendMsg(), and adxl37x_sensor_value::ts.
Referenced by task().
reportHwStatus()
void reportHwStatus () private
Function to send a HW status message to HW metrics task.
The function retrieve the HW status by calling function getStatus, request a pointer to the mailbox of HW metrics task and a message from message pool, set message type to eHwStatusAdxl37x, set Adxl37x task as sender, copy the boolean status value into payload of the message and send it to HW metrics mailbox.
Definition at line 437 of file adxl37x.cpp.
References bSelftestPassed, eHwMetrics, eHwStatusAdxl37x, getHwStatus(), hw_metrics::num_errors, and Mbox::sendMsg().
Referenced by task().
selftest()
bool selftest () private
print()
void print (void) static private
Print function.
Not implemented, for future use
Definition at line 81 of file adxl37x.cpp.
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the adxl37x task
Definition at line 200 of file adxl37x.h.
Referenced by Adxl37x(), task(), and timer1_expired().
myTimer
Timer* myTimer
One shot timer to control suspend timeout and resume measurement.
Definition at line 202 of file adxl37x.h.
Referenced by Adxl37x(), and task().
sensorDev
const struct device * sensorDev = 0 static
Pointer to the sensor device driver structure.
Definition at line 205 of file adxl37x.h.
Referenced by configure(), getHwStatus(), setExtSync(), setFifoBypass(), setFifoOn(), and setOpMode().
adxl372Status
struct adxl372_status adxl372Status static
Structure containing status information and number of FIFO entries.
Definition at line 205 of file adxl37x.h.
samples
adxl372_xyz_accel_data samples static
The measured raw data.
Definition at line 211 of file adxl37x.h.
Referenced by Adxl37x(), fifo_handler(), and report().
dirty
bool dirty = {0} static
Indicates which buffer is currently in use.
Definition at line 214 of file adxl37x.h.
Referenced by fifo_handler(), report(), resume(), and task().
cur_buf
uint8_t cur_buf = 0 static
The current data buffer of the driver.
Definition at line 216 of file adxl37x.h.
Referenced by fifo_handler(), report(), and task().
sample_cnt
uint16_t sample_cnt = 0 static
The sample counter.
Definition at line 217 of file adxl37x.h.
Referenced by fifo_handler(), and report().
extSync
bool extSync = false static
state of internal/external sync mode
Definition at line 222 of file adxl37x.h.
Referenced by fifo_handler(), and setExtSync().
suspendTimeout
const uint32_t suspendTimeout = 5*60 static private
Maximal suspend time (5 minutes)
Definition at line 238 of file adxl37x.h.
Referenced by Adxl37x().
device_good
bool device_good = false static private
Flag indicating if hardware init was successful or not.
Definition at line 246 of file adxl37x.h.
Referenced by getHwStatus().
bSelftestPassed
bool bSelftestPassed = false static private
Flag indicating that self test has been passed or not.
Definition at line 248 of file adxl37x.h.
Referenced by getHwStatus(), and reportHwStatus().
The documentation for this class was generated from the following files:
drv/spi/adxl37x.cpp
drv/spi/adxl37x.h