AXO X1: FwStateList Struct Reference
FwStateList Struct Reference
Structure containing pointer to all state instances of the state machine.
#include <fsm.h>
Detailed Description
Structure containing pointer to all state instances of the state machine.
Definition at line 35 of file fsm.h.
Static Public Member Functions
static FwState * createIdle (void *pd)
Pointer to the Idle state instance.
static FwState * createTriggered (void *pd)
Pointer to the Triggered state instance.
static FwState * createDownload (void *pd)
Pointer to the Download state instance.
static FwState * createReady (void *pd)
Pointer to the Ready state instance.
Member Function Documentation
createIdle()
FwState * createIdle (void * pd) static
Pointer to the Idle state instance.
Creator function for constucting the idle state.
Parameters
pd The pointer to a data object
Returns
A pointer to the state instance of type FwState, the state base class
The function allocates an instance of the class FwIdle with operator new and return the pointer to this instance.
Definition at line 59 of file fsm.cpp.
Referenced by FwFsm::FwFsm().
createTriggered()
FwState * createTriggered (void * pd) static
Pointer to the Triggered state instance.
Creator function for constucting the triggered state.
Parameters
pd The pointer to a data object
Returns
A pointer to the state instance of type FwState, the state base class
The function allocates an instance of the class FwTriggered with operator new and return the pointer to this instance.
Definition at line 71 of file fsm.cpp.
Referenced by FwFsm::FwFsm().
createDownload()
FwState * createDownload (void * pd) static
Pointer to the Download state instance.
Creator function for constucting the firmware download state.
Parameters
pd The pointer to a data object
Returns
A pointer to the state instance of type FwState, the state base class
The function allocates an instance of the class FwDownload with operator new and return the pointer to this instance.
Definition at line 83 of file fsm.cpp.
Referenced by FwFsm::FwFsm().
createReady()
FwState * createReady (void * pd) static
Pointer to the Ready state instance.
Creator function for constucting the ready state.
Parameters
pd The pointer to a data object
Returns
A pointer to the state instance of type FwState, the state base class
The function allocates an instance of the class FwReady with operator new and return the pointer to this instance.
Definition at line 95 of file fsm.cpp.
Referenced by FwFsm::FwFsm().
The documentation for this struct was generated from the following files:
update/fsm.h
update/fsm.cpp