AXO X1: ADConverter Class Reference
ADConverter Class Reference
AD converter driver class derived from task base class.
#include <adconverter.h>
Detailed Description
AD converter driver class derived from task base class.
Detailed Description
The AD converter driver class handle the reception of the analog values, convert them into digital values and report them to the registered listener task on request. For testing purposes cyclic timer handling is implemented and can be used for automatic cyclic sampling. The timers are organized in a vector and will be allocated in the autoSample method, which is only called by inactive testing scenarios.
The AD converter class provides methods to sample the data of the provided AD channels, to initialize the AD devices and to report the data to the registered listener tasks. It uses the public zephyr API for the sensor driver. See details in Zephyr ADC API documentation and for details of the ADC channel configuration in the devicetree Message Interaction:
Receive
Timer interrupt callback (only for testing purposes)
AD converter task (self, only for testing purposes)
Battery manager task
Transmit
Battery manager task
AD converter task (self, transmission in timer callback, only for testing purposes)
Definition at line 55 of file adconverter.cpp.
Public Member Functions
ADConverter (const char *name="??")
AD converter task constructor.
ADConverter ()=delete
virtual ~ADConverter ()
AD converter task destructor.
virtual void task (void)
ADConverter task function.
void timer1_expired (uint8_t chmask)
Timer expired function for the cyclic sample timer.
void autoSample (uint8_t chmask, uint32_t interval, Mbox *listener)
Function to start cyclic automatic sampling if specified ADC channels.
void notifyListener (uint8_t channel, int16_t raw, int32_t mv)
Send ADC data to optional registered listener for specified channel.
void registerListener (uint8_t chmask, Mbox *listener)
Function to register a listener for a specific ADC channels.
Public Member Functions inherited from Task
Task (const char *name="??")
Task class constructor.
virtual ~Task ()
Task class destructor.
void create (k_thread_stack_t *stack, size_t stack_size, int prio)
Function to create a task and to assign the name of the task.
void setId (uint8_t id)
Setter function to set the ID of the task.
void start ()
Function to start a task.
virtual void configure ()
Virtual task configure function.
Static Public Member Functions
static void timer_cb (k_timer *timer)
Timer callback function for the cyclic sample timers.
Static Public Member Functions inherited from Task
static void taskCode (void *p1, void *p2, void *p3)
Entry point for the operating system.
Data Fields
Mbox * pInMbox
Mailbox of the ADConverter task.
Private Member Functions
void initDevice ()
The init function.
void sample (uint8_t chmask)
Function to sample ADC data for specified channels.
Private Attributes
std::vector< Timer * > timers
auto sampling timers (only for testing purposes)
Mbox * adc_listeners [8]
pointer to the listeners mailboxes
Static Private Attributes
static struct adc_dt_spec adc_channels [8]
static size_t adc_total_channels = DT_PROP_LEN(DT_PATH(zephyr_user), io_channels)
Structure for an user-specific timer data.
Additional Inherited Members
Protected Attributes inherited from Task
struct k_thread thread_handle
Thread administration structure.
k_tid_t tid
The unique ID of the task provided by the OS.
char myName [16]
The unique name of the task.
uint8_t myId
The unique ID of the task.
Constructor & Destructor Documentation
ADConverter() [1/2]
ADConverter (const char * name = "??") explicit
AD converter task constructor.
Parameters
name The name of the class
The constructor allocate and register the mailbox of the AD converter task.
Definition at line 254 of file adconverter.cpp.
References Mbox::eADConverter, pInMbox, and Mbox::registerMbox().
ADConverter() [2/2]
ADConverter () delete
~ADConverter()
~ADConverter () virtual
AD converter task destructor.
The destructor is never called and is implemented only for completion reasons. It simply triggers a debug message on info debug level.
Definition at line 269 of file adconverter.cpp.
Member Function Documentation
task()
void task (void) virtual
ADConverter task function.
Initially the AD converters will be initialized by calling member function initDevice. Then the timers for cyclic automatic sampling are started. Note, that these timer are only created for testing purposes. In productive software the vector of timers is empty. I2cBus instance. sensor device will be initialized by call of member function initDevice. For testing purposes a cyclic timer can be activated by commenting in the start method of the timer to initiate a cyclic sampling of the sensor data.
Afterwards the function enters the endless loop and wait for messages. Task wakes up when a message is in the mailbox and read the message by calling mailbox read method which returns the pointer pElem to the message. All expected messages will be handled, in case of an unexpected message an error debug message will be triggered. Finally the message will be released by calling class PoolElem method free, if the pointer pElem is not explicitly set to 0.
Message Handling:
eTimerExpired: On sample timer expiry sensor data will be sampled and reported to registered listeners by calling function sample. The pointer pElem will be set to 0, to prevent releasing the message because it is allocated static.
eAdcReport: On ADC report request sensor data will be sampled and reported to registered listeners by calling function sample.
Implements Task.
Definition at line 361 of file adconverter.cpp.
References eAdcReport, eTimerExpired, PoolElem::free(), MuxController::init(), initDevice(), PoolElem::mtype, mux, Task::myName, PoolElem::p1, pInMbox, Mbox::read(), sample(), timers, and UNIT_TEST_STOP_LOOP.
timer_cb()
void timer_cb (k_timer * timer) static
Timer callback function for the cyclic sample timers.
Parameters
timer Pointer to timer of type k_timer
The function retrieve the user-specific data from the timer by calling kernel function k_timer_user_data_get and call timer expired member function timer1_expired with the channel bitmask as parameter extracted from the user-specific data of type AdcTimerInfo.
Definition at line 103 of file adconverter.cpp.
References AdcTimerInfo::ch_mask, AdcTimerInfo::self, and timer1_expired().
Referenced by autoSample().
timer1_expired()
void timer1_expired (uint8_t chmask)
Timer expired function for the cyclic sample timer.
Parameters
chmask Channel bitmask
The function initializes the static pool element e1 with message type eTimerExpired, set AD converter task as sender, copy channel bitmask chmask in the payload of the message and put message into own (AD converter's) mailbox.
Definition at line 124 of file adconverter.cpp.
References eTimerExpired, PoolElem::p1, pInMbox, and Mbox::write().
Referenced by timer_cb().
autoSample()
void autoSample (uint8_t chmask, uint32_t interval, Mbox * listener)
Function to start cyclic automatic sampling if specified ADC channels.
Parameters
chmask Bitmask specifying which channels shall be reported to listener
interval The sample intervall in millliseconds
listener An optional listener, can be NULL if not required
The function allocates a structure of type AdcTimerInfo and assign the this pointer of the class instance and the specified channel bitmask to it. Afterwards it allocates a cyclic timer with duration and period specified by parameter interval and copy the pointer to the timer in vector timers by calling the vector class method push_back. Finally it checks if spezified mailbox pointer listener is not NULL and in this case it registers the listener for the channels specified in channel bitmask chmask by calling member function registerListener.
Note
This function is only implemented for testing purposes, in productive software this function is not called.
Definition at line 292 of file adconverter.cpp.
References AdcTimerInfo::ch_mask, registerListener(), AdcTimerInfo::self, timer_cb(), and timers.
notifyListener()
void notifyListener (uint8_t channel, int16_t raw, int32_t mv)
Send ADC data to optional registered listener for specified channel.
Parameters
channel The specified ADC channel
raw The measured ADC raw data
mv The measured ADC data converted to millivolt
The function checks if there is a listener registered for the specified channel and if the pointer to listener mailbox in array adc_listeners is not NULL, it requests a message from message pool, set message type to eAdcData, set eADConverter as sender and send message to the listener's mailbox.
Definition at line 146 of file adconverter.cpp.
References adc_listeners, ADInput::channel, eAdcData, MsgPool::getNewElem(), MsgPool::inst(), ADInput::mv, ADInput::raw, and Mbox::write().
Referenced by sample().
registerListener()
void registerListener (uint8_t chmask, Mbox * listener)
Function to register a listener for a specific ADC channels.
Parameters
chmask Bitmask specifying which channels shall be reported to listener
listener Pointer to the mailbox of the listener
The function enter a loop over the maximum number of ADC channels and if channel at index ch of array adc_listeners is specified by channel bitmask chmask, it register the listener by copy the pointer to the mailbox in array listeners at index ch, before leaving the function.
Definition at line 322 of file adconverter.cpp.
References adc_listeners.
Referenced by autoSample(), and main().
initDevice()
void initDevice () private
The init function.
The function enters a loop over the array of containers with the ADC channel information specified in devicetree and checks if the device at index i is ready for usage with call of function device_is_ready. Afterwards the ADC channel of device at index i will be configured by calling function adc_channel_setup_dt provided by the Zephyr ADC API.
Definition at line 79 of file adconverter.cpp.
References adc_total_channels.
Referenced by task().
sample()
void sample (uint8_t chmask) private
Function to sample ADC data for specified channels.
Parameters
chmask The channel bitmask, specifying the channels which shall be sampled
The function allocates a structure of type struct adc_sequence which defines an ADC sampling sequence with an 16 bit unsigned integer type. Than it enters a loop over the ADC channels and check if bit at position i is set in channel bitmask chmask. If bit is set, it initialize the struct sequence of type adc_sequence with the information provided array adc_channels of type struct adc_dt_spec at index i by calling function adc_sequence_init_dt provided by Zephyr ADC API. With call of function adc_read also provided by Zephyr ADC API it reads the raw value into structure sequence. Afterwards the raw value will be assigned to to local varible val_mv and converted to millivolt by call of function adc_raw_to_millivolts_dt also provided by Zephyr ADC API, which uses the ADC specification from device tree from structure struct adc_dt_spec provided by array adc_channels at position i. Finally the listeners will be informed by calling member function notifyListener.
Definition at line 192 of file adconverter.cpp.
References mux, notifyListener(), and MuxController::selectChannel().
Referenced by task().
Field Documentation
pInMbox
Mbox* pInMbox
Mailbox of the ADConverter task.
Definition at line 100 of file adconverter.h.
Referenced by ADConverter(), task(), and timer1_expired().
timers
std::vector<Timer*> timers private
auto sampling timers (only for testing purposes)
Definition at line 104 of file adconverter.h.
Referenced by autoSample(), and task().
adc_listeners
Mbox* adc_listeners[8] private
pointer to the listeners mailboxes
Definition at line 106 of file adconverter.h.
Referenced by notifyListener(), and registerListener().
adc_channels
struct adc_dt_spec adc_channels[8] static private
Array of containers for ADC channel information specified in devicetree
Definition at line 106 of file adconverter.h.
adc_total_channels
size_t adc_total_channels = DT_PROP_LEN(DT_PATH(zephyr_user), io_channels) static private
Structure for an user-specific timer data.
Definition at line 113 of file adconverter.h.
Referenced by initDevice().
The documentation for this class was generated from the following files:
drv/adc/adconverter.cpp
drv/adc/adconverter.h