AXO X1: version.h File Reference
version.h File Reference
Header file of software version management.
Detailed Description
Header file of software version management.
Project
AXO Track Firmware 2023
Copyright
(c) 2023 AXO Track GmbH, Berlin. All rights reserved.
Author
AXO Track GmbH, Berlin (Germany)
Detailed Description
This file provides a getter function to retrieve the software version and a function to display the software version at startup im debug mode
Remarks
This source code is confidential and proprietary information of AXO Track GmbH, Berlin. You may not disclose, copy, or distribute this source code or any part thereof without the explicit permission of AXO Track GmbH, Berlin.
Definition in file version.h.
Functions
const char * getFwVersion ()
Getter function to retrieve the software version.
const void displayFwVersion ()
Function to display the firmware version in Debug Mode at Startup.
Function Documentation
getFwVersion()
const char* getFwVersion ()
Getter function to retrieve the software version.
Returns
Returns the software version string
Getter function to retrieve the software version.
Definition at line 37 of file version.cpp.
References fwVersion.
Referenced by displayFwVersion(), and MetricsBuilder::finalize().
displayFwVersion()
const void displayFwVersion ()
Function to display the firmware version in Debug Mode at Startup.
Display Fimrware version at Startup in Debug Mode (Debug-Level = WRN)
Definition at line 45 of file version.cpp.
References getFwVersion().
Referenced by main().